### ISSUE TITLE
Fuzzy date setting not respected on show list

### ISSUE THREAD

**Issue by below9k** [pymedusa/Medusa#7463] opened 2019-12-09 16:32 UTC
**Describe the bug**
Fuzzy dates aren't working on the show home page

**To Reproduce**
1. Enable "Display fuzzy dates"
2. View the show list
3. Notice dates are not fuzzy

**Expected behavior**
Dates to be fuzzy

**Screenshots**
![Screen Shot 2019-12-09 at 10 27 24 AM](https://user-images.githubusercontent.com/6232236/70453676-cca03e80-1a6e-11ea-8d52-4d2fd278b877.png)
![Screen Shot 2019-12-09 at 10 27 41 AM](https://user-images.githubusercontent.com/6232236/70453677-cca03e80-1a6e-11ea-9acb-2d2c2e0481a1.png)

**Medusa Info**
Branch: master
Commit: 8b7f433d4dce89058a8b9b62cc9bcd7a162a3344
Version: 0.3.8
Database: 44.14
Python Version: 2.7.12 (default, Oct 8 2019, 14:14:10) [GCC 5.4.0 20160609]
SSL Version: OpenSSL 1.0.2g 1 Mar 2016
OS: Linux-4.15.0-70-generic-x86_64-with-Ubuntu-16.04-xenial
Locale: en_US.UTF-8

**Additional context**
Probably unrelated
![Screen Shot 2019-12-09 at 10 31 29 AM](https://user-images.githubusercontent.com/6232236/70453848-125d0700-1a6f-11ea-8d7e-00e65cc05b74.png)

**Comment by sharkykh** [comment] 2019-12-09 18:08
This is the same on the Schedule and DisplayShow pages as well.
The issue is this line runs before the page is rendered by Vue.
https://github.com/pymedusa/Medusa/blob/d1befd33e89cc46d122f84282852393754ef2ce6/themes-default/slim/static/js/common/init.js#L99
Probably need to get a similar plugin for Vue (that doesn't use jQuery)...

**Comment by p0psicles** [comment] 2020-09-06 14:12
should be fixed already. At least for show page.

**Closed by p0psicles** 2020-09-06 14:12 UTC
Labels: Bug, Frontend
