### ISSUE TITLE
Subtitle error

### ISSUE THREAD

**Issue by Dohnerd** [pymedusa/Medusa#10542] opened 2022-05-02 14:10 UTC
Im getting this quite some often:
```
2022-05-02 14:12:26 WARNING  FINDSUBTITLES :: [e4870f8] Unexpected error. Provider addic7ed
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/babelfish/converters/__init__.py", line 168, in reverse
    return self.from_symbol[code]
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/babelfish/converters/__init__.py", line 51, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'french (canadian)'
```
During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/subliminal/core.py", line 115, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/medusa/subtitle_providers/addic7ed.py", line 285, in list_subtitles
    subtitles = [s for s in self.query(show_id, title, video.season, video.year)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/medusa/subtitle_providers/addic7ed.py", line 257, in query
    language = Language.fromaddic7ed(cells[3].text)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/subliminal/converters/addic7ed.py", line 32, in reverse
    return self.name_converter.reverse(addic7ed)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/babelfish/converters/__init__.py", line 170, in reverse
    raise LanguageReverseError(code)
babelfish.exceptions.LanguageReverseError: 'French (Canadian)'
```
I dont even use/search for french ?

**Comment by p0psicles** [comment] 2022-05-04 06:46
Any way i can reproduce this?
A specific show this error is thrown?

**Comment by Dohnerd** [comment] 2022-05-04 10:29
I don't know, I get it often, always from addic7ed.

2022-05-04 07:18:58 WARNING  FINDSUBTITLES :: [e4870f8] Unexpected error. Provider addic7ed'

This is my latest.

where is the debug log located?

Which template is that, I just pushed new issue and wrote there ?

**Comment by p0psicles** [comment] 2022-05-04 10:43
Enable debug logging in config - general - Logs
Then restart medusa.
if you click on New Issue - bug report. You'll get a template that you need to fill in.
![image](https://user-images.githubusercontent.com/1331394/166666885-f9bb971d-a8a4-46db-94dc-1798d1c03e1f.png)

**Comment by Dohnerd** [comment] 2022-05-04 11:04
Already enabled it, but where do i find it :)

**Comment by p0psicles** [comment] 2022-05-04 12:14
Medusa has a Logs folder in the program folder.
There you'll find application.log as older retentioned application.log.x files.

**Comment by Dohnerd** [comment] 2022-05-04 12:45
Cool, found this in log for the error:

2022-05-04 07:18:37 INFO     FINDSUBTITLES :: [e4870f8] Getting the page of show id 1175, season 11
2022-05-04 07:18:39 DEBUG    EPISODEUPDATER :: [e4870f8] Finished updating network timezones
2022-05-04 07:18:58 DEBUG    FINDSUBTITLES :: [e4870f8] Found subtitle <Addic7edSubtitle 'updated/1/168305/0' [en]>
2022-05-04 07:18:58 DEBUG    FINDSUBTITLES :: [e4870f8] Ignoring subtitle with status 23.96% Completed
2022-05-04 07:18:58 DEBUG    FINDSUBTITLES :: [e4870f8] Found subtitle <Addic7edSubtitle 'updated/1/168305/1' [en]>
2022-05-04 07:18:58 DEBUG    FINDSUBTITLES :: [e4870f8] Found subtitle <Addic7edSubtitle 'updated/10/168305/2' [pt-BR]>
2022-05-04 07:18:58 DEBUG    FINDSUBTITLES :: [e4870f8] Found subtitle <Addic7edSubtitle 'updated/16/168305/3' [tr]>
2022-05-04 07:18:58 DEBUG    FINDSUBTITLES :: [e4870f8] Found subtitle <Addic7edSubtitle 'updated/7/168305/4' [it]>
2022-05-04 07:18:58 DEBUG    FINDSUBTITLES :: [e4870f8] Found subtitle <Addic7edSubtitle 'updated/17/168305/5' [nl]>
2022-05-04 07:18:58 DEBUG    FINDSUBTITLES :: [e4870f8] Found subtitle <Addic7edSubtitle 'updated/8/168305/6' [fr]>
2022-05-04 07:18:58 DEBUG    FINDSUBTITLES :: [e4870f8] Found subtitle <Addic7edSubtitle 'updated/8/168305/7' [fr]>
2022-05-04 07:18:58 DEBUG    FINDSUBTITLES :: [e4870f8] Found subtitle <Addic7edSubtitle 'updated/8/168305/8' [fr]>
2022-05-04 07:18:58 WARNING  FINDSUBTITLES :: [e4870f8] Unexpected error. Provider addic7ed
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/babelfish/converters/__init__.py", line 168, in reverse
    return self.from_symbol[code]
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/babelfish/converters/__init__.py", line 51, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'french (canadian)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/subliminal/core.py", line 115, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/medusa/subtitle_providers/addic7ed.py", line 285, in list_subtitles
    subtitles = [s for s in self.query(show_id, title, video.season, video.year)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/medusa/subtitle_providers/addic7ed.py", line 257, in query
    language = Language.fromaddic7ed(cells[3].text)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/subliminal/converters/addic7ed.py", line 32, in reverse
    return self.name_converter.reverse(addic7ed)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/babelfish/converters/__init__.py", line 170, in reverse
    raise LanguageReverseError(code)
babelfish.exceptions.LanguageReverseError: 'French (Canadian)'
2022-05-04 07:18:59 DEBUG    FINDSUBTITLES :: [e4870f8] Discarding provider addic7ed
2022-05-04 07:18:59 DEBUG    FINDSUBTITLES :: [e4870f8] Could not search in addic7ed provider. Discarding for now
2022-05-04 07:18:59 DEBUG    FINDSUBTITLES :: [e4870f8] Could not search in tvsubtitles provider. Discarding for now

**Comment by p0psicles** [comment] 2022-05-07 15:22
I suspect this is for the show `the walking dead`.
I'll try to reproduce it. which languages do you have enabled?

**Comment by Dohnerd** [comment] 2022-05-07 21:05
Danish and English.

**Comment by p0psicles** [comment] 2022-05-08 08:24
I'm not going to spend a lot of time on this. Yesterday I tried to reproduce. But I only got timeouts from addic7ed. We added a custom addic7ed provider, cause someone found a workaround for the logon. But it's really a hit and miss solution. Like when it works, nice.

**Comment by mmhere** [comment] 2022-05-09 03:36
I suggest that this is a dupe of https://github.com/pymedusa/Medusa/issues/10344 which was just re-opened with a suggestion on how to improve the situation.

**Closed** 2022-06-21 09:38 UTC
