### ISSUE TITLE
[APP SUBMITTED]: ConnectionError: HTTPSConnectionPool(host='cdn.pymedusa.com', port=443): Max retries exceeded with url: /scene_exceptions/scene_exceptions_tvdb.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x70843590>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#2964] opened 2017-07-14 23:18 UTC
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.28-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@e7a2e5b9638738129e3cedda491095fae73ad201
**Link to Log**: https://gist.github.com/bcb4db5230b26ab8cbb2539f422063a6
### ERROR
<pre>
2017-07-14 20:19:02 ERROR    MAIN :: [e7a2e5b] Unable to update scene exceptions for 1. Error: HTTPSConnectionPool(host='cdn.pymedusa.com', port=443): Max retries exceeded with url: /scene_exceptions/scene_exceptions_tvdb.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x70843590>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/e7a2e5b9638738129e3cedda491095fae73ad201/medusa/scene_exceptions.py#L305">medusa/scene_exceptions.py</a>", line 305, in _get_custom_exceptions
    response = indexerApi(indexer).session.get(location, timeout=60)
  File "/home/pi/Medusa/<a href="../blob/e7a2e5b9638738129e3cedda491095fae73ad201/lib/requests/sessions.py#L487">lib/requests/sessions.py</a>", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/home/pi/Medusa/<a href="../blob/e7a2e5b9638738129e3cedda491095fae73ad201/lib/requests/sessions.py#L475">lib/requests/sessions.py</a>", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/Medusa/<a href="../blob/e7a2e5b9638738129e3cedda491095fae73ad201/lib/requests/sessions.py#L585">lib/requests/sessions.py</a>", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/Medusa/<a href="../blob/e7a2e5b9638738129e3cedda491095fae73ad201/lib/cachecontrol/adapter.py#L46">lib/cachecontrol/adapter.py</a>", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/home/pi/Medusa/<a href="../blob/e7a2e5b9638738129e3cedda491095fae73ad201/lib/requests/adapters.py#L467">lib/requests/adapters.py</a>", line 467, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='cdn.pymedusa.com', port=443): Max retries exceeded with url: /scene_exceptions/scene_exceptions_tvdb.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x70843590>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment] 2017-07-15 09:44
Duplicate of https://github.com/pymedusa/Medusa/issues/2963

**Closed by medariox** 2017-07-15 09:44 UTC
