### ISSUE TITLE
[Trakt Checker] AttributeError: 'NoneType' object has no attribute 'get_episode'

### ISSUE THREAD

**Issue by ratoaq2** [pymedusa/Medusa#2782] opened 2017-05-11 16:50 UTC
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
**OS:**
**What you did:**
**What happened:**
**What you expected:**
**Logs:**
```

2017-05-11 18:42:04 ERROR    TRAKTCHECKER :: [6b2df91] Exception generated: 'NoneType' object has no attribute 'get_episode'
Traceback (most recent call last):
  File "/volumeUSB1/usbshare/applications/sickrage/SickBeard/medusa/scheduler.py", line 103, in run
    self.action.run(self.force)
  File "/volumeUSB1/usbshare/applications/sickrage/SickBeard/medusa/trakt_checker.py", line 89, in run
    self.sync_watchlist()
  File "/volumeUSB1/usbshare/applications/sickrage/SickBeard/medusa/trakt_checker.py", line 320, in sync_watchlist
    self.sync_trakt_episodes()
  File "/volumeUSB1/usbshare/applications/sickrage/SickBeard/medusa/trakt_checker.py", line 555, in sync_trakt_episodes
    set_episode_to_wanted(show, trakt_season, trakt_episode)
  File "/volumeUSB1/usbshare/applications/sickrage/SickBeard/medusa/trakt_checker.py", line 37, in set_episode_to_wanted
    ep_obj = show.get_episode(season, episode)
AttributeError: 'NoneType' object has no attribute 'get_episode'
```

**Comment by fernandog** [comment] 2017-05-11 17:42
known issue
this will be fixed only when I finish the Trakt rewrite as talked to @p0psicles some time ago.
no ETA to finish tho

**Comment by medariox** [comment] 2017-05-21 13:17
Code still needs to be maintained util rewrite, especially if it's a quick fix like this one.
Fixed here https://github.com/pymedusa/Medusa/pull/2817

**Comment by fernandog** [comment] 2017-05-21 13:22
not that easy fix as that will postpone the set ep to added in the next run of trakt (1h)
the real problem is we are adding a new show and must wait it to be added to then set ep as wanted.
Today we call the method to add show and seconds later set as wanted, so ofc the show won't exist

**Comment by medariox** [comment] 2017-05-21 13:41
The problem here is that we are calling set_episode_to_wanted() with show as None. That's the issue, that's fixed. If I look at the rest of the method, I honestly ask myself how that even got merged in the first place.

**Comment by fernandog** [comment] 2017-05-21 13:58
that is the original code of trakt and this is a known issue since the first implementation.
yes, the show is none because it was stil being added. This issue exists since sickrage. As the correct fix is to check the queue (and its not that easy)

**Comment by medariox** [comment] 2017-05-21 14:04
Code from March 22nd: https://github.com/pymedusa/Medusa/commit/a6af9b96f10e053cfb6045c1d390db6413af37d4#diff-74901db55787195accf764175a17c9e6R545

Once again that is not the issue, the issue is that you are never assigning the show variable again and set_episode_to_wanted() is called with show still being None.

**Comment by fernandog** [comment] 2017-05-21 14:12
The issue of adding episode to wanted right after Trakt adds to Medusa (before being added) is old. But if you knows is better, fine.

So please test this:
1) Add an episode to Watchlist in trakt for a show you doesn't have in Trakt
2) Set in medusa Trakt settings to "Get pilot only"

Medusa must add the show and set ONLY the first episode as wanted.
Let me know if works with your fix

**Comment by ratoaq2** [comment] 2017-05-28 05:27
I still have the same issue with latest develop

```
2017-05-27 23:33:27 ERROR    TRAKTCHECKER :: [1a2ba63] Exception generated: 'NoneType' object has no attribute 'get_episode'
Traceback (most recent call last):
  File "/volumeUSB1/usbshare/applications/sickrage/SickBeard/medusa/scheduler.py", line 103, in run
    self.action.run(self.force)
  File "/volumeUSB1/usbshare/applications/sickrage/SickBeard/medusa/trakt_checker.py", line 89, in run
    self.sync_watchlist()
  File "/volumeUSB1/usbshare/applications/sickrage/SickBeard/medusa/trakt_checker.py", line 320, in sync_watchlist
    self.sync_trakt_episodes()
  File "/volumeUSB1/usbshare/applications/sickrage/SickBeard/medusa/trakt_checker.py", line 555, in sync_trakt_episodes
    set_episode_to_wanted(show, trakt_season, trakt_episode)
  File "/volumeUSB1/usbshare/applications/sickrage/SickBeard/medusa/trakt_checker.py", line 37, in set_episode_to_wanted
    ep_obj = show.get_episode(season, episode)
AttributeError: 'NoneType' object has no attribute 'get_episode'
```

**Closed** 2017-05-29 17:30 UTC
Labels: Bug, Concluded
