### ISSUE TITLE
DownloadStation Error - download_station_client.py wrongly named

### ISSUE THREAD

**Issue by taochern** [pymedusa/Medusa#5631] opened 2018-11-05 01:45 UTC
I was getting an error when I attempted to use the downloadstation client in a new installation. Changing the file download_station_client.py to downloadstation_client.py corrected the error,

**Comment by sharkykh** [comment] 2018-11-05 05:15
Duplicate of #5559, fixed in `develop`.

**Closed by sharkykh** 2018-11-05 05:15 UTC
Labels: triage
