### ISSUE TITLE
Opening a page triggers a massive hit on the database, UI non-responsive until finished

### ISSUE THREAD

**Issue by labrys** [pymedusa/Medusa#1989] opened 2017-01-17 02:58 UTC
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**  Dev
**OS:** N/A
**What you did:** Opened the UI in browser
**What happened:** Slow response, viewing log saw tons of DB hits
**What you expected:**  Responsive UI
**Logs:**

Hundreds of the following lines appear: 
```
 main.db: SELECT last_refreshed FROM xem_refresh WHERE indexer = ? and indexer_id = ? with args [1, XXXXX]
 main.db: SELECT season, episode, scene_season, scene_episode FROM tv_episodes WHERE indexer = ? and showid = ? and (scene_season or scene_episode) != 0 ORDER BY season, episode with args [1, XXXXX]
 main.db: UPDATE [xem_refresh] SET last_refreshed = ?, indexer = ? WHERE indexer_id = ? with args [1484620490, 1, XXXXX]
```

**Comment by fernandog** [comment] 2017-01-30 20:54
already fixed in develop

**Comment by labrys** [comment] 2017-02-18 00:27
This was never fixed.

**Comment by fernandog** [comment] 2017-02-18 00:31
Yes it is. Look at that PR

**Comment by labrys** [comment] 2017-02-18 00:34
That was only half of the issue.. The other half was display show getting the entire db by requesting one show at a time instead of the entire results in a single query.

**Comment by fernandog** [comment] 2017-02-18 00:42
Would you point me the query that displayShow "getting the entire db"
What I see is querying by indexer

**Comment by fernandog** [comment] 2017-02-18 00:55
i can't find this MASSIVE hit on database.

my displayShow loads in Mako: 0.1796s  in a Rpi1. 

![image](https://cloud.githubusercontent.com/assets/2620870/23088464/fbd47df2-f563-11e6-983c-41e2547c5767.png)

A show with 12 seaons loads in Mako: 0.9527s.
So the issue we in fact XEM_REFRESH

**Comment by labrys** [comment] 2017-02-18 01:24
From initial issue:
```
 main.db: SELECT season, episode, scene_season, scene_episode FROM tv_episodes WHERE indexer = ? and showid = ? and (scene_season or scene_episode) != 0 ORDER BY season, episode with args [1, XXXXX]
```
That triggers one hit to db for every show.  If you have 10 shows, you wouldn't notice much, but this is O(n) complexity and since db access is slow, this is a significant performance issue.  Instead this should query for all shows in the db, making it O(1) complexity.

**Comment by fernandog** [comment] 2017-02-18 01:27
@labrys 
im lost. first you say about displayShow. but displayShow is about a single show

Anyway this should be moved to another issue as a feature request for DB improvement, maybe with new DB model.
Anyway closing this as there is nothing more we can do about it

**Comment by fernandog** [comment] 2017-02-18 01:28
what a childish attitude. i will unsubscribe for this issue

**Comment by labrys** [comment] 2017-02-18 01:30
Closing an issue that you don't understand is a childish.

**Comment by fernandog** [comment] 2017-02-18 01:31
again, not a BUG 😂 

what is not working?

**Comment by labrys** [comment] 2017-02-18 01:32
"...massive hit on the database, UI non-responsive until finished"  and I corrected my previous comment, removing reference to display show.

**Comment by fernandog** [comment] 2017-02-18 01:34
no one will fix this for you. 😂 

so its up to you. get to work

**Comment by labrys** [comment] 2017-02-18 01:35
Very mature attitude, yet I'm the one being childish because i reopened an issue that was not fully resolved.

**Comment by OmgImAlexis** [comment] 2017-02-18 02:09
If everyone could stop arguing that'd be great.

**Comment by p0psicles** [comment] 2017-02-18 12:19
I don't understand. The titel of the issue is talking about a massive db hit on opening a show in displayShow right? Let's keep the focus there. We can create one vague "we do too many db queries". Or something like that. But that won't get us anywhere.

In stead create specific issues, that can be resolved, and after the issue can be closed.

**Comment by labrys** [comment] 2017-02-18 14:14
The initial issue said nothing about displayShow ... the issue was during UI access.  3 specific db queries (listed as one issue since they all appeared in the logs sequentially) were listed as the root cause.  Two have been mostly addressed by the xem_refresh PR since the xem_refresh frequency has been drastically reduced.  The third db hit has not yet been addressed.

**Comment by labrys** [comment] 2017-02-18 17:16
This is not a DB upgrade issue, this is a shitty usage of SQL issue.

**Comment by labrys** [comment] 2017-02-18 17:23
Full log of starting Medusa, waiting for UI to completely finish loading, then refreshing the page: https://gist.github.com/labrys/8bef7dde9215832868b2d54c20f93da9

doing a `grep "SELECT season, episode, scene_season" application.log` on the logs shows that initial page load spends 6 seconds on the query.  second page load spends another 6 seconds on the query.

**Comment by labrys** [comment] 2017-02-18 17:32
Also more specifically, that is the exact same method "fixed" by the previous PR `get_xem_numbering_for_show` so it is most definitely related to the initial issue.

**Comment by ripper1967** [comment] 2017-02-18 17:50
Ok i can tell u loading time did increase again , I wasn't going to say nothing was just going to have the devs post about it i am currently at Load time: 2.4740s / Mako: 2.2380s | Branch: develop | Now: Saturday, 02/18/2017 12:45 PM  was only 0.32 to 0.95 average load times before.

**Comment by labrys** [comment] 2017-02-18 17:53
@ripper1967 There are actually multiple causes for the slow down, I'm restricting this one to those exclusively referenced in the initial issue.

**Comment by labrys** [comment] 2017-02-18 18:21
Full logs with a partial fix (e.g. improving the SQL statement and making `get_xem_numbering_for_show` lazy) and multiple reloads of the home page: https://gist.github.com/labrys/24534d220e092d8af406e610fac75e73

Doing a `grep "XEM_NUMBERING"` shows only a single hit (regardless of the number of page loads) to the DB lasting only 0.183000087738 seconds (including the time to build a dict from the results for lazy usage).
```
2017-02-18 13:06:41 INFO     Thread-33 :: [805e40e] BEGIN UPDATE XEM_NUMBERING: 1487441201.92
2017-02-18 13:06:42 INFO     Thread-33 :: [805e40e] END UPDATE XEM_NUMBERING: 1487441202.11
2017-02-18 13:06:42 INFO     Thread-33 :: [805e40e] TIME UPDATING XEM_NUMBERING: 0.183000087738
```

This is a partial fix because it does not include any refreshes of the numbering, although a refresh can be done easily by `XEM_NUMBERING = None` which would force the numbering to be rebuilt from the DB.  Ideally XEM_NUMBERING would be expired upon refresh of data from XEM or even better, adding update timestamps to the data and updating XEM_NUMBERING with only the fresh data.

**Closed** 2018-01-22 22:58 UTC
Labels: Bug, Priority: 2. Medium
