### ISSUE TITLE
[APP SUBMITTED]: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /shows/in-the-dark-2019/ratings (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000020CE47FA550>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

### ISSUE THREAD

**Issue by WarEagleUS21** [pymedusa/Medusa#9927] opened 2021-10-08 10:43 UTC
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.22000-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-10-08 00:10:06 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [21e350c] Could not connect to Trakt service: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /shows/in-the-dark-2019/ratings (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000020CE47FA550>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/urllib3/connection.py#L159">ext\urllib3\connection.py</a>", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/urllib3/util/connection.py#L80">ext\urllib3\util\connection.py</a>", line 80, in create_connection
    raise err
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/urllib3/util/connection.py#L70">ext\urllib3\util\connection.py</a>", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/urllib3/connectionpool.py#L600">ext\urllib3\connectionpool.py</a>", line 600, in urlopen
    chunked=chunked)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/urllib3/connectionpool.py#L343">ext\urllib3\connectionpool.py</a>", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/urllib3/connectionpool.py#L839">ext\urllib3\connectionpool.py</a>", line 839, in _validate_conn
    conn.connect()
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/urllib3/connection.py#L301">ext\urllib3\connection.py</a>", line 301, in connect
    conn = self._new_conn()
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/urllib3/connection.py#L168">ext\urllib3\connection.py</a>", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000020CE47FA550>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/requests/adapters.py#L449">ext\requests\adapters.py</a>", line 449, in send
    timeout=timeout
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/urllib3/connectionpool.py#L638">ext\urllib3\connectionpool.py</a>", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/urllib3/util/retry.py#L398">ext\urllib3\util\retry.py</a>", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /shows/in-the-dark-2019/ratings (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000020CE47FA550>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/medusa/show/recommendations/trakt.py#L165">medusa\show\recommendations\trakt.py</a>", line 165, in fetch_popular_shows
    recommended_show = self._create_recommended_show(show, subcat=trakt_list)
  File "<C:\Medusa\Medusa\ext\decorator.py:decorator-gen-54>", line 2, in _create_recommended_show
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/dogpile/cache/region.py#L1578">ext\dogpile\cache\region.py</a>", line 1578, in get_or_create_for_user_func
    key, user_func, timeout, should_cache_fn, (arg, kw)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/dogpile/cache/region.py#L1047">ext\dogpile\cache\region.py</a>", line 1047, in get_or_create
    async_creator,
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/dogpile/lock.py#L185">ext\dogpile\lock.py</a>", line 185, in __enter__
    return self._enter()
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/dogpile/lock.py#L94">ext\dogpile\lock.py</a>", line 94, in _enter
    generated = self._enter_create(value, createdtime)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/dogpile/lock.py#L178">ext\dogpile\lock.py</a>", line 178, in _enter_create
    return self.creator()
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/dogpile/cache/region.py#L996">ext\dogpile\cache\region.py</a>", line 996, in gen_value
    *creator_args[0], **creator_args[1]
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/medusa/show/recommendations/trakt.py#L68">medusa\show\recommendations\trakt.py</a>", line 68, in _create_recommended_show
    **{'rating': show.ratings['rating'],
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/trakt/core.py#L547">ext\trakt\core.py</a>", line 547, in inner
    json_data = self._handle_request('get', url)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/trakt/core.py#L518">ext\trakt\core.py</a>", line 518, in _handle_request
    headers=HEADERS)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/requests/api.py#L61">ext\requests\api.py</a>", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/requests/sessions.py#L542">ext\requests\sessions.py</a>", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/requests/sessions.py#L655">ext\requests\sessions.py</a>", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/requests/adapters.py#L516">ext\requests\adapters.py</a>", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /shows/in-the-dark-2019/ratings (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000020CE47FA550>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment] 2021-10-21 16:14
Duplicate of https://github.com/pymedusa/Medusa/issues/9938

**Closed as completed by medariox** 2021-10-21 16:14 UTC
