### ISSUE TITLE
Scene name per season not available anymore (& scene abs numbering not right & can't show result of manual search..)

### ISSUE THREAD

**Issue by hergonoway** [pymedusa/Medusa#7340] opened 2019-11-12 10:42 UTC
**INFO**
Python Version: 3.7.5 (default, Oct 17 2019, 12:25:15) [GCC 8.3.0]
Operating System: Linux-4.4.59+-x86_64-with
Locale: UTF-8
Branch: master
Database: 44.15
Commit: 918cfe7

**Describe the bug**
Scene name for season can't be seen with the new main show page interface. Can't see theXem icon per season with corresponding scene name anymore. Scene abs numbering seems to be quite ***ked up too :o, I don't know if it's related. I've performed a restart and full refresh of the show before posting this issue.

![image](https://user-images.githubusercontent.com/8405448/68663623-4eb84880-053f-11ea-8750-e8ee5f4133f3.png)

![image](https://user-images.githubusercontent.com/8405448/68663540-2deff300-053f-11ea-9300-62c862a2459c.png)

![image](https://user-images.githubusercontent.com/8405448/68663209-8d99ce80-053e-11ea-9d04-429ed9f88dab.png)

Worst when I perform a search nothing shows UP ; Here I manual force search for season 3 episode 2

![image](https://user-images.githubusercontent.com/8405448/68664192-398fe980-0540-11ea-8cc8-12f9a932f140.png)

But in the logs, it seems to catch results ... with the good season scene name...

Logs : https://pastebin.com/F1pjdpze

**Comment by p0psicles** [comment] 2019-11-12 11:02
Pfew, those are allot of reported issues. I'll pick them up one at a time.

**Comment by hergonoway** [comment] 2019-11-12 11:04
Sorry :( it stacked up while writing this issue

**Comment by p0psicles** [comment] 2019-11-12 11:05
What's wrong with the scene absolute column? You except different values?

**Comment by hergonoway** [comment] 2019-11-12 11:13
Well , for this season (PsychoPass 3) from ep 1 to 7 it’s tagged from 2 to 8 and 8 well 8 as for ep 7. I may understand in which case Scene Abs # may be useful, like same scene for a 2 part season, or a TV special as ep 0 so tagged as ep 1. But in this case it should be equal to the season ep number (at least up to the end of this season) —> http://thexem.de/xem/show/1345

**Comment by medariox** [comment] 2019-11-12 11:35
That is just fine. The abs. scene numbering is coming from theXEM and it is correct. It is mapping s3e01 to s2e11 and s3e01 to s3e02 etc. The reason why no results are showing up is because you have deleted the cache and the first search won't show up unless you refresh the page. If the scene abs. column confuses you, you can simply hide them.

**Comment by hergonoway** [comment] 2019-11-12 12:03
> That is just fine. The abs. scene numbering is coming from theXEM and it is correct. It is mapping s3e01 to s2e11 and s3e01 to s3e02 etc. The reason why no results are showing up is because you have deleted the cache and the first search won't show up unless you refresh the page. If the scene abs. column confuses you, you can simply hide them.

Regarding Asb# : really ? I don't see it like that on 
![image](https://user-images.githubusercontent.com/8405448/68669412-b9bb4c80-054a-11ea-9ec4-6f568905d3a8.png)

nor in the change logs : 
![image](https://user-images.githubusercontent.com/8405448/68669202-444f7c00-054a-11ea-9918-b86d75d4141b.png)

It won't bother me since it's not something I use, just wanted to be sure that there no issue because it's just too strange to see since there's no offset between TVdb and Anidb, at least from what I see on http://thexem.de/xem/show/1345

Regarding Manual Search issue : I tried on Safari and Chrome (last stable version for both without any adblocker enabled), refreshed the page (F5 or cmd+R), but still nothing shows up, when I refresh the page the mention " The episode is being searched, please wait......" reroll above the result tab then state "Search finished" and still nothing. I've tried multiple times. Tried also in incognito mode, same result.

**Comment by medariox** [comment] 2019-11-12 13:06
This is what theXEM API returns for that show, so that's what's being used. You can report it to them if you wish: https://github.com/thezoggy/xem, we have no control over that whatsoever.

Looking at the logs it seems like guessit confuses the release for a multi-ep results: `Found multi-episode (2, 3) result [Erai-raws].Psycho-Pass.3.-.02.[720p][Multiple.Subtitle].mkv`

So this is actually a guessit bug affecting exactly one show. Please make sure to specify this kind of things in the bug report next time, as it reduces the time required to find the cause by a lot.

**Comment by hergonoway** [comment] 2019-11-12 13:35
> This is what theXEM API returns for that show, so that's what's being used. You can report it to them if you wish: https://github.com/thezoggy/xem, we have no control over that whatsoever.
> 
> Looking at the logs it seems like guessit confuses the release for a multi-ep results: `Found multi-episode (2, 3) result [Erai-raws].Psycho-Pass.3.-.02.[720p][Multiple.Subtitle].mkv`
> 
> So this is actually a guessit bug affecting exactly one show. Please make sure to specify this kind of things in the bug report next time, as it reduces the time required to find the cause by a lot.

Sorry for the inconvenience, I've discovered the download issue after submiting the issue, between the logs and the fact that season scene name is not shown anymore, I thought at first that scene season wasn't handled anymore

**Comment by p0psicles** [comment] 2019-11-16 11:42
Scene name for season can't be seen with the new main show page interface
will be fixed with: #7360

**Comment by medariox** [comment] 2019-11-17 22:36
Fixed with https://github.com/pymedusa/Medusa/pull/7360

**Closed by medariox** 2019-11-17 22:36 UTC
Labels: Bug, Guessit
