### ISSUE TITLE
No download files location for Synology DS

### ISSUE THREAD

**Issue by peppinl** [pymedusa/Medusa#5395] opened 2018-10-13 08:54 UTC
**Describe the bug**
No download files location to set for Synology DS. 

**To Reproduce**
1. Install it on windows 10/Synology Nas
2. Check torrent search
3. No error, simply nothing to fill. 

**Expected behavior**
A field to fill in the Download location for TV shows with Synology DS.

**Screenshots**
![image](https://user-images.githubusercontent.com/638852/46903476-c3046080-ced5-11e8-84f0-5ff4ed33d724.png)

**Medusa (please complete the following information):**
 - OS: Windows 10 
 - Branch: master
 - Commit: 5acfc6

**Logs:**
No log files to attach

**Additional context**
This is happening on a Synology NAS as well as Windows 10. I've noticed that the SABNZBD logo appears instead of the Synology logo.

**Comment by ward0** [comment] 2018-10-15 07:20
I seem to have the same problem:

`2018-10-15 09:18:06 WARNING  Thread_9 :: [4614efc] Error: {u'success': False, u'error': {u'code': 400}}
2018-10-15 09:18:06 DEBUG    Thread_9 :: [4614efc] User-Agent: Medusa/0.2.10 (Linux; 4.4.59+; ef88390f-d03a-11e8-ac94-001132906ee2)
2018-10-15 09:18:06 DEBUG    Thread_9 :: [4614efc] GET URL: http://localhost:5000/webapi/auth.cgi?session=DownloadStation&account=**********&version=2&format=cookie&passwd=**********&api=SYNO.API.Auth&method=login [Status: 200]
2018-10-15 09:18:02 DEBUG    Thread_9 :: [4614efc] User-Agent: Medusa/0.2.10 (Linux; 4.4.59+; ef88390f-d03a-11e8-ac94-001132906ee2)`

**Comment by SirMaple** [comment] 2018-10-17 14:37
I have the same issue:

`2018-10-17 08:28:08 INFO     SNATCHQUEUE-MANUALSNATCH-72108 :: [4614efc] Request failed: HTTPSConnectionPool(host='192.168.0.175', port=5001): Max retries exceeded with url: /webapi/auth.cgi?session=DownloadStation&account=**********&version=2&format=cookie&passwd=***********&api=SYNO.API.Auth&method=login (Caused by ProxyError('Cannot connect to proxy.', error(104, 'Connection reset by peer')))`

Download Station Version: 3.8.11-3517
DSM Version: DSM 6.2.1-23824

**Comment by medariox** [comment] 2018-10-17 15:11
Fixed with https://github.com/pymedusa/Medusa/pull/5443

**Comment by medariox** [comment] 2018-10-18 13:11
Fixed in develop.

**Closed by medariox** 2018-10-18 13:11 UTC
Labels: Bug, Fixed
