### ISSUE TITLE
Manual Post-Processing does not work when the directory is not changed on each execution

### ISSUE THREAD

**Issue by reconman** [pymedusa/Medusa#9377] opened 2021-03-22 18:58 UTC
**Describe the bug**
When you go to the manual Post-Processing page, the directory will already be filled in with the directory from Config -> Post-Processing -> Post-Processing Dir.

If you don't change the directory, the HTTP request sent to medusa when clicking `Process` will always be empty. Clicking on the file selector and then clicking OK does not change anything, only clicking on ".." in the file selector and then choosing the directory again.

**To Reproduce**
1. Configure a valid Post-Processing directory in Config -> Post-Processing -> Post-Processing Dir
2. Go to Manual Post-Processing
3. Enter some valid settings, but leave the Post-Processing directory untouched and click `Process`
4. Nothing happens. If you look into the network tab of the Chrome Developer Console, the request has an empty `proc_dir` attribute.

**Expected behavior**
The default Post-Processing directory should be used in the request.

**Screenshots:**
![image](https://user-images.githubusercontent.com/12360257/112043088-91812c00-8b48-11eb-99aa-c9876ee31aea.png)

**Medusa (please complete the following information):**
- OS: Docker container
- Branch: master
- Commit: 55cecb9e821fb15f20efe75b0f59d13e896e1d87
- Python version: Unknown
- Database version: Unknown

**Comment by jaybone2012** [comment] 2021-03-29 08:19
Confirmed this also impacts nzbToMedia post processing script
Error is "missing post processing dir"

**Comment by noodle-** [comment] 2021-03-30 11:44
> Confirmed this also impacts nzbToMedia post processing script
> Error is "missing post processing dir"

While trying to process a fully automated download you mean? I think that's not related to this issue, or at least fixable through nzbToMedia config as automated downloads are still working fine through nzbToMedia for me since the update.

If you mean while starting post-processing manually then yea of course.

**Comment by reconman** [comment] 2021-04-09 09:58
Seems to have been fixed in develop?

**Comment by p0psicles** [comment] 2021-04-09 11:09
Ooh sorry no. I still need to fix this one

**Comment by reconman** [comment] 2021-04-09 11:18
Right, I wasn't able to reproduce it, but now I can again.

**Comment by p0psicles** [comment] 2021-04-11 11:33
I tried it out, but it's working fine for me. I followed your steps.
But it's sending the default configured proc_dir through the api call.

**Comment by reconman** [comment] 2021-04-11 12:47
Seems to be related to how you get to the post-processing page.

If you go to /home and then navigate to the Post-Processing page via Shows -> Manual Post-Processing, it doesn't work. If you go to /home/postprocess/ directly, it works.

**Comment by p0psicles** [comment] 2021-05-12 14:38
This one whould be fixed. Closing it.

**Closed by p0psicles** 2021-05-12 14:38 UTC
