### ISSUE TITLE
[APP SUBMITTED]: TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#3088] opened 2017-09-10 16:28 UTC
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@1d0d7ea39cddd8b0a40f0dcec26dfa2eeac724fd
**Link to Log**: https://gist.github.com/87fa972c3a12bb5c1669ff8fcea04bf6
### ERROR
<pre>
2017-09-10 17:21:43 ERROR    Thread-16 :: [1d0d7ea] Exception generated: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/1d0d7ea39cddd8b0a40f0dcec26dfa2eeac724fd/medusa/server/web/core/base.py#L258">medusa/server/web/core/base.py</a>", line 258, in async_call
    result = function(**kwargs)
  File "/home/pi/Medusa/<a href="../blob/1d0d7ea39cddd8b0a40f0dcec26dfa2eeac724fd/medusa/server/web/home/handler.py#L2252">medusa/server/web/home/handler.py</a>", line 2252, in manual_search_subtitles
    ui.notifications.message(ep_obj.series.name, 'No subtitle found')
  File "/home/pi/Medusa/<a href="../blob/1d0d7ea39cddd8b0a40f0dcec26dfa2eeac724fd/medusa/ui.py#L51">medusa/ui.py</a>", line 51, in message
    'hash': hash(new_notification)}}))
  File "/home/pi/Medusa/<a href="../blob/1d0d7ea39cddd8b0a40f0dcec26dfa2eeac724fd/medusa/ws/MedusaWebSocketHandler.py#L30">medusa/ws/MedusaWebSocketHandler.py</a>", line 30, in push_to_web_socket
    client.write_message(msg)
  File "/home/pi/Medusa/<a href="../blob/1d0d7ea39cddd8b0a40f0dcec26dfa2eeac724fd/lib/tornado/websocket.py#L218">lib/tornado/websocket.py</a>", line 218, in write_message
    return self.ws_connection.write_message(message, binary=binary)
  File "/home/pi/Medusa/<a href="../blob/1d0d7ea39cddd8b0a40f0dcec26dfa2eeac724fd/lib/tornado/websocket.py#L693">lib/tornado/websocket.py</a>", line 693, in write_message
    return self._write_frame(True, opcode, message, flags=flags)
  File "/home/pi/Medusa/<a href="../blob/1d0d7ea39cddd8b0a40f0dcec26dfa2eeac724fd/lib/tornado/websocket.py#L676">lib/tornado/websocket.py</a>", line 676, in _write_frame
    return self.stream.write(frame)
  File "/home/pi/Medusa/<a href="../blob/1d0d7ea39cddd8b0a40f0dcec26dfa2eeac724fd/lib/tornado/iostream.py#L398">lib/tornado/iostream.py</a>", line 398, in write
    self._handle_write()
  File "/home/pi/Medusa/<a href="../blob/1d0d7ea39cddd8b0a40f0dcec26dfa2eeac724fd/lib/tornado/iostream.py#L850">lib/tornado/iostream.py</a>", line 850, in _handle_write
    _merge_prefix(self._write_buffer, num_bytes)
  File "/home/pi/Medusa/<a href="../blob/1d0d7ea39cddd8b0a40f0dcec26dfa2eeac724fd/lib/tornado/iostream.py#L1528">lib/tornado/iostream.py</a>", line 1528, in _merge_prefix
    if len(deque) == 1 and len(deque[0]) <= size:
TypeError: object of type 'NoneType' has no len()
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sharkykh** [comment] 2018-04-28 09:55
@medariox I remember seeing this bug on tornadoweb/tornado repo - they keep insisting that this `deque` issue is the result of using threading and not combing back to IOLoop (main tornado thread) to use `self.write`, `self.finish` and the likes.

**Comment by labrys** [comment] 2018-04-28 13:58
@sharkykh in my custom fork of medusa I have pinned Tornado at < 5 as it breaks medusa hard in Python 3.6 due to the use of threading, so I wouldn't be surprised if this is a threading issue.

**Comment by medariox** [comment] 2018-04-28 14:12
@sharkykh This is almost certainly caused by our current implementation of WS. Certainly not caused by Tornado 5, since it was already happening with Tornado 4.

**Comment by medariox** [comment] 2018-06-07 11:44
Fixed with: https://github.com/pymedusa/Medusa/pull/4312

**Closed by medariox** 2018-06-07 11:44 UTC
Labels: Bug
