### ISSUE TITLE
[APP SUBMITTED]: KeyError: 371572

### ISSUE THREAD

**Issue by Avian-Flew** [pymedusa/Medusa#7623] opened 2020-01-23 22:04 UTC
### INFO
**Python Version**: `3.7.4 (default, Oct 02 2019, 11:13:20) [GCC 7.4.0]`
**Operating System**: `Linux-4.1.13-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@942040af95311a71d9663236c7136434b6711ca5
**Link to Log**: https://gist.github.com/7dac7a5a10ccb9657c419a009a4ce02e
### ERROR
<pre>
2020-01-23 22:02:09 ERROR    SHOWUPDATER :: [942040a] Problem running show_updater, Indexer TVDBv2 seems to be having issues while trying to get updates for show House of the Dragon. Cause: KeyError(371572)
Traceback (most recent call last):
  File "/mnt/HD/HD_a2/Nas_Prog/medusa/Medusa/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/ext/tvdbapiv2/rest.py#L54">ext/tvdbapiv2/rest.py</a>", line 54, in request
    r.raise_for_status()
  File "/mnt/HD/HD_a2/Nas_Prog/medusa/Medusa/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/ext/requests/models.py#L940">ext/requests/models.py</a>", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://tvdb2.plex.tv/series/371572/episodes/query?page=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/HD/HD_a2/Nas_Prog/medusa/Medusa/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/medusa/indexers/tvdbv2/tvdbv2_api.py#L277">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 277, in _query_series
    tvdb_id, page=page, accept_language=self.config['language']
  File "/mnt/HD/HD_a2/Nas_Prog/medusa/Medusa/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/ext/tvdbapiv2/apis/series_api.py#L468">ext/tvdbapiv2/apis/series_api.py</a>", line 468, in series_id_episodes_query_get
    callback=params.get('callback'))
  File "/mnt/HD/HD_a2/Nas_Prog/medusa/Medusa/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/ext/tvdbapiv2/api_client.py#L295">ext/tvdbapiv2/api_client.py</a>", line 295, in call_api
    response_type, auth_settings, callback)
  File "/mnt/HD/HD_a2/Nas_Prog/medusa/Medusa/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/ext/tvdbapiv2/api_client.py#L122">ext/tvdbapiv2/api_client.py</a>", line 122, in __call_api
    post_params=post_params, body=body)
  File "/mnt/HD/HD_a2/Nas_Prog/medusa/Medusa/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/ext/tvdbapiv2/api_client.py#L315">ext/tvdbapiv2/api_client.py</a>", line 315, in request
    headers=headers)
  File "/mnt/HD/HD_a2/Nas_Prog/medusa/Medusa/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/ext/tvdbapiv2/rest.py#L70">ext/tvdbapiv2/rest.py</a>", line 70, in get
    query_params=query_params)
  File "/mnt/HD/HD_a2/Nas_Prog/medusa/Medusa/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/ext/tvdbapiv2/rest.py#L63">ext/tvdbapiv2/rest.py</a>", line 63, in request
    raise ApiException(status=status, reason=msg)
tvdbapiv2.exceptions.ApiException: (404)
Reason: HTTPError
404 Client Error: Not Found for url: https://tvdb2.plex.tv/series/371572/episodes/query?page=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/HD/HD_a2/Nas_Prog/medusa/Medusa/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/medusa/show_updater.py#L147">medusa/show_updater.py</a>", line 147, in run
    update_max_weeks)
  File "/mnt/HD/HD_a2/Nas_Prog/medusa/Medusa/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/medusa/indexers/tvdbv2/tvdbv2_api.py#L666">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 666, in get_last_updated_seasons
    episodes = self._query_series(show_id)
  File "/mnt/HD/HD_a2/Nas_Prog/medusa/Medusa/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/medusa/indexers/tvdbv2/fallback.py#L135">medusa/indexers/tvdbv2/fallback.py</a>", line 135, in __call__
    return self.func(*args, **kwargs)
  File "/mnt/HD/HD_a2/Nas_Prog/medusa/Medusa/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/medusa/indexers/tvdbv2/tvdbv2_api.py#L294">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 294, in _query_series
    if error.status == 404 and not self.shows[tvdb_id]['firstaired']:
KeyError: 371572
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment] 2020-01-31 10:50
Duplicate of https://github.com/pymedusa/Medusa/issues/7511

**Closed by medariox** 2020-01-31 10:50 UTC
Labels: triage
