### ISSUE TITLE
Include subtitles from subfolders when post-processing (manual or auto)

### ISSUE THREAD

**Issue by Xanobia** [pymedusa/Medusa#5689] opened 2018-11-10 13:00 UTC
**Is your feature request related to a problem? Please describe.**
It would be really cool if the subtitles files (that some torrent keep in a subfolder) is scanned and processed when the media file is

**Describe the solution you'd like**
When processing - any subfolder holding subtitles matching the media should be processed as well

**Comment by phoenix83** [comment] 2019-03-23 08:49
Appears to be a duplicate of #4034?

**Comment by medariox** [comment] 2020-12-15 16:58
Added.

**Closed by medariox** 2020-12-15 16:58 UTC
Labels: Feature request
