### ISSUE TITLE
1883   file update not working correctly;

### ISSUE THREAD

**Issue by nydave69** [pymedusa/Medusa#10353] opened 2022-02-16 21:21 UTC
**Describe the bug**
Noticed that series 1883 had lost some episodes.  Tried a refresh.  things got worse.

now looks like this;
![image](https://user-images.githubusercontent.com/14140816/154356768-3b2cf3ee-d740-4623-a59c-d0819eed4441.png)

the folder has;
![image](https://user-images.githubusercontent.com/14140816/154356902-84ed9db7-8227-4461-8702-0aa5c2b81019.png)

the log shows;
2022-02-16 15:45:22 INFO	SHOWQUEUE-REFRESH :: [4908f30] Cache check completed
2022-02-16 15:45:22 INFO	SHOWQUEUE-REFRESH :: [4908f30] 396390: Updating NFOs for show with new indexer info
2022-02-16 15:45:22 INFO	SHOWQUEUE-REFRESH :: [4908f30] Trying to clean any empty folder under O:\series\1883 (2021)
2022-02-16 15:45:21 INFO	SHOWQUEUE-REFRESH :: [4908f30] 396390: Looking for hanging associated files for: '1883' S01E05 in: O:\series\1883 (2021)\Season 01\1883 (2021) (S01E05) (2022-01-09) (1080p-h264 BluRay EAC3-6ch) TBA.mkv
2022-02-16 15:45:21 INFO	SHOWQUEUE-REFRESH :: [4908f30] 396390: Looking for hanging associated files for: '1883' S01E03 in: O:\series\1883 (2021)\Season 01\1883 (2021) (S01E03) (2021-12-26) (1080p-h264 BluRay EAC3-6ch) River.mkv
2022-02-16 15:45:21 INFO	SHOWQUEUE-REFRESH :: [4908f30] 396390: Looking for hanging associated files for: '1883' S01E02 in: O:\series\1883 (2021)\Season 01\1883 (2021) (S01E02) (2021-12-19) (1080p-h264 BluRay AC3-2ch) Behind Us, A Cliff.mkv
2022-02-16 15:45:20 INFO	SHOWQUEUE-REFRESH :: [4908f30] 396390: Looking for hanging associated files for: '1883' S01E01 in: O:\series\1883 (2021)\Season 01\1883 (2021) (S01E01) (2021-12-19) (1080p-h264 BluRay AC3-2ch) 1883.mkv
2022-02-16 15:45:16 INFO	SHOWQUEUE-REFRESH :: [4908f30] 396390: Performing refresh on 1883
2022-02-16 15:43:13 INFO	POSTPROCESSOR :: [4908f30] Post-processing completed.
2022-02-16 15:35:03 INFO	SHOWQUEUE-REFRESH :: [4908f30] Cache check completed

and from the command window;
2022-02-16 15:45:19 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] Series result returned zero
2022-02-16 15:45:20 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] Series 1883 is anime
2022-02-16 15:45:20 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] 396390: No entries found in show: 1883
2022-02-16 15:45:20 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] 396390: The result that was found (O:\series\1883 (2021)\Season 01\1883 (2021) (S01E01) (2021-12-19) (1080p-x264 BluRay AC3-2ch) 1883.mkv) i
s not yet supported by Medusa and will be skipped. Sorry.
2022-02-16 15:45:20 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] 396390: Creating episode from: O:\series\1883 (2021)\Season 01\1883 (2021) (S01E03) (2021-12-26) (1080p-AVC BluRay EAC3-6ch) River.mkv
2022-02-16 15:45:20 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] 396390: Creating episode object from O:\series\1883 (2021)\Season 01\1883 (2021) (S01E03) (2021-12-26) (1080p-AVC BluRay EAC3-6ch) River.mkv

2022-02-16 15:45:20 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] Using guessit cache item for O:\series\1883 (2021)\Season 01\1883 (2021) (S01E03) (2021-12-26) (1080p-AVC BluRay EAC3-6ch) River.mkv
2022-02-16 15:45:20 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] Series 1883 is anime
2022-02-16 15:45:20 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] 396390: No entries found in show: 1883
2022-02-16 15:45:20 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] 396390: The result that was found (O:\series\1883 (2021)\Season 01\1883 (2021) (S01E03) (2021-12-26) (1080p-AVC BluRay EAC3-6ch) River.mkv)
is not yet supported by Medusa and will be skipped. Sorry.
2022-02-16 15:45:20 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] 396390: Loading all episodes from '1883' with a location from the database
2022-02-16 15:45:20 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] 396390: Location for '1883' S01E01 doesn't exist and current status is 'Downloaded', removing it and changing status to 'Archived'
2022-02-16 15:45:20 INFO     SHOWQUEUE-REFRESH :: [4908f30] 396390: Looking for hanging associated files for: '1883' S01E01 in: O:\series\1883 (2021)\Season 01\1883 (2021) (S01E01) (2021-12-19) (1080p
-h264 BluRay AC3-2ch) 1883.mkv
2022-02-16 15:45:20 DEBUG    APIv2-Thread_7 :: [4908f30] Broken providers already updated in the last hour
2022-02-16 15:45:21 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] No associated files were found for O:\series\1883 (2021)\Season 01\1883 (2021) (S01E01) (2021-12-19) (1080p-h264 BluRay AC3-2ch) 1883.mkv
2022-02-16 15:45:21 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] 396390: Location for '1883' S01E02 doesn't exist and current status is 'Downloaded', removing it and changing status to 'Archived'
2022-02-16 15:45:21 INFO     SHOWQUEUE-REFRESH :: [4908f30] 396390: Looking for hanging associated files for: '1883' S01E02 in: O:\series\1883 (2021)\Season 01\1883 (2021) (S01E02) (2021-12-19) (1080p
-h264 BluRay AC3-2ch) Behind Us, A Cliff.mkv
2022-02-16 15:45:21 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] No associated files were found for O:\series\1883 (2021)\Season 01\1883 (2021) (S01E02) (2021-12-19) (1080p-h264 BluRay AC3-2ch) Behind Us,
A Cliff.mkv
2022-02-16 15:45:21 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] 396390: Location for '1883' S01E03 doesn't exist and current status is 'Downloaded', removing it and changing status to 'Archived'
2022-02-16 15:45:21 INFO     SHOWQUEUE-REFRESH :: [4908f30] 396390: Looking for hanging associated files for: '1883' S01E03 in: O:\series\1883 (2021)\Season 01\1883 (2021) (S01E03) (2021-12-26) (1080p
-h264 BluRay EAC3-6ch) River.mkv
2022-02-16 15:45:21 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] No associated files were found for O:\series\1883 (2021)\Season 01\1883 (2021) (S01E03) (2021-12-26) (1080p-h264 BluRay EAC3-6ch) River.mkv
2022-02-16 15:45:21 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] 396390: Location for '1883' S01E05 doesn't exist and current status is 'Downloaded', removing it and changing status to 'Archived'
2022-02-16 15:45:21 INFO     SHOWQUEUE-REFRESH :: [4908f30] 396390: Looking for hanging associated files for: '1883' S01E05 in: O:\series\1883 (2021)\Season 01\1883 (2021) (S01E05) (2022-01-09) (1080p
-h264 BluRay EAC3-6ch) TBA.mkv
2022-02-16 15:45:22 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] No associated files were found for O:\series\1883 (2021)\Season 01\1883 (2021) (S01E05) (2022-01-09) (1080p-h264 BluRay EAC3-6ch) TBA.mkv
2022-02-16 15:45:22 INFO     SHOWQUEUE-REFRESH :: [4908f30] Trying to clean any empty folder under O:\series\1883 (2021)
2022-02-16 15:45:22 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] Not deleting O:\series\1883 (2021)\.actors. The folder is not empty or should be kept.
2022-02-16 15:45:22 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] Not deleting O:\series\1883 (2021)\Season 01. The folder is not empty or should be kept.
2022-02-16 15:45:22 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] Transaction with 4 queries executed
2022-02-16 15:45:22 INFO     SHOWQUEUE-REFRESH :: [4908f30] 396390: Updating NFOs for show with new indexer info
2022-02-16 15:45:22 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] Checking if O:\series\1883 (2021)\tvshow.nfo exists: True
2022-02-16 15:45:22 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] Metadata provider KODI updating series indexer info metadata file for 1883
2022-02-16 15:45:22 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] Checking if O:\series\1883 (2021)\tvshow.nfo exists: True
2022-02-16 15:45:22 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] Metadata provider KODI 12+ updating series indexer info metadata file for 1883
2022-02-16 15:45:22 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] Checking if O:\series\1883 (2021)\folder.jpg exists: True

and I found season 1 episode 5 in the trash..
I had all 8 episodes listed yesterday

 Medusa Info:	Branch: master
Commit: 4908f30db4fb3d9d6e59c51ca07deab95fb03a91
Version: 0.5.24
Database: 44.19
 Python Version:	3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
 SSL Version:	OpenSSL 1.1.0j 20 Nov 2018
 OS:	Windows-7-6.1.7601-SP1
 Locale:	en_US.cp1252
 Timezone:	Eastern Standard Time
 	 
 	 
 User:	Plex
 Program Folder:	C:\Medusa\Medusa
 Config File:	C:\Medusa\Data\config.ini
 Database File:	C:\Medusa\Data\main.db
 Cache Folder:	C:\Medusa\Data\cache
 Log Folder:	C:\Medusa\Data\Logs
 Arguments:	
--nolaunch --datadir=C:\Medusa\Data
 	 
I haven't tried a refresh on any other series since this one didn't turn out so good.
I'm checking other series to see if any are missing episodes..

2022-02-16 15:45:20 DEBUG    SHOWQUEUE-REFRESH :: [4908f30] Series 1883 is anime;
![image](https://user-images.githubusercontent.com/14140816/154359567-dcf16c44-56b5-466d-b8a4-f19e5edcbb14.png)

I don't have any anime...

**Comment by nydave69** [comment] 2022-02-17 15:50
Anything on this?

**Comment by p0psicles** [comment] 2022-02-17 17:35
Medusa doesn't remove episodes.
It's nog possible.

**Comment by p0psicles** [comment] 2022-02-18 09:50
I noticed an issue with the rule that was supposed to parse the release `/1883 (2021)/Season 01/1883 (2021) (S01E03) (2021-12-26) (1080p-AVC BluRay EAC3-6ch) River.mkv`. But somehow it still parsed an absolute episode number of 1883. Which should only be the shows title.

This should be fixed in PR #10358

**Comment by p0psicles** [comment] 2022-02-18 15:01
Could you enable debug. And then refresh a show. You could create a backup of the show folder if your not sure

**Comment by nydave69** [comment] 2022-02-18 16:26
> Could you enable debug. And then refresh a show. You could create a backup of the show folder if your not sure

[application.1.log](https://github.com/pymedusa/Medusa/files/8098705/application.1.log)

Here is the log,  Please remove from post

**Comment by nydave69** [comment] 2022-02-18 16:34
After that refresh,  the tool tips now show the correct file path for season 5

episodes 4 and 7 are missing and not in the recycle folder..

**Comment by nydave69** [comment] 2022-02-18 17:03
Found another show BattleBots (2015) season 6

![image](https://user-images.githubusercontent.com/14140816/154725598-7f3a9826-df2d-4218-af9e-608b06dd2e4f.png)

![image](https://user-images.githubusercontent.com/14140816/154725960-b907ee3c-5495-4211-a1df-b78439aa090a.png)

Here is the file locations for season 6 from the database..
![image](https://user-images.githubusercontent.com/14140816/154727654-ad98858a-6164-4a32-b6be-4cbfa5b04ce5.png)

the last 2 have a folder that should not be known by Medusa and there are no files in that folder
The files would not be processed by any app to that folder.  

I wish I had thought of getting the file locations for Engineering Catastrophes (2018) from the DB before the update..
It had more wrong locations..

**Comment by p0psicles** [comment] 2022-02-19 09:41
The log you posted has no information on the show refresh.
If you can reproduce this to a show refresh, then we might be able to quickly address the issue. But for that I need relevant logs.

So Again, refresh a show. And then try to `grep` on the application.log. Like. `grep "REFRESH" ./application.log`

If this is a bug introduced in the last release, then i'd expect more users notice episodes missing. I'll ask around for that.
But the only change made to the refresh process is in this PR: https://github.com/pymedusa/Medusa/pull/10316

But you can see it's only a minimal change. So you could possible revert that code change in your `post_processor.py` and see if that fixes the issue? https://github.com/pymedusa/Medusa/pull/10316/files#diff-fb2b5b3afd4cea77e24b390d741de2ce8245c74d1509d241f8bf88d76e9aa839L213

**Comment by nydave69** [comment] 2022-02-19 15:40
O:\utorrent\compledDownload  is where all the utorrents download to depending on their label
Medusa should only know O:\utorrent\compledDownload\MU not any others...

the SER, SC and others are used by other apps... and they haven't been affected.
I have never seen a MU download in any other folder as it would trigger errors from the other apps....

> Can you confirm that an episode that has been postprocessed recently (like in the last week) has been put in a wrong location?

That's the thing about this is it doesn't put the files in these odd locatations, just puts the location in the DB for the episode.
For the downloaded file I'm not sure, all I know is that files in seasons that were complete start loosing episodes, Medusa should not even look at those as they are complete and not needed.

OK,  I have three files sitting in MU that finished downloading since I shut down Medusa, they are all current release episodes
Before I start Medusa and see what happens any suggestions?

**Comment by nydave69** [comment] 2022-02-20 12:39
Update..

In checking,  the only thing I can think of is that the new download handling is looking at all files that are in the downloading queue including those from other apps..  I turned download handling off and turned Scheduled Post-Processor back on.
cleaned up as much of the shows as I can and restarted.

**Comment by medariox** [comment] 2022-06-13 09:08
Seems to be fixed? Ping if not.

**Closed by medariox** 2022-06-13 09:08 UTC
