### ISSUE TITLE
Show title link is obstructed by poster link on show page

### ISSUE THREAD

**Issue by xnick** [pymedusa/Medusa#4190] opened 2018-05-12 13:25 UTC
**Branch/Commit:** Master/77b20916ab577b82112ebc624f816054788c63f2
**OS:** Linux-4.16.7-1-ARCH-x86_64-with-glibc2.2.5
**What you did:** Clicked on the show name that is above the poster image (See images below)
**What happened:** Linked to the poster image
**What you expected:** To link to the show page
**Logs:** Request if applicable

If I click on the part of the show's name that is directly above the poster, I am linked to the poster instead of the show itself. In the following image that is the link that is provided when I hover over "DuckTales". 
![mouse_on_ducktales](https://user-images.githubusercontent.com/4283706/39957752-9f7b7c6e-5600-11e8-9750-937c4b0d6e40.png)

On the other hand, if I hover over "(2017)".
![mouse_on_2017](https://user-images.githubusercontent.com/4283706/39957755-a3a19986-5600-11e8-8814-d90ae7bad38e.png)

I am correctly linked to the show's page.

If I hit inspect element on "Ducktales"
![inspect](https://user-images.githubusercontent.com/4283706/39957758-a6be12f2-5600-11e8-9abc-7864acf258ff.png)

Confirmed in both Firefox and Chrome. Same applies to all shows obviously, not just DuckTales. :)

**Comment by p0psicles** [comment] 2018-05-12 13:40
Fixed in develop branch. Tnx for reporting!

**Closed by p0psicles** 2018-05-12 13:40 UTC

**Comment by sharkykh** [comment] 2018-05-12 14:04
Not fixed yet. But the issue was identified. #4060

**Comment by p0psicles** [comment] 2018-05-12 14:11
@omgimalexis can you look at this pls?

**Comment by xnick** [comment] 2018-05-12 14:27
Weirdly, I did search 'title link poster' before posting this issue. Now I can see #4060 in the results. I guess I didn't notice it. Sorry for that!

**Comment by sharkykh** [comment] 2018-05-12 14:46
@xnick It had a different title, this is the second issue to be a duplicate of that, so I changed the title to be more descriptive of the isuse.
