### ISSUE TITLE
[APP SUBMITTED]: OperationalError: table tv_episodes has no column named watched

### ISSUE THREAD

**Issue by bulls23nt** [pymedusa/Medusa#5202] opened 2018-09-12 19:23 UTC
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.4.121-1.el7.elrepo.x86_64-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/22d0089b1db28c72b05b560cb5c9b924
### ERROR
<pre>
2018-09-12 18:55:35 ERROR    SHOWQUEUE-UPDATE :: [4614efc] DB error: OperationalError('table tv_episodes has no column named watched',)
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/db.py#L115">medusa/db.py</a>", line 115, in _execute
    sql_results = cursor.execute(query, args)
OperationalError: table tv_episodes has no column named watched
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment] 2018-09-12 19:35
https://github.com/pymedusa/Medusa/issues/4917#issuecomment-414308310

**Comment by sharkykh** [comment] 2018-09-12 21:49
Duplicate of #5203

**Closed by sharkykh** 2018-09-12 21:49 UTC
Labels: triage
