### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'MutableMapping'"

### ISSUE THREAD

**Issue by OneCDOnly** [pymedusa/Medusa#10171] opened 2021-12-16 20:21 UTC
Hi guys, after upgrading to Python 3.10, it seems Medusa no-longer wants to start. 😞 

- QNAP NAS running QTS 5.0.0 #20211201
- Python 3.10.0 installed via Entware
- Medusa is installed via the [sherpa](https://github.com/OneCDOnly/sherpa) package manager and is pulled from `master` branch source before each application start.
- `pip` was used to install all modules as per `requirements.txt`
```
[~] # /etc/init.d/omedusa.sh start
daemon: NOT active
file (/opt/bin/git): exists
update 'OMedusa' from remote repository: OK
current git branch: master
file (/opt/bin/python3): exists
load UI ports from application: OK
start daemon: failed!
= ExecuteAndLog()
output: "Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/medusa/__init__.py", line 24, in <module>
    initialize()
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/medusa/init/__init__.py", line 37, in initialize
    _configure_guessit()
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/medusa/init/__init__.py", line 201, in _configure_guessit
    import guessit
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/guessit/__init__.py", line 8, in <module>
    from .api import guessit, GuessItApi
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/guessit/api.py", line 17, in <module>
    from .rules import rebulk_builder
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/guessit/rules/__init__.py", line 11, in <module>
    from .properties.episodes import episodes
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/guessit/rules/properties/episodes.py", line 16, in <module>
    from .title import TitleFromPosition
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/guessit/rules/properties/title.py", line 11, in <module>
    from .language import (
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/guessit/rules/properties/language.py", line 10, in <module>
    import babelfish
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/babelfish/__init__.py", line 20, in <module>
    from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/babelfish/converters/__init__.py", line 6, in <module>
    from pkg_resources import iter_entry_points, EntryPoint
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/lib/pkg_resources/__init__.py", line 77, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/lib/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/lib/pkg_resources/extern/__init__.py", line 43, in load_module
    __import__(extant)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/lib/pkg_resources/_vendor/pyparsing.py", line 943, in <module>
    collections.MutableMapping.register(ParseResults)
AttributeError: module 'collections' has no attribute 'MutableMapping'"
result: [1]
```
```
[~] # opkg list-installed
ar - 2.37-1
binutils - 2.37-1
ca-bundle - 20211016-1
ca-certificates - 20211016-1
entware-opt - 227000-3
entware-release - 1.0-2
entware-upgrade - 1.0-1
file - 5.40-4
findutils - 4.8.0-1
gcc - 7.4.0-7
git - 2.33.1-1
git-http - 2.33.1-1
grep - 3.7-2
less - 590-2a
libbfd - 2.37-1
libbz2 - 1.0.8-1a
libc - 2.27-11
libctf - 2.37-1
libcurl - 7.80.0-1
libexpat - 2.4.1-1
libffi - 3.4.2-2
libgcc - 8.4.0-11
libgdbm - 1.21-1
libintl-full - 0.21-2
liblzma - 5.2.5-3
libmagic - 5.40-4
libmediainfo - 21.09-1
libncursesw - 6.2-3
libopcodes - 2.37-1
libopenssl - 1.1.1l-1
libpcre - 8.45-2
libpthread - 2.27-11
libpython3 - 3.10.0-1
libreadline - 8.1-1
librt - 2.27-11
libsqlite3 - 3330000-2
libssp - 8.4.0-11
libstdcpp - 8.4.0-11
libtirpc - 1.3.2-1
libuuid - 2.37-1
libzen - 0.4.39-1
locales - 2.27-9
nano - 5.9-2
objdump - 2.37-1
opkg - 2021-06-13-1bf042dd-1
python-pip-conf - 0.1-1
python3 - 3.10.0-1
python3-asyncio - 3.10.0-1
python3-base - 3.10.0-1
python3-cffi - 1.15.0-1
python3-cgi - 3.10.0-1
python3-cgitb - 3.10.0-1
python3-codecs - 3.10.0-1
python3-cryptography - 3.4.8-1
python3-ctypes - 3.10.0-1
python3-dbm - 3.10.0-1
python3-decimal - 3.10.0-1
python3-distutils - 3.10.0-1
python3-email - 3.10.0-1
python3-light - 3.10.0-1
python3-logging - 3.10.0-1
python3-lzma - 3.10.0-1
python3-multiprocessing - 3.10.0-1
python3-ncurses - 3.10.0-1
python3-openssl - 3.10.0-1
python3-pip - 21.2.3-1
python3-pkg-resources - 57.4.0-1
python3-ply - 3.11-2
python3-pycparser - 2.21-1
python3-pydoc - 3.10.0-1
python3-pyopenssl - 21.0.0-1
python3-readline - 3.10.0-1
python3-setuptools - 57.4.0-1
python3-six - 1.16.0-1
python3-sqlite3 - 3.10.0-1
python3-unittest - 3.10.0-1
python3-urllib - 3.10.0-1
python3-uuid - 3.10.0-1
python3-xml - 3.10.0-1
sed - 4.8-3
terminfo - 6.2-3
zlib - 1.2.11-3
zoneinfo-asia - 2021e-1
zoneinfo-europe - 2021e-1
```
```
~] # python3 -m pip list
Package           Version
----------------- -----------
adba              1.1.0
appdirs           1.4.4
attrs             18.2.0
babelfish         0.5.6.dev0
beautifulsoup4    4.9.3
bencode.py        4.0.0
boto              2.48.0
CacheControl      0.12.6
certifi           2020.12.5
cffi              1.15.0
chardet           4.0.0
click             8.0.3
cloudscraper      1.2.58
configobj         5.0.6
contextlib2       0.6.0.post1
cryptography      3.4.8
decorator         5.1.0
deluge-client     1.9.0
Deprecated        1.2.13
dirtyjson         1.0.7
diskcache         2.9.0
dogpile.cache     1.1.2
enzyme            0.4.2.dev0
feedparser        6.0.2
future            0.18.2
gntp              1.0.3
guessit           3.3.1
html5lib          1.1
idna              2.10
imdbpie           5.6.4
jsonrpclib-pelix  0.4.2
knowit            0.3.0.dev0
Mako              1.1.4
markdown2         2.4.0
MarkupSafe        2.0.1
msgpack           1.0.3
oauthlib          3.1.1
packaging         21.3
pbr               5.8.0
Pint              0.18
pip               21.3.1
ply               3.11
profilehooks      1.12.0
pycparser         2.21
PyGithub          1.45
PyJWT             2.0.1
pymediainfo       5.1.0
pyOpenSSL         21.0.0
pyparsing         3.0.6
pysrt             1.1.2
python-dateutil   2.8.1
python-twitter    3.5
pytimeparse       1.1.8
pytz              2021.3
PyYAML            6.0
rarfile           3.1
rebulk            3.0.1
requests          2.25.1
requests-oauthlib 1.3.0
requests-toolbelt 0.9.1
setuptools        57.4.0
sgmllib3k         1.0.0
six               1.15.0
soupsieve         2.3.1
stevedore         3.5.0
subliminal        2.1.0
tmdbsimple        2.8.0
tornado           6.1
tornroutes        0.5.1
trakt             3.1.0
trans             2.1.0
ttl-cache         1.6
tvdbapiv2         1.0.1
urllib3           1.26.7
validators        0.18.2
webencodings      0.5.1
wheel             0.30.0
wrapt             1.13.3
```
Any thoughts? Thank you.

**Comment by p0psicles** [comment] 2021-12-16 20:39
Already fixed in develop branch. I'll release to master tomorrow

**Comment by OneCDOnly** [comment] 2021-12-16 20:54
I tried pulling from `develop` too, and got the same error.

**Comment by p0psicles** [comment] 2021-12-16 21:11
It was a couple of weeks ago. But I could run develop on py3.10 just fine

**Comment by papampi** [comment] 2021-12-17 09:54
Having the same issue.
Waiting for the fix.

**Comment by papampi** [comment] 2021-12-17 10:19
Updated babelfish to 0.6.0 and still have the same issue.
```
[~] # python3 -m pip list
Package      Version
------------ -------
babelfish    0.6.0
cffi         1.15.0
cryptography 3.4.8
idna         3.3
Pillow       8.4.0
pip          21.3.1
pycparser    2.21
pyOpenSSL    21.0.0
rencode      1.0.6
setuptools   57.4.0
wheel        0.37.0
```

**Comment by papampi** [comment] 2021-12-17 20:44
@p0psicles 
Just tried develop branch, it gives the same error and not starts.

**Comment by p0psicles** [comment] 2021-12-17 21:25
Okay, I'll check it out

**Comment by parktopark** [comment] 2021-12-19 10:49
Hi,
Having the same problem, is there going to be a fix for this anytime soon?
Don't wanna be pushy but wife n kids are starting to nag for their daily shows.

**Comment by p0psicles** [comment] 2021-12-19 10:56
Apparently medusa is running fine on windows with python 3.10. I'm looking into why it's not on linux.

**Comment by medariox** [comment] 2021-12-19 11:18
It's caused by the old `pyparsing` in `pkg_resources`. This PR should fix it: https://github.com/pymedusa/Medusa/pull/10175

**Comment by papampi** [comment] 2021-12-19 13:23
Thanks, fixed in dev branch.

**Closed** 2021-12-19 13:31 UTC

**Comment by chip33** [comment] 2021-12-20 11:56
Confirmed working with develop branch on win11 and Python v3.10.1.
