### ISSUE TITLE
Empty language while adding show

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#1525] opened 2016-11-10 12:49 UTC
Empty language 

![empty language](https://cloud.githubusercontent.com/assets/2620870/20177312/4ae0a918-a733-11e6-9744-6d3ac267284d.png)

**branch:** feature/search-show-lang-feedback

@p0psicles

**Comment by duramato** [comment] 2016-11-10 12:52
That's uses the one uses what  you have set in the default language Metadata. Afaik was always like that

**Comment by fernandog** [comment] 2016-11-10 12:53
so it must be named "default" in listbox

**Comment by p0psicles** [comment] 2016-11-10 13:26
Settings - General, also has the empty select item.

**Comment by p0psicles** [comment] 2016-11-10 14:06
Well this is actually not a bug. If you add blank="true" to line:
https://github.com/pymedusa/Medusa/blob/develop/views/config_general.mako#L47

It works. Like for ex:
<select name="indexerDefaultLang" id="indexerDefaultLang" class="form-control form-control-inline input-sm bfh-languages" **data-blank="false"**  data-language=${app.INDEXER_DEFAULT_LANGUAGE} data-available="${','.join(app.indexerApi().config['valid_languages'])}"></select>

**Comment by medariox** [comment] 2016-11-10 17:47
Fixed with https://github.com/pymedusa/Medusa/pull/1527

**Closed by medariox** 2016-11-10 17:47 UTC
Labels: Bug
