### ISSUE TITLE
Anidex error

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#2874] opened 2017-06-11 11:37 UTC
```
2017-06-11 13:32:46 ERROR    SEARCHQUEUE-MANUAL-321671 :: [AniDex] :: [21ec574] Unknown exception while searching AniDex. Error: 'sequence item 0: expected string or Unicode, int found'
Traceback (most recent call last):
  File "/opt/Medusa/medusa/search/core.py", line 553, in search_providers
    down_cur_quality, manual_search, manual_search_type)
  File "/opt/Medusa/medusa/providers/generic_provider.py", line 402, in find_search_results
    ', '.join(search_result.parsed_result.episode_numbers),
TypeError: sequence item 0: expected string or Unicode, int found
2017-06-11 13:32:46 DEBUG    SEARCHQUEUE-MANUAL-321671 :: [AniDex] :: [21ec574] Traceback (most recent call last):
  File "/opt/Medusa/medusa/search/core.py", line 553, in search_providers
    down_cur_quality, manual_search, manual_search_type)
  File "/opt/Medusa/medusa/providers/generic_provider.py", line 402, in find_search_results
    ', '.join(search_result.parsed_result.episode_numbers),
TypeError: sequence item 0: expected string or Unicode, int found
2017-06-11 13:32:46 DEBUG    SEARCHQUEUE-MANUAL-321671 :: [AniDex] :: [21ec574] Found result [GSK].Busou.Shoujo.Machiavellianism.[1-4][720p][VOSTFR][10Bits]. at https://anidex.info/dl/40771
```

**Comment by p0psicles** [comment] 2017-06-11 12:10
Yeah it's a general searching bug. Will be fixed this week.

**Comment by IDerr** [comment] 2017-06-11 12:34
Ok :)

**Comment by medariox** [comment] 2017-06-12 19:13
Duplicate of https://github.com/pymedusa/Medusa/issues/2871

**Closed by medariox** 2017-06-12 19:13 UTC
Labels: Duplicate
