### ISSUE TITLE
impossible to send nzb to nzbget

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#3831] opened 2018-03-04 12:50 UTC
**Branch/Commit:** last develop update
**OS:** windows 10

**What you did:**
as 2 recently aired episodes didn't get downloaded, I tried to force it, either automatically or manually.

**What happened:**
only torrent file could be send to deluge
2 nzb from 2 different indexers didn't get send by Medusa to Nzbget
![image](https://user-images.githubusercontent.com/9487685/36945680-fc8384e0-1fb1-11e8-88d0-bd6f2dc21bd2.png)

Logs says to nzb was sent to nzbget but it didn't.
I checked nzbget connection manually and it was successful.
on its side, Nzbget doesn't seem to receive anything...

last time a nzb was successfully sent to nzbget was 2 days ago.
I didn't touch Nzbget since then.
however, I updated Medusa (as I update nearly on a daily basis).
so I think something got broken in Medusa, in the few recent commits.

What do you think?
can you help me please?

**Logs:**
```
2018-03-04 13:38:10 DEBUG    SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] URL: http://**********:**********@localhost:6789/xmlrpc
2018-03-04 13:38:10 INFO     SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Sending NZB to NZBget
2018-03-04 13:38:10 DEBUG    SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Successfully connected to NZBget
2018-03-04 13:38:09 INFO     SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Downloading Scandal.US.S07E12.1080p.WEB.x264-CONVOY.English with size: 2.10 GB from NZBFINDER
2018-03-04 13:38:09 INFO     SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Beginning to manual snatch release: Scandal.US.S07E12.1080p.WEB.x264-CONVOY.English
2018-03-04 13:34:54 DEBUG    Thread-35 :: [a064dbf] Broken providers already updated in the last hour
2018-03-04 13:34:36 DEBUG    SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] URL: http://**********:**********@localhost:6789/xmlrpc
2018-03-04 13:34:36 INFO     SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Sending NZB to NZBget
2018-03-04 13:34:36 DEBUG    SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Successfully connected to NZBget
2018-03-04 13:34:35 INFO     SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Downloading Scandal.US.S07E12.1080p.WEB.x264-CONVOY with size: 2.10 GB from NZB.Cat
2018-03-04 13:34:35 INFO     SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Beginning to manual snatch release: Scandal.US.S07E12.1080p.WEB.x264-CONVOY
2018-03-04 13:33:01 DEBUG    SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Transaction with 1 queries executed
2018-03-04 13:33:01 DEBUG    SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] 248841: Formatting pattern: %SN - %Sx12 - %EN - %QN -> Scandal (2012) - 7x12 - Allow Me to Reintroduce Myself (1) - 1080p WEB-DL
2018-03-04 13:33:01 DEBUG    SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Found codec for Scandal (2012) Allow Me to Reintroduce Myself (1)
2018-03-04 13:33:01 DEBUG    SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Checking if we should stop searching for a better quality for for episode Scandal.US.S07E12.1080p.WEB.x264-CONVOY[rartv]
2018-03-04 13:32:59 DEBUG    SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Calling DelugeD Client
2018-03-04 13:32:59 INFO     SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Downloading Scandal.US.S07E12.1080p.WEB.x264-CONVOY[rartv] with 119 seeders and 46 leechers and size 1.85 GB from Rarbg
2018-03-04 13:32:59 INFO     SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Beginning to manual snatch release: Scandal.US.S07E12.1080p.WEB.x264-CONVOY[rartv]
2018-03-04 13:32:51 DEBUG    SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] URL: http://**********:**********@localhost:6789/xmlrpc
2018-03-04 13:32:51 INFO     SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Sending NZB to NZBget
2018-03-04 13:32:51 DEBUG    SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Successfully connected to NZBget
2018-03-04 13:32:50 INFO     SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Downloading Scandal.US.S07E12.1080p.WEB.x264-CONVOY with size: 2.10 GB from NZB.Cat
2018-03-04 13:32:50 INFO     SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Beginning to manual snatch release: Scandal.US.S07E12.1080p.WEB.x264-CONVOY
2018-03-04 13:32:09 DEBUG    Thread-34 :: [a064dbf] Successfully connected to NZBget
2018-03-04 13:30:20 DEBUG    SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] URL: http://**********:**********@localhost:6789/xmlrpc
2018-03-04 13:30:20 INFO     SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Sending NZB to NZBget
2018-03-04 13:30:20 DEBUG    SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Successfully connected to NZBget
2018-03-04 13:30:19 INFO     SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Downloading Scandal.US.S07E12.1080p.WEB.x264-CONVOY.English with size: 2.10 GB from NZBFINDER
2018-03-04 13:30:19 INFO     SNATCHQUEUE-MANUALSNATCH-248841 :: [a064dbf] Beginning to manual snatch release: Scandal.US.S07E12.1080p.WEB.x264-CONVOY.English
```

**Comment by medariox** [comment] 2018-03-04 18:31
Thanks for the bug report. This is probably caused by the changes towards Python 3 compatibility. Can you please let me know if this PR fixes your issue? https://github.com/pymedusa/Medusa/pull/3832

**Comment by NicoLeOca** [comment] 2018-03-04 21:33
@medariox 
no it doesn't

**Comment by medariox** [comment] 2018-03-04 21:41
Update and try again, please.

**Comment by NicoLeOca** [comment] 2018-03-05 05:57
@medariox 
nzbget now working properly!
thanks for the quick fix

**Comment by medariox** [comment] 2018-03-05 17:06
Hmm, strange. Can you update and try once again?

**Comment by NicoLeOca** [comment] 2018-03-05 18:45
@medariox 
maybe you didn't get my message right
you fixed the issue!
thanks

**Comment by medariox** [comment] 2018-03-05 19:57
Yeah, but can you try with the updated PR anyway please?

**Comment by medariox** [comment] 2018-03-05 21:35
Thanks for the feedback. The fix has been merged to develop.

**Closed by medariox** 2018-03-05 21:35 UTC
Labels: Fixed
