### ISSUE TITLE
[APP SUBMITTED]: 321285: Multiple entries found in show: Boruto - Naruto Next Generations 

### ISSUE THREAD

**Issue by PxReaz** [pymedusa/Medusa#4857] opened 2018-08-05 19:44 UTC
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-3.16.0-6-amd64-x86_64-with-debian-8.11`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@f5973b28465246e67465d7d86bdc8aa74d13e659
**Link to Log**: https://gist.github.com/24caae955e057e707616546a2159e039
### ERROR
<pre>
2018-08-04 22:15:19 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Yggtorrent] :: [f5973b2] 321285: Multiple entries found in show: Boruto - Naruto Next Generations 
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment] 2018-08-16 20:25
This is probably caused by the fact that the query uses only the show ID and not the show ID + indexer ID.
https://github.com/pymedusa/Medusa/blob/b7333559c9a747cd3e8b4022c4073757a62b32ed/medusa/tv/series.py#L740-L751

**Comment by medariox** [comment] 2018-08-21 08:47
Fixed with https://github.com/pymedusa/Medusa/pull/4933

**Closed by medariox** 2018-08-21 08:47 UTC
Labels: Bug, Fixed
