### ISSUE TITLE
[APP SUBMITTED]: TypeError: create_episode_structure() missing 1 required positional argument: 'episodes'

### ISSUE THREAD

**Issue by pax0707** [pymedusa/Medusa#8988] opened 2021-01-11 10:14 UTC
### INFO
**Python Version**: `3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]`
**Operating System**: `Linux-5.4.83-v7l+-armv7l-with-debian-10.7`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@5839c67dd78e5d5eb9b058fac805c8bf4a51e22b
**Link to Log**: https://gist.github.com/128769b2c1496f7d63066b17c9de131f
### ERROR
<pre>
2021-01-11 11:13:44 ERROR    TORNADO :: [5839c67] Uncaught exception in APIv2: TypeError("create_episode_structure() missing 1 required positional argument: 'episodes'")
Request: GET /api/v2/series/tvdb369568/episodes?limit=1000&season=1 (172.16.1.9)
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/5839c67dd78e5d5eb9b058fac805c8bf4a51e22b/ext/tornado/web.py#L1592">ext/tornado/web.py</a>", line 1592, in _execute
    result = yield result
  File "/opt/medusa/<a href="../blob/5839c67dd78e5d5eb9b058fac805c8bf4a51e22b/ext/tornado/gen.py#L1133">ext/tornado/gen.py</a>", line 1133, in run
    value = future.result()
  File "/opt/medusa/<a href="../blob/5839c67dd78e5d5eb9b058fac805c8bf4a51e22b/ext/tornado/gen.py#L1141">ext/tornado/gen.py</a>", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/medusa/<a href="../blob/5839c67dd78e5d5eb9b058fac805c8bf4a51e22b/medusa/server/api/v2/base.py#L83">medusa/server/api/v2/base.py</a>", line 83, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/opt/medusa/<a href="../blob/5839c67dd78e5d5eb9b058fac805c8bf4a51e22b/ext/tornado/gen.py#L1133">ext/tornado/gen.py</a>", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/medusa/<a href="../blob/5839c67dd78e5d5eb9b058fac805c8bf4a51e22b/medusa/server/api/v2/episodes.py#L60">medusa/server/api/v2/episodes.py</a>", line 60, in get
    data = [e.to_json(detailed=detailed) for e in series.get_all_episodes(season=season)]
  File "/opt/medusa/<a href="../blob/5839c67dd78e5d5eb9b058fac805c8bf4a51e22b/medusa/tv/series.py#L831">medusa/tv/series.py</a>", line 831, in get_all_episodes
    cur_ep = self.get_episode(cur_result['season'], cur_result['episode'])
  File "/opt/medusa/<a href="../blob/5839c67dd78e5d5eb9b058fac805c8bf4a51e22b/medusa/tv/series.py#L944">medusa/tv/series.py</a>", line 944, in get_episode
    ep = Episode(self, season, episode)
  File "/opt/medusa/<a href="../blob/5839c67dd78e5d5eb9b058fac805c8bf4a51e22b/medusa/tv/episode.py#L271">medusa/tv/episode.py</a>", line 271, in __init__
    self._specify_episode(self.season, self.episode)
  File "/opt/medusa/<a href="../blob/5839c67dd78e5d5eb9b058fac805c8bf4a51e22b/medusa/tv/episode.py#L642">medusa/tv/episode.py</a>", line 642, in _specify_episode
    sql_results = self.load_from_db(season, episode)
  File "/opt/medusa/<a href="../blob/5839c67dd78e5d5eb9b058fac805c8bf4a51e22b/medusa/tv/episode.py#L722">medusa/tv/episode.py</a>", line 722, in load_from_db
    self.status = int(sql_results[0]['status'] or UNSET)
  File "/opt/medusa/<a href="../blob/5839c67dd78e5d5eb9b058fac805c8bf4a51e22b/medusa/tv/base.py#L63">medusa/tv/base.py</a>", line 63, in __setattr__
    super(TV, self).__setattr__(key, value)
  File "/opt/medusa/<a href="../blob/5839c67dd78e5d5eb9b058fac805c8bf4a51e22b/medusa/tv/episode.py#L428">medusa/tv/episode.py</a>", line 428, in status
    self._sync_trakt(value)
  File "/opt/medusa/<a href="../blob/5839c67dd78e5d5eb9b058fac805c8bf4a51e22b/medusa/tv/episode.py#L450">medusa/tv/episode.py</a>", line 450, in _sync_trakt
    notifiers.trakt_notifier.update_watchlist_episode(self)
  File "/opt/medusa/<a href="../blob/5839c67dd78e5d5eb9b058fac805c8bf4a51e22b/medusa/notifiers/trakt.py#L120">medusa/notifiers/trakt.py</a>", line 120, in update_watchlist_episode
    result = sync.add_to_watchlist({'shows': [create_episode_structure(episodes)]})
TypeError: create_episode_structure() missing 1 required positional argument: 'episodes'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment] 2021-01-11 12:08
Duplicate of https://github.com/pymedusa/Medusa/issues/8984

**Closed by medariox** 2021-01-11 12:08 UTC
Labels: Bug
