### ISSUE TITLE
Adding Recommended Shows

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#6394] opened 2019-03-21 13:17 UTC
**Describe the bug**
Adding recommended shows are fine under python 2.7 but when under python 3 get this error 

Fetching of Recommender Data failed. Exception:

db type could not be determined

Branch: master 
Commit: b34f1df336e52cf0a690acbc393440ac9f8b3581 
Version: 0.3.1 
Database: 44.14
Python Version:	3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
 SSL Version:	OpenSSL 1.1.0j 20 Nov 2018
 OS:	Windows-10-10.0.17134-SP0
 Locale:	en_US.cp1252

Debug Log: https://gist.github.com/ripper1967/4f80395679a47998b2a6a4ff96395f09

**Comment by medariox** [comment] 2019-03-21 13:19
Duplicate of https://github.com/pymedusa/Medusa/issues/6388

**Closed by medariox** 2019-03-21 13:19 UTC
Labels: triage

**Comment by gilfrade** [comment] 2019-06-05 16:43
Exactly as described before. Clicking on any Recommended Providers gives:
```
Fetching of Recommender Data failed. Exception:

db type could not be determined
```

This seems to be the only visible error from a web view. Checked the logs and there's a bunch of the same Exception in different functions, some of them are logged as `Warning` instead of `Error`. It does not seam to be relate to #6388. This is most likely a bad conversion from python2.7 to python3. Is there a quick fix like deleting the database in question so its recreated with the new code?


Branch: master 
Commit: 6a21a6001b10827d14d450135bae61729b01edf1 
Version: 0.3.2 
Database: 44.14
Python Version: 3.6.6 (default, Jul 19 2018, 14:25:17) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
SSL Version: OpenSSL 1.1.0h-fips 27 Mar 2018
OS: Linux-4.18.5-200.fc28.x86_64-x86_64-with-fedora-28-Twenty_Eight
Locale: pt_PT.UTF-8

Some Exceptions from logs:
```
2019-06-05 17:13:51 ERROR	Thread-19 :: [f46bfac] Exception generated: db type could not be determined
Traceback (most recent call last):
  File "/opt/src/Medusa/medusa/server/web/core/base.py", line 262, in async_call
    result = function(**kwargs)
  File "/opt/src/Medusa/medusa/server/web/home/handler.py", line 2252, in fetch_releasegroups
    groups = get_release_groups_for_anime(series_name)
  File "<decorator-gen-15>", line 2, in get_release_groups_for_anime
  File "/opt/src/Medusa/ext/dogpile/cache/region.py", line 1272, in get_or_create_for_user_func
    should_cache_fn, (arg, kw))
  File "/opt/src/Medusa/ext/dogpile/cache/region.py", line 879, in get_or_create
    async_creator) as value:
  File "/opt/src/Medusa/ext/dogpile/lock.py", line 186, in __enter__
    return self._enter()
  File "/opt/src/Medusa/ext/dogpile/lock.py", line 86, in _enter
    value = value_fn()
  File "/opt/src/Medusa/ext/dogpile/cache/region.py", line 826, in get_value
    value = self.backend.get(key)
  File "/opt/src/Medusa/ext/dogpile/cache/backends/file.py", line 220, in get
    with self._dbm_file(False) as dbm:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/src/Medusa/ext/dogpile/cache/backends/file.py", line 215, in _dbm_file
    "w" if write else "r")
  File "/usr/lib64/python3.6/dbm/__init__.py", line 88, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determined
Traceback (most recent call last):
  File "/opt/src/Medusa/ext/subliminal/core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/opt/src/Medusa/ext/subliminal/providers/tvsubtitles.py", line 200, in list_subtitles
    show_id = self.search_show_id(title, video.year)
  File "<decorator-gen-5>", line 2, in search_show_id
  File "/opt/src/Medusa/ext/dogpile/cache/region.py", line 1272, in get_or_create_for_user_func
    should_cache_fn, (arg, kw))
  File "/opt/src/Medusa/ext/dogpile/cache/region.py", line 879, in get_or_create
    async_creator) as value:
  File "/opt/src/Medusa/ext/dogpile/lock.py", line 186, in __enter__
    return self._enter()
  File "/opt/src/Medusa/ext/dogpile/lock.py", line 86, in _enter
    value = value_fn()
  File "/opt/src/Medusa/ext/dogpile/cache/region.py", line 826, in get_value
    value = self.backend.get(key)
  File "/opt/src/Medusa/ext/dogpile/cache/backends/file.py", line 220, in get
    with self._dbm_file(False) as dbm:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/src/Medusa/ext/dogpile/cache/backends/file.py", line 215, in _dbm_file
    "w" if write else "r")
  File "/usr/lib64/python3.6/dbm/__init__.py", line 88, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determined
```

**Comment by medariox** [comment] 2019-06-05 16:56
This is the result of having an external version of subliminal installed.

**Comment by gilfrade** [comment] 2019-06-05 17:02
Just checked and i don't have subliminal installed as global so it must be included in medusa source.
Inside medusa source is this:
```
./cache/subliminal.dbm
./ext/subliminal
./ext/subliminal/utils.py
./ext/subliminal/video.py
./ext/subliminal/__pycache__
./ext/subliminal/__pycache__/core.cpython-36.pyc
./ext/subliminal/__pycache__/score.cpython-36.pyc
./ext/subliminal/__pycache__/exceptions.cpython-36.pyc
./ext/subliminal/__pycache__/__init__.cpython-36.pyc
./ext/subliminal/__pycache__/utils.cpython-36.pyc
./ext/subliminal/__pycache__/video.cpython-36.pyc
./ext/subliminal/__pycache__/cache.cpython-36.pyc
./ext/subliminal/__pycache__/subtitle.cpython-36.pyc
./ext/subliminal/__pycache__/extensions.cpython-36.pyc
./ext/subliminal/cli.py
./ext/subliminal/refiners
./ext/subliminal/refiners/omdb.py
./ext/subliminal/refiners/__pycache__
./ext/subliminal/refiners/__pycache__/tvdb.cpython-36.pyc
./ext/subliminal/refiners/__pycache__/omdb.cpython-36.pyc
./ext/subliminal/refiners/__pycache__/__init__.cpython-36.pyc
./ext/subliminal/refiners/__pycache__/metadata.cpython-36.pyc
./ext/subliminal/refiners/tvdb.py
./ext/subliminal/refiners/__init__.py
./ext/subliminal/refiners/metadata.py
./ext/subliminal/cache.py
./ext/subliminal/__init__.py
./ext/subliminal/core.py
./ext/subliminal/score.py
./ext/subliminal/subtitle.py
./ext/subliminal/providers
./ext/subliminal/providers/__pycache__
./ext/subliminal/providers/__pycache__/thesubdb.cpython-36.pyc
./ext/subliminal/providers/__pycache__/legendastv.cpython-36.pyc
./ext/subliminal/providers/__pycache__/tvsubtitles.cpython-36.pyc
./ext/subliminal/providers/__pycache__/opensubtitles.cpython-36.pyc
./ext/subliminal/providers/__pycache__/__init__.cpython-36.pyc
./ext/subliminal/providers/__pycache__/addic7ed.cpython-36.pyc
./ext/subliminal/providers/__pycache__/napiprojekt.cpython-36.pyc
./ext/subliminal/providers/__pycache__/shooter.cpython-36.pyc
./ext/subliminal/providers/__pycache__/podnapisi.cpython-36.pyc
./ext/subliminal/providers/napiprojekt.py
./ext/subliminal/providers/__init__.py
./ext/subliminal/providers/opensubtitles.py
./ext/subliminal/providers/tvsubtitles.py
./ext/subliminal/providers/shooter.py
./ext/subliminal/providers/legendastv.py
./ext/subliminal/providers/podnapisi.py
./ext/subliminal/providers/thesubdb.py
./ext/subliminal/providers/addic7ed.py
./ext/subliminal/extensions.py
./ext/subliminal/exceptions.py
./ext/subliminal/converters
./ext/subliminal/converters/__pycache__
./ext/subliminal/converters/__pycache__/thesubdb.cpython-36.pyc
./ext/subliminal/converters/__pycache__/legendastv.cpython-36.pyc
./ext/subliminal/converters/__pycache__/__init__.cpython-36.pyc
./ext/subliminal/converters/__init__.py
./ext/subliminal/converters/tvsubtitles.py
./ext/subliminal/converters/shooter.py
./ext/subliminal/converters/legendastv.py
./ext/subliminal/converters/thesubdb.py
./ext/subliminal/converters/addic7ed.py
```
@medariox are you saying that something failed during the update from python2.7 to python3 ?

**Comment by p0psicles** [comment] 2019-06-05 17:03
Could be. Delete your .dbm files in cache foleery

**Comment by gilfrade** [comment] 2019-06-05 17:15
Done. Thanks for the help!
