### ISSUE TITLE
Jackett integration broken for providers redirecting to magnets

### ISSUE THREAD

**Issue by darkbroodzed** [pymedusa/Medusa#3435] opened 2017-12-08 13:23 UTC
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** any
**OS:** any
**What you did:** add jackett to custom nbzsearch provider
**What happened:** it don't work
**What you expected:** working custom provider
**Logs:**
```
2017-12-08 16:00:53 WARNING  SNATCHQUEUE-MANUALSNATCH-80379 :: [b96b3ee] Failed to download any results for The.Big.Bang.Theory.S11E08.720p.HDTV.x264-AVS[ettv]
2017-12-08 16:00:50 INFO     SNATCHQUEUE-MANUALSNATCH-80379 :: [b96b3ee] Downloading The.Big.Bang.Theory.S11E08.720p.HDTV.x264-AVS[ettv] from Jackett at http://192.168.100.7:9117/dl/ettv/?jackett_apikey=h6rq1vjac3idb35tkolvue760cudcfns&path=aFhrOVlwbGpMTkZ5YmdYUnNGejlyOWxBT3ZpbDlkUG9wcU9zTUd3Vm93c2Y0b1NwVnhPWU5rVUh1M2V4RGI1WlRYY1R0MTdXZDl1SktqNmpCMTd0TTRpRSs0NXR2U0poNUE3QXpqT1hoZjRoOXdJVTQzcUU1Y3hxSXhuSHUzWUdkZEJ6UncyV1MzemhLNDA5WVpPM2cxYjQvWElqczFqM3Q2T0Z1Z29SSXB2U1l5UzZHeUtudkdwQy9FTnoyTXJwazdxbmM5OEZLc0lFNnVNbXZmdTB6TFNYK29KUjNyTVRJbUo1Ull2VjhZRDB4QXA0MjNudHVPWTAzODY4N2hLSmZYdnB5OFRiWEhocjdKOVA3czhMWWJ1THVBQUxqY0NPcVY2bnByWGhWKy9Ka3RFOWhlN2Z6MXZhdjdUOG5Cd3NYdHdsK1pSTmdnSkdHam9DTktFb1hsS0ZnNW5wTmRQblA2NXg0S0JMSS9KdkZmWDZ0WkR4YzdpWHlqZ1o3RUlxZTlpaFN1cDBDNFloL3dpdG8rd2psZz090&file=The.Big.Bang.Theory.S11E08.720p.HDTV.x264-AVS[ettv]
2017-12-08 16:00:50 INFO     SNATCHQUEUE-MANUALSNATCH-80379 :: [b96b3ee] Downloading The.Big.Bang.Theory.S11E08.720p.HDTV.x264-AVS[ettv] with 1095 seeders and 174 leechers and size 531.00 MB from Jackett
2017-12-08 16:00:50 INFO     SNATCHQUEUE-MANUALSNATCH-80379 :: [b96b3ee] Beginning to manual snatch release: The.Big.Bang.Theory.S11E08.720p.HDTV.x264-AVS[ettv]
```
it's not miss config form jacket side, url accessable and provide right magnet link:
wget "http://192.168.100.7:9117/dl/ettv/?jackett_apikey=h6rq1vjac3idb35tkolvue760cudcfns&path=aFhrOVlwbGpMTkZ5YmdYUnNGejlyOWxBT3ZpbDlkUG9wcU9zTUd3Vm93c2Y0b1NwVnhPWU5rVUh1M2V4RGI1WlRYY1R0MTdXZDl1SktqNmpCMTd0TTRpRSs0NXR2U0poNUE3QXpqT1hoZjRoOXdJVTQzcUU1Y3hxSXhuSHUzWUdkZEJ6UncyV1MzemhLNDA5WVpPM2cxYjQvWElqczFqM3Q2T0Z1Z29SSXB2U1l5UzZHeUtudkdwQy9FTnoyTXJwazdxbmM5OEZLc0lFNnVNbXZmdTB6TFNYK29KUjNyTVRJbUo1Ull2VjhZRDB4QXA0MjNudHVPWTAzODY4N2hLSmZYdnB5OFRiWEhocjdKOVA3czhMWWJ1THVBQUxqY0NPcVY2bnByWGhWKy9Ka3RFOWhlN2Z6MXZhdjdUOG5Cd3NYdHdsK1pSTmdnSkdHam9DTktFb1hsS0ZnNW5wTmRQblA2NXg0S0JMSS9KdkZmWDZ0WkR4YzdpWHlqZ1o3RUlxZTlpaFN1cDBDNFloL3dpdG8rd2psZz090&file=The.Big.Bang.Theory.S11E08.720p.HDTV.x264-AVS[ettv]"
The name is too long, 666 chars total.
Trying to shorten...
New name is index.html?jackett_apikey=h6rq1vjac3idb35tkolvue760cudcfns&path=aFhrOVlwbGpMTkZ5YmdYUnNGejlyOWxBT3ZpbDlkUG9wcU9zTUd3Vm93c2Y0b1NwVnhPWU5rVUh1M2V4RGI1WlRYY1R0MTdXZDl1SktqNmpCMTd0TTRpRSs0NXR2U0poNUE3QXpqT1hoZjRoOXdJVTQzcUU1Y3hxSXhuSHUzWUdk.
--2017-12-08 16:07:17--  http://192.168.100.7:9117/dl/ettv/?jackett_apikey=h6rq1vjac3idb35tkolvue760cudcfns&path=aFhrOVlwbGpMTkZ5YmdYUnNGejlyOWxBT3ZpbDlkUG9wcU9zTUd3Vm93c2Y0b1NwVnhPWU5rVUh1M2V4RGI1WlRYY1R0MTdXZDl1SktqNmpCMTd0TTRpRSs0NXR2U0poNUE3QXpqT1hoZjRoOXdJVTQzcUU1Y3hxSXhuSHUzWUdkZEJ6UncyV1MzemhLNDA5WVpPM2cxYjQvWElqczFqM3Q2T0Z1Z29SSXB2U1l5UzZHeUtudkdwQy9FTnoyTXJwazdxbmM5OEZLc0lFNnVNbXZmdTB6TFNYK29KUjNyTVRJbUo1Ull2VjhZRDB4QXA0MjNudHVPWTAzODY4N2hLSmZYdnB5OFRiWEhocjdKOVA3czhMWWJ1THVBQUxqY0NPcVY2bnByWGhWKy9Ka3RFOWhlN2Z6MXZhdjdUOG5Cd3NYdHdsK1pSTmdnSkdHam9DTktFb1hsS0ZnNW5wTmRQblA2NXg0S0JMSS9KdkZmWDZ0WkR4YzdpWHlqZ1o3RUlxZTlpaFN1cDBDNFloL3dpdG8rd2psZz090&file=The.Big.Bang.Theory.S11E08.720p.HDTV.x264-AVS[ettv]
Connecting to 192.168.100.7:9117... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: magnet:?xt=urn:btih:1112a88b598d0021c7f4a29a1de0d4d48cc1eabf&dn=The.Big.Bang.Theory.S11E08.720p.HDTV.x264-AVS[ettv]&xl=530935764&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://9.rarbg.to:2710/announce&tr=udp://9.rarbg.me:2710/announce&tr=udp://tracker.cyberia.is:6969/announce&tr=udp://tracker.internetwarriors.net:1337/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://p4p.arenabg.com:1337/announce&tr=udp://eddie4.nl:6969/announce&tr=udp://shadowshq.yi.org:6969/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://explodie.org:6969/announce&tr=udp://tracker.tiny-vps.com:6969/announce&tr=udp://inferno.demonoid.pw:3391/announce&tr=udp://ipv4.tracker.harry.lu:80/announce&tr=udp://peerfect.org:6969/announce&tr=udp://tracker.pirateparty.gr:6969/announce&tr=udp://tracker.coppersurfer.tk:6969&tr=udp://tracker.vanitycore.co:6969/announce&tr=udp://open.stealth.si:80/announce&tr=http://xk.is:1337/announce&tr=udp://tracker.leechers-paradise.org:6969 [following]
magnet:?xt=urn:btih:1112a88b598d0021c7f4a29a1de0d4d48cc1eabf&dn=The.Big.Bang.Theory.S11E08.720p.HDTV.x264-AVS[ettv]&xl=530935764&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://9.rarbg.to:2710/announce&tr=udp://9.rarbg.me:2710/announce&tr=udp://tracker.cyberia.is:6969/announce&tr=udp://tracker.internetwarriors.net:1337/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://p4p.arenabg.com:1337/announce&tr=udp://eddie4.nl:6969/announce&tr=udp://shadowshq.yi.org:6969/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://explodie.org:6969/announce&tr=udp://tracker.tiny-vps.com:6969/announce&tr=udp://inferno.demonoid.pw:3391/announce&tr=udp://ipv4.tracker.harry.lu:80/announce&tr=udp://peerfect.org:6969/announce&tr=udp://tracker.pirateparty.gr:6969/announce&tr=udp://tracker.coppersurfer.tk:6969&tr=udp://tracker.vanitycore.co:6969/announce&tr=udp://open.stealth.si:80/announce&tr=http://xk.is:1337/announce&tr=udp://tracker.leechers-paradise.org:6969: Unsupported scheme 'magnet'.

for simpler installation for debug i recommend use jackett in docker from it's repo readme https://github.com/Jackett/Jackett

**Comment by medariox** [comment] 2017-12-08 13:44
You are running an old version. Update to latest master and optionally delete your `cache.db`.

**Comment by darkbroodzed** [comment] 2017-12-08 13:57
>You are running an old version.
??? 
logs form last version:

2017-12-08 16:55:45 WARNING  SNATCHQUEUE-MANUALSNATCH-80379 :: [1a8dc66] Failed to download any results for The.Big.Bang.Theory.S11E08.720p.HDTV.x264-AVS[ettv]
2017-12-08 16:55:42 INFO     SNATCHQUEUE-MANUALSNATCH-80379 :: [1a8dc66] Downloading The.Big.Bang.Theory.S11E08.720p.HDTV.x264-AVS[ettv] from Jackett at http://192.168.100.7:9117/dl/ettv/?jackett_apikey=**********&path=aFhrOVlwbGpMTkZ5YmdYUnNGejlyOWxBT3ZpbDlkUG9wcU9zTUd3Vm93c2Y0b1NwVnhPWU5rVUh1M2V4RGI1WlRYY1R0MTdXZDl1SktqNmpCMTd0TTRpRSs0NXR2U0poNUE3QXpqT1hoZjRoOXdJVTQzcUU1Y3hxSXhuSHUzWUdkZEJ6UncyV1MzemhLNDA5WVpPM2cxYjQvWElqczFqM3Q2T0Z1Z29SSXB2U1l5UzZHeUtudkdwQy9FTnoyTXJwazdxbmM5OEZLc0lFNnVNbXZmdTB6TFNYK29KUjNyTVRJbUo1Ull2VjhZRDB4QXA0MjNudHVPWTAzODY4N2hLSmZYdnB5OFRiWEhocjdKOVA3czhMWWJ1THVBQUxqY0NPcVY2bnByWGhWKy9Ka3RFOWhlN2Z6MXZhdjdUOG5Cd3NYdHdsK1pSTmdnSkdHam9DTktFb1hsS0ZnNW5wTmRQblA2NXg0S0JMSS9KdkZmWDZ0WkR4YzdpWHlqZ1o3RUlxZTlpaFN1cDBDNFloL3dpdG8rd2psZz090&file=The.Big.Bang.Theory.S11E08.720p.HDTV.x264-AVS[ettv]
2017-12-08 16:55:42 INFO     SNATCHQUEUE-MANUALSNATCH-80379 :: [1a8dc66] Downloading The.Big.Bang.Theory.S11E08.720p.HDTV.x264-AVS[ettv] with 1095 seeders and 174 leechers and size 531.00 MB from Jackett
2017-12-08 16:55:42 INFO     SNATCHQUEUE-MANUALSNATCH-80379 :: [1a8dc66] Beginning to manual snatch release: The.Big.Bang.Theory.S11E08.720p.HDTV.x264-AVS[ettv]

**Comment by medariox** [comment] 2017-12-08 14:02
Now that you updated, you can either delete `cache.db` or force a new search and download from the fresh results.

**Comment by darkbroodzed** [comment] 2017-12-08 14:15
2017-12-08 17:06:02 WARNING  SNATCHQUEUE-MANUALSNATCH-80379 :: [1a8dc66] Failed to download any results for The.Big.Bang.Theory.S11E08.720p.HDTV.x264-AVS[ettv]
2017-12-08 17:05:59 INFO     SNATCHQUEUE-MANUALSNATCH-80379 :: [1a8dc66] Downloading The.Big.Bang.Theory.S11E08.720p.HDTV.x264-AVS[ettv] from Jackett at http://192.168.100.7:9117/dl/ettv/?jackett_apikey=**********&path=aFhrOVlwbGpMTkZ5YmdYUnNGejlyOWxBT3ZpbDlkUG9wcU9zTUd3Vm93c2Y0b1NwVnhPWU5rVUh1M2V4RGI1WlRYY1R0MTdXZDl1SktqNmpCMTd0TTRpRSs0NXR2U0poNUE3QXpqT1hoZjRoOXdJVTQzcUU1Y3hxSXhuSHUzWUdkZEJ6UncyV1MzemhLNDA5WVpPM2cxYjQvWElqczFqM3Q2T0Z1Z29SSXB2U1l5UzZHeUtudkdwQy9FTnoyTXJwazdxbmM5OEZLc0lFNnVNbXZmdTB6TFNYK29KUjNyTVRJbUo1Ull2VjhZRDB4QXA0MjNudHVPWTAzODY4N2hLSmZYdnB5OFRiWEhocjdKOVA3czhMWWJ1THVBQUxqY0NPcVY2bnByWGhWKy9Ka3RFOWhlN2Z6MXZhdjdUOG5Cd3NYdHdsK1pSTmdnSkdHam9DTktFb1hsS0ZnNW5wTmRQblA2NXg0S0JMSS9KdkZmWDZ0WkR4YzdpWHlqZ1o3RUlxZTlpaFN1cDBDNFloL3dpdG8rd2psZz090&file=The.Big.Bang.Theory.S11E08.720p.HDTV.x264-AVS[ettv]
2017-12-08 17:05:59 INFO     SNATCHQUEUE-MANUALSNATCH-80379 :: [1a8dc66] Downloading The.Big.Bang.Theory.S11E08.720p.HDTV.x264-AVS[ettv] with 1095 seeders and 174 leechers and size 531.00 MB from Jackett
2017-12-08 17:05:59 INFO     SNATCHQUEUE-MANUALSNATCH-80379 :: [1a8dc66] Beginning to manual snatch release: The.Big.Bang.Theory.S11E08.720p.HDTV.x264-AVS[ettv]
2017-12-08 17:05:01 INFO     SEARCHQUEUE-MANUAL-80379 :: [AlphaRatio] :: [1a8dc66] Performing episode search for The Big Bang Theory
2017-12-08 17:04:43 INFO     SEARCHQUEUE-MANUAL-80379 :: [Torrentz2] :: [1a8dc66] Performing episode search for The Big Bang Theory
2017-12-08 17:04:21 INFO     SEARCHQUEUE-MANUAL-80379 :: [Rarbg] :: [1a8dc66] Performing episode search for The Big Bang Theory
2017-12-08 17:04:00 INFO     SEARCHQUEUE-MANUAL-80379 :: [Jackett] :: [1a8dc66] Performing episode search for The Big Bang Theory
2017-12-08 17:04:00 INFO     SEARCHQUEUE-MANUAL-80379 :: [1a8dc66] Using manual search providers
2017-12-08 17:04:00 INFO     SEARCHQUEUE-MANUAL-80379 :: [1a8dc66] Building internal name cache for The Big Bang Theory
2017-12-08 17:04:00 INFO     SEARCHQUEUE-MANUAL-80379 :: [1a8dc66] Finished processing 2565 scene exceptions.
2017-12-08 17:04:00 INFO     SEARCHQUEUE-MANUAL-80379 :: [1a8dc66] Updating exception_cache and exception_season_cache
2017-12-08 17:04:00 INFO     SEARCHQUEUE-MANUAL-80379 :: [1a8dc66] Beginning manual search for: The Big Bang Theory - S11E08 - The Tesla Recoil

**Comment by medariox** [comment] 2017-12-08 15:28
That's a Jackett bug. The link from Jackett returns a magnet instead of the torrent. You'll need to report it to them to get it fixed.

**Comment by kaso17** [comment] 2017-12-08 17:08
@medariox this is kaso17 from the jackett team.
It's not a bug. The redirect to a manget link is intentional. ETTV doesn't provide torrent files.
E.g. Sonarr and Radarr are handeling this case perfectly fine, most torrent clients do so too.
It would be great if medusa would support manget links too.
Without magnet support the ETTV and Torrent Downloads indexers are not usable.

**Comment by medariox** [comment] 2017-12-08 17:18
@kaso17 
What's the point of having a redirect to the magnet link instead of just providing the magnet link directly (like you do for TPB for example)? I tested a bunch of public indexers that use magnets and they work just fine, ETTV seems more like an exception.

**Comment by kaso17** [comment] 2017-12-08 18:22
@medariox TPB and others includes the magnet hash/link within the search results. ETTV and Torrent Downloads only provide it on the torrent's details page. In order to return the magnet link as part of the torznab query (like TPB) we would have to request all the details pages (which would make the search very slow and sooner or later you'll probably run into request limits). That's why we decided to take the download link/redirect approach which will only request the corresponding details page.

**Comment by MonkWho** [comment] 2018-03-28 03:07
I was just curious to see if there's been any movement on resolving this issue with Jackett?

PS: Or possibly adding ETTV as a provider directly into Medusa? I've seen Sickgear was the only one to add full support in a commit back in December (don't have it installed so I haven't actually tested it to see if it works).

**Comment by p0psicles** [comment] 2018-03-28 05:49
This is almost finished. Lots of changes happening in develop currently, so that's why its taking a little longer.

**Comment by medariox** [comment] 2018-04-01 15:57
This will be solved with https://github.com/pymedusa/Medusa/pull/3513. Thanks for the feedback.

**Closed by medariox** 2018-04-01 15:57 UTC
Labels: Bug
