### ISSUE TITLE
[APP SUBMITTED]: KeyError: u'The.Voice.US.S11.720p.HDTV.WEBRip.MIXED.x264.x265'

### ISSUE THREAD

**Issue by bluelavalamp** [pymedusa/Medusa#7491] opened 2019-12-15 01:08 UTC
### INFO
**Python Version**: `2.7.15 (default, Jun 17 2018, 22:57:51) [GCC 7.3.0]`
**Operating System**: `Linux-5.1.4-x86_64-Intel-R-_Xeon-R-_CPU___________X5650__@_2.67GHz-with-slackware-14.2`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@d0c136d7a528a471b51676140bd35d24d97f65c6
**Link to Log**: https://gist.github.com/fd56fdf4d4f8322d021020020af9776e
### ERROR
<pre>
2019-12-14 17:43:14 ERROR    POSTPROCESSOR :: [d0c136d] Exception generated: u'The.Voice.US.S11.720p.HDTV.WEBRip.MIXED.x264.x265'
Traceback (most recent call last):
  File "/opt/Medusa-master/<a href="../blob/d0c136d7a528a471b51676140bd35d24d97f65c6/medusa/scheduler.py#L93">medusa/scheduler.py</a>", line 93, in run
    self.action.run(self.force)
  File "/opt/Medusa-master/<a href="../blob/d0c136d7a528a471b51676140bd35d24d97f65c6/medusa/process_tv.py#L65">medusa/process_tv.py</a>", line 65, in run
    return ProcessResult(path, process_method).process(force=force, **kwargs)
  File "/opt/Medusa-master/<a href="../blob/d0c136d7a528a471b51676140bd35d24d97f65c6/medusa/process_tv.py#L188">medusa/process_tv.py</a>", line 188, in process
    ignore_subs=ignore_subs)
  File "/opt/Medusa-master/<a href="../blob/d0c136d7a528a471b51676140bd35d24d97f65c6/medusa/process_tv.py#L378">medusa/process_tv.py</a>", line 378, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/opt/Medusa-master/<a href="../blob/d0c136d7a528a471b51676140bd35d24d97f65c6/medusa/process_tv.py#L599">medusa/process_tv.py</a>", line 599, in process_media
    self.result = processor.process()
  File "/opt/Medusa-master/<a href="../blob/d0c136d7a528a471b51676140bd35d24d97f65c6/medusa/post_processor.py#L1183">medusa/post_processor.py</a>", line 1183, in process
    nzb_release_name = naming.determine_release_name(self.folder_path, self.nzb_name)
  File "/opt/Medusa-master/<a href="../blob/d0c136d7a528a471b51676140bd35d24d97f65c6/medusa/show/naming.py#L151">medusa/show/naming.py</a>", line 151, in determine_release_name
    if filter_bad_releases(folder):
  File "/opt/Medusa-master/<a href="../blob/d0c136d7a528a471b51676140bd35d24d97f65c6/medusa/show/naming.py#L105">medusa/show/naming.py</a>", line 105, in filter_bad_releases
    NameParser().parse(name)
  File "/opt/Medusa-master/<a href="../blob/d0c136d7a528a471b51676140bd35d24d97f65c6/medusa/name_parser/parser.py#L383">medusa/name_parser/parser.py</a>", line 383, in parse
    cached = name_parser_cache.get(name)
  File "/opt/Medusa-master/<a href="../blob/d0c136d7a528a471b51676140bd35d24d97f65c6/medusa/name_parser/parser.py#L617">medusa/name_parser/parser.py</a>", line 617, in get
    return self.cache[name]
KeyError: u'The.Voice.US.S11.720p.HDTV.WEBRip.MIXED.x264.x265'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment] 2020-01-06 10:10
Duplicate of https://github.com/pymedusa/Medusa/issues/7537

**Closed by medariox** 2020-01-06 10:10 UTC
Labels: triage
