### ISSUE TITLE
Getting subtitles for Archived episodes --> Too many requests

### ISSUE THREAD

**Issue by Olivier6767** [pymedusa/Medusa#3248] opened 2017-11-09 07:42 UTC
Branch: master
Commit: b16e0e5eb4ded727eebd2ab2cd9683ab597662f5
Version: v0.1.17

I get constant errors from several subtitle providers: Too many requests.
After turning on debug, I found out that Medusa is regularly trying to download subtitles for shows and episodes marked as Archived. Since I have many of them, it generates too many requests to the subtitle providers and eventually it exceeds their request quota.

**More information:**
I have many shows where I had downloaded the first seasons in local language (french). I did this by adding <french> in the required words field in the Advanced season settings.
Once I had watched one season, I marked all the episodes for this season as Archived.
For the latest seasons, since the French version is usually not available upon release, I remove the required keyword <french> and I enable Search subtitles in the Main season settings.

What I found out by reviewing the debug logs, is that Medusa still **wants to download all missing subtitles for old seasons marked as Archived**. This represents a huge list of subtitles.
This exceeds the subtitle provider's quota and generates daily errors for 'Too Many Requests'.
Therefore no subtitles are downloaded for newly fetched episodes.

Is this a normal behavior?
Is there a setting that would avoid Medusa trying to download old subtitles (for episodes marked as Archived)?

**Comment by p0psicles** [comment] 2017-11-09 07:49
It's definitely not expected behavior. Will put up a fix for it shortly.

**Comment by p0psicles** [comment] 2017-11-09 08:06
@fernandog in our sql query for episodes that should search for subtitles, i found this: `"AND (e.status LIKE '%4' OR e.status LIKE '%6') "`.
It looks like where looking explicitly for episodes that have a status of `archived`. You have any idea why?

**Comment by fernandog** [comment] 2017-11-09 08:21
ARCHIVED means It wont snatch any other quality but If show has subtitle enabled and EP is missing subs It will download it.  So ARCHIVED is not related with subs

**Comment by p0psicles** [comment] 2017-11-09 08:26
okay, but is the right? I mean, when you archive a show, your mostly done with it right?

**Comment by fernandog** [comment] 2017-11-09 08:28
Also It dont pick ALL missing Episodes in a each run. It limits.

Addic7ed active blocks subliminal. It can be after 1 request or 10. Please try opensubtiles

**Comment by fernandog** [comment] 2017-11-09 08:30
You are done with snatches. Not subs. Changing this wont make Addic7ed works.

**Comment by p0psicles** [comment] 2017-11-09 08:40
No I understand. But users assume that when `archiving` certain episodes, medusa is done with them. I'm just challenging if there is a valid use case, where you archive certain episodes, but still want to keep searching subtitles for them?

Alternative could be that we inform users somehow, that changing episodes to archived, will still have medusa search for them.

There is currently no option for users to configure, not to have medusa search for a subset of episodes of a show. You can disable subtitles only on a show level. Same goes for disabling a **show**.

**Comment by p0psicles** [comment] 2017-11-09 08:42
@pymedusa/developers anyone wants to pitch in here?

**Comment by Olivier6767** [comment] 2017-11-09 08:43
Could we implement a checkbox in the subtitles settings asking if we should still search for subtitles for Archived episodes?
This way everyone can choose the best option for their use case.

**Comment by p0psicles** [comment] 2017-11-09 08:45
Well sickrage only downloads subtitles for episodes with a status of `downloaded`.

**Comment by fernandog** [comment] 2017-11-09 08:46
It blocks subliminal based on how many subliminal users are requesting subs not only single users. Trust me, we did tons of tests

**Comment by Olivier6767** [comment] 2017-11-09 08:49
I trust you. I'm just saying that the current settings of trying to gather subtitles for older/archived episodes generates more requests, thus hitting the subliminal limits quicker.
If there is a use case to still search for subtitles for Archived episodes, maybe the checkbox option is the most flexible.

**Comment by p0psicles** [comment] 2017-11-09 08:52
First i'd like to challenge the requirement of downloading subs for archived eps. If nobody can come up with a use case, we just change it. Then as a backup a checkbox can always be an option. But if possible i'd like to not include another option.

**Comment by Olivier6767** [comment] 2017-11-09 08:56
ok, thank you.

**Comment by fernandog** [comment] 2017-11-09 09:53
The use case is when user decide to download subs after get all episodes downloaded.

In this issue, user installed Medusa after he had all episodes already downloaded.
So by default, Medusa will try to download subtitles because subtitles are enabled.
Personally I don't see a issue with that, its by design.

**Comment by Olivier6767** [comment] 2017-11-09 15:48
If the user user decides to download subs after all episodes are downloaded, this will happen automatically as long as the episodes are in **Downloaded** status. The question is if the subs should get downloaded even after episodes are marched as **Archived**. I think it should not.

Then, episodes can still be changed back from **Archived** to **Downloaded** if the user wants to fetch subs for them after the fact.

This would provide a more flexible option allowing for both uses cases.

**Comment by NicoLeOca** [comment] 2017-11-10 18:12
Hi,
I use subtitles on a regular basis and I agree that Medusa shouldn't search for subtiles of archived episodes.

**Comment by medariox** [comment] 2017-11-17 16:48
The change has been merged to develop and will be available in master in the next release.
https://github.com/pymedusa/Medusa/pull/3266

Thanks for the feedback!

**Closed by medariox** 2017-11-17 16:48 UTC
Labels: Discussion, Question

**Comment by fernandog** [comment] 2017-11-27 12:57
Latest subliminal which is already in master wont raise `Too many requests` anymore. It will debug log that provider didn't replied with any data
