### ISSUE TITLE
"Found hanging associated files" deleted my files

### ISSUE THREAD

**Issue by deusxanime** [pymedusa/Medusa#4449] opened 2018-06-22 17:47 UTC
Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)
^ Don't really want to delete more files to do this but might be able to work something out if really needed.

**Branch/Commit:** master / c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**OS:** Linux-4.14.40-unRAID-x86_64-with (unRAID linuxserver.io docker container)

**What you did:** Renaming some files that are cross-over episodes with other series and then re-scanned them to update qualities/status.
**What happened:** It deleted my files without asking!
**What you expected:** Just updated the qualities or at least throw a warning and ASK before deleting
**Logs:**
```
2018-06-22 11:49:25 INFO     SHOWQUEUE-REFRESH :: [c65ca26] Trying to clean any empty folder under /tv/tv shows/The Flash (2014)
2018-06-22 11:49:25 INFO     SHOWQUEUE-REFRESH :: [c65ca26] 279121: Looking for hanging associated files for: 'The Flash (2014)' S03E17 in: /tv/tv shows/The Flash (2014)/Season 3/The Flash (2014) - 3x17 - Duet (Part 2 of 2).mkv
2018-06-22 11:49:25 INFO     SHOWQUEUE-REFRESH :: [c65ca26] 279121: Found hanging associated files for 'The Flash (2014)' S02E08, deleting: '/tv/tv shows/The Flash (2014)/Season 2/The Flash (2014) - 2x08 - Legends of Today (1) [x-o Arrow 4x08].720p.HDTV.h264.mkv'
2018-06-22 11:49:25 INFO     SHOWQUEUE-REFRESH :: [c65ca26] 279121: Looking for hanging associated files for: 'The Flash (2014)' S02E08 in: /tv/tv shows/The Flash (2014)/Season 2/The Flash (2014) - 2x08 - Legends of Today.mkv
2018-06-22 11:49:25 INFO     SHOWQUEUE-REFRESH :: [c65ca26] 279121: Found hanging associated files for 'The Flash (2014)' S01E08, deleting: '/tv/tv shows/The Flash (2014)/Season 1/The Flash (2014) - 1x08 - Flash vs. Arrow (1) [x-o Arrow 3x08].720p.HDTV.h264.mkv'
2018-06-22 11:49:25 INFO     SHOWQUEUE-REFRESH :: [c65ca26] 279121: Looking for hanging associated files for: 'The Flash (2014)' S01E08 in: /tv/tv shows/The Flash (2014)/Season 1/The Flash (2014) - 1x08 - Flash vs. Arrow.mkv
2018-06-22 11:49:06 INFO     SHOWQUEUE-REFRESH :: [c65ca26] 279121: Performing refresh on The Flash (2014)
```

This is completely crazy to me. The program should NEVER delete a file without asking/prompting. I'm still not even sure why it did so or what "Found hanging associated files" means. Frankly, I think there should be an option in settings (I don't see one currently unless I missed it) to NEVER allow Medusa to delete a file AT ALL. At most it should just log a warning/error for the user and then allow them to take action if needed.

edit: Also just want to say that I have had other shows named similarly with crossover and Medusa doesn't seem to have a problem with them. For example - "CSI - Crime Scene Investigation - 10x07 - The Lost Girls (3) [x-o CSI Miami 08x07, CSI NY 6x07].DVD.XviD.avi" is in Medusa just fine without issue.

**Comment by medariox** [comment] 2018-06-23 00:11
The problem is that you have multiple files for the same episode. That's not supported at all. You should have one file per episode in your library. Either keep `The Flash (2014) - 1x08 - Flash vs. Arrow.mkv` or `The Flash (2014) - 1x08 - Flash vs. Arrow (1) [x-o Arrow 3x08].720p.HDTV.h264.mkv`.

**Comment by deusxanime** [comment] 2018-06-23 03:21
I never did have two files for the same episode though, not sure why it would have thought that... I renamed it from one to the other. Perhaps it added the new first before removing the old and so it briefly thought I had two, even though I did not? Either way, deleting a file without user acknowledgement doesn't seem like it should be the answer. I'm having to go out and find those files again and it is a PITA as they are from a couple years back and not well seeded.

**Comment by medariox** [comment] 2018-06-23 12:19
Can't reproduce the issue with the files getting deleted. You will need to post debug logs as well.

**Comment by deusxanime** [comment] 2018-06-24 19:30
I'll turn debug on as I keep sorting my files and see if it happens again for a third time. Honestly I'd rather not but that way if it does I can post the logs here.

**Comment by medariox** [comment] 2018-07-14 16:19
Closing as it seems solved.

**Closed by medariox** 2018-07-14 16:19 UTC
Labels: Can't reproduce, Support
