### ISSUE TITLE
Medusa doesn't success to search series

### ISSUE THREAD

**Issue by Whisper40** [pymedusa/Medusa#9361] opened 2021-03-18 21:47 UTC
Hello, i re open this issue #5965  because medusa is not using any of my jackett providers ( no problem with radarr & sonarr  with jackett too)
medusa is not able to find any series, same problem for all series.
No one filter is blocking the search ( no one has been configured to block )

Thanks for help
![image](https://user-images.githubusercontent.com/30440458/111701462-2d562380-883b-11eb-80aa-600d9dcdaf9a.png)
![image](https://user-images.githubusercontent.com/30440458/111701528-465ed480-883b-11eb-9b54-ef35df4e3ac8.png)

My debug logs : 
```
2021-03-18 21:39:58 INFO     FORCEDSEARCHQUEUE-BACKLOG-268592 :: [] Beginning backlog search for: Les 100
2021-03-18 21:39:58 INFO     FORCEDSEARCHQUEUE-BACKLOG-268592 :: [] Updating exception_cache and exception_season_cache
2021-03-18 21:39:58 INFO     FORCEDSEARCHQUEUE-BACKLOG-268592 :: [] Finished processing 3425 scene exceptions.
2021-03-18 21:39:58 INFO     FORCEDSEARCHQUEUE-BACKLOG-268592 :: [] Building internal name cache for Les 100
2021-03-18 21:39:58 DEBUG    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [] Internal name cache for les 100 set to: les 100
2021-03-18 21:39:58 INFO     FORCEDSEARCHQUEUE-BACKLOG-268592 :: [] Using backlog search providers
2021-03-18 21:39:58 WARNING  FORCEDSEARCHQUEUE-BACKLOG-268592 :: [] No NZB/Torrent providers found or enabled in the application config for backlog searches. Please check your settings
2021-03-18 21:39:58 DEBUG    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [] Combining single and multi-episode results
2021-03-18 21:39:58 DEBUG    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [] No results to sort.
2021-03-18 21:39:58 INFO     FORCEDSEARCHQUEUE-BACKLOG-268592 :: [] No needed episodes found during backlog search for: Les 100
```

**Comment by medariox** [comment] 2021-03-18 22:22
https://github.com/pymedusa/Medusa/issues/5965#issuecomment-452010523
https://github.com/pymedusa/Medusa/issues/5965#issuecomment-453502095

If you don't get any categories it likely that you are using the wrong URL.
Moving to Q&A as this is surely not a bug.

**Closed** 2021-03-18 22:22 UTC
