### ISSUE TITLE
Results for manual search contain broken/invalid HTML

### ISSUE THREAD

**Issue by below9k** [pymedusa/Medusa#7742] opened 2020-02-10 17:48 UTC
`snatchSelection/` route results table's first entry "Release" (row:1, column:1) is showing broken html sometimes

**To Reproduce**
1. Navigate to a show
2. Click on the manual search option for an episode
3. Wait for results...
4. Notice the first row "Release" name has partial html in it

**Expected behavior**
Print the release name and html correctly

**Screenshots**
![Screen Shot 2020-02-10 at 11 40 44 AM](https://user-images.githubusercontent.com/6232236/74174781-31585080-4bfa-11ea-84f7-838272323d27.png)

**Medusa Info**
Branch: master
Commit: ee1b898d0f74750c4c265d077fcc0da73d17b41e
Version: 0.3.12
Database: 44.14
Python Version: 2.7.12 (default, Oct 8 2019, 14:14:10) [GCC 5.4.0 20160609]
SSL Version: OpenSSL 1.0.2g 1 Mar 2016
OS: Linux-4.15.0-76-generic-x86_64-with-Ubuntu-16.04-xenial
Locale: en_US.UTF-8

**Additional context**
Might not happen every time or I don't notice it every time. Maybe this happens to other rows?

**EDIT** 19/02/2020: ~Looks like it might just be the snached (purple/pink) item that has the broken text.~ Actually looks like it might be something to do with the characters in the name. I have anime with the same subber "`[Erai-raws]`" doing the same thing 
![Screen Shot 2020-02-19 at 10 13 40 AM](https://user-images.githubusercontent.com/6232236/74851190-82ee9280-5300-11ea-8a3c-38728de9e625.png)

**Comment by sharkykh** [comment] 2020-02-20 08:51
The <code>\`</code> character is the issue in both screenshots.
The issue is on the following line, on the `class` attribute.
https://github.com/pymedusa/Medusa/blob/d0e90f9843f109424949899efdd2b3156f6c6e72/themes-default/slim/views/snatchSelection.mako#L122

**Comment by rafi-d** [comment] 2020-02-21 07:54
Just a thought regarding "links" in manual search: 

 Will it be possible to make the show name (or the provider icon) a real link to the provided site, so one could click it to view this show-torrent (and alternatives)  on the original site?  Or if not, at lease trigger a search on the provider site with this show name as parameter?

Thanks

**Comment by p0psicles** [comment] 2020-02-21 12:39
It's possible. And someone started working on that in the past. But it's allot of work. As you need to adjust code for each individual provider. And store it in the tables. Also not each torrent site provided a detailed page. So if you want to add this. Go ahead.

**Comment by rafi-d** [comment] 2020-02-26 17:10
> 
> 
> It's possible. And someone started working on that in the past. But it's allot of work. As you need to adjust code for each individual provider. And store it in the tables. Also not each torrent site provided a detailed page. So if you want to add this. Go ahead.

Can I request one small change then: change the providers icons on the manual search page to those clikable linked-icons that you use in the settings->search-providers' list? They are already linked to the sites. 

From there, it will be possible to change the links, adding the show name. Here is an example for rarbg:

Available link/icon is : http://dereferer.org/?https://rarbg.com   (based probably on self.url in rarbg.ph) 

My suggested addition to the code : self.search_url = https://rarbgtor.org/torrents.php?search= 
And the resulted link will be eventually for an example-episode torrent:

https://rarbgtor.org/torrents.php?search=Star.Trek.Picard.S01E05.REPACK.iNTERNAL.1080p.WEB.H264-AMRAP[rartv]

![image](https://user-images.githubusercontent.com/2458280/75369165-91721680-58cb-11ea-8b03-ac79ffc5b993.png)

 what do you think?

**Comment by medariox** [comment] 2020-12-16 14:28
Should be fixed.

**Closed by medariox** 2020-12-16 14:28 UTC
Labels: Bug, Frontend
