### ISSUE TITLE
[APP SUBMITTED]: IOError: [Errno 22] invalid mode ('rb') or filename: u'Z:\\TV Shows\\The Blacklist\\Season 3\\The Blacklist S03E18 Mr. Solomon? Conclusion 1080p WEB-DL DD5.1 H264.mkv'

### ISSUE THREAD

**Issue by stephan-schwarz** [pymedusa/Medusa#3596] opened 2018-01-10 21:04 UTC
### INFO
**Python Version**: `2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-2012Server-6.2.9200`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@7b9111eef5836a6846499ef257ffff3f1f35df8f
**Link to Log**: https://gist.github.com/2b50534491715189d145e010377c7785
### ERROR
<pre>
2018-01-10 03:04:44 ERROR    SHOWQUEUE-REFRESH :: [7b9111e] 266189: Error while refreshing show The Blacklist. Error: 
Traceback (most recent call last):
  File "D:\Medusa\medusa\show_queue.py", line 629, in run
    self.show.refresh_dir()
  File "D:\Medusa\medusa\tv\series.py", line 1831, in refresh_dir
    cur_loc, subfolders=True)
  File "D:\Medusa\medusa\post_processor.py", line 191, in list_associated_files
    processed_names += filter(None, (self._rar_basename(file_path, files),))
  File "D:\Medusa\medusa\post_processor.py", line 301, in _rar_basename
    for rar in rars:
  File "D:\Medusa\medusa\post_processor.py", line 299, in <genexpr>
    rars = (x for x in files if rarfile.is_rarfile(x))
  File "D:\Medusa\ext\rarfile.py", line 404, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "D:\Medusa\ext\rarfile.py", line 389, in _get_rar_version
    with XFile(xfile) as fd:
  File "D:\Medusa\ext\rarfile.py", line 2401, in __init__
    self._fd = open(xfile, 'rb', bufsize)
IOError: [Errno 22] invalid mode ('rb') or filename: u'Z:\\TV Shows\\The Blacklist\\Season 3\\The Blacklist S03E18 Mr. Solomon? Conclusion 1080p WEB-DL DD5.1 H264.mkv'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment] 2018-01-11 19:03
Duplicate of https://github.com/pymedusa/Medusa/issues/3596

**Closed by medariox** 2018-01-11 19:03 UTC
Labels: Duplicate
