### ISSUE TITLE
adding show Dr. Phil locks browser on show load

### ISSUE THREAD

**Issue by jxer** [pymedusa/Medusa#5298] opened 2018-09-24 14:10 UTC
add this show to medusa lastest master.

after it adds from tvdb2, trying to go into the show itself causes the browser to go unresponsive. tried 2 times, both times it locks up, requiring a restore of the server since i can't go into the show to delete it

**Comment by medariox** [comment] 2019-03-03 20:20
Duplicate of https://github.com/pymedusa/Medusa/issues/5856

**Closed by medariox** 2019-03-03 20:20 UTC
Labels: Support
