### ISSUE TITLE
unable to find hdtv episode

### ISSUE THREAD

**Issue by MrAurik** [pymedusa/Medusa#4688] opened 2018-07-17 19:26 UTC
**Describe the bug**

I have a problem with the hdtv search, the episode is hd but medusa refuse it.

do you know why ?

thanks in advance.

**Medusa (please complete the following information):**
 - OS: Alpine linux 3.7, docker medusa for synology
 - Branch: master
 - Commit: v0.2.6  e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64 

**Logs:**
<details>

2018-07-18 16:33:01 INFO     SEARCHQUEUE-FORCED-80379 :: [e7c4ff3] Unable to find forced results for: The Big Bang Theory - S11E23 - 
2018-07-18 16:33:01 DEBUG    SEARCHQUEUE-FORCED-80379 :: [e7c4ff3] 80379: Formatting pattern: %SN - S%0SE23 - %EN -> The Big Bang Theory - S11E23 - 
2018-07-18 16:33:01 DEBUG    SEARCHQUEUE-FORCED-80379 :: [e7c4ff3] No results to sort.
2018-07-18 16:33:01 DEBUG    SEARCHQUEUE-FORCED-80379 :: [e7c4ff3] Combining single and multi-episode results
2018-07-18 16:33:01 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] No wanted results found.
2018-07-18 16:33:01 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] The.Big.Bang.Theory.S11E23.HDTV.VOSTFR is an unwanted quality, rejecting it
2018-07-18 16:33:01 INFO     SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Quality of The.Big.Bang.Theory.S11E23.HDTV.VOSTFR is SDTV
2018-07-18 16:33:01 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] The.Big.Bang.Theory.S11E23.HDTV.VOSTFR is an unwanted quality, rejecting it
2018-07-18 16:33:01 INFO     SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Quality of The.Big.Bang.Theory.S11E23.HDTV.VOSTFR is SDTV
2018-07-18 16:33:01 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Transaction with 2 queries executed
2018-07-18 16:33:01 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Found single episode result The.Big.Bang.Theory.S11E23.HDTV.VOSTFR at http://192.168.1.22:39177/dl/torrent9/?jackett_apikey=**********&path=c1hBdzRjWGd3SzY2a1diTEZsZDNNa3BKcE5STFBTczE5RWtaVnMwZis2S0Q4ZFd1NElDeFFXdUh0ckNvbytnRTFDaXE4cGM1cXRZbldSZUJYajNnb1M1cmNqY3FraWhQakJac0M5bFJCbHRPRXFTclh5a0ZaTnFxVjV3aythYXRpdXJ6ZnhZRk1uZTd4QnY5aFhwaGxmUERwb2toQUJqUk9STlJTOC9ldm1KRUtCeGJ2S085VzJIUFViOWxIalJqbjNUNGxoNjNheWh0SmQ2M0dBQ3NsOTJoV2xGb1I5VUx0Qzh1YkFJY0xDZCs2Zm1saTdZWHBnOXFad1BjZDQzMjFXVTFtOWJsSDFINWU5MTNKbkhzUHBvVUdIeFRGTHNBS2lnbytGNTArdmNNNUVxY256cUFCdXZvNTY4N0dFUUtYZHFTOHZnU0lTdnJIWlJEakY4QUQ3SmtKWkpZekhNa3Vadk5MVktROFZMOG1VRlJGKy9EOWFzNlZDVnJwMTY40&file=The+Big+Bang+Theory+S11E23+HDTV+VOSTFR+
2018-07-18 16:33:01 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Found result The.Big.Bang.Theory.S11E23.HDTV.VOSTFR at http://192.168.1.22:39177/dl/torrent9/?jackett_apikey=**********&path=c1hBdzRjWGd3SzY2a1diTEZsZDNNa3BKcE5STFBTczE5RWtaVnMwZis2S0Q4ZFd1NElDeFFXdUh0ckNvbytnRTFDaXE4cGM1cXRZbldSZUJYajNnb1M1cmNqY3FraWhQakJac0M5bFJCbHRPRXFTclh5a0ZaTnFxVjV3aythYXRpdXJ6ZnhZRk1uZTd4QnY5aFhwaGxmUERwb2toQUJqUk9STlJTOC9ldm1KRUtCeGJ2S085VzJIUFViOWxIalJqbjNUNGxoNjNheWh0SmQ2M0dBQ3NsOTJoV2xGb1I5VUx0Qzh1YkFJY0xDZCs2Zm1saTdZWHBnOXFad1BjZDQzMjFXVTFtOWJsSDFINWU5MTNKbkhzUHBvVUdIeFRGTHNBS2lnbytGNTArdmNNNUVxY256cUFCdXZvNTY4N0dFUUtYZHFTOHZnU0lTdnJIWlJEakY4QUQ3SmtKWkpZekhNa3Vadk5MVktROFZMOG1VRlJGKy9EOWFzNlZDVnJwMTY40&file=The+Big+Bang+Theory+S11E23+HDTV+VOSTFR+
2018-07-18 16:33:01 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Added RSS item: The.Big.Bang.Theory.S11E23.HDTV.VOSTFR to cache: jackett_torrent9 with url http://192.168.1.22:39177/dl/torrent9/?jackett_apikey=**********&path=c1hBdzRjWGd3SzY2a1diTEZsZDNNa3BKcE5STFBTczE5RWtaVnMwZis2S0Q4ZFd1NElDeFFXdUh0ckNvbytnRTFDaXE4cGM1cXRZbldSZUJYajNnb1M1cmNqY3FraWhQakJac0M5bFJCbHRPRXFTclh5a0ZaTnFxVjV3aythYXRpdXJ6ZnhZRk1uZTd4QnY5aFhwaGxmUERwb2toQUJqUk9STlJTOC9ldm1KRUtCeGJ2S085VzJIUFViOWxIalJqbjNUNGxoNjNheWh0SmQ2M0dBQ3NsOTJoV2xGb1I5VUx0Qzh1YkFJY0xDZCs2Zm1saTdZWHBnOXFad1BjZDQzMjFXVTFtOWJsSDFINWU5MTNKbkhzUHBvVUdIeFRGTHNBS2lnbytGNTArdmNNNUVxY256cUFCdXZvNTY4N0dFUUtYZHFTOHZnU0lTdnJIWlJEakY4QUQ3SmtKWkpZekhNa3Vadk5MVktROFZMOG1VRlJGKy9EOWFzNlZDVnJwMTY40&file=The+Big+Bang+Theory+S11E23+HDTV+VOSTFR+
2018-07-18 16:33:01 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Adding item from search to cache: u'The.Big.Bang.Theory.S11E23.HDTV.VOSTFR'
2018-07-18 16:33:01 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Found single episode result The.Big.Bang.Theory.S11E23.HDTV.VOSTFR at http://192.168.1.22:39177/dl/torrent9/?jackett_apikey=**********&path=L09yOGZsVjhnUUorenVvcFJiRGRzT09XeUQvK1VreTREUFJyYVN5ZmVKcVVkVkNBTXhhYXQ1bENNb3MwenJJbzNZeXVlTGhrSXZYcXdtT3crZHl0QVJ2Yys2K3FYTnZxNXY3ZjAzK2sxZWlHdWxvdjVWdHFuR1RVd1RuVnRTdWF0SXFEUEl6cXBpb29mMFNFY25wd0ZZN2t4Tkgrb2xVUnpoc29nSWViR1lPOXJMN0NQdVlpQStsQjhMeGJNcVhhb29vNUl4czF5NlRKVFpndHFCeFJycXFVS1R5NVJzMEdidmVtcnczWGtXL2hqUFZaQ2pUdWQyR2lrRVl3UHN0R0dZQUh4NEVFcUZWVTFlK3kzOGJiVVZ4ZWwxcGRXRGZ3SkN5ZkpwSTlUc0RPSVVneGZQelA3andOVTVsRzNvZ1NySjFLc1ZneVgzN2F1dWxINXZ0VDVOVjlKNlR4U2lsZ0JJOTc5UGFvTjV6Mk5HZTRqMmMvcUVvU0hsOU1GeUNH0&file=The+Big+Bang+Theory+S11E23+HDTV+VOSTFR+
2018-07-18 16:33:01 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Found result The.Big.Bang.Theory.S11E23.HDTV.VOSTFR at http://192.168.1.22:39177/dl/torrent9/?jackett_apikey=**********&path=L09yOGZsVjhnUUorenVvcFJiRGRzT09XeUQvK1VreTREUFJyYVN5ZmVKcVVkVkNBTXhhYXQ1bENNb3MwenJJbzNZeXVlTGhrSXZYcXdtT3crZHl0QVJ2Yys2K3FYTnZxNXY3ZjAzK2sxZWlHdWxvdjVWdHFuR1RVd1RuVnRTdWF0SXFEUEl6cXBpb29mMFNFY25wd0ZZN2t4Tkgrb2xVUnpoc29nSWViR1lPOXJMN0NQdVlpQStsQjhMeGJNcVhhb29vNUl4czF5NlRKVFpndHFCeFJycXFVS1R5NVJzMEdidmVtcnczWGtXL2hqUFZaQ2pUdWQyR2lrRVl3UHN0R0dZQUh4NEVFcUZWVTFlK3kzOGJiVVZ4ZWwxcGRXRGZ3SkN5ZkpwSTlUc0RPSVVneGZQelA3andOVTVsRzNvZ1NySjFLc1ZneVgzN2F1dWxINXZ0VDVOVjlKNlR4U2lsZ0JJOTc5UGFvTjV6Mk5HZTRqMmMvcUVvU0hsOU1GeUNH0&file=The+Big+Bang+Theory+S11E23+HDTV+VOSTFR+
2018-07-18 16:33:01 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Added RSS item: The.Big.Bang.Theory.S11E23.HDTV.VOSTFR to cache: jackett_torrent9 with url http://192.168.1.22:39177/dl/torrent9/?jackett_apikey=**********&path=L09yOGZsVjhnUUorenVvcFJiRGRzT09XeUQvK1VreTREUFJyYVN5ZmVKcVVkVkNBTXhhYXQ1bENNb3MwenJJbzNZeXVlTGhrSXZYcXdtT3crZHl0QVJ2Yys2K3FYTnZxNXY3ZjAzK2sxZWlHdWxvdjVWdHFuR1RVd1RuVnRTdWF0SXFEUEl6cXBpb29mMFNFY25wd0ZZN2t4Tkgrb2xVUnpoc29nSWViR1lPOXJMN0NQdVlpQStsQjhMeGJNcVhhb29vNUl4czF5NlRKVFpndHFCeFJycXFVS1R5NVJzMEdidmVtcnczWGtXL2hqUFZaQ2pUdWQyR2lrRVl3UHN0R0dZQUh4NEVFcUZWVTFlK3kzOGJiVVZ4ZWwxcGRXRGZ3SkN5ZkpwSTlUc0RPSVVneGZQelA3andOVTVsRzNvZ1NySjFLc1ZneVgzN2F1dWxINXZ0VDVOVjlKNlR4U2lsZ0JJOTc5UGFvTjV6Mk5HZTRqMmMvcUVvU0hsOU1GeUNH0&file=The+Big+Bang+Theory+S11E23+HDTV+VOSTFR+
2018-07-18 16:33:01 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Adding item from search to cache: u'The.Big.Bang.Theory.S11E23.HDTV.VOSTFR'
2018-07-18 16:33:01 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Using cached parse result for The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:33:01 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Using cached parse result for The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:33:01 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Found qualities: [2]
2018-07-18 16:33:01 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Found 2 unique items
2018-07-18 16:33:01 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Found result: The Big Bang Theory S11E23 HDTV VOSTFR with 121 seeders and 124 leechers
2018-07-18 16:33:00 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] User-Agent: Medusa/0.2.6 (Linux; 3.10.105; f6ba58f5-8864-11e8-a158-0242ac110002)
2018-07-18 16:33:00 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] GET URL: **********api?apikey=**********&cat=5000%2C5010%2C5020%2C5030%2C5040%2C5045%2C5050%2C5060%2C5070%2C5080&q=The+Big+Bang+Theory+S11E23&limit=100&t=search&offset=0 [Status: 200]
2018-07-18 16:33:00 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Search show using search string: The Big Bang Theory S11E23
2018-07-18 16:33:00 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] No results returned from provider. Check chosen Torznab search categories in provider settings.
2018-07-18 16:33:00 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] User-Agent: Medusa/0.2.6 (Linux; 3.10.105; f6ba58f5-8864-11e8-a158-0242ac110002)
2018-07-18 16:33:00 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] GET URL: **********api?apikey=**********&cat=5000%2C5010%2C5020%2C5030%2C5040%2C5045%2C5050%2C5060%2C5070%2C5080&q=TBBT+S11E23&limit=100&t=search&offset=0 [Status: 200]
2018-07-18 16:33:00 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Search show using search string: TBBT S11E23
2018-07-18 16:33:00 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Found result: The Big Bang Theory S11E23 HDTV VOSTFR with 121 seeders and 124 leechers
2018-07-18 16:33:00 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] User-Agent: Medusa/0.2.6 (Linux; 3.10.105; f6ba58f5-8864-11e8-a158-0242ac110002)
2018-07-18 16:33:00 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] GET URL: **********api?apikey=**********&cat=5000%2C5010%2C5020%2C5030%2C5040%2C5045%2C5050%2C5060%2C5070%2C5080&q=Big+Bang+Theory+S11E23&limit=100&t=search&offset=0 [Status: 200]
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Search show using search string: Big Bang Theory S11E23
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Search mode: Episode
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Ignoring The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Ignoring found result for 'The Big Bang Theory' S11E23 with unwanted quality 'SDTV'
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Allowed, Preferred = [ 720p HDTV, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay ] [ None ] Found = [ SDTV ]
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Using cached parse result for The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Ignoring The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Ignoring found result for 'The Big Bang Theory' S11E23 with unwanted quality 'SDTV'
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Allowed, Preferred = [ 720p HDTV, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay ] [ None ] Found = [ SDTV ]
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Using cached parse result for The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Ignoring The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Ignoring found result for 'The Big Bang Theory' S11E23 with unwanted quality 'SDTV'
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Allowed, Preferred = [ 720p HDTV, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay ] [ None ] Found = [ SDTV ]
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Using cached parse result for The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Ignoring The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Ignoring found result for 'The Big Bang Theory' S11E23 with unwanted quality 'SDTV'
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Allowed, Preferred = [ 720p HDTV, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay ] [ None ] Found = [ SDTV ]
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Using cached parse result for The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Ignoring The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Ignoring found result for 'The Big Bang Theory' S11E23 with unwanted quality 'SDTV'
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Allowed, Preferred = [ 720p HDTV, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay ] [ None ] Found = [ SDTV ]
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Using cached parse result for The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Ignoring The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Ignoring found result for 'The Big Bang Theory' S11E23 with unwanted quality 'SDTV'
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Allowed, Preferred = [ 720p HDTV, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay ] [ None ] Found = [ SDTV ]
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Using cached parse result for The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Ignoring The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Ignoring found result for 'The Big Bang Theory' S11E23 with unwanted quality 'SDTV'
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Allowed, Preferred = [ 720p HDTV, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay ] [ None ] Found = [ SDTV ]
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Using cached parse result for The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Ignoring The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Ignoring found result for 'The Big Bang Theory' S11E23 with unwanted quality 'SDTV'
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Allowed, Preferred = [ 720p HDTV, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay ] [ None ] Found = [ SDTV ]
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Using cached parse result for The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Ignoring The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Ignoring found result for 'The Big Bang Theory' S11E23 with unwanted quality 'SDTV'
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Allowed, Preferred = [ 720p HDTV, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay ] [ None ] Found = [ SDTV ]
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Using cached parse result for The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Ignoring The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Ignoring found result for 'The Big Bang Theory' S11E23 with unwanted quality 'SDTV'
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Allowed, Preferred = [ 720p HDTV, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay ] [ None ] Found = [ SDTV ]
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Using cached parse result for The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Ignoring The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Ignoring found result for 'The Big Bang Theory' S11E23 with unwanted quality 'SDTV'
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Allowed, Preferred = [ 720p HDTV, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay ] [ None ] Found = [ SDTV ]
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Using cached parse result for The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Ignoring The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Ignoring found result for 'The Big Bang Theory' S11E23 with unwanted quality 'SDTV'
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] 80379: Allowed, Preferred = [ 720p HDTV, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay ] [ None ] Found = [ SDTV ]
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Using cached parse result for The.Big.Bang.Theory.S11E23.HDTV.VOSTFR
2018-07-18 16:32:59 INFO     SEARCHQUEUE-FORCED-80379 :: [jackett torrent9] :: [e7c4ff3] Performing episode search for The Big Bang Theory
2018-07-18 16:32:59 INFO     SEARCHQUEUE-FORCED-80379 :: [e7c4ff3] Using backlog search providers
2018-07-18 16:32:59 DEBUG    SEARCHQUEUE-FORCED-80379 :: [e7c4ff3] Internal name cache for the big bang theory set to: tbbt, the big bang theory, big bang theory
2018-07-18 16:32:59 INFO     SEARCHQUEUE-FORCED-80379 :: [e7c4ff3] Building internal name cache for The Big Bang Theory
2018-07-18 16:32:59 INFO     SEARCHQUEUE-FORCED-80379 :: [e7c4ff3] Finished processing 2844 scene exceptions.
2018-07-18 16:32:58 INFO     SEARCHQUEUE-FORCED-80379 :: [e7c4ff3] Updating exception_cache and exception_season_cache
2018-07-18 16:32:58 INFO     SEARCHQUEUE-FORCED-80379 :: [e7c4ff3] Beginning forced search for: The Big Bang Theory - S11E23 - 
2018-07-18 16:32:58 DEBUG    SEARCHQUEUE-FORCED-80379 :: [e7c4ff3] 80379: Formatting pattern: %SN - S%0SE23 - %EN -> The Big Bang Theory - S11E23 - 

</details>

**Comment by medariox** [comment] 2018-07-17 19:29
`HDTV` is `SD TV` in Medusa. Anway, no support can be provided without debug logs. Closing until you update the issue with the debug logs of the relevant search, make sure to comment once you have them included.

**Comment by MrAurik** [comment] 2018-07-18 14:37
I've just updated my problem, but if HDTV is SDTV for medusa, it is not an "error" anymore ? ;-)

Thanks

**Comment by MrAurik** [comment] 2018-07-18 14:50
The Quality settings is HD : 720p HDTV, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay.

It was the first time I tried to download this episode.

regards.

**Comment by medariox** [comment] 2018-07-18 14:53
It's not a bug then. You need to add SDTV as wanted quality. Even if the file title says `HDTV` the actual file quality is SD. This is because the quality in the file title refers to the source of the file, not the file quality itself.

**Closed by medariox** 2018-07-18 14:53 UTC
Labels: Needs more info

**Comment by MrAurik** [comment] 2018-07-18 14:55
ok, ok, perfect, thank you !
