### ISSUE TITLE
Unable to read ' from file system

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#3345] opened 2017-11-29 16:40 UTC
Medusa Info: 
Branch: master                 
Commit: b96b3ee10760ffa03a15a207841a1a2bc65798dd                 
Version: v0.1.19                 
Database: 44.8
Python Version: | 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
SSL Version: | OpenSSL 1.0.2j  26 Sep 2016
OS: | Windows-10-10.0.14393
Locale: | nl_NL.cp1252

Coming from SickRage where I did not have this issue
When a file has a `'` in the file name Medusa generates an error.
`2017-11-29 17:26:15 WARNING  SHOWQUEUE-ADD :: [b96b3ee] Unable to scan video: C:\DATA\TVSeries\The Mayor (2017)\Season 01\The Mayor (2017) - S01E03 - Buyerâ€™s Remorse (720p.HDTV-AVS).mkv. Error: Path does not exist`
![image](https://user-images.githubusercontent.com/4103090/33386842-3050c6aa-d52c-11e7-831e-6c9b1e2370fd.png)

**Comment by p0psicles** [comment] 2017-11-29 17:07
Tnx for the report, we'll look into it.

**Comment by Rouzax** [comment] 2018-01-07 11:35
Also getting this with other characters.
```
2018-01-06 17:42:57 WARNING  FINDSUBTITLES :: [7b9111e] Unable to scan video: C:\DATA\TVSeries\Speechless\Season 01\Speechless - S01E04 - I-N-Sâ€“ INSPIRATIONS (720p.HDTV-AVS).mkv. Error: Path does not exist
2018-01-06 17:42:55 WARNING  FINDSUBTITLES :: [7b9111e] Unable to scan video: C:\DATA\TVSeries\Speechless\Season 02\Speechless - S02E06 - S-Hâ€“SHIPPING (720p.HDTV-AVS).mkv. Error: Path does not exist
2018-01-06 17:42:55 WARNING  FINDSUBTITLES :: [7b9111e] Unable to scan video: C:\DATA\TVSeries\Speechless\Season 02\Speechless - S02E07 - B-R-Iâ€“ BRITISH I-N-Vâ€“ INVASION (720p.HDTV-AVS).mkv. Error: Path does not exist
2018-01-06 17:42:55 WARNING  FINDSUBTITLES :: [7b9111e] Unable to scan video: C:\DATA\TVSeries\Speechless\Season 01\Speechless - S01E03 - B-O-Nâ€“BONFIRE (720p.HDTV-AVS).mkv. Error: Path does not exist
2018-01-06 17:42:53 WARNING  FINDSUBTITLES :: [7b9111e] Unable to scan video: C:\DATA\TVSeries\Speechless\Season 02\Speechless - S02E02 - F-Iâ€“ FIRST S-Eâ€“ SECOND Fâ€“ FIRST DAY (720p.HDTV-AVS).mkv. Error: Path does not exist
2018-01-06 17:42:53 WARNING  FINDSUBTITLES :: [7b9111e] Unable to scan video: C:\DATA\TVSeries\Speechless\Season 02\Speechless - S02E03 - J-Jâ€™S D-Râ€“DREAM (720p.HDTV-AVS).mkv. Error: Path does not exist
2018-01-06 17:42:53 WARNING  FINDSUBTITLES :: [7b9111e] Unable to scan video: C:\DATA\TVSeries\Speechless\Season 02\Speechless - S02E01 - W-Eâ€“ WEâ€™RE B-Aâ€“ BACK! (720p.HDTV-AVS).mkv. Error: Path does not exist
2018-01-06 17:42:53 WARNING  FINDSUBTITLES :: [7b9111e] Unable to scan video: C:\DATA\TVSeries\Speechless\Season 02\Speechless - S02E05 - N-Iâ€“NIGHTMARE ON D-Iâ€“DIMEO STREET (720p.HDTV-AVS).mkv. Error: Path does not exist
2018-01-06 17:42:53 WARNING  FINDSUBTITLES :: [7b9111e] Unable to scan video: C:\DATA\TVSeries\Speechless\Season 02\Speechless - S02E04 - T-TRâ€“ TRAINING D-Aâ€“ DAY (720p.HDTV-AVS).mkv. Error: Path does not exist
```

**Comment by medariox** [comment] 2018-01-07 12:02
I'm unable to reproduce this. Can you share relevant debug logs, please?

**Comment by labrys** [comment] 2018-01-07 12:07
@medariox they are UTF-8 characters on a windows system.  Specifcally the orignal was a right-single quote.

**Comment by medariox** [comment] 2018-01-07 12:09
Yes, that's what I thought. I tried to name files like that and search for subs and it works just fine for me. I'm on Windows 10 as well.
@Rouzax Can you describe the steps to reproduce the issue?

**Comment by labrys** [comment] 2018-01-07 12:10
I get this error for other characters as well.  #3445

**Comment by labrys** [comment] 2018-01-07 12:12
Removing duplicate tag because while its the same issue, the one i opened was for refreshing show, although it gets the same issue during scanning of the video.

**Comment by labrys** [comment] 2018-01-07 12:15
Examples from my system:
```
2018-01-07 02:36:44 WARNING  SHOWQUEUE-REFRESH :: [4f6f8e8] Unable to scan video: D:\series\active\Crazy Ex-Girlfriend (2015)\Season 03\Crazy Ex-Girlfriend - S03E04 - Joshâ€™s Ex-Girlfriend is Crazy.mkv. Error: Path does not exist
2018-01-07 02:36:24 WARNING  SHOWQUEUE-REFRESH :: [4f6f8e8] Unable to scan video: D:\series\active\Crazy Ex-Girlfriend (2015)\Season 02\Crazy Ex-Girlfriend - S02E05 - Why Is Joshâ€™s Ex-Girlfriend Eating Carbs.mkv. Error: Path does not exist
2018-01-07 02:36:21 WARNING  SHOWQUEUE-REFRESH :: [4f6f8e8] Unable to scan video: D:\series\active\Crazy Ex-Girlfriend (2015)\Season 02\Crazy Ex-Girlfriend - S02E03 - All Signs Point to Joshâ€¦ or Is It Joshâ€™s Friend.mkv. Error: Path does not exist
2018-01-07 02:36:02 WARNING  SHOWQUEUE-REFRESH :: [4f6f8e8] Unable to scan video: D:\series\active\Crazy Ex-Girlfriend (2015)\Season 01\Crazy Ex-Girlfriend - S01E08 - My Mom, Gregâ€™s Mom and Joshâ€™s Sweet Dance Moves!.mp4. Error: Path does not exist
2018-01-07 02:35:56 WARNING  SHOWQUEUE-REFRESH :: [4f6f8e8] Unable to scan video: D:\series\active\Crazy Ex-Girlfriend (2015)\Season 01\Crazy Ex-Girlfriend - S01E04 - Iâ€™m Going on a Date with Joshâ€™s Friend!.mp4. Error: Path does not exist
2018-01-07 02:35:53 WARNING  SHOWQUEUE-REFRESH :: [4f6f8e8] Unable to scan video: D:\series\active\Crazy Ex-Girlfriend (2015)\Season 01\Crazy Ex-Girlfriend - S01E02 - Joshâ€™s Girlfriend is Really Cool!.mp4. Error: Path does not exist
```

**Comment by medariox** [comment] 2018-01-07 12:26
Got it now. 👍

**Comment by medariox** [comment] 2018-01-07 18:19
Fixed with https://github.com/pymedusa/Medusa/pull/3581

**Closed by medariox** 2018-01-07 18:19 UTC
Labels: Bug, Confirmed
