### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='tvdb2.plex.tv', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3c9b9c6310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

### ISSUE THREAD

**Issue by ztaale** [pymedusa/Medusa#3875] opened 2018-03-18 05:22 UTC
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-5-amd64-x86_64-with-debian-9.3`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**Link to Log**: https://gist.github.com/42fa0f859a583554dee4adc92723363f
### ERROR
<pre>
2018-03-18 03:13:37 ERROR    SHOWQUEUE-REFRESH :: [d6eb72d] 295647: Error while refreshing show Blindspot. Error: Show episode search exception, could not get any episodes. Did a season [1] search. Exception: ConnectionError
HTTPSConnectionPool(host='tvdb2.plex.tv', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3c9b9c6310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/show_queue.py#L635">medusa/show_queue.py</a>", line 635, in run
    self.show.refresh_dir()
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/tv/series.py#L1753">medusa/tv/series.py</a>", line 1753, in refresh_dir
    self.load_episodes_from_dir()
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/tv/series.py#L931">medusa/tv/series.py</a>", line 931, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/tv/series.py#L1397">medusa/tv/series.py</a>", line 1397, in make_ep_from_file
    root_ep.create_meta_files()
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/tv/episode.py#L1108">medusa/tv/episode.py</a>", line 1108, in create_meta_files
    self.__create_thumbnail(metadata_provider)
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/tv/episode.py#L1131">medusa/tv/episode.py</a>", line 1131, in __create_thumbnail
    result = metadata_provider.create_episode_thumb(self) or result
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/metadata/generic.py#L326">medusa/metadata/generic.py</a>", line 326, in create_episode_thumb
    ep_obj.set_indexer_data(season=ep_obj.season, indexer_api=self.indexer_api)
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/tv/episode.py#L679">medusa/tv/episode.py</a>", line 679, in set_indexer_data
    api._get_episodes(self.series.series_id, aired_season=season)
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/indexers/tvdbv2/tvdbv2_api.py#L223">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 223, in _get_episodes
    episodes = self._query_series(tvdb_id, specials=specials, aired_season=aired_season, full_info=True)
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/indexers/tvdbv2/fallback.py#L110">medusa/indexers/tvdbv2/fallback.py</a>", line 110, in __call__
    return self.func(*args, **kwargs)
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/indexers/tvdbv2/tvdbv2_api.py#L303">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 303, in _query_series
    (search_type='full' if not aired_season else 'season {season}'.format(season=aired_season), e=e.reason)
IndexerShowIncomplete: Show episode search exception, could not get any episodes. Did a season [1] search. Exception: ConnectionError
HTTPSConnectionPool(host='tvdb2.plex.tv', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3c9b9c6310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by abeloin** [comment] 2018-03-18 13:13
Duplicate of #3874

**Closed** 2018-03-18 13:41 UTC
