### ISSUE TITLE
Medusa fails to start, python 3.6.9

### ISSUE THREAD

**Issue by sdn3rd** [pymedusa/Medusa#9485] opened 2021-04-27 18:24 UTC
Apr 27 17:47:30 lx00 medusa[29488]: from .rebulk import Rebulk
Apr 27 17:47:30 lx00 medusa[29488]: File "/opt/medusa/ext/rebulk/rebulk.py", line 8, in
Apr 27 17:47:30 lx00 medusa[29488]: from .builder import Builder
Apr 27 17:47:30 lx00 medusa[29488]: File "/opt/medusa/ext/rebulk/builder.py", line 16
Apr 27 17:47:30 lx00 medusa[29488]: class Builder(metaclass=ABCMeta):
Apr 27 17:47:30 lx00 medusa[29488]: ^
Apr 27 17:47:30 lx00 medusa[29488]: SyntaxError: invalid syntax
Apr 27 17:47:30 lx00 systemd[1]: medusa.service: Control process exited, code=exited status=1
Apr 27 17:47:30 lx00 systemd[1]: medusa.service: Failed with result 'exit-code'.
Apr 27 17:47:30 lx00 systemd[1]: Failed to start LSB: starts instance of Medusa.
root@lx00:/opt/medusa# env python
Python 3.6.9 (default, Jan 26 2021, 15:33:00)

**Comment by medariox** [comment] 2021-04-27 19:22
Duplicate of https://github.com/pymedusa/Medusa/issues/9484

**Closed by medariox** 2021-04-27 19:22 UTC
