### ISSUE TITLE
Paginating show view - is implemented "illogically"... Suggesting to fix/improve

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#7385] opened 2019-11-19 19:37 UTC
Using 0.37. Nice work with improved vue!  
Just commenting on a "bug" in the new pagination feature:

1. See attached. When paginating by lines # (as per the current design) - seasons are being split in the middle between pages. 
2. Also the summery in the bottom lines is illogical for the last/first season when splitted

 I suggest to fix it by:
A.  Page size will be # of seasons, and not # lines , so for example : page=2 - two *whole* seasons=1 page
B. Provide the paging control also at the beginning of the page, not only at the bottom

![1](https://user-images.githubusercontent.com/2458280/69179684-97aa6700-0b14-11ea-8fde-e64b23f0c111.png)

**Comment by p0psicles** [comment] 2019-11-20 06:41
That's not that easy to implement unfortunately.

**Comment by p0psicles** [comment] 2019-11-20 06:41
I'll add an option that disabled pagination

**Comment by rafi-d** [comment] 2019-11-20 06:45
Good workaround... But, that it is the logical way to do it, right?...  Isn't it just adding up/counting the episodes and split in the right place?... :)

**Comment by p0psicles** [comment] 2019-11-20 07:59
Yeah, but i'm using vue-good-tables for the vue table rendering. I already had to add allot of modifications. And pagination was one of the features I could kinda use out of the box. So rewriting that will cost me like 3 days. I can use my time better. So i'm moving on.

**Comment by rafi-d** [comment] 2019-11-20 08:15
OK. 

On a side-note: 
I wanted to open a couple of PRs (utorrent client fix,  season 0 support, etc), and had problems syncing  my remote fork to you (push -force of develop did not work, it asked to merge stuff). 
What would be the easiest way for me to "reset" my remote fork to your *current* develop branch, so to easily checkin the PR into it?

Thanks
what would be the quickest way for me to "reset"/sync my

**Comment by p0psicles** [comment] 2019-11-20 08:37
you can checkin at discord?

**Comment by rafi-d** [comment] 2019-11-20 08:43
No. Never tried/registered.

**Comment by p0psicles** [comment] 2019-11-20 08:45
https://discord.gg/zMdAdUK

**Comment by shawnhicks** [comment] 2019-11-30 05:11
> I'll add an option that disabled pagination

Where is the "DISABLE PAGINATION" option? This feature is useless to me, it makes the pages load substantially slower than without. Can't access Specials until browser lets me get to the end of the page, choose All, wait some more for the fields to be prettied up, scroll again to the end (HOME and END key navigation seem to be broken as well). 
The dropdown for season lists Specials as the first item, but does nothing when they're not visible due to episode limit. Saturday Night Live should be your test case, as it probably has the largest number of episodes including specials. 
I like the "Search Episodes" entry box, but it needs a "clear filter/search" button. It would be nice to search show descriptions, not just titles. I always wondered why episode descriptions wasn't optionally displayed as a separate field instead of just a hover.

**Comment by rafi-d** [comment] 2019-11-30 06:30
> Can't access Specials until browser lets me get to the end of the page,

Do you auto-download specials? If so, how?

**Comment by shawnhicks** [comment] 2019-11-30 07:25
I don't auto-download specials, I search for them manually. To clarify, with the new pagination, I can't see the Specials section of the page until overriding the limit at the bottom of the initially loaded page, then waiting for the rest to draw.

**Comment by p0psicles** [comment] 2019-11-30 07:54
Pls tone it down a notch. I've spend allot of hours trying to improve this project for you guys. Sometime it takes a couple of iterations. I'll add the option when I get time and feel like it. Because users like you, I feel less like it

**Comment by rafi-d** [comment] 2019-11-30 08:07
> 
> 
> I don't auto-download specials, I search for them manually. To clarify, with the new pagination, I can't see the Specials section of the page until overriding the limit at the bottom of the initially loaded page, then waiting for the rest to draw.

Do you want to test my modification so to try auto-downloading the specials?

**Comment by p0psicles** [comment] 2019-11-30 08:17
@rafi-d you can create a PR. I'm also interested.

**Comment by rafi-d** [comment] 2019-11-30 08:28
Sure, after I am satisfied it is working *well*, so not to take much of your time...  If someone else can try it out - it can help.

It is not easy to test it, since specials are rare, and the way I test it (at least that it becomes "wanted") , is by changing my PC date. 
Sadly, I don't know how to change it back to unaired status. Any easy way to do it?

**Comment by medariox** [comment] 2019-11-30 09:19
Change the value in the DB.

**Comment by rafi-d** [comment] 2019-11-30 13:17
> 
> 
> Change the value in the DB.

For some reason it does not seem to work (changed to episode status 1). Is it related being in season 0? or to cache?

It might be useful is you can add "Unaired" to the  Change status to: list on the show page ... :)

**Comment by shawnhicks** [comment] 2019-11-30 16:11
How do I roll back to a version that doesn't have pagination? The following is the performance analysis of SNL. I'm ready to fork, where was the pagination last disabled/unimplemented?

![image](https://user-images.githubusercontent.com/26195502/69902990-b3014780-1348-11ea-8c6a-bd433f84d9c9.png)

**Comment by medariox** [comment] 2019-11-30 17:11
No kidding, it's because you are disabling pagination. You can check the commit history yourself. Stop polluting this thread with nonsense.

**Comment by p0psicles** [comment] 2019-11-30 17:15
Cleaning thread

**Comment by shawnhicks** [comment] 2019-12-02 02:39
To be blunt, I love Medusa, I loved it's predecessors; I'm annoyed that pagination is slowing my use down, and that work on a feature that doesn't appear to add value has been prioritized over a verifiable UI bug I reported 6 weeks ago. 
While I understand the described intent behind pagination, I don't see how it's an optimization or improves UX, it is increasing script processing by the browser and adding a detrimental delay. 
It takes 85 seconds to load SNL over the network by initiating separate http get requests for each season and waiting for the browser to draw a table before requesting the next season. That's irrespective of the actual script processing time. (Ironic that it's chopping tables by episode count rather than displaying each entire season until the limit is reached.) 
The entire show is loaded (all seasons are transferred) whether or not it's displayed, so it's not about saving server cpu time or network bandwidth, only to present/draw tables one at a time instead of the entire page at once. I did wireshark captures to confirm behavior. 
I want to go back to default displaying the whole page with a single get, how can I do that? I've never had an issue with a second or two (or ten) of black screen while a page loads, but this multi-minute delay in getting to the Specials season of SNL is disturbing. (It happens to be the highest number of episodes of any show I use.) The additional cpu usage on both the server and the client retards performance.
If there's a more appropriate location to voice my complaint, please inform me. If I can get an expedited resolution to this issue, I might be willing to pay for it.

**Comment by p0psicles** [comment] 2019-12-02 11:24
@shawnhicks as you can see in PR #7438 i've added the option.
My billable rate is € 60 an hour. I've spent two hours on it.
Let me know how you want to do the transaction.

Having that out of the way. You don't have any right to complain. I do this in my spare time. I'm not getting paid for it. I enjoy programming. But the enjoyment goes away pretty fast with people like you thinking they are entitled to support, while doing absolutely nothing to help the project them self. Did you create any pull requests? Did you help others by answering questions in github issues or on discord? Did you write any documentation in the WIKI? No. But you do know which feature adds value and which does not? And dare to complain about us spending time on "not-important" features over your personal issue?

Let me tell you, if you know best. Then improve displayShow. We'll be expecting a PR.

**Comment by shawnhicks** [comment] 2019-12-02 17:31
As soon as I see it working in production, I'd be happy to paypal your €120.

**Comment by shawnhicks** [comment] 2019-12-14 20:24
I'm thrilled to see the option to disable pagination working in production, unfortunately the performance issue caused by loading one table at a time persists. I believe this was "vueification", I want it as fast as before the recent tampering. Willing to send partial payment as appreciation. What paypal address should I send it to?

**Comment by p0psicles** [comment] 2019-12-14 20:49
Before vueification some of the bigger shows. Like daily shows didn't load at all. They do now. So that's not an option. I did what you requested.

**Comment by shawnhicks** [comment] 2019-12-14 20:57
/home/displayShow gets this: /api/v2/series/tvdb76177/episodes?limit=1000&season=1
then it gets http://192.168.50.160:7073/api/v2/series/tvdb76177/episodes?limit=1000
Why not season=0?

**Comment by p0psicles** [comment] 2019-12-14 21:20
Tnx for reporting the bug.
I've fixed it in #7490

**Closed** 2020-09-29 18:10 UTC
Labels: triage
