### ISSUE TITLE
[APP SUBMITTED]: requests.exceptions.SSLError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /sync/collection (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))

### ISSUE THREAD

**Issue by papampi** [pymedusa/Medusa#9014] opened 2021-01-13 07:27 UTC
### INFO
**Python Version**: `3.9.0 (default, Dec 02 2020, 16:57:56) [GCC 8.4.0]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.27`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@698ca1db9903a9f716d9ed1910972cbf70ea50e8
**Link to Log**: https://gist.github.com/8fdd8b850af1666126ef3b21787e1d5a
### ERROR
<pre>
2021-01-13 10:52:23 ERROR    Thread_0 :: [698ca1d] Environment error: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /sync/collection (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/ext/urllib3/connectionpool.py#L597">ext/urllib3/connectionpool.py</a>", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/ext/urllib3/connectionpool.py#L343">ext/urllib3/connectionpool.py</a>", line 343, in _make_request
    self._validate_conn(conn)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/ext/urllib3/connectionpool.py#L839">ext/urllib3/connectionpool.py</a>", line 839, in _validate_conn
    conn.connect()
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/ext/urllib3/connection.py#L337">ext/urllib3/connection.py</a>", line 337, in connect
    self.sock = ssl_wrap_socket(
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/ext/urllib3/util/ssl_.py#L344">ext/urllib3/util/ssl_.py</a>", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/lib/python3.9/ssl.py", line 500, in wrap_socket
  File "/opt/lib/python3.9/ssl.py", line 1040, in _create
  File "/opt/lib/python3.9/ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1122)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/ext/requests/adapters.py#L439">ext/requests/adapters.py</a>", line 439, in send
    resp = conn.urlopen(
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/ext/urllib3/connectionpool.py#L637">ext/urllib3/connectionpool.py</a>", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/ext/urllib3/util/retry.py#L398">ext/urllib3/util/retry.py</a>", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /sync/collection (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/medusa/server/web/home/post_process.py#L52">medusa/server/web/home/post_process.py</a>", line 52, in processEpisode
    result = app.post_processor_scheduler.action.run(
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/medusa/process_tv.py#L61">medusa/process_tv.py</a>", line 61, in run
    return ProcessResult(path, process_method).process(force=force, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/medusa/process_tv.py#L187">medusa/process_tv.py</a>", line 187, in process
    self.process_files(dir_path, force=force, is_priority=is_priority,
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/medusa/process_tv.py#L380">medusa/process_tv.py</a>", line 380, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/medusa/process_tv.py#L600">medusa/process_tv.py</a>", line 600, in process_media
    self.result = processor.process()
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/medusa/post_processor.py#L1300">medusa/post_processor.py</a>", line 1300, in process
    notifiers.trakt_notifier.update_library(ep_obj)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/medusa/notifiers/trakt.py#L83">medusa/notifiers/trakt.py</a>", line 83, in update_library
    sync.add_to_collection(data)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/ext/trakt/core.py#L575">ext/trakt/core.py</a>", line 575, in inner
    json_data = self._handle_request('post', url, data=args)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/ext/trakt/core.py#L513">ext/trakt/core.py</a>", line 513, in _handle_request
    response = requests.request(method, url, data=json.dumps(data),
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/ext/requests/api.py#L61">ext/requests/api.py</a>", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/ext/requests/sessions.py#L542">ext/requests/sessions.py</a>", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/ext/requests/sessions.py#L655">ext/requests/sessions.py</a>", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/ext/requests/adapters.py#L514">ext/requests/adapters.py</a>", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /sync/collection (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by papampi** [comment] 2021-01-13 07:29
Enabled Trakt after last update 
This error pops up and post processor dont move downloaded episodes to their folders.
Disabled trakt again

**Comment by p0psicles** [comment] 2021-01-13 13:22
Does the trakt test button also results in this error?

**Comment by papampi** [comment] 2021-01-13 13:31
Yes, It does.
But it seems its connected
Trakt recommendation was giving some other errors when I enabled it in notifications its working now.

**Comment by p0psicles** [comment] 2021-01-13 14:05
So your not getting this error all the time? Can you reproduce the issue at all time?

**Comment by papampi** [comment] 2021-01-13 14:09
As I said earlier I disabled trakt notification because when it's enabled it won't let post processor move downloaded files.
I can enable and run any tests you need.

**Comment by raptor75** [comment] 2021-01-13 15:40
Last I had this error was because there was intermittent loss of connectivity to Trakt, hence retries  and then fail.

**Comment by p0psicles** [comment] 2021-01-13 20:41
Should be fixed in develop branch

**Closed by p0psicles** 2021-01-13 20:41 UTC

**Comment by papampi** [comment] 2021-01-13 21:58
Thanks will wit for update in master my qnap wont switch to develop again.

**Comment by papampi** [comment] 2021-01-25 13:10
### INFO
**Python Version**: `3.9.0 (default, Dec 02 2020, 16:57:56) [GCC 8.4.0]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.27`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@2b874c2c6a3c33d653eec6e50598a194627a6f76
**Link to Log**: https://gist.github.com/43cecff227a862245f2de43b478c415e
### ERROR
<pre>
2021-01-25 16:39:21 ERROR    Thread_0 :: [2b874c2] Environment error: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /oauth/device/code (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/2b874c2c6a3c33d653eec6e50598a194627a6f76/ext/urllib3/connectionpool.py#L597">ext/urllib3/connectionpool.py</a>", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/2b874c2c6a3c33d653eec6e50598a194627a6f76/ext/urllib3/connectionpool.py#L343">ext/urllib3/connectionpool.py</a>", line 343, in _make_request
    self._validate_conn(conn)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/2b874c2c6a3c33d653eec6e50598a194627a6f76/ext/urllib3/connectionpool.py#L839">ext/urllib3/connectionpool.py</a>", line 839, in _validate_conn
    conn.connect()
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/2b874c2c6a3c33d653eec6e50598a194627a6f76/ext/urllib3/connection.py#L337">ext/urllib3/connection.py</a>", line 337, in connect
    self.sock = ssl_wrap_socket(
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/2b874c2c6a3c33d653eec6e50598a194627a6f76/ext/urllib3/util/ssl_.py#L344">ext/urllib3/util/ssl_.py</a>", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/lib/python3.9/ssl.py", line 500, in wrap_socket
  File "/opt/lib/python3.9/ssl.py", line 1040, in _create
  File "/opt/lib/python3.9/ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1122)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/2b874c2c6a3c33d653eec6e50598a194627a6f76/ext/requests/adapters.py#L439">ext/requests/adapters.py</a>", line 439, in send
    resp = conn.urlopen(
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/2b874c2c6a3c33d653eec6e50598a194627a6f76/ext/urllib3/connectionpool.py#L637">ext/urllib3/connectionpool.py</a>", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/2b874c2c6a3c33d653eec6e50598a194627a6f76/ext/urllib3/util/retry.py#L398">ext/urllib3/util/retry.py</a>", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /oauth/device/code (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/2b874c2c6a3c33d653eec6e50598a194627a6f76/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/2b874c2c6a3c33d653eec6e50598a194627a6f76/medusa/server/web/home/handler.py#L454">medusa/server/web/home/handler.py</a>", line 454, in requestTraktDeviceCodeOauth
    app.TRAKT_DEVICE_CODE = trakt.get_device_code(app.TRAKT_API_KEY, app.TRAKT_API_SECRET)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/2b874c2c6a3c33d653eec6e50598a194627a6f76/ext/trakt/core.py#L228">ext/trakt/core.py</a>", line 228, in get_device_code
    device_response = requests.post(device_code_url, json=data,
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/2b874c2c6a3c33d653eec6e50598a194627a6f76/ext/requests/api.py#L119">ext/requests/api.py</a>", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/2b874c2c6a3c33d653eec6e50598a194627a6f76/ext/requests/api.py#L61">ext/requests/api.py</a>", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/2b874c2c6a3c33d653eec6e50598a194627a6f76/ext/requests/sessions.py#L542">ext/requests/sessions.py</a>", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/2b874c2c6a3c33d653eec6e50598a194627a6f76/ext/requests/sessions.py#L655">ext/requests/sessions.py</a>", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/2b874c2c6a3c33d653eec6e50598a194627a6f76/ext/requests/adapters.py#L514">ext/requests/adapters.py</a>", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /oauth/device/code (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
