### ISSUE TITLE
Rtorrent Not connecting

### ISSUE THREAD

**Issue by is33** [pymedusa/Medusa#3084] opened 2017-09-06 18:44 UTC
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:Main/latest
**OS:Ubuntu 16.x
**What you did: Attempted to connect my seedboxes rTorrent instance, doublechecked with seedbox company to confirm my information is correct
**What happened: "Could Not connect to rtorrent"
**What you expected: .... Connection to r torrent
**Logs:**
```
2017-09-06 14:43:36 DEBUG    SNATCHQUEUE-MANUALSNATCH-72218 :: [3f23fd2] Traceback (most recent call last):
  File "/opt/medusa/medusa/search/queue.py", line 487, in run
    self.success = snatch_episode(result)
  File "/opt/medusa/medusa/search/core.py", line 153, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/opt/medusa/medusa/clients/torrent/generic.py", line 242, in send_torrent
    if not self._get_auth():
  File "/opt/medusa/medusa/clients/torrent/rtorrent_client.py", line 50, in _get_auth
    self.auth = RTorrent(self.host, self.username, self.password, True, tp_kwargs=tp_kwargs)
  File "/opt/medusa/lib/rtorrent/__init__.py", line 83, in __init__
    self._verify_conn()
  File "/opt/medusa/lib/rtorrent/__init__.py", line 122, in _verify_conn
    assert "system.client_version" in self._get_rpc_methods(
  File "/opt/medusa/lib/rtorrent/__init__.py", line 161, in _get_rpc_methods
    return(self._rpc_methods or self._update_rpc_methods())
  File "/opt/medusa/lib/rtorrent/__init__.py", line 150, in _update_rpc_methods
    self._rpc_methods = self._get_conn().system.listMethods()
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/opt/medusa/lib/rtorrent/lib/xmlrpc/requests_transport.py", line 150, in request
    response.headers)
ProtocolError: <ProtocolError for http://nl4727.dediseedbox.com//rutorrent/plugins/httprpc/action.php: 401 Client Error: Unauthorized for url: http://nl4727.dediseedbox.com//rutorrent/plugins/httprpc/action.php Traceback (most recent call last):
  File "/opt/medusa/lib/rtorrent/lib/xmlrpc/requests_transport.py", line 145, in request
    response.raise_for_status()
  File "/opt/medusa/lib/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 401 Client Error: Unauthorized for url: http://nl4727.dediseedbox.com//rutorrent/plugins/httprpc/action.php
```
Side Note, this does work with couchpotato

**Comment by is33** [comment] 2017-09-06 18:50
Just for sake of being thorough:
![image](https://user-images.githubusercontent.com/1373128/30129068-b93a876e-9312-11e7-8364-f36c4ca654dd.png)

**Comment by medariox** [comment] 2017-09-06 19:01
Ist the double slash intentional?
```http://nl4727.dediseedbox.com//rutorrent/plugins/httprpc/action.php```

**Comment by is33** [comment] 2017-09-06 19:08
no, i double checked and will provide screenshots in a minute that, that is
not what is entered, it is a single slash

**Comment by medariox** [comment] 2017-09-06 19:16
No need, I have no reason to not believe you. Can you try with https instead of http? If that doesn't work either, I would say it currently only works with scgi (as that is what I currently use myself).

**Comment by is33** [comment] 2017-09-06 19:19
I am told that it won't work but I suspect it would give you a different error, log below

 File "/opt/medusa/medusa/search/queue.py", line 487, in run
    self.success = snatch_episode(result)
  File "/opt/medusa/medusa/search/core.py", line 153, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/opt/medusa/medusa/clients/torrent/generic.py", line 242, in send_torrent
    if not self._get_auth():
  File "/opt/medusa/medusa/clients/torrent/rtorrent_client.py", line 50, in _get_auth
    self.auth = RTorrent(self.host, self.username, self.password, True, tp_kwargs=tp_kwargs)
  File "/opt/medusa/lib/rtorrent/__init__.py", line 83, in __init__
    self._verify_conn()
  File "/opt/medusa/lib/rtorrent/__init__.py", line 122, in _verify_conn
    assert "system.client_version" in self._get_rpc_methods(
  File "/opt/medusa/lib/rtorrent/__init__.py", line 161, in _get_rpc_methods
    return(self._rpc_methods or self._update_rpc_methods())
  File "/opt/medusa/lib/rtorrent/__init__.py", line 150, in _update_rpc_methods
    self._rpc_methods = self._get_conn().system.listMethods()
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/opt/medusa/lib/rtorrent/lib/xmlrpc/requests_transport.py", line 150, in request
    response.headers)
ProtocolError: <ProtocolError for https://nl4727.dediseedbox.com//rutorrent/plugins/httprpc/action.php: 401 Client Error: Unauthorized for url: https://nl4727.dediseedbox.com//rutorrent/plugins/httprpc/action.php Traceback (most recent call last):
  File "/opt/medusa/lib/rtorrent/lib/xmlrpc/requests_transport.py", line 145, in request
    response.raise_for_status()
  File "/opt/medusa/lib/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 401 Client Error: Unauthorized for url: https://nl4727.dediseedbox.com//rutorrent/plugins/httprpc/action.php

**Comment by is33** [comment] 2017-09-06 19:29
Curious, only for my information because I do have a workaround. Would this be something that would be fixed? Again, no worries if it isn't, I know its free and open source, so fixing this would not be a major priority. I just want to know so I can set my instance to work.

**Comment by medariox** [comment] 2017-09-06 19:34
Of course, if it is a confirmed bug (seems like it) it will be fixed ASAP. Just keep in mind that all devs are volunteers and right now most, if not all, of us are still on vacation.

**Comment by is33** [comment] 2017-09-06 19:42
Understood, Just wanted to check in :)

**Comment by medariox** [comment] 2017-09-30 13:48
@is33 
Sorry for the extremely late reply.
I successfully tested this setting on my config and it works just fine here.

This is how my config looks like:
![image](https://snapr.pw/i/159f8b3606.png)

You have Basic Authentication enabled, right?

**Comment by is33** [comment] 2017-09-30 16:13
Dont worry about it. I know you guys are super busy :)
yes i did. and did double check everything. I provided logs earlier and its
(medusa) adding another '/'

On Sep 30, 2017 9:48 AM, "Dario" <notifications@github.com> wrote:

@is33 <https://github.com/is33>
Sorry for the extremely late reply.
I successfully tested this setting on my config and it works just fine here.

This is how my config looks like:
[image: image]
<https://camo.githubusercontent.com/f05dbeec61c8158e13bbff87d814d8c9d5ea6fec/68747470733a2f2f736e6170722e70772f692f313539663862333630362e706e67>

You have Basic Authentication enabled, right?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/pymedusa/Medusa/issues/3084#issuecomment-333309742>,
or mute
the thread

**Comment by medariox** [comment] 2017-09-30 17:39
Turns out that's not the issue, it just appears like that in the logs, but the request is actually done without the double slash. Are you sure that you are using the correct credentials (try to login with them within the browser)? Is the auth method really "Basic" or "Digest" (in your couchpotato screenshot you are using "Digest")? Can you please post a screenshot of your settings like I did above?

**Comment by medariox** [comment] 2017-09-30 21:00
I pushed the fix, it should be merged soon and will be available with the next release: https://github.com/pymedusa/Medusa/pull/3141

Thanks again for the bug report!

**Comment by is33** [comment] 2017-09-30 21:18
I will try in a minute i have been away from my computer all day till now

**Comment by is33** [comment] 2017-09-30 21:24
Mr. Medariox, Just posting this for sake of accuracy and documentation. I see you have found the issue so no worries :) thank you again for all of your help. Lemme know if I can be of further assistance to your project in any way :)
![image](https://user-images.githubusercontent.com/1373128/31049587-28cf9430-a604-11e7-8cd6-07256806c207.png)

**Comment by medariox** [comment] 2017-09-30 21:40
@is33 
If the double slashes were causing your issue, it should definitely be fixed now. It would be great to know if the issues is solved for you.

**Comment by is33** [comment] 2017-09-30 22:40
Hey,

Trying to pull the update. Not coming up on my end yet.

**Comment by is33** [comment] 2017-09-30 22:54
Just an update,

2017-09-30 18:53:08 WARNING  SNATCHQUEUE-MANUALSNATCH-108611 :: [c1a3b91] rTorrent: Unable to send Torrent
2017-09-30 18:53:08 WARNING  SNATCHQUEUE-MANUALSNATCH-108611 :: [c1a3b91] Error while sending torrent: <Fault -506: "Method 'load' not defined">
2017-09-30 18:53:07 DEBUG    SNATCHQUEUE-MANUALSNATCH-108611 :: [c1a3b91] Calling rTorrent Client

I am working on this to see if maybe its an error on my end/ providers end.

**Comment by is33** [comment] 2017-09-30 23:00
Yes, so I can authenticate, but I am getting a red 'x' when I try and add a torrent. I will get back to this in a little bit. I need to do stuff around the house, sorry

**Comment by medariox** [comment] 2017-10-01 18:00
No worries, whenever you have time.

**Comment by is33** [comment] 2017-10-02 04:30
okay so running it again with debug returns the following error in the logs:

2017-10-02 00:26:54 WARNING  SNATCHQUEUE-MANUALSNATCH-108611 ::
[c1a3b91] Error while sending torrent: <Fault -506: "Method 'load' not
defined">
2017-10-02 00:26:52 DEBUG    SNATCHQUEUE-MANUALSNATCH-108611 ::
[c1a3b91] Calling rTorrent Client
2017-10-02 00:26:52 INFO     SNATCHQUEUE-MANUALSNATCH-108611 ::
[c1a3b91] Downloading

**Comment by medariox** [comment] 2017-10-02 11:51
That sounds like an issue with your rTorrent setup. It doesn't have the necessary RPC method. Are you sure RPC is active and working? Maybe your provider is using a very old rTorrent version? There really isn't much that can be done from our end at this point.

**Comment by is33** [comment] 2017-10-02 15:13
no worries at all, i will check with my seedbox company to see what the
issue seems to be. thanks again for you help!

**Closed** 2017-10-25 13:25 UTC
Labels: Fixed
