### ISSUE TITLE
Global Ignore words not working anymore

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#6344] opened 2019-03-14 04:11 UTC
**Describe the bug**
After the upgrade to 0.30 my global ignore words are not being picked up anymore.

**Expected behavior**
With the new addition of filtering ignore words per show basis I would still expect that by default all Global Ignore words would still be applied

**Screenshots**
![image](https://user-images.githubusercontent.com/4103090/54330768-037f1c00-45e5-11e9-84e7-0bb1ee82e5e5.png)

![image](https://user-images.githubusercontent.com/4103090/54330795-21e51780-45e5-11e9-84d3-37b2e4e9b2db.png)

I have Strife as Global Ignore Word but shows up as valid downloads
![image](https://user-images.githubusercontent.com/4103090/54330841-4fca5c00-45e5-11e9-9243-0b3bbdf1016f.png)

**Medusa (please complete the following information):**

Medusa Info: | Branch:                 master                  Commit:                 94fae847b6e7e443d74c59cb11bdbd37c464b363                  Version:                 0.3.0                  Database:                 44.12
-- | --
Python Version: | 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
SSL Version: | OpenSSL 1.0.2o  27 Mar 2018
OS: | Windows-10-10.0.17763
Locale: | nl_NL.cp1252

**Comment by p0psicles** [comment] 2019-03-14 05:48
You sure it's ignoring the global ignored words in backlog / daily search? Or it's a manual search visualize thing?

**Comment by scott451** [comment] 2019-03-14 10:46
hello. 

i am having a similar issue. in my install it looks like the global ignore words are used for ignore words and required words as well. though adding exceptions works correctly on screen.

preferred words display correctly but are not taken into account in manual search. neither required nor ignored works seem to be taken into account in manual search.

i will keep an eye on log for examples from automatic searches. thanks.

- scott

**Comment by medariox** [comment] 2019-03-14 11:24
Manual search **never** takes into account any restriction, that's the whole point of the manual search: to give you the full overview of what's actually available. It only highlights the ignored/preferred releases with different colors and that may be broken. That doesn't mean that the ignored/preferred words are broken on a normal/backlog search. That's why we need debug logs of a non-manual search, to actually verify this bug and eventually take care of it.

**Comment by scott451** [comment] 2019-03-14 12:12
sorry i wasn't clear. the highlighting is no longer present in the visualisation of manual searches.

**Comment by Rouzax** [comment] 2019-03-14 12:20
It not showing my ignore words and it is not marking the entries as red in the search result list, which was previously the case.

**Comment by rafi-d** [comment] 2019-03-15 21:08
Since this issue seems confirmed, is there a hot fix planed for it to v0.30?

**Comment by medariox** [comment] 2019-03-15 21:23
Since it is an issue that doesn't affect functionality, it probably won't make it into the first hotfix release.

**Comment by rafi-d** [comment] 2019-03-16 08:10
> 
> 
> You sure it's ignoring the global ignored words in backlog / daily search? Or it's a manual search visualize thing?

I've checked, and it seems NOT to ignore the global "Ignored words" in daily search.
Still, UI is related to functionality too, just a bit ... :)

**Comment by p0psicles** [comment] 2019-03-16 11:22
For now the api returns it as one list. But maybe for future sure

**Comment by rafi-d** [comment] 2019-03-16 11:51
> 
> For now the api returns it as one list. But maybe for future sure

Maybe you can simply  use (for example)  series.release_ignore_words AND app.IGNORE_WORDS separately, one after the other? I am using this to priorities local over global for 'key words' I am using with %keyword=value format.

**Comment by Rouzax** [comment] 2019-05-11 16:02
There has been a release in the mean time but this was not picked up.

**Comment by p0psicles** [comment] 2019-05-13 18:51
will be implemented with #6315

**Comment by rafi-d** [comment] 2019-05-13 19:05
But when?... :)

**Comment by p0psicles** [comment] 2019-05-13 19:53
When its merged :)

**Closed** 2019-11-27 19:23 UTC
Labels: Bug, Frontend

**Comment by Rouzax** [comment] 2020-02-02 11:47
@p0psicles 
This was fixed with a recent release but it seems to be broken again, is that correct.
![image](https://user-images.githubusercontent.com/4103090/73607661-43fad600-45b9-11ea-8bd0-7b1a61ed2938.png)

**Comment by p0psicles** [comment] 2020-02-02 15:37
Afaik we haven't changed anything in that area

**Comment by rafi-d** [comment] 2020-02-02 15:45
> 
> 
> There has been a release in the mean time but this was not picked up.

He is right, it seems not to work also in 0.3.10 ... :(
![image](https://user-images.githubusercontent.com/2458280/73610778-c4cec780-45e3-11ea-9b76-861e5f9f94ad.png)

**Comment by Rouzax** [comment] 2020-02-02 16:16
> > There has been a release in the mean time but this was not picked up.
> 
> He is right, it seems not to work also in 0.3.10 , I guess a regression has crawled in ... :(
> ![image](https://user-images.githubusercontent.com/2458280/73610778-c4cec780-45e3-11ea-9b76-861e5f9f94ad.png)
> 
> Not sure if it is GUI related only or not, I don't see this effecting the downloads...

On a side note, I see you have things like min and max sizes, is that something that is already supported?

**Comment by rafi-d** [comment] 2020-02-02 16:18
> 
> 
> > > There has been a release in the mean time but this was not picked up.
> > 
> > 
> > He is right, it seems not to work also in 0.3.10 , I guess a regression has crawled in ... :(
> > ![image](https://user-images.githubusercontent.com/2458280/73610778-c4cec780-45e3-11ea-9b76-861e5f9f94ad.png)
> > Not sure if it is GUI related only or not, I don't see this effecting the downloads...
> 
> On a side note, I see you have things like min and max sizes, is that something that is already supported?

Yes, fully supported by my own local modded version.. ;p

**Comment by Rouzax** [comment] 2020-02-03 08:00
They probably are looking to integrate it more into the GUI.

**Comment by rafi-d** [comment] 2020-02-03 11:44
> 
> 
> They probably are looking to integrate it more into the GUI.

That's probably one consideration. 
Another is that it not "general"/flexible enough in their view, since my "concept" (due to lack of GUI) is to be as automatic as possible, so, taking the factors of episode run-time, resolution and compression type automatically to auto-tune/normalize  the desired size limit to be snatched... 

In my experience, this is working pretty good so far :)
