### ISSUE TITLE
Add Recomended show IMDB Popular error

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#4228] opened 2018-05-21 08:51 UTC
Medusa Info: | Branch: master                     Commit: 212cd1c8a350f2d5ca40f172ed5a227d9a5cb80f                     Version: v0.2.3                     Database: 44.9
-- | --
Python Version: | 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
SSL Version: | OpenSSL 1.0.2k  26 Jan 2017
OS: | Windows-10-10.0.14393
Locale: | nl_NL.cp1252

![image](https://user-images.githubusercontent.com/4103090/40298816-9eac8b1c-5ce4-11e8-99ad-12b7fa8a33d0.png)

```
2018-05-21 10:48:00 WARNING  Thread_24 :: [212cd1c] Could not parse show tt6845390 with error: u'year'
```

**Comment by p0psicles** [comment] 2018-05-21 10:08
I cant reproduce this. Its working fine for me

**Comment by Rouzax** [comment] 2018-05-21 11:03
This was the only line in the debug log. The server time is synchronized with an external time source

**Comment by sharkykh** [comment] 2018-05-21 11:14
http://www.imdb.com/title/tt6845390/ has no year.
I think the exception is `KeyError: u'year'`.

**Comment by medariox** [comment] 2018-05-23 13:19
Fixed with https://github.com/pymedusa/Medusa/pull/4239

**Closed by medariox** 2018-05-23 13:19 UTC
Labels: Fixed
