### ISSUE TITLE
Timeout on Startup - Raspbian Stretch

### ISSUE THREAD

**Issue by eximo84** [pymedusa/Medusa#3847] opened 2018-03-10 10:27 UTC
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** Latest pulled from GitHub
**OS:** Raspbian Stretch Nov 2017
**What you did:**  Installed from guide https://github.com/pymedusa/Medusa/wiki/Medusa-installation-Ubuntu-15
**What happened:** Medusa doesnt start via Systemd or when invoked via python /opt/medusa/SickBeard.py
**What you expected:** The app to start
**Logs:** -
```
Mar 10 09:25:02 torrentpi CRON[853]: pam_unix(cron:session): session closed for user pi
Mar 10 09:25:05 torrentpi sudo[865]:       pi : TTY=pts/0 ; PWD=/opt ; USER=root ; COMMAND=/bin/cp -v /opt/medusa/runscripts/init.systemd /etMar 10 09:25:05 torrentpi sudo[865]: pam_unix(sudo:session): session opened for user root by pi(uid=0)
Mar 10 09:25:05 torrentpi sudo[865]: pam_unix(sudo:session): session closed for user root
Mar 10 09:25:12 torrentpi sudo[873]:       pi : TTY=pts/0 ; PWD=/opt ; USER=root ; COMMAND=/bin/chown root:root /etc/systemd/system/medusa.seMar 10 09:25:12 torrentpi sudo[873]: pam_unix(sudo:session): session opened for user root by pi(uid=0)
Mar 10 09:25:13 torrentpi sudo[873]: pam_unix(sudo:session): session closed for user root
Mar 10 09:25:17 torrentpi sudo[881]:       pi : TTY=pts/0 ; PWD=/opt ; USER=root ; COMMAND=/bin/chmod 644 /etc/systemd/system/medusa.service Mar 10 09:25:17 torrentpi sudo[881]: pam_unix(sudo:session): session opened for user root by pi(uid=0)
Mar 10 09:25:18 torrentpi sudo[881]: pam_unix(sudo:session): session closed for user root
Mar 10 09:25:22 torrentpi sudo[889]:       pi : TTY=pts/0 ; PWD=/opt ; USER=root ; COMMAND=/bin/systemctl enable medusa
Mar 10 09:25:22 torrentpi sudo[889]: pam_unix(sudo:session): session opened for user root by pi(uid=0)
Mar 10 09:25:22 torrentpi systemd[1]: Reloading.
Mar 10 09:25:24 torrentpi systemd[1]: apt-daily.timer: Adding 4h 61.212ms random time.
Mar 10 09:25:24 torrentpi systemd[1]: apt-daily-upgrade.timer: Adding 20min 18.434222s random time.
Mar 10 09:25:25 torrentpi sudo[889]: pam_unix(sudo:session): session closed for user root
Mar 10 09:25:30 torrentpi sudo[912]:       pi : TTY=pts/0 ; PWD=/opt ; USER=root ; COMMAND=/bin/systemctl start medusa
Mar 10 09:25:30 torrentpi sudo[912]: pam_unix(sudo:session): session opened for user root by pi(uid=0)
Mar 10 09:25:30 torrentpi systemd[1]: Starting Medusa Daemon...
-- Subject: Unit medusa.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit medusa.service has begun starting up.
Mar 10 09:27:00 torrentpi systemd[1]: medusa.service: Start operation timed out. Terminating.
Mar 10 09:27:00 torrentpi systemd[1]: Failed to start Medusa Daemon.
-- Subject: Unit medusa.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit medusa.service has failed.
--
-- The result is failed.
Mar 10 09:27:00 torrentpi systemd[1]: medusa.service: Unit entered failed state.
Mar 10 09:27:00 torrentpi systemd[1]: medusa.service: Failed with result 'timeout'.
Mar 10 09:27:00 torrentpi sudo[912]: pam_unix(sudo:session): session closed for user root
```

**Comment by p0psicles** [comment] 2018-03-10 11:05
Do you also have some medusa application logs?

**Comment by p0psicles** [comment] 2018-03-10 11:05
Can you manually start Medusa using the correct user?

**Comment by eximo84** [comment] 2018-03-10 19:15
I cant see any log files, in /opt/medusa.  Where are they normally located?

Sorry - im a bit of a linux noob, how would i run the app as the medusa user?

**Comment by medariox** [comment] 2018-03-10 19:22
Try to start with `/opt/medusa/start.py` from console and post the logs please.

**Comment by eximo84** [comment] 2018-03-10 19:29
Running as Pi user i get Data directory must be writeable: /opt/medusa

**Comment by p0psicles** [comment] 2018-03-10 19:30
If you installed in /opt/medusa probably in /opt/medusa/Logs

**Comment by medariox** [comment] 2018-03-10 19:31
There you go, that's the issue. Give Pi permissions to read/write to that folder.

**Comment by eximo84** [comment] 2018-03-10 19:46
So if i chown the medusa folder i can start the application with the pi user.  Problem is systemd doesnt start the daemon.  Same timeout issue, nothing is logged in the Logs folder because the daemon doesnt start.

**Comment by abeloin** [comment] 2018-03-11 14:30
Did you modified the user in the service file(`/etc/systemd/system/medusa.service`)? 

If not, can you check if the user `medusa` has access to `/opt/medusa`? If not, try resseting the permissions with `sudo chown medusa:medusa -R /opt/medusa`

**Comment by eximo84** [comment] 2018-03-12 08:13
Yes i changed the user Pi in the service config then set the owner of /opt/medusa to Pi - no change.

Changed it back to medusa and reset permissions.  I have also changed the folder / file permissions to 777 and still it doesnt start via Systemd.  If i run the command manually as Pi it runs...

**Comment by abeloin** [comment] 2018-03-12 13:51
OK, did you modified anything else in `/etc/systemd/system/medusa.service`?

More specifically, any change on those 3 lines?
```
Type=forking
GuessMainPID=no
ExecStart=/usr/bin/python2.7 /opt/medusa/start.py -q --daemon --nolaunch --datadir=/opt/medusa
```

**Comment by eximo84** [comment] 2018-03-12 14:23
Yes sorry. I modified the execstart line removing /usr/bin/python2.7

If I run that line from console without /usr/bin/python2.7 it starts up.

**Comment by abeloin** [comment] 2018-03-12 18:23
If I understand correctly, the execstart line in your medusa.service is:
`ExecStart=/opt/medusa/start.py -q --daemon --nolaunch --datadir=/opt/medusa`

I think the issue is that you removed the python executable in the ExecStart.

If so can you try adding back the python part:
1. Stop medusa: `systemctl stop medusa`
2. Add the python exec part: `ExecStart=/usr/bin/python2.7 /opt/medusa/start.py -q --daemon --nolaunch --datadir=/opt/medusa`
3. Reload systemd: `systemctl daemon-reload`
4. Start medusa: `systemctl start medusa`

If it still doesn't work, what do you get if you try this command `which python2.7`

**Comment by p0psicles** [comment] 2018-03-12 18:41
This is the systemd script i'm using:
```

[Unit]
Description=Medusa Daemon

[Service]
User=medusa
Group=medusa

Type=forking
GuessMainPID=no
ExecStart=/opt/medusa/start.py -q --daemon --nolaunch --datadir=/opt/medusa-data

[Install]
WantedBy=multi-user.target
```

I have the application data (cloned from git) in /opt/medusa and the data separate in /opt/medusa-data.
Both have the medusa:medusa as owner.

**Comment by abeloin** [comment] 2018-03-12 18:56
@eximo84 
Could you try without forking:
```
Type=simple
ExecStart=/opt/medusa/start.py -q --nolaunch --datadir=/opt/medusa
```

**Comment by eximo84** [comment] 2018-03-12 22:19
@abeloin - thanks this seems to have fixed my issue.  Using the same as you have posted.  i havent tried it with putting back in /usr/bin/python2.7 though.

**Comment by abeloin** [comment] 2018-03-12 22:34
It's ok you don't need to. For some reason, systemd is unable to find the PID of the forked process.

**Comment by medariox** [comment] 2018-03-16 22:29
Closing as fixed.

**Closed by medariox** 2018-03-16 22:29 UTC
