### ISSUE TITLE
[APP SUBMITTED]: error: need 'c' or 'n' flag to open new db

### ISSUE THREAD

**Issue by tomsema** [pymedusa/Medusa#4009] opened 2018-04-13 08:17 UTC
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.4.0-119-generic-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**Link to Log**: https://gist.github.com/e14066318bbb5ec4eb0e7f58fa88b69c
### ERROR
<pre>
2018-04-13 11:03:10 ERROR    Thread-29 :: [d6eb72d] Exception generated: need 'c' or 'n' flag to open new db
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/server/web/core/base.py#L283">medusa/server/web/core/base.py</a>", line 283, in async_call
    result = function(**kwargs)
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/server/web/home/handler.py#L2287">medusa/server/web/home/handler.py</a>", line 2287, in manual_search_subtitles
    found_subtitles = subtitles.list_subtitles(tv_episode=ep_obj, video_path=video_path)
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/subtitles.py#L331">medusa/subtitles.py</a>", line 331, in list_subtitles
    cache.set(subtitle_key.format(id=subtitle.id).encode('utf-8'), subtitle)
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/ext/dogpile/cache/region.py#L984">ext/dogpile/cache/region.py</a>", line 984, in set
    self.backend.set(key, self._value(value))
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/ext/dogpile/cache/backends/file.py#L237">ext/dogpile/cache/backends/file.py</a>", line 237, in set
    with self._dbm_file(True) as dbm:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/ext/dogpile/cache/backends/file.py#L215">ext/dogpile/cache/backends/file.py</a>", line 215, in _dbm_file
    "w" if write else "r")
  File "/usr/lib/python2.7/anydbm.py", line 79, in open
    raise error, "need 'c' or 'n' flag to open new db"
error: need 'c' or 'n' flag to open new db
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sharkykh** [comment] 2018-04-13 11:09
I believe these errors are caused by the "erase subtitle cache" option (#2051).
@fernandog 
The cache is configured before it is removed:
https://github.com/pymedusa/Medusa/blob/e43eefb2dbaaa0ae62cc8fb04963dbdbfd781aa9/medusa/__main__.py#L508-L510
Maybe we need to reconfigure the cache after it?
https://github.com/pymedusa/Medusa/blob/e43eefb2dbaaa0ae62cc8fb04963dbdbfd781aa9/medusa/__main__.py#L1085-L1095

**Comment by fernandog** [comment] 2018-04-13 16:02
Yes, that seems to be the issue

**Comment by fernandog** [comment] 2018-04-13 16:49
@sharkykh this commit fixed the issue. If you have another idea let me know:

```
2018-04-13 13:47:43 INFO     MAIN :: [dcf3ad3] Removing subtitles cache file: /home/osmc/Medusa/cache/subliminal.dbm
2018-04-13 13:47:43 INFO     MAIN :: [dcf3ad3] Removing subtitles cache file: /home/osmc/Medusa/cache/application.dbm
```

https://github.com/fernandog/Medusa/commit/dcf3ad33fc91d3455fcf6562ceb8c8b86683ca40

**Comment by medariox** [comment] 2018-04-14 15:03
Thanks for the bug report. Fixed with: https://github.com/pymedusa/Medusa/pull/4011

**Closed by medariox** 2018-04-14 15:03 UTC
