### ISSUE TITLE
Jackett use?

### ISSUE THREAD

**Issue by bobbysteel** [pymedusa/Medusa#3213] opened 2017-11-01 22:22 UTC
Is anyone else using Jackett? I'm seeing log hits for Jackett searches but nothing else showing number of items returned. Manual search in jackett returns results but I'm not seeing any when manual searching in Medusa. I've also checked the categories which seem to be set ok

**Comment by bobbysteel** [comment] 2017-11-01 22:24
Debug mode is not more verbose unfortunately either

**Comment by medariox** [comment] 2017-11-01 23:09
I use it... are you sure that you have it set up correctly? It's returning results for manual and daily searches for me. Here is how it should look like:
![img](https://snapr.pw/i/7956d2e037.png)

**Comment by bobbysteel** [comment] 2017-11-01 23:11
Yep that's how I have it configured as well. Using TPB as an example of a
public site w/ lots of results, nothing comes up in manual search (despite
also having it checked as a manual results option under Provider options.
I've never used it before but in the Jackett UI it pulls results fine.
Medusa logs show the search completes normally but even in debug doesn't
return anything more helpful unfortunately (even # of results or URL used
would be helpful).

**Comment by medariox** [comment] 2017-11-01 23:17
Try with all 3 options enabled, that's how I have it configured:
![img](https://snapr.pw/i/288e84fe25.png)

**Comment by bobbysteel** [comment] 2017-11-01 23:39
Hm. So I wasn't seeing the full debug logs earlier (my stupidity).
Looking at a manual search using TPB as an example, the logs show:

```
2017-11-01 23:31:26 INFO     SEARCHQUEUE-MANUAL-311954 :: [JACKETT RUTRACKER] :: [b16e0e5] Performing episode search for Riverdale
2017-11-01 23:31:26 INFO     SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] Performing season pack search for Riverdale
2017-11-01 23:31:26 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] Fallback season pack search initiate
2017-11-01 23:31:25 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] User-Agent: Medusa/0.0.1 (Linux; 4.9.49-moby; 27a3d95e-bf5c-11e7-bdcb-0242ac110004)
2017-11-01 23:31:25 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] GET URL: **********api?apikey=**********&maxage=2700&cat=5030%2C5040&q=Riverdale+S02E02&limit=100&t=search&offset=0 [Status: 200]
2017-11-01 23:31:22 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] Search show using search string: Riverdale S02E02
2017-11-01 23:31:22 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] User-Agent: Medusa/0.0.1 (Linux; 4.9.49-moby; 27a3d95e-bf5c-11e7-bdcb-0242ac110004)
2017-11-01 23:31:22 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] GET URL: **********api?apikey=**********&maxage=2700&cat=5030%2C5040&q=Riverdale+US+S02E02&limit=100&t=search&offset=0 [Status: 200]
2017-11-01 23:31:19 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] Search show using search string: Riverdale US S02E02
2017-11-01 23:31:19 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] No results returned from provider. Check chosen Newznab search categories in provider settings and/or usenet retention
2017-11-01 23:31:19 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] User-Agent: Medusa/0.0.1 (Linux; 4.9.49-moby; 27a3d95e-bf5c-11e7-bdcb-0242ac110004)
2017-11-01 23:31:19 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] GET URL: **********api?apikey=**********&maxage=2700&cat=5030%2C5040&q=Riverdale+%28USA%29+S02E02&limit=100&t=search&offset=0 [Status: 200]
2017-11-01 23:31:16 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] Search show using search string: Riverdale (USA) S02E02
2017-11-01 23:31:16 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] Search mode: Episode
2017-11-01 23:31:15 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] User-Agent: Medusa/0.0.1 (Linux; 4.9.49-moby; 27a3d95e-bf5c-11e7-bdcb-0242ac110004)
2017-11-01 23:31:15 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] GET URL: **********api?apikey=**********&maxage=2700&cat=5030%2C5040&q=Riverdale+S02E02&limit=100&t=search&offset=0 [Status: 200]
2017-11-01 23:31:12 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] Search show using search string: Riverdale S02E02
2017-11-01 23:31:12 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] User-Agent: Medusa/0.0.1 (Linux; 4.9.49-moby; 27a3d95e-bf5c-11e7-bdcb-0242ac110004)
2017-11-01 23:31:12 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] GET URL: **********api?apikey=**********&maxage=2700&cat=5030%2C5040&q=Riverdale+US+S02E02&limit=100&t=search&offset=0 [Status: 200]
2017-11-01 23:31:09 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] Search show using search string: Riverdale US S02E02
2017-11-01 23:31:09 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] No results returned from provider. Check chosen Newznab search categories in provider settings and/or usenet retention
2017-11-01 23:31:09 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] User-Agent: Medusa/0.0.1 (Linux; 4.9.49-moby; 27a3d95e-bf5c-11e7-bdcb-0242ac110004)
2017-11-01 23:31:09 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] GET URL: **********api?apikey=**********&maxage=2700&cat=5030%2C5040&q=Riverdale+%28USA%29+S02E02&limit=100&t=search&offset=0 [Status: 200]
2017-11-01 23:31:06 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] Search show using search string: Riverdale (USA) S02E02
2017-11-01 23:31:06 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] Search mode: Episode
2017-11-01 23:31:06 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] User-Agent: Medusa/0.0.1 (Linux; 4.9.49-moby; 27a3d95e-bf5c-11e7-bdcb-0242ac110004)
2017-11-01 23:31:06 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] GET URL: **********api?apikey=**********&t=caps [Status: 200]
2017-11-01 23:31:06 INFO     SEARCHQUEUE-MANUAL-311954 :: [JACKETT TPB] :: [b16e0e5] Performing episode search for Riverdale
2017-11-01 23:31:06 INFO     SEARCHQUEUE-MANUAL-311954 :: [USENET-CRAWLER] :: [b16e0e5] Performing season pack search for Riverdale
2017-11-01 23:31:06 DEBUG    SEARCHQUEUE-MANUAL-311954 :: [USENET-CRAWLER] :: [b16e0e5] Fallback season pack search initiate
```
Now manually building the URL myself as suggested by Jackett
```
http://myserver.com:9117/api/v2.0/indexers/thepiratebay/results/torznab/?apikey=xxxxxxxxx&maxage=2700&cat=5030%2C5040&q=Riverdale+S02E02&limit=100&t=search&offset=0
```
Returns valid results. 

So it seems that from the logs, Medusa is requesting a bad URL? The full URL should end in torznab/ but the logs seem to end at ...api?

**Comment by bobbysteel** [comment] 2017-11-01 23:43
Also it doesn't seem the newznab category numbers are sticking anywhere. I can choose them, but they aren't showing up anywhere saved in the config.ini (although this is not the cause as in the above case the default works fine)

**Comment by bobbysteel** [comment] 2017-11-01 23:50
Hm, trying the v1 API format still shows results from browser but no results returned in Medusa
```
http://myserver.com:9117/torznab/thepiratebay/api?apikey=xx&maxage=2700&cat=5030%2C5040&q=Empire+%282015%29+S04E01&limit=100&t=search&offset=0
```
Logs don't say "no results returned" but no results appear on manual search returned results.

**Comment by medariox** [comment] 2017-11-02 11:10
This will be fixed with: https://github.com/pymedusa/Medusa/pull/3214

The issue is with providers that provide magnets instead of direct download URLs for torrents (e.g. TPB), that explains why I couldn't reproduce the issue with 1337x.

Please open a new issue regarding the categories not sticking if you feel like it: one issue for one problem.

Thanks for the bug report!

**Comment by bobbysteel** [comment] 2017-11-02 11:31
Awesome thanks!

**Closed** 2017-11-02 11:41 UTC
Labels: Fixed
