### ISSUE TITLE
Problem after current update Master

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#7462] opened 2019-12-08 23:07 UTC
**Describe the bug**
After the current update to master when clicking on forced search for a show it redirects to a success page

**To Reproduce**
1. Go to '...' Schedule page
2. Click on 'a missed show forced search.' 
3. it redirects to a results success page.
![sucess](https://user-images.githubusercontent.com/7034303/70398018-20fedc00-19e5-11ea-9788-d0a5ed7bf24d.png)

Branch: masterCommit: 8b7f433d4dce89058a8b9b62cc9bcd7a162a3344
Version: 0.3.8Database: 44.14
Python Version: | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.0j 20 Nov 2018
OS: | Windows-10-10.0.18362-SP0
Locale: | en_US.cp1252

*Debug logs 
https://gist.github.com/ripper1967/233acc0341139a0c25577a8e97e26b2e

**Comment by jandreaucodes** [comment] 2019-12-09 12:50
I can confirm I'm seeing this too.

It looks like the Ajax search isn't working properly and is redirecting to the JSON results, instead of handling it properly.

**Comment by sharkykh** [comment] 2019-12-20 18:55
Fixed on develop with #7512

**Closed by sharkykh** 2019-12-20 18:55 UTC
Labels: Bug, Confirmed, Frontend
