### ISSUE TITLE
[APP SUBMITTED]: OSError: [Errno 2] No such file or directory: '/home/gerlin/Downloads/sabnzbdplus/complete/Arrow.S05E04.720p.BluRay.DD5.1.x264-SbR/zFmKNE1X1ZDp0enupjuAxxcY7kE.mkv'

### ISSUE THREAD

**Issue by gnolascord** [pymedusa/Medusa#5147] opened 2018-09-08 03:34 UTC
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.4.0-134-generic-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@db3d9d767bbf3fe7c365df20d92099b0cbbd91b4
**Link to Log**: **No Log available**
### ERROR
<pre>
2018-09-07 22:11:48 ERROR    Thread_3 :: [db3d9d7] Unable to move file /home/gerlin/Downloads/sabnzbdplus/complete/Arrow.S05E04.720p.BluRay.DD5.1.x264-SbR/zFmKNE1X1ZDp0enupjuAxxcY7kE.mkv to /media/Plex/tv/Arrow/Season 05/Arrow - S05E04 - Penance.mkv: OSError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/db3d9d767bbf3fe7c365df20d92099b0cbbd91b4/medusa/post_processor.py#L472">medusa/post_processor.py</a>", line 472, in move
    helpers.move_file(cur_file_path, new_file_path)
  File "/opt/medusa/<a href="../blob/db3d9d767bbf3fe7c365df20d92099b0cbbd91b4/medusa/helpers/__init__.py#L316">medusa/helpers/__init__.py</a>", line 316, in move_file
    os.unlink(src_file)
  File "/opt/medusa/<a href="../blob/db3d9d767bbf3fe7c365df20d92099b0cbbd91b4/medusa/init/filesystem.py#L113">medusa/init/filesystem.py</a>", line 113, in patched_output
    return handle_output(f(*args, **kwargs))
OSError: [Errno 2] No such file or directory: '/home/gerlin/Downloads/sabnzbdplus/complete/Arrow.S05E04.720p.BluRay.DD5.1.x264-SbR/zFmKNE1X1ZDp0enupjuAxxcY7kE.mkv'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Rouzax** [comment] 2018-09-08 09:30
This is the same issue as:
https://github.com/pymedusa/Medusa/issues/5146
https://github.com/pymedusa/Medusa/issues/5147
https://github.com/pymedusa/Medusa/issues/5148
https://github.com/pymedusa/Medusa/issues/5149
https://github.com/pymedusa/Medusa/issues/5150
https://github.com/pymedusa/Medusa/issues/5151
https://github.com/pymedusa/Medusa/issues/5152
https://github.com/pymedusa/Medusa/issues/5153

Most likely this is an Access permissions issue.

**Comment by OmgImAlexis** [comment] 2018-09-08 10:47
Duplicate of https://github.com/pymedusa/Medusa/issues/5146

**Closed by OmgImAlexis** 2018-09-08 10:47 UTC
Labels: Duplicate
