### ISSUE TITLE
[0.30->0.34 regression]Wrong sizes in Show's manual search pages (GB<->MB)

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#7077] opened 2019-08-21 04:52 UTC
Hi,
Following my update to 0.34, one more glitch: seems  like show manual search lists  mix-up between MB and GB in torrent file sizes. It seems all over,  but more visible in season search, or 2-digits GBs ...
Maybe Torrentz2 related?

Attaching example.
![1](https://user-images.githubusercontent.com/2458280/63403544-5ce74480-c3e8-11e9-80f3-d420e7fd63d6.png)

Medusa Info: | Branch:                 master                  Commit:                 74c3f124fb599ad923e23f46fc320778b8b4217c                  Version:                 0.3.4                  Database:                 44.14
-- | --
Python Version: | 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]
SSL Version: | OpenSSL 1.0.2j  26 Sep 2016
OS: | Windows-10-10.0.17763
Locale: | en_US.cp1255
  |  
  |  
User: | RAFI-PC$
Program Folder: | D:\Program Files\Medusa\Medusa
Config File: | D:\Program Files\Medusa\Data\config.ini
Database File: | D:\Program Files\Medusa\Data\main.db
Cache Folder: | D:\Program Files\Medusa\Data\cache
Log Folder: | D:\Program Files\Medusa\Data\Logs
Arguments: | --nolaunch --port=8081 --datadir=D:\Program Files\Medusa\Data

**Comment by rafi-d** [comment] 2019-08-21 05:26
BTW, semi-related, we have discussed it before, but I have just integrated my implementation of  file size limiter (min/max) into core.py, derived from 2 dedicated ignored words, in case you are interested to offer it to others, until  more general quality profiling and GUI will be done in the future.

**Comment by medariox** [comment] 2019-08-21 10:04
This is always provider related and also most likely not a regression, considering the provider hasn't been touched for a long time.

**Comment by rafi-d** [comment] 2019-08-21 12:06
Ok, maybe not a regression...  I guess there is always the first time, and it is now... Can you fix it please?

**Comment by medariox** [comment] 2019-08-28 11:32
Fixed with https://github.com/pymedusa/Medusa/pull/7094

**Closed by medariox** 2019-08-28 11:32 UTC
Labels: Bug

**Comment by rafi-d** [comment] 2019-08-28 11:52
Still same issue:
![image](https://user-images.githubusercontent.com/2458280/63853470-74539e00-c9a3-11e9-87ba-8c0d81387977.png)

**Comment by medariox** [comment] 2019-08-28 12:11
You need to force the search. I tested it and it's working correctly.

**Comment by rafi-d** [comment] 2019-08-28 12:27
I did. Maybe they really have "MB" sometimes? 
Can you check the same shows/seasons?

![image](https://user-images.githubusercontent.com/2458280/63855550-56d50300-c9a8-11e9-83cd-b655d6376467.png)

**Comment by medariox** [comment] 2019-08-28 12:37
These are old results that aren't even available anymore. That's why they are not updated. You can verify this by checking the Updated column.

**Comment by rafi-d** [comment] 2019-08-28 13:10
So, how should I clear them?

**Comment by rafi-d** [comment] 2019-08-28 13:54
BTW, you are right, logs shows that all sizes are correct., so  maybe the bug is not getting rid of non-existence  old records/results?

2019-08-28 16:41:46 INFO	SEARCHQUEUE-MANUAL-290853 :: Zooqle :: [74c3f12] Performing season pack search for Fear the Walking Dead
2019-08-28 16:41:44 INFO	SEARCHQUEUE-MANUAL-290853 :: LimeTorrents :: [74c3f12] Performing season pack search for Fear the Walking Dead
2019-08-28 16:41:40 INFO	SEARCHQUEUE-MANUAL-290853 :: ThePirateBay :: [74c3f12] Performing season pack search for Fear the Walking Dead
2019-08-28 16:41:33 INFO	SEARCHQUEUE-MANUAL-290853 :: Rarbg :: [74c3f12] Performing season pack search for Fear the Walking Dead
2019-08-28 16:41:32 INFO	SEARCHQUEUE-MANUAL-290853 :: Torrentz2 :: [74c3f12] Tz2 torrent size: torrent_size- 51 GB size- 54760833024
2019-08-28 16:41:32 INFO	SEARCHQUEUE-MANUAL-290853 :: Torrentz2 :: [74c3f12] Tz2 torrent size: torrent_size- 5662 MB size- 5937037312
2019-08-28 16:41:32 INFO	SEARCHQUEUE-MANUAL-290853 :: Torrentz2 :: [74c3f12] Tz2 torrent size: torrent_size- 35 GB size- 37580963840
2019-08-28 16:41:32 INFO	SEARCHQUEUE-MANUAL-290853 :: Torrentz2 :: [74c3f12] Tz2 torrent size: torrent_size- 54 GB size- 57982058496
2019-08-28 16:41:32 INFO	SEARCHQUEUE-MANUAL-290853 :: Torrentz2 :: [74c3f12] Tz2 torrent size: torrent_size- 7662 MB size- 8034189312
2019-08-28 16:41:32 INFO	SEARCHQUEUE-MANUAL-290853 :: Torrentz2 :: [74c3f12] Tz2 torrent size: torrent_size- 15 GB size- 16106127360
2019-08-28 16:41:32 INFO	SEARCHQUEUE-MANUAL-290853 :: Torrentz2 :: [74c3f12] Tz2 torrent size: torrent_size- 521 MB size- 546308096
2019-08-28 16:41:32 INFO	SEARCHQUEUE-MANUAL-290853 :: Torrentz2 :: [74c3f12] Tz2 torrent size: torrent_size- 405 MB size- 424673280
2019-08-28 16:41:32 INFO	SEARCHQUEUE-MANUAL-290853 :: Torrentz2 :: [74c3f12] Tz2 torrent size: torrent_size- 550 MB size- 576716800
2019-08-28 16:41:32 INFO	SEARCHQUEUE-MANUAL-290853 :: Torrentz2 :: [74c3f12] Tz2 torrent size: torrent_size- 4284 MB size- 4492099584
2019-08-28 16:41:32 INFO	SEARCHQUEUE-MANUAL-290853 :: Torrentz2 :: [74c3f12] Tz2 torrent size: torrent_size- 2100 MB size- 2202009600
2019-08-28 16:41:32 INFO	SEARCHQUEUE-MANUAL-290853 :: Torrentz2 :: [74c3f12] Tz2 torrent size: torrent_size- 25 GB size- 26843545600
2019-08-28 16:41:32 INFO	SEARCHQUEUE-MANUAL-290853 :: Torrentz2 :: [74c3f12] Tz2 torrent size: torrent_size- 1909 MB size- 2001731584
2019-08-28 16:41:31 INFO	SEARCHQUEUE-MANUAL-290853 :: Torrentz2 :: [74c3f12] Performing season pack search for Fear the Walking Dead
2019-08-28 16:41:31 INFO	SEARCHQUEUE-MANUAL-290853 :: [74c3f12] Using manual search providers
2019-08-28 16:41:31 INFO	SEARCHQUEUE-MANUAL-290853 :: [74c3f12] Building internal name cache for Fear the Walking Dead
2019-08-28 16:41:31 INFO	SEARCHQUEUE-MANUAL-290853 :: [74c3f12] Finished processing 3145 scene exceptions.
2019-08-28 16:41:31 INFO	SEARCHQUEUE-MANUAL-290853 :: [74c3f12] Updating exception_cache and exception_season_cache
2019-08-28 16:41:31 INFO	SEARCHQUEUE-MANUAL-290853 :: [74c3f12] Beginning manual season pack search for: Fear the Walking Dead - S04E01 - What's Your Story
2019-08-28 16:40:48 WARNING	CHECKVERSION :: [74c3f12] git rev-list --left-right "@{upstream}"...HEAD returned : fatal: no upstream configured for branch 'master'
2019-08-28 16:40:48 WARNING	CHECKVERSION :: [74c3f12] git rev-parse --verify --quiet "@{upstream}" returned : fatal: no upstream configured for branch 'master'

**Comment by medariox** [comment] 2019-08-28 14:01
It's not a bug. You can enable cache trimming and the will be removed after the desired amount of days.
