### ISSUE TITLE
PPing a wrong episode and then deleting it causes it to be set as "ignored"

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#2426] opened 2017-03-18 00:37 UTC
For example I had an episode that was named S12E10 instead of being S12E01 so I manually moved the file over and rescanned files but since it was removed Medusa now thinks that's ignored. If I mark it as wanted that same download will happen, if I leave it Medusa won't snatch it.

We need a check if the episode it out right now when we do a rescan. If it's not and the file was set as "downloaded" we should change it to "unaired" instead of ignored.

**Comment by fernandog** [comment] 2017-03-21 17:03
I didn't understood this.... sorry

**Comment by labrys** [comment] 2017-03-21 23:46
@fernandog the problem isnt the default status, its that its an incorrectly named release (it says its a future episode).  Since medusa saw the file as having been there at one point, instead of restoring the future episode to "Unaired" its setting it to default status so if default status is "Wanted" it would repeatedly download the incorrect release.

@OmgImAlexis one fix would be to run a manual search for the future episode (S12E10) and snatch the incorrect release.  When it snatches, go back to the series page, and run a "retry download" and mark the snatch as failed.  This way it wont retry the release.  If there are multiple incorrect releases, rinse and repeat until all incorrect releases are marked as failed.  Finally set the status to wanted and it should snatch correctly when the future episode finally airs.

**Comment by fernandog** [comment] 2017-03-22 00:03
ok, in this case the best solution is the `failed` as @labrys said as there is nothing we can't do otherwise it may impact when user deletes episode after watching

**Comment by fernandog** [comment] 2017-03-23 00:17
@OmgImAlexis did you renamed the episode and make a mistake?  or file was wrong in the provider?

**Comment by OmgImAlexis** [comment] 2017-03-23 01:36
@labrys that would work as a work-around but this should be fixed. If the episodes before haven't been released then ideally it should be set as unaired again.

@fernandog what about people that don't use failed downloads? There's not really any solution for them.

The file downloaded from dognzbd and the title was correct but the file had a typo and was listed as `S12E10` instead of `S12E01` I've had this happen a handful of times over the last year and there isn't much that can be done on the provider side as they're just innocent typos that usually cause this.

Could we not have an option to mark it as unaired in the dropdown if there's no airdate?

**Comment by fernandog** [comment] 2017-03-23 01:43
@OmgImAlexis what about a user that snatched a release before airdate (leak), watched the episode and deleted it. Should make unaired again? We should think about all cases

What we could do is not allow PP a episode with status UNAIRED except user manuall PP with force enabled.

**Comment by labrys** [comment] 2017-03-23 01:59
@OmgImAlexis even without failed-download handling marking snatches as failed still works.  This is one of those situations where current handling is not ideal, but its such a one-off situation that imo the work-around is sufficient.  The advantage the work-around provides is when the episode actually airs, all the incorrectly labeled torrents should have been marked failed so you wont end up getting the wrong episode downloaded then.

**Comment by labrys** [comment] 2017-03-23 02:01
As for not allowing a show to PP when UNAIRED except when forced, early releases happen way more often then @OmgImAlexis's situation, so it would make it much less convenient for those situations.

**Comment by fernandog** [comment] 2017-03-23 02:07
Btw we cant support this actions:

"so I manually moved the file over and rescanned files"

**Closed** 2017-04-23 00:00 UTC
Labels: Bug, Priority: 3. Low, Question
