### ISSUE TITLE
[APP SUBMITTED]: OperationalError: attempt to write a readonly database

### ISSUE THREAD

**Issue by thyeestes** [pymedusa/Medusa#4752] opened 2018-07-25 13:12 UTC
### INFO
**Python Version**: `2.7.14 (default, May 28 2018, 15:25:50) [GCC 4.8.3 20140106 (prerelease)]`
**Operating System**: `Linux-3.10.102-armv7l-with-glibc2.4`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64
**Link to Log**: https://gist.github.com/90c9cf744552fff5d6739e04126ca349
### ERROR
<pre>
2018-07-25 15:06:28 ERROR    SHOWQUEUE-ADD :: [e7c4ff3] Error loading IMDb info: attempt to write a readonly database
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64/medusa/show_queue.py#L587">medusa/show_queue.py</a>", line 587, in run
    self.show.load_imdb_info()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64/medusa/tv/series.py#L1543">medusa/tv/series.py</a>", line 1543, in load_imdb_info
    imdb_info = imdb_api.get_title(self.imdb_id)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64/ext/imdbpie/imdbpie.py#L80">ext/imdbpie/imdbpie.py</a>", line 80, in get_title
    '/title/{0}/auxiliary'.format(imdb_id)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64/ext/imdbpie/imdbpie.py#L265">ext/imdbpie/imdbpie.py</a>", line 265, in _get_resource
    return self._get(url=url)['resource']
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64/ext/imdbpie/imdbpie.py#L272">ext/imdbpie/imdbpie.py</a>", line 272, in _get
    headers.update(self.get_auth_headers(path))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64/ext/imdbpie/auth.py#L112">ext/imdbpie/auth.py</a>", line 112, in get_auth_headers
    creds, soon_expires = self._creds_soon_expiring()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64/ext/imdbpie/auth.py#L97">ext/imdbpie/auth.py</a>", line 97, in _creds_soon_expiring
    creds = self._get_creds()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64/ext/imdbpie/auth.py#L84">ext/imdbpie/auth.py</a>", line 84, in _get_creds
    with diskcache.Cache(directory=self._cachedir) as cache:
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64/ext/diskcache/core.py#L408">ext/diskcache/core.py</a>", line 408, in __init__
    sql(query, (key, value))
OperationalError: attempt to write a readonly database
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sharkykh** [comment] 2018-07-25 13:16
Duplicate of #4743.
There's a temporary solution described in there.

Also, it's fixed in develop (#4745).

**Closed by sharkykh** 2018-07-25 13:16 UTC
Labels: Duplicate
