### ISSUE TITLE
[APP SUBMITTED]: AttributeError: 'Manage' object has no attribute 'setStatus'

### ISSUE THREAD

**Issue by bassings** [pymedusa/Medusa#9215] opened 2021-02-13 10:00 UTC
### INFO
**Python Version**: `3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]`
**Operating System**: `Linux-4.18.0-240.10.1.el8_3.x86_64-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-02-13 19:59:45 ERROR    Thread_0 :: [b21beeb] Exception generated: 'Manage' object has no attribute 'setStatus'
Traceback (most recent call last):
  File "/var/lib/**********mediaserver/medusa/medusa/server/web/core/base.py", line 252, in async_call
    result = function(**kwargs)
  File "/var/lib/**********mediaserver/medusa/medusa/server/web/manage/handler.py", line 175, in changeEpisodeStatuses
    self.setStatus(
AttributeError: 'Manage' object has no attribute 'setStatus'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment] 2021-02-13 11:07
Duplicate of https://github.com/pymedusa/Medusa/issues/9213

**Closed by medariox** 2021-02-13 11:07 UTC

**Comment by nydave69** [comment] 2021-02-14 22:04
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-02-14 17:03:04 ERROR    Thread_12 :: [b21beeb] Exception generated: 'Manage' object has no attribute 'setStatus'
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/medusa/server/web/core/base.py#L252">medusa\server\web\core\base.py</a>", line 252, in async_call
    result = function(**kwargs)
  File "C:\Medusa\Medusa\<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/medusa/server/web/manage/handler.py#L175">medusa\server\web\manage\handler.py</a>", line 175, in changeEpisodeStatuses
    self.setStatus(
AttributeError: 'Manage' object has no attribute 'setStatus'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by flick1999** [comment] 2021-02-15 17:58
### INFO
**Python Version**: `3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]`
**Operating System**: `Linux-4.19.107-Unraid-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@94fae847b6e7e443d74c59cb11bdbd37c464b363
**Link to Log**: https://gist.github.com/5d5fc8328ad0e1f2b9f5d90a9c42e3db
### ERROR
<pre>
2021-02-15 10:55:19 ERROR    Thread_0 :: [94fae84] Exception generated: 'Manage' object has no attribute 'setStatus'
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/94fae847b6e7e443d74c59cb11bdbd37c464b363/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
  File "/app/medusa/<a href="../blob/94fae847b6e7e443d74c59cb11bdbd37c464b363/medusa/server/web/manage/handler.py#L175">medusa/server/web/manage/handler.py</a>", line 175, in changeEpisodeStatuses
    self.setStatus(
AttributeError: 'Manage' object has no attribute 'setStatus'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ruyruin** [comment] 2021-02-20 13:55
### INFO
**Python Version**: `3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]`
**Operating System**: `Linux-5.8.0-43-generic-x86_64-with-glibc2.29`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-02-20 14:39:42 ERROR    Thread_0 :: [b21beeb] Exception generated: 'Manage' object has no attribute 'setStatus'
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
  File "/opt/medusa/<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/medusa/server/web/manage/handler.py#L175">medusa/server/web/manage/handler.py</a>", line 175, in changeEpisodeStatuses
    self.setStatus(
AttributeError: 'Manage' object has no attribute 'setStatus'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by emipa606** [comment] 2021-02-26 13:10
### INFO
**Python Version**: `3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]`
**Operating System**: `Linux-5.4.0-66-generic-x86_64-with-glibc2.29`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-02-26 14:10:24 ERROR    Thread_0 :: [b21beeb] Exception generated: 'Manage' object has no attribute 'setStatus'
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
  File "/opt/medusa/<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/medusa/server/web/manage/handler.py#L175">medusa/server/web/manage/handler.py</a>", line 175, in changeEpisodeStatuses
    self.setStatus(
AttributeError: 'Manage' object has no attribute 'setStatus'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
