### ISSUE TITLE
[APP SUBMITTED]: KeyError: 133031

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [pymedusa/Medusa#7809] opened 2020-03-03 00:10 UTC
### INFO
**Python Version**: `3.7.6 (default, Dec 30 2019, 19:38:26) [Clang 11.0.0 (clang-1100.0.33.16)]`
**Operating System**: `Darwin-19.3.0-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@65a9c84ef98d927b706d552a01617baf1554b713
**Link to Log**: https://gist.github.com/e05c0fb75aadfa8bc5abd4187e1b2212
### ERROR
<pre>
2020-03-03 08:40:04 ERROR    SHOWUPDATER :: [65a9c84] Problem running show_updater, Indexer TVDBv2 seems to be having issues while trying to get updates for show Aki Sora. Cause: KeyError(133031)
Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/ext/tvdbapiv2/rest.py#L54">ext/tvdbapiv2/rest.py</a>", line 54, in request
    r.raise_for_status()
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/ext/requests/models.py#L941">ext/requests/models.py</a>", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://tvdb2.plex.tv/series/133031/episodes/query?page=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/medusa/indexers/tvdbv2/tvdbv2_api.py#L277">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 277, in _query_series
    tvdb_id, page=page, accept_language=self.config['language']
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/ext/tvdbapiv2/apis/series_api.py#L468">ext/tvdbapiv2/apis/series_api.py</a>", line 468, in series_id_episodes_query_get
    callback=params.get('callback'))
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/ext/tvdbapiv2/api_client.py#L295">ext/tvdbapiv2/api_client.py</a>", line 295, in call_api
    response_type, auth_settings, callback)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/ext/tvdbapiv2/api_client.py#L122">ext/tvdbapiv2/api_client.py</a>", line 122, in __call_api
    post_params=post_params, body=body)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/ext/tvdbapiv2/api_client.py#L315">ext/tvdbapiv2/api_client.py</a>", line 315, in request
    headers=headers)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/ext/tvdbapiv2/rest.py#L70">ext/tvdbapiv2/rest.py</a>", line 70, in get
    query_params=query_params)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/ext/tvdbapiv2/rest.py#L63">ext/tvdbapiv2/rest.py</a>", line 63, in request
    raise ApiException(status=status, reason=msg)
tvdbapiv2.exceptions.ApiException: (404)
Reason: HTTPError
404 Client Error: Not Found for url: https://tvdb2.plex.tv/series/133031/episodes/query?page=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/medusa/show_updater.py#L128">medusa/show_updater.py</a>", line 128, in run
    [show.indexerid], show.last_update_indexer, update_max_weeks)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/medusa/indexers/tvdbv2/tvdbv2_api.py#L669">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 669, in get_last_updated_seasons
    episodes = self._query_series(show_id)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/medusa/indexers/tvdbv2/fallback.py#L135">medusa/indexers/tvdbv2/fallback.py</a>", line 135, in __call__
    return self.func(*args, **kwargs)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/medusa/indexers/tvdbv2/tvdbv2_api.py#L294">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 294, in _query_series
    if error.status == 404 and not self.shows[tvdb_id]['firstaired']:
KeyError: 133031
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment] 2020-03-08 22:30
Duplicate of https://github.com/pymedusa/Medusa/issues/7511

**Closed by medariox** 2020-03-08 22:30 UTC
Labels: triage
