### ISSUE TITLE
ability to change indexer

### ISSUE THREAD

**Issue by donbrew1** [pymedusa/Medusa#7966] opened 2020-04-13 20:38 UTC
**Is your feature request related to a problem? Please describe.**

If I choose an indexer when I add a show, sometimes the listings are incorrect and another indexer is correct.
**Describe the solution you'd like**

I would like to easily change indexer for a given show without having to delete the show then re add it with the new indexer.
**Describe alternatives you've considered**

Delete the show from data base and re add it with a different indexer.
**Additional context**
For instance:  American Pickers; TheTVDB list the season as YearExx.  TVMaze lists it as Actual SxxExx.   The source I use lists SxxExx like TVMaze, but when I originally added the show I chose TheTVDB so Medusa does not find the show even though it does exist under a different format.

**Comment by Generator** [comment] 2020-04-14 00:48
Duplicate of #6531

**Comment by donbrew1** [comment] 2020-04-14 02:21
The supposed duplicate was not resolved except for the admonition to open an issue.  I was under the impression that I was opening an issue.

How about some help?

**Comment by p0psicles** [comment] 2020-04-14 05:52
It's not an easy feature to implement. Else it would have been added already. 
But sure you can always request 👍

**Comment by medariox** [comment] 2020-04-14 09:57
Closing because it's a duplicate of https://github.com/pymedusa/Medusa/issues/6531
The "open a new issue" comment was referring to the comment above it, not the feature request.

**Closed by medariox** 2020-04-14 09:57 UTC
Labels: triage
