### ISSUE TITLE
[APP SUBMITTED]: TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by gilly65** [pymedusa/Medusa#8061] opened 2020-05-06 10:45 UTC
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: https://gist.github.com/9b4fd431731fca44238d880406e5b499
### ERROR
<pre>
2020-05-06 07:44:20 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [BinSearch] :: [d9c31da] DailySearchQueueItem Exception, error: TypeError("'NoneType' object has no attribute '__getitem__'",)
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/search/queue.py#L266">medusa/search/queue.py</a>", line 266, in run
    found_results = search_for_needed_episodes(self.scheduler_start_time, force=self.force)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/search/core.py#L526">medusa/search/core.py</a>", line 526, in search_for_needed_episodes
    cur_provider.cache.update_cache(scheduler_start_time)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/tv/cache.py#L225">medusa/tv/cache.py</a>", line 225, in update_cache
    data = self._get_rss_data()
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/tv/cache.py#L200">medusa/tv/cache.py</a>", line 200, in _get_rss_data
    return {'entries': self.provider.search(self.search_params)}
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/providers/nzb/binsearch.py#L95">medusa/providers/nzb/binsearch.py</a>", line 95, in search
    results += self.parse(response.text, mode)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/providers/nzb/binsearch.py#L116">medusa/providers/nzb/binsearch.py</a>", line 116, in parse
    post_url = html.find('form', {'method': 'post'})['action']
TypeError: 'NoneType' object has no attribute '__getitem__'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment] 2020-05-08 10:59
Duplicate of https://github.com/pymedusa/Medusa/issues/8059

**Closed by medariox** 2020-05-08 10:59 UTC
Labels: triage
