### ISSUE TITLE
[APP SUBMITTED]: HTTPError: 405 Client Error: Method Not Allowed for url: https://api.trakt.tv//search/imdb/https://www.imdb.com/titl?type=show

### ISSUE THREAD

**Issue by pct00** [pymedusa/Medusa#6641] opened 2019-05-02 19:05 UTC
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@f46bfacf8763204fbde4f26a5916095371d494d1
**Link to Log**: https://gist.github.com/e9d9d437edfcd1ec2e4bb092cbd1bb5f
### ERROR
<pre>
2019-05-02 20:03:13 ERROR    SHOWQUEUE-ADD :: [f46bfac] Unknown Trakt request exception. Error: 405
Traceback (most recent call last):
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/lib/traktor/trakt.py#L118">lib\traktor\trakt.py</a>", line 118, in request
    resp.raise_for_status()
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/ext/requests/models.py#L940">ext\requests\models.py</a>", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 405 Client Error: Method Not Allowed for url: https://api.trakt.tv//search/imdb/https://www.imdb.com/titl?type=show
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by pct00** [comment] 2019-05-02 19:10
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@f46bfacf8763204fbde4f26a5916095371d494d1
**Link to Log**: https://gist.github.com/1ed6276645bc75ed8d244fadc0be70ba
### ERROR
<pre>
2019-05-02 20:08:08 ERROR    SHOWQUEUE-ADD :: [f46bfac] Unknown Trakt request exception. Error: 405
Traceback (most recent call last):
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/lib/traktor/trakt.py#L118">lib\traktor\trakt.py</a>", line 118, in request
    resp.raise_for_status()
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/ext/requests/models.py#L940">ext\requests\models.py</a>", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 405 Client Error: Method Not Allowed for url: https://api.trakt.tv//search/imdb/https://www.imdb.com/titl?type=show
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment] 2019-05-02 19:36
Duplicate of https://github.com/pymedusa/Medusa/issues/5454

**Closed by medariox** 2019-05-02 19:36 UTC
Labels: triage
