### ISSUE TITLE
[APP SUBMITTED]: KeyError: 361868

### ISSUE THREAD

**Issue by baya44** [pymedusa/Medusa#7487] opened 2019-12-14 12:14 UTC
### INFO
**Python Version**: `2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.105-x86_64-with-glibc2.2.5`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@d0c136d7a528a471b51676140bd35d24d97f65c6
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-12-14 04:00:27 ERROR    SHOWUPDATER :: [d0c136d] Problem running show_updater, Indexer TVDBv2 seems to be having issues while trying to get updates for show Stargirl. Cause: KeyError(361868,)
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/d0c136d7a528a471b51676140bd35d24d97f65c6/medusa/show_updater.py#L147">medusa/show_updater.py</a>", line 147, in run
    update_max_weeks)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/d0c136d7a528a471b51676140bd35d24d97f65c6/medusa/indexers/tvdbv2/tvdbv2_api.py#L666">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 666, in get_last_updated_seasons
    episodes = self._query_series(show_id)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/d0c136d7a528a471b51676140bd35d24d97f65c6/medusa/indexers/tvdbv2/fallback.py#L135">medusa/indexers/tvdbv2/fallback.py</a>", line 135, in __call__
    return self.func(*args, **kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/d0c136d7a528a471b51676140bd35d24d97f65c6/medusa/indexers/tvdbv2/tvdbv2_api.py#L294">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 294, in _query_series
    if error.status == 404 and not self.shows[tvdb_id]['firstaired']:
KeyError: 361868
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by furafollas** [comment] 2019-12-19 11:50
### INFO
**Python Version**: `2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.105-x86_64-with-glibc2.2.5`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@ae5acb0e7a025200c2cb671907b2255905ce480d
**Link to Log**: https://gist.github.com/ea316d9ed27cc379a9458f3bad869d29
### ERROR
<pre>
2019-12-19 02:01:00 ERROR    SHOWUPDATER :: [ae5acb0] Problem running show_updater, Indexer TVDBv2 seems to be having issues while trying to get updates for show Stargirl. Cause: KeyError(361868,)
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/ae5acb0e7a025200c2cb671907b2255905ce480d/medusa/show_updater.py#L147">medusa/show_updater.py</a>", line 147, in run
    update_max_weeks)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/ae5acb0e7a025200c2cb671907b2255905ce480d/medusa/indexers/tvdbv2/tvdbv2_api.py#L666">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 666, in get_last_updated_seasons
    episodes = self._query_series(show_id)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/ae5acb0e7a025200c2cb671907b2255905ce480d/medusa/indexers/tvdbv2/fallback.py#L135">medusa/indexers/tvdbv2/fallback.py</a>", line 135, in __call__
    return self.func(*args, **kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/ae5acb0e7a025200c2cb671907b2255905ce480d/medusa/indexers/tvdbv2/tvdbv2_api.py#L294">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 294, in _query_series
    if error.status == 404 and not self.shows[tvdb_id]['firstaired']:
KeyError: 361868
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment] 2020-01-06 10:16
Duplicate of https://github.com/pymedusa/Medusa/issues/7511

**Closed by medariox** 2020-01-06 10:16 UTC
Labels: triage
