### ISSUE TITLE
Update PMS library not working

### ISSUE THREAD

**Issue by 60wsr** [pymedusa/Medusa#10063] opened 2021-11-09 22:24 UTC
Hi,

All boxes from Notifications -> Plex Media server are completed with the correct information (token, user, password, server ip:port) and I`m receiving the blue box with (error trying to update plex).
What is surprisingly, when using the Test Plex Media Server, the test is ok even if the Token field is empty.

Error received:
Thread_2 :: [] PLEX: Unauthorized. Please set TOKEN or USERNAME and PASSWORD in Plex settings

**Comment by WarEagleUS21** [comment] 2021-11-14 17:11
I too am receiving the same blue box error. I have redone the set up multiple times and verified and the error remains the same. Test Plex connection works fine. If I have my VPN on, same issue but I have routed past it and even turned it off to no avail. Just noticed it happening the other week (if doing manually, everything still updates automatically when manually post processing or letting the system auto handle). Not sure what the deal is but I haven't seen anything in error logs, debug logs, etc.

**Comment by p0psicles** [comment] 2021-11-22 18:40
Can you in detail describe the steps for me to reproduce this error?
Also you shouldn't need to fill in the `Plex Media Server Auth Token`. Username and password is enough.

**Comment by WarEagleUS21** [comment] 2021-11-26 14:15
See logs but ultimately it succeeds on its own. This is just when I do Manage -> Update Plex. I used to never get the blue notification saying it failed, only green or red (and red would happen when I was connected to my old VPN). Not sure what is going on with it but Plex get’s updated but I believe that is more to do with the Plex handling of scanning new library files on add than Medusa sending it through.

 

2021-11-26 08:11:28 WARNING      TORNADO :: [f35a19d] 404 GET /home/updatePLEX/ (127.0.0.1) 1.50ms

2021-11-26 08:11:28 DEBUG        TORNADO :: [f35a19d] Failed doing web ui get request 'updatePLEX': Traceback (most recent call last):

  File "C:\Medusa\Medusa\medusa\server\web\core\base.py", line 218, in get

    method = getattr(self, route)

AttributeError: 'Home' object has no attribute 'updatePLEX'

2021-11-26 08:11:27 INFO TORNADO :: [f35a19d] 304 GET /api/v2/log/reporter?level=WARNING (127.0.0.1) 1.00ms

2021-11-26 08:11:25 INFO TORNADO :: [f35a19d] 200 GET /api/v2/log/reporter?level=WARNING (127.0.0.1) 1.00ms

2021-11-26 08:11:24 INFO TORNADO :: [f35a19d] 101 GET /ws/ui (127.0.0.1) 1.00ms

2021-11-26 08:11:24 INFO TORNADO :: [f35a19d] 200 GET /api/v2/config/ (127.0.0.1) 28.02ms

2021-11-26 08:11:24 INFO TORNADO :: [f35a19d] 304 GET /api/v2/stats/ (127.0.0.1) 18.02ms

2021-11-26 08:11:24 WARNING      TORNADO :: [f35a19d] 404 GET /home/updatePLEX/ (127.0.0.1) 48.04ms

2021-11-26 08:11:24 DEBUG        TORNADO :: [f35a19d] Failed doing web ui get request 'updatePLEX': Traceback (most recent call last):

  File "C:\Medusa\Medusa\medusa\server\web\core\base.py", line 218, in get

    method = getattr(self, route)

AttributeError: 'Home' object has no attribute 'updatePLEX'

2021-11-26 08:11:23 INFO TORNADO :: [f35a19d] 200 GET /api/v2/log/reporter?level=WARNING (127.0.0.1) 1.00ms

2021-11-26 08:11:22 INFO TORNADO :: [f35a19d] 304 GET /api/v2/series?limit=1000&page=1 (127.0.0.1) 60.05ms

2021-11-26 08:11:22 INFO TORNADO :: [f35a19d] 101 GET /ws/ui (127.0.0.1) 0.50ms

2021-11-26 08:11:22 INFO TORNADO :: [f35a19d] 200 GET /api/v2/config/ (127.0.0.1) 27.52ms

2021-11-26 08:11:22 INFO TORNADO :: [f35a19d] 304 GET /api/v2/stats/ (127.0.0.1) 24.02ms

2021-11-26 08:11:21 INFO TORNADO :: [f35a19d] 304 GET /errorlogs/?level=30 (127.0.0.1) 2.00ms

**Comment by p0psicles** [comment] 2021-11-26 15:05
Should be fixed in the develop branch.
Could you give that branch a try?

**Comment by WarEagleUS21** [comment] 2021-11-26 20:07
Will do.  Thanks buddy. I'll move to that when I get back to the house.
Happy Thanksgiving.

**Comment by WarEagleUS21** [comment] 2021-11-28 16:29
Will doing the checkout branch – develop install and update to version 6 or will I need to manually uninstall it and reinstall it to get the latest version and that branch?

**Comment by p0psicles** [comment] 2021-11-28 16:44
Yes checkout develop branch and doing a pull should be sufficient

**Comment by WarEagleUS21** [comment] 2021-11-28 16:45
Tried that but the logs said it couldn’t identify or match the checkout version with the installed version.

**Comment by WarEagleUS21** [comment] 2021-11-28 16:49
Logs are attached. If you can’t see those, let me know and I will upload to google drive and share with you.

 

It does this for the Master version as well. I am on 5.x

**Comment by WarEagleUS21** [comment] 2021-11-28 17:51
Email didn't send the logs
[Development Branch Checkout Logs.docx](https://github.com/pymedusa/Medusa/files/7614045/Development.Branch.Checkout.Logs.docx)

**Comment by p0psicles** [comment] 2021-11-28 18:02
Run these commands. 
Git fetch origin
Git checkout -t origin/develop

**Comment by WarEagleUS21** [comment] 2021-11-28 18:07
PS C:\Medusa\Git\cmd> .\Git fetch origin
fatal: not a git repository (or any of the parent directories): .git
PS C:\Medusa\Git\cmd>

That is what I get when I navigate to the directory C:\Medusa\Git\cmd

**Comment by p0psicles** [comment] 2021-11-28 18:43
You should run the commands in Medusa dir. Where also the start.py is located

**Comment by WarEagleUS21** [comment] 2021-11-28 18:46
It didn't work there,I tried initially since I saw it on a forum page but I
went ahead and deleted and am installing freshly. Probably some other
issues now that I moved fully to worried 11. I appreciate all your help
p0p. You and the team are brilliant and I really am thankful for your help
and that y'all have patience for us. I'm not a total idiot but some of
these things are daunting and out of my element. I'll report back after the
reinstall

**Comment by WarEagleUS21** [comment] 2021-11-28 18:51
Well, it installed and updated to develop and python, etc but now it won't
connect. Let me make sure everything is up and up.

**Comment by WarEagleUS21** [comment] 2021-11-28 19:10
Seems that after reinstalling it can't start the service. Says the C:\Medusa\Installer\nssm.exe can't be found from the event logs but the program is actually in there...

**Comment by WarEagleUS21** [comment] 2021-11-28 19:43
After a 3rd fresh install and even a backup and restore, it still cannot start the service.

**Comment by WarEagleUS21** [comment] 2021-11-28 20:26
Going to create a new issue and stop hijacking this one, apologies.

**Comment by p0psicles** [comment] 2021-11-28 20:51
No probs. Make sure to comletely uninstall before installing

**Closed** 2022-01-02 11:37 UTC
