### ISSUE TITLE
Sorting methode doesn’t stick

### ISSUE THREAD

**Issue by ac3nl** [pymedusa/Medusa#11330] opened 2023-05-28 05:56 UTC
i am on docker 1.0.16

Normally i sort my gui to “next episode”
This is saved to a cookie, i presume.
next time i open the ui, it is still sorted this way.

now, when i open the gui again, it is sorted alphabetical again.
So it doesn’t save the last sorting methode

this also happens with a refreh page in the browser

minor bug, not that important.
Maybe fix with next update?

**Comment by medariox** [comment] 2023-05-28 10:33
It works for me. What browser and version are you using?

**Comment by ac3nl** [comment] 2023-05-28 10:55
Both on firefox (windows) as on safari (ios)
Same behaviour…

**Comment by PlaceboPRS** [comment] 2023-06-01 06:40
No idea if it's related but I also have a sorting issue with the latest update when I search for an episode manually, I always sort by size in descending order but it's sorting by quality and even if I change back to size it's forgetting that the next time I search for something manually, this is new behaviour.

Windows 11, Firefox 113.02 64bit

![image](https://github.com/pymedusa/Medusa/assets/23120453/4a2cd99e-feda-44df-b024-74fa929c20c0)

**Comment by marcmv1** [comment] 2023-06-02 13:35
I can confirm this as well. Sort order is lost on every browser refresh. Multiple browsers tested.

**Comment by NMJToolbox** [comment] 2023-06-04 08:57
Also confirmed, running Medusa on Synology NAS, tested in Edge, Brave and Chrome.  
Cookie info states :
Name
home-simple-sort-field

Content
%5B%22nextAirDate%22%5D

but always sorts alphabetically by show name on refresh.

**Comment by gmusgrave** [comment] 2023-06-04 13:59
I have the same problem. It started with the newest update.

I'm on V1.0.16 using Chrome (113.0.5672.129 (Official Build) (64-bit)).

I noticed a new option in "General Configuration | Interface" called  "show lists" that appears to have something to do with sorting. I can't find any info on how this works or how to configure it. Could be related?

**Comment by deusxanime** [comment] 2023-06-06 18:53
Same here. Running the latest/up-to-date Medusa docker container by linuxserver.io on unRAID. (Actually running two different Medusa containers for different purposes and both exhibit this.)

The home page keeps resetting to the default sorting of alphabetically by Show name. I like to sort by Status first (then by Show name after) and so I change it and it will work while I navigate around back and forth between show listings, home, etc, but if I close and come back or even just do a refresh on the home page, then it forgets the custom sorting order by Status first on the home page, and default backs to just alpha by Show name.

**Comment by PlaceboPRS** [comment] 2023-06-15 13:52
No workaround or anything? Quite annoying, was hoping there might be an update to fix it or something as it's been a few weeks now (apologies in advance if I'm being rude I don't mean to be!) :)

**Comment by marcmv1** [comment] 2023-06-15 14:25
> No workaround or anything? Quite annoying, was hoping there might be an update to fix it or something as it's been a few weeks now (apologies in advance if I'm sounding rude I don't mean to be!) :)

It's a FREE product made available by people who volunteer their time. They're not making money from this. So be patient and wait for them to release a fix. No one owes you, me or anyone else anything including an update or setting expectations. The update comes with it comes. Don't act entitled.

**Comment by PlaceboPRS** [comment] 2023-06-15 14:28
> 

I thought my apology caveat would be enough, but lecture received and understood, tho I don't believe I was acting entitled. :)

**Comment by medariox** [comment] 2023-06-29 17:07
Fixed with v1.0.17 https://github.com/pymedusa/Medusa/releases/tag/v1.0.17

**Closed by medariox** 2023-06-29 17:07 UTC
