### ISSUE TITLE
TypeError: remove() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by scott451** [pymedusa/Medusa#3613] opened 2018-01-16 12:37 UTC
hello,

i use Medusa on DSM 6.1.4. Today I updated Git on the DSM to 1.15.1 I also update Python to 2.7.14. Following this update Medusa refused to start. I have tried everything including a re-install to no avail.

following is the error message i see when i try to start. sorry to not have more info and thanks for your help.

- scott

```
root@Valinor:/var/packages/sickbeard-custom# /var/packages/sickbeard-custom/scripts/start-stop-status start
Starting SickBeard Custom ...
/usr/local/ffmpeg/bin/ffprobe: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.87)
/usr/local/ffmpeg/bin/ffprobe: /lib/libstdc++.so.6: no version information available (required by /usr/local/ffmpeg/lib/libx265.so.87)
Traceback (most recent call last):
  File "/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py", line 4, in <module>
    from medusa.__main__ import main
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/__main__.py", line 67, in <module>
    from . import (
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/providers/__init__.py", line 10, in <module>
    from medusa.providers.nzb import (
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/providers/nzb/anizb.py", line 14, in <module>
    from medusa.providers.nzb.nzb_provider import NZBProvider
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/providers/nzb/nzb_provider.py", line 8, in <module>
    from medusa.providers.generic_provider import GenericProvider
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/providers/generic_provider.py", line 18, in <module>
    from medusa import (
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/config.py", line 30, in <module>
    from medusa.version_checker import CheckVersion
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/version_checker.py", line 31, in <module>
    from medusa.github_client import get_github_repo
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/github_client.py", line 6, in <module>
    import github
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/github/__init__.py", line 37, in <module>
    from MainClass import Github, GithubIntegration
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/github/MainClass.py", line 34, in <module>
    import jwt
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/jwt/__init__.py", line 19, in <module>
    from .api_jwt import (
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/jwt/api_jwt.py", line 8, in <module>
    from .api_jws import PyJWS
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/jwt/api_jws.py", line 7, in <module>
    from .algorithms import (
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/jwt/algorithms.py", line 8, in <module>
    from .utils import (
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/jwt/utils.py", line 8, in <module>
    from cryptography.hazmat.primitives.asymmetric.utils import (
  File "/var/packages/python/target/lib/python2.7/site-packages/cryptography/hazmat/primitives/asymmetric/utils.py", line 9, in <module>
    from asn1crypto.algos import DSASignature
  File "/var/packages/python/target/lib/python2.7/site-packages/asn1crypto/algos.py", line 24, in <module>
    from ._int import fill_width
  File "/var/packages/python/target/lib/python2.7/site-packages/asn1crypto/_int.py", line 56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "/var/packages/python/target/lib/python2.7/site-packages/asn1crypto/_perf/_big_num_ctypes.py", line 35, in <module>
    libcrypto_path = find_library(b'crypto' if sys.version_info < (3,) else 'crypto')
  File "/var/packages/python/target/lib/python2.7/ctypes/util.py", line 274, in find_library
    return _findSoname_ldconfig(name) or _get_soname(_findLib_gcc(name))
  File "/var/packages/python/target/lib/python2.7/ctypes/util.py", line 107, in _findLib_gcc
    temp.close()
  File "/var/packages/python/target/lib/python2.7/tempfile.py", line 431, in close
    self.unlink(self.name)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/init/filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
TypeError: remove() takes exactly 1 argument (2 given)
```

**Comment by fernandog** [comment] 2018-01-16 12:42
@stefaang @medariox

**Comment by medariox** [comment] 2018-01-16 12:51
What version is 1.15.1 supposed to be? Probably using a version pre-fix.

**Comment by scott451** [comment] 2018-01-16 12:57
sorry typo. git and python version are what i see in the dsm package center.

dsm v6.1.4
git v2.15.1
python v2.7.14

**Comment by medariox** [comment] 2018-01-16 13:53
@scott451 
That sadly doesn't tell us anything about the Medusa version you are trying to use.

**Comment by fernandog** [comment] 2018-01-16 13:57
@scott451 send a full print of the Medusa version in the config page

medusa-ip:port/config/

**Comment by scott451** [comment] 2018-01-16 14:01
i know. i grabbed it today from the master branch. can i see the version somewhere without launching the app ?

**Comment by medariox** [comment] 2018-01-16 14:09
The current master branch doesn't include the fix you are waiting for. It will be included in the next release, which should become available later today.

**Comment by scott451** [comment] 2018-01-16 14:22
ah. great !

**Comment by stefaang** [comment] 2018-01-16 15:36
Looks like a duplicate of https://github.com/pymedusa/Medusa/issues/3567
I saw the issues with python version 2.7.13 on Entware but I couldn't reproduce it with python version 2.7.12 on Ubuntu 16.04.

Makes me think that the root cause is in the python version...

Anyway, fix is available on develop branch. Make sure you set the locale to use UTF-8, see original issue.

**Comment by medariox** [comment] 2018-01-16 19:31
The new release is out. Please update and see if the issue is solved.

**Comment by udochrist** [comment] 2018-01-16 19:31
just to be sure since the timestamps of this issue and the releasing of 0.1.23 are somewhat overlapping.

this issue is not fixed with release 0.1.23  on synology and their latest python update to 2.7.14.
the app (sickbeard-custom using the medusa-git repo as source) does no longer start from package center

**Comment by medariox** [comment] 2018-01-16 19:32
@udochrist 
Are you sure that you did update to the latest version?

**Comment by udochrist** [comment] 2018-01-16 19:35
git pull on the shell says  "already up to date", so yes

**Comment by scott451** [comment] 2018-01-16 19:40
i just reinstalled. still receiving same error message.

**Comment by udochrist** [comment] 2018-01-16 19:42
last view lines from startup log are:

```
    temp.close()
  File "/usr/local/python/lib/python2.7/tempfile.py", line 431, in close
    self.unlink(self.name)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/init/filesystem.py", line 108, in patched_output
    return handle_output(f(*args, **kwargs))
TypeError: remove() takes exactly 1 argument (2 given)
2018/01/16 20:38:38 start sickbeard-custom 20151220-4 End start-stop-status start ret=[1]
2018/01/16 20:38:38 (system) trigger sickbeard-custom 20151220-4 Begin start-stop-status stop
SickBeard Custom is not running 
```
git log btw says:
```
commit ef68ec25f7cb0563e5f687dba61a4c9d8dc84c58
Merge: 7b9111e 2c3767d
Author: p0ps <p0psicles@users.noreply.github.com>
Date:   Tue Jan 16 18:12:55 2018 +0100

    Merge pull request #3612 from pymedusa/develop

    Release 0.1.23
```
on the shell i have LANG as en_US.utf8 fwiw.

**Comment by udochrist** [comment] 2018-01-16 22:21
Ok this is definitely an issue that still needs to be solved (at least for synology based installs).
my analysis so far:

the sickbeard-custom package needs the python package from synocommunity. This python package got upgraded which lets medusa 0.1.23 fail to start. i initally thought that the python package was from synology, but this is not the case.

The failure to start medusa is related to the python virtualenv created when the sickbeard-custom package got installed initially. when i move the env/lib/python-2,7 (inside the sickbeard-package) out of the way i can successfully start the app.

**Comment by stefaang** [comment] 2018-01-17 10:37
Please let me know if you can do the following without virtualenv modifications:

    git checkout master
    git pull
    export LANG=en_US.UTF8
    env/bin/python SickBeard.py --help

**Comment by stefaang** [comment] 2018-01-17 11:54
This simple harmless oneliner seems to do the job.
https://github.com/pymedusa/Medusa/pull/3619

**Closed** 2018-01-17 14:40 UTC
Labels: Fixed
