### ISSUE TITLE
Manually Process Files Failed & Changing Show Status After New Update

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#5130] opened 2018-09-07 00:56 UTC
Hi Team

I have just updated to the new version and cannot Manually Process Files

Describe the bug
Manually Process Files Failed

To Reproduce
It happens every time i try and manually process files

Expected behavior
Process Files

Screenshots
N / A

Medusa (please complete the following information):
Branch: master 
Commit: db3d9d767bbf3fe7c365df20d92099b0cbbd91b4 
Version: Unknown 
Database: 44.12
Python Version:	2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
SSL Version:	LibreSSL 2.6.5
OS:	Linux-3.10.102-x86_64-with
Locale:	Unknown.Unknown
 	 

Logs:

```
2018-09-07 02:51:41 ERROR    Thread_12 :: [db3d9d7] Exception generated: No item with that key
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 259, in async_call
    result = function(**kwargs)
  File "/app/medusa/medusa/server/web/home/post_process.py", line 49, in processEpisode
    ignore_subs=argToBool(ignore_subs)
  File "/app/medusa/medusa/process_tv.py", line 145, in process
    ignore_subs=ignore_subs)
  File "/app/medusa/medusa/process_tv.py", line 333, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/app/medusa/medusa/process_tv.py", line 554, in process_media
    self.result = processor.process()
  File "/app/medusa/medusa/post_processor.py", line 1037, in process
    ep_obj = self._get_ep_obj(series_obj, season, episodes)
  File "/app/medusa/medusa/post_processor.py", line 743, in _get_ep_obj
    cur_ep = series_obj.get_episode(season, cur_episode)
  File "/app/medusa/medusa/tv/series.py", line 796, in get_episode
    ep = Episode(self, season, episode)
  File "/app/medusa/medusa/tv/episode.py", line 270, in __init__
    self._specify_episode(self.season, self.episode)
  File "/app/medusa/medusa/tv/episode.py", line 554, in _specify_episode
    sql_results = self.load_from_db(season, episode)
  File "/app/medusa/medusa/tv/episode.py", line 635, in load_from_db
    self.watched = int(sql_results[0][b'watched'])
IndexError: No item with that key
```

Additional context
Synology
DSM 6.1.7-15284 Update 2
Running In Docker

Thanks

**Comment by HPMSGEN8** [comment] 2018-09-07 01:09
Next Error

```
2018-09-07 03:08:14 ERROR    Thread_8 :: [db3d9d7] Exception generated: No item with that key
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 259, in async_call
    result = function(**kwargs)
  File "/app/medusa/medusa/server/web/home/handler.py", line 1913, in setStatus
    ep_obj = series_obj.get_episode(season_no, episode_no)
  File "/app/medusa/medusa/tv/series.py", line 796, in get_episode
    ep = Episode(self, season, episode)
  File "/app/medusa/medusa/tv/episode.py", line 270, in __init__
    self._specify_episode(self.season, self.episode)
  File "/app/medusa/medusa/tv/episode.py", line 554, in _specify_episode
    sql_results = self.load_from_db(season, episode)
  File "/app/medusa/medusa/tv/episode.py", line 635, in load_from_db
    self.watched = int(sql_results[0][b'watched'])
IndexError: No item with that key
```

**Comment by p0psicles** [comment] 2018-09-07 05:44
@sharkykh i'm starting to feel we're inserting episodes without the 'watched' value somehow?
If not, then i'll just add a fix method to the check() method.

**Comment by p0psicles** [comment] 2018-09-07 05:51
@HPMSGEN8 do you still have logs from the upgrade?
Did you come from previous master? Or did you run the develop branch?

**Comment by sharkykh** [comment] 2018-09-07 08:07
I explained before that the the reason the migration goes wrong is because most (all?) of the docker images are using some kind of service restarter, which means Medusa is loaded twice **at the same time**.

https://github.com/pymedusa/medusa.github.io/pull/117

**Comment by sharkykh** [comment] 2018-09-07 08:12
About the actual bug (a duplicate of #4917), pasting my workaround for it at the moment:

----

If you put this script in your data folder and run the following command, you can fix this issue.
Be sure to follow the instructions provided by the script.

https://gist.github.com/sharkykh/72870e9edd3b7f186ac361fb67a841e4
Command to run when from within the data folder:
```shell
python fix_db.py main
```

Example output:
```
Current "main" database version: 44.12
Incorrect database version detected, `tv_episodes.watched` column missing.
Need to revert database version to 44.11, confirm? [y/N]: y
Setting version...
New "main" database version: 44.11
Please **shut down** Medusa and wait 30 seconds for it to go back up again (assuming you are using a restarting service).
If Medusa is not up after 30 seconds, start it again manually.
```

**Comment by HPMSGEN8** [comment] 2018-09-07 08:49
@p0psicles I came from the latest master then i upgraded. Where can i find the upgrade logs ?

**Comment by HPMSGEN8** [comment] 2018-09-07 08:53
@sharkykh Can you let me know how do i run this as i have never done this before.

**Comment by sharkykh** [comment] 2018-09-07 09:05
@HPMSGEN8 
I can't say for sure, as I don't have Syno DS or Docker, but if you can get a shell terminal inside your machine, you can try: (following https://stackoverflow.com/a/26181666/7597273):
```
docker exec -it CONTAINER_ID /bin/bash

# [terminal opens]

cd /config
curl -o fix_db.py https://gist.githubusercontent.com/sharkykh/72870e9edd3b7f186ac361fb67a841e4/raw/b107e62c7e75f5fa531548f91476368de9abe5d3/fix_db.py
python fix_db.py main
```
where `CONTAINER_ID` is the ID for the medusa container.

**Comment by HPMSGEN8** [comment] 2018-09-07 09:26
@p0psicles @sharkykh This worked :) Thanks so much

```
ash-4.3# curl -o fix_db.py https://gist.githubusercontent.com/sharkykh/72870e9edd3b7f186ac361fb67a841e4/raw/b107e62c7e75f5fa531548f91476368de9abe5d3/fix_db.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2912  100  2912    0     0   5157      0 --:--:-- --:--:-- --:--:--  5153
ash-4.3# python fix_db.py main
Current "main" database version: 44.12
Incorrect database version detected, `tv_episodes.watched` column missing.
Need to revert database version to 44.11, confirm? [y/N]: y
Setting version...
New "main" database version: 44.11
Please **shut down** Medusa and wait 30 seconds for it to go back up again (assuming you are using a restarting service).
If Medusa is not up after 30 seconds, start it again manually.
ash-4.3#
```

I just tested the 2 issues i have and both fixed :) 

Thanks again.

**Comment by HPMSGEN8** [comment] 2018-09-07 09:29
@sharkykh Also if you have a setup like the below.

**File/Folder:** docker/config (OR where ever you have it)
**Mount Path:** /config

Then you just need to go to that location on you NAS via Putty and run the commands you gave me and sorted :) 

```
cd /config
curl -o fix_db.py https://gist.githubusercontent.com/sharkykh/72870e9edd3b7f186ac361fb67a841e4/raw/b107e62c7e75f5fa531548f91476368de9abe5d3/fix_db.py
python fix_db.py main
```

**Comment by sharkykh** [comment] 2018-09-07 09:49
@HPMSGEN8 
>Can this get added to the WIKI for Docker Images and fixes etc...

I disagree because this is a bug with basically all the medusa dockers currently available, including the "official" one that is published directly from this repository.
They need to be fixed, because if not, this will happen *every single time* there's a database migration.

**Comment by HPMSGEN8** [comment] 2018-09-07 10:02
I did not know that and thanks. then i will keep this on hand until fixed :) 

I will log this issue on the docker github then as well.

Thanks again.

**Closed** 2018-09-07 14:30 UTC
Labels: Bug

**Comment by HPMSGEN8** [comment] 2018-09-10 14:05
@sharkykh FYI i updated to 0.2.10 and so far i did not have to do this again :)

**Comment by sharkykh** [comment] 2018-09-10 14:53
@HPMSGEN8 
I assume you mean you didn't need to run the `fix_db.py` script?
That's because 0.2.10 did not include any database migrations.
It only "creates' database issues like the one above when we change the database schema using a database migration (and [the reason is explained here](https://github.com/pymedusa/medusa.github.io/pull/117/files?short_path=f16fbd5#diff-f16fbd58616139583332c38b045fa1a7), however it didn't get merged to the news)

**Comment by HPMSGEN8** [comment] 2018-09-10 15:26
Ah ok thanks :)
