### ISSUE TITLE
[APP SUBMITTED]: ConnectionError: HTTPSConnectionPool(host='cdn.pymedusa.com', port=443): Max retries exceeded with url: /news/news.md (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09881670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#3624] opened 2018-01-17 21:48 UTC
### INFO
**Python Version**: `2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@2c3767d0b68cc92e0716e3c3f8e57495e05996c3
**Link to Log**: https://gist.github.com/ee02e1173adc40cadd3f55e935dfe2be
### ERROR
<pre>
2018-01-17 19:01:19 ERROR    CHECKVERSION :: [2c3767d] Environment error: HTTPSConnectionPool(host='cdn.pymedusa.com', port=443): Max retries exceeded with url: /news/news.md (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09881670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Traceback (most recent call last):
  File "C:\Medusa\medusa\scheduler.py", line 90, in run
    self.action.run(self.force)
  File "C:\Medusa\medusa\version_checker.py", line 82, in run
    self.check_for_new_news(force)
  File "C:\Medusa\medusa\version_checker.py", line 310, in check_for_new_news
    response = self.session.get(app.NEWS_URL)
  File "C:\Medusa\ext\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Medusa\medusa\session\core.py", line 94, in request
    **kwargs)
  File "C:\Medusa\ext\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Medusa\ext\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Medusa\ext\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='cdn.pymedusa.com', port=443): Max retries exceeded with url: /news/news.md (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x09881670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Bangorbob** [comment] 2018-01-22 13:54
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@bd0832551d836713481dd0a93f4118372bb5d963
**Link to Log**: https://gist.github.com/c5e7d0229478737d5ab66f3f5ae73b3f
### ERROR
<pre>
2018-01-20 11:37:04 ERROR    CHECKVERSION :: [bd08325] Environment error: HTTPSConnectionPool(host='cdn.pymedusa.com', port=443): Max retries exceeded with url: /news/news.md (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000000D977048>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\scheduler.py", line 90, in run
    self.action.run(self.force)
  File "C:\Medusa\Medusa\medusa\version_checker.py", line 82, in run
    self.check_for_new_news(force)
  File "C:\Medusa\Medusa\medusa\version_checker.py", line 310, in check_for_new_news
    response = self.session.get(app.NEWS_URL)
  File "C:\Medusa\Medusa\ext\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Medusa\Medusa\medusa\session\core.py", line 94, in request
    **kwargs)
  File "C:\Medusa\Medusa\ext\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Medusa\Medusa\ext\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Medusa\Medusa\ext\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='cdn.pymedusa.com', port=443): Max retries exceeded with url: /news/news.md (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000000D977048>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment] 2018-01-23 21:13
Fixed in develop.

**Closed by medariox** 2018-01-23 21:13 UTC
Labels: Priority: 3. Low

**Comment by scott451** [comment] 2018-01-27 13:45
### INFO
**Python Version**: `2.7.14 (default, Jan 15 2018, 19:15:25) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.102-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@bd0832551d836713481dd0a93f4118372bb5d963
**Link to Log**: https://gist.github.com/e2437a0a7aa3c784ab4bd2742547691b
### ERROR
<pre>
2018-01-27 02:26:08 ERROR    CHECKVERSION :: [bd08325] Environment error: HTTPSConnectionPool(host='cdn.pymedusa.com', port=443): Max retries exceeded with url: /news/news.md (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1cd8307a50>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/SickBeard/medusa/scheduler.py#L90">SickBeard/medusa/scheduler.py</a>", line 90, in run
    self.action.run(self.force)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/SickBeard/medusa/version_checker.py#L82">SickBeard/medusa/version_checker.py</a>", line 82, in run
    self.check_for_new_news(force)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/SickBeard/medusa/version_checker.py#L310">SickBeard/medusa/version_checker.py</a>", line 310, in check_for_new_news
    response = self.session.get(app.NEWS_URL)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/SickBeard/ext/requests/sessions.py#L521">SickBeard/ext/requests/sessions.py</a>", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/SickBeard/medusa/session/core.py#L94">SickBeard/medusa/session/core.py</a>", line 94, in request
    **kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/SickBeard/ext/requests/sessions.py#L508">SickBeard/ext/requests/sessions.py</a>", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/SickBeard/ext/requests/sessions.py#L618">SickBeard/ext/requests/sessions.py</a>", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/SickBeard/ext/requests/adapters.py#L508">SickBeard/ext/requests/adapters.py</a>", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='cdn.pymedusa.com', port=443): Max retries exceeded with url: /news/news.md (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1cd8307a50>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
