### ISSUE TITLE
[APP SUBMITTED]: OSError: [Errno 17] File exists: '/media/Plex/tv/Arrow/Season 05/'

### ISSUE THREAD

**Issue by gnolascord** [pymedusa/Medusa#5154] opened 2018-09-08 03:34 UTC
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.4.0-134-generic-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@db3d9d767bbf3fe7c365df20d92099b0cbbd91b4
**Link to Log**: https://gist.github.com/dc553f3ac733a561fe89b196968fae5d
### ERROR
<pre>
2018-09-07 21:40:58 ERROR    Thread_6 :: [db3d9d7] Failed creating /media/Plex/tv/Arrow/Season 05/ : OSError(17, 'File exists')
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/db3d9d767bbf3fe7c365df20d92099b0cbbd91b4/medusa/helpers/__init__.py#L511">medusa/helpers/__init__.py</a>", line 511, in make_dirs
    os.mkdir(sofar)
  File "/opt/medusa/<a href="../blob/db3d9d767bbf3fe7c365df20d92099b0cbbd91b4/medusa/init/filesystem.py#L113">medusa/init/filesystem.py</a>", line 113, in patched_output
    return handle_output(f(*args, **kwargs))
OSError: [Errno 17] File exists: '/media/Plex/tv/Arrow/Season 05/'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Rouzax** [comment] 2018-09-08 09:31
This is the same issue as:
https://github.com/pymedusa/Medusa/issues/5146
https://github.com/pymedusa/Medusa/issues/5147
https://github.com/pymedusa/Medusa/issues/5148
https://github.com/pymedusa/Medusa/issues/5149
https://github.com/pymedusa/Medusa/issues/5150
https://github.com/pymedusa/Medusa/issues/5151
https://github.com/pymedusa/Medusa/issues/5152
https://github.com/pymedusa/Medusa/issues/5153

Most likely this is an Access permissions issue.

**Comment by OmgImAlexis** [comment] 2018-09-08 10:49
Duplicate of https://github.com/pymedusa/Medusa/issues/5146

**Closed by OmgImAlexis** 2018-09-08 10:49 UTC
Labels: Duplicate
