### ISSUE TITLE
Thumbs not renaming 

### ISSUE THREAD

**Issue by Hancock33** [pymedusa/Medusa#9224] opened 2021-02-15 07:33 UTC
**Describe the bug**
When doing a mass rename the *-thumb.jpg are been left as their original name, only the media file and nfo gets renamed.
My Show - S01E01.mp4               ---> S01E01 - MyShow - Episode 1.mp4
My Show - S01E01.nfo                 ---> S01E01 - MyShow - Episode 1.nfo
My Show - S01E01-thumb.jpg     Not Renamed

**To Reproduce**
1. Enable Kodi12+ in the Post-Processing options
2. Select a show and click on the "Rename Preview" button 
Result
2021-02-15 07:13:47 INFO     Thread_0 :: [b21beeb] Renaming file from 'T:\tv\\Myshow\Season 01\Myshow - S01E01.mp4' to 'T:\tv\\Myshow\Season 01\S01E01 - Myshow - Episode 1.mp4'
2021-02-15 07:13:47 INFO     Thread_0 :: [b21beeb] Trying to clean any empty folder under T:\tv\\Myshow\Season 01
2021-02-15 07:13:47 INFO     Thread_0 :: [b21beeb] Renaming file from 'T:\tv\\Myshow\Season 01\Myshow - S01E01.nfo' to 'T:\tv\\Myshow\Season 01\S01E01 - Myshow - Episode 1.nfo'
2021-02-15 07:13:47 INFO     Thread_0 :: [b21beeb] Trying to clean any empty folder under T:\tv\\Myshow\Season 01

**Expected behavior**
My Show - S01E01.mp4               ---> S01E01 - MyShow - Episode 1.mp4
My Show - S01E01.nfo                 ---> S01E01 - MyShow - Episode 1.nfo
My Show - S01E01-thumb.jpg     ---> S01E01 - MyShow - Episode 1-thumb.jpg

**Medusa (please complete the following information):**
Branch: master 
Commit: b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9
Version: 0.5.8
Database: 44.17
Python Version: | 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)]
SSL Version: | OpenSSL 1.1.1d 10 Sep 2019
OS: | Windows-10-10.0.21313-SP0
Locale: | en_GB.cp1252

**Comment by medariox** [comment] 2021-02-15 09:33
Duplicate of https://github.com/pymedusa/Medusa/issues/8378

**Closed by medariox** 2021-02-15 09:33 UTC
