### ISSUE TITLE
Hard to read show name in Schedule

### ISSUE THREAD

**Issue by ejc1967** [pymedusa/Medusa#8343] opened 2020-08-17 05:34 UTC
**Describe the bug**
In schedule overview the show name is almost invisible when using the dark display theme because the link is now white.

**To Reproduce**
See Screenshot of Schedule

**Screenshots**
![image](https://user-images.githubusercontent.com/12794265/90360286-a39f6700-e05b-11ea-9d8e-4d4221328733.png)

**Medusa:**
Branch: master
Commit: 471c8ed43f6125ebdcd471c260757d8c7cae2ad4
Version: 0.4.0
Database: 44.16

Python Version:	3.5.6 (default, Nov 25 2018, 14:24:15) [GCC 4.7.3 20130102 (prerelease)]
SSL Version:	OpenSSL 1.0.2n 7 Dec 2017
OS:	Linux-3.10.105-x86_64-with-glibc2.2.5
Locale:	en_US.UTF-8

**Comment by p0psicles** [comment] 2020-08-17 05:43
Tnx. Will pick it up

**Comment by p0psicles** [comment] 2020-08-17 07:44
Can't reproduce on mobile. 
Did you try clear cache and refresh? 

I'll try again when I get home.

**Comment by PlaceboPRS** [comment] 2020-08-17 08:21
Was coming here to report same thing, waterfox, chrome, firefox, edge on PC all the same.

![image](https://user-images.githubusercontent.com/23120453/90374206-6d6de180-e073-11ea-97d1-94f548eea373.png)

**Comment by ejc1967** [comment] 2020-08-17 09:34
Clearing the cache and refreshing didn't solve the issue.

**Comment by ejc1967** [comment] 2020-08-17 09:36
Oeps, wrong button.
Didn't mean to close it.

**Comment by papampi** [comment] 2020-08-17 12:10
Same issue with latest release


Medusa Info: | Branch: masterCommit: 471c8ed43f6125ebdcd471c260757d8c7cae2ad4Version: 0.4.0Database: 44.16
-- | --
Python Version: | 3.8.1 (default, Mar 23 2020, 07:23:17) [GCC 8.3.0]
SSL Version: | OpenSSL 1.1.1g 21 Apr 2020
OS: | Linux-4.14.24-qnap-x86_64-with-glibc2.2.5
Locale: | en_US.UTF-8

**Comment by ukharley** [comment] 2020-08-17 14:12
Same here.
Windows 10 Pro
Waterfox

**Comment by p0psicles** [comment] 2020-08-17 15:01
Fixed in develop

**Closed by p0psicles** 2020-08-17 15:01 UTC

**Comment by papampi** [comment] 2020-08-19 10:44
Now the History page is unreadable 
![Screenshot from 2020-08-19 15-13-09](https://user-images.githubusercontent.com/1108483/90625359-b1591600-e22e-11ea-9192-817ea77fb488.png)

**Comment by PlaceboPRS** [comment] 2020-08-19 12:19
Same :(

![image](https://user-images.githubusercontent.com/23120453/90633767-ebbeb500-e226-11ea-9ffa-919ca9a445c6.png)

**Comment by ukharley** [comment] 2020-08-19 12:26
Same for me.

**Comment by p0psicles** [comment] 2020-08-19 12:34
Okay, I'll fix it in develop. Might take some time before I release again. So if it really bothers you, switch to develop

**Comment by papampi** [comment] 2020-08-19 22:16
Thanks mate
Light theme is OK.
So anyone not willing to switch to develop version can switch to light theme.
