### ISSUE TITLE
Medusa has problems searching for and/or parsing show Garo: Vanishing Line

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#3218] opened 2017-11-02 14:09 UTC
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** develop
**OS:** windows/linux
**What you did:** To search for the series garo: Vanishing Line, which is released as "Garo - vanishing line"
**What happened:** Daily searches find the series, but can't match it up with a local series, as "Garo - vanishing line" is parsed as the show "Garo", with the episode title: 'vanishing line'
**What you expected:** To find the shows episode at least using nyaa.si.
**Logs:**
```
https://gist.github.com/p0psicles/4b73b24774818d2daa102ab400837a15
```

Guessit report:

```
python report_guessit.py "Garo - Vanishing Line - 04 (1280x720 HEVC2 AAC).mkv"
# guessit: 2.1.4  rebulk: 0.9.0
? Garo - Vanishing Line - 04 (1280x720 HEVC2 AAC).mkv
: title: Garo
  alias: Garo - Vanishing
  alternative_title: Vanishing
  other: LiNE
  episode: 4
  absolute_episode: 4
  screen_size: 720p
  release_group: HEVC2
  audio_codec: AAC
  container: mkv
  type: episode
  parsing_time: 0.085000038147
```

```
python report_guessit.py "[HorribleSubs] Garo - Vanishing Line - 04 [1080p].mkv"
# guessit: 2.1.4  rebulk: 0.9.0
? [HorribleSubs] Garo - Vanishing Line - 04 [1080p].mkv
: release_group: HorribleSubs
  title: Garo
  alias: Garo - Vanishing
  alternative_title: Vanishing
  other: LiNE
  episode: 4
  absolute_episode: 4
  screen_size: 1080p
  container: mkv
  type: episode
  parsing_time:  #0.0309998989105
```

@ratoaq2 can you take a look at this? I think guessit is parsing is wrongly.

**Comment by medariox** [comment] 2017-11-06 10:38
This is most probably a guessit issue caused by the `line` word in the episode title. It should be fixed upstream IMO.

**Comment by p0psicles** [comment] 2017-11-06 10:41
Do we match alias with the show title?

**Comment by medariox** [comment] 2017-11-06 10:53
Yeah, I think [it tries `alias` first](https://github.com/pymedusa/Medusa/blob/master/medusa/name_parser/parser.py#L349) and that's why it fails (expects `Garo` or `Garo - Vanishing Line`, but has `Garo - Vanishing`).

**Comment by p0psicles** [comment] 2017-11-06 11:07
That's easy enough to test. Just add `garo - vanishing` as scene exception.

**Closed** 2017-11-06 11:19 UTC
Labels: Guessit

**Comment by medariox** [comment] 2017-11-06 12:07
Sure, why not. But IMO the real issue here is that we use either `alias` (as first choice) or `title`, while we should probably use both for the show matching.

**Comment by p0psicles** [comment] 2017-11-06 13:11
Imo is the real issue the expected titles function. But I still need to profile that one.

But yes, title / alias should also be looked into. But I haven't seen any releases misparsed because of that one.
