### ISSUE TITLE
[ FEATURE ] Snatched Removes File Name in GUI

### ISSUE THREAD

**Issue by bnevets27** [pymedusa/Medusa#3012] opened 2017-08-15 02:02 UTC
When an episode gets snatched to upgrade the quality, the previous version file name of the episode gets removed from the GUI even though the old file still exists. 

Expected behavior is that the filename and size of the file should stay in the GUI until it gets replaced with the snatched file.

Attached is a screenshot which will hopefully make more sense. Medusa shows 21 of 22 files but the filenames aren't shown for the snatched/upgraded episodes.

http://i.imgur.com/S9vRK4c.jpg

**Comment by fernandog** [comment] 2017-08-15 18:18
It's by design as the current status is SNATCHED and this status doesn't have size or filename - even its on disk.

**Comment by p0psicles** [comment] 2017-08-22 11:07
@bnevets27 i agree with you that this is not how you would expect this to work. But the underlying quality system is not easily modified. So don't expect us to change this anytime soon. But it will be fixed eventually.

**Comment by labrys** [comment] 2017-12-09 18:04
Closing this as it has been added to the  #282 **Master Feature List** to track all feature requests.  Discussion specific to this feature can continue in this thread.

**Closed by labrys** 2017-12-09 18:04 UTC
Labels: Discussion, Feature request
