### ISSUE TITLE
[APP SUBMITTED]: AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by Aste88** [pymedusa/Medusa#4941] opened 2018-08-21 22:55 UTC
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.9.0-8-amd64-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@f5973b28465246e67465d7d86bdc8aa74d13e659
**Link to Log**: https://gist.github.com/fc5b49522882a34aa5c6c23b8ea16c36
### ERROR
<pre>
2018-08-21 22:50:35 ERROR    SHOWQUEUE-REFRESH :: [f5973b2] 71863: Error while refreshing show Lupin III. Error: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/show_queue.py#L686">medusa/show_queue.py</a>", line 686, in run
    self.show.refresh_dir()
  File "/app/medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/tv/series.py#L1718">medusa/tv/series.py</a>", line 1718, in refresh_dir
    self.load_episodes_from_dir()
  File "/app/medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/tv/series.py#L1006">medusa/tv/series.py</a>", line 1006, in load_episodes_from_dir
    parse_result = NameParser(series=self, try_indexers=True).parse(ep_file_name)
  File "/app/medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/name_parser/parser.py#L366">medusa/name_parser/parser.py</a>", line 366, in parse
    result = self._parse_string(name)
  File "/app/medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/name_parser/parser.py#L297">medusa/name_parser/parser.py</a>", line 297, in _parse_string
    new_episode_numbers, new_season_numbers, new_absolute_numbers = self._parse_anime(result)
  File "/app/medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/name_parser/parser.py#L189">medusa/name_parser/parser.py</a>", line 189, in _parse_anime
    scene_season = scene_exceptions.get_scene_exceptions_by_name(result.series_name)[0][1]
  File "/app/medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/scene_exceptions.py#L173">medusa/scene_exceptions.py</a>", line 173, in get_scene_exceptions_by_name
    if show_name.lower() in show_names:
AttributeError: 'NoneType' object has no attribute 'lower'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Aste88** [comment] 2018-08-21 22:57
Happening on file re-scan and full update on Lupin III and another show with season folder and episodes copied manually (named S**E**.mkv)

**Comment by Aste88** [comment] 2018-08-22 13:38
Fyi disabling the anime flag and re-scanning seems to fix it. Even after re-enabling the flag and adding a new episode it works.

**Comment by p0psicles** [comment] 2018-08-22 14:11
@medariox the guesit parse cant match a local show object. We should make sure we dont run the lower on a none object. But also look at the root cause here.

**Comment by p0psicles** [comment] 2018-08-25 19:17
Should be fixed in develop branch

**Closed by p0psicles** 2018-08-25 19:17 UTC
Labels: Bug, In progress
