### ISSUE TITLE
Error message "Failed parsing provider" & "list index out of range"

### ISSUE THREAD

**Issue by gers1978** [pymedusa/Medusa#8835] opened 2020-12-05 12:23 UTC
**Describe the bug**
Error message:

`2020-12-05 07:52:25 ERROR    SEARCHQUEUE-BACKLOG-260586 :: [Beyond-HD] :: [ce68da5] Failed parsing provider.
Traceback (most recent call last):
  File "/Applications/Medusa/medusa/providers/torrent/html/beyondhd.py", line 128, in parse
    download_url = urljoin(self.url, cells[2].find('a')['href'])
IndexError: list index out of range`

**Medusa (please complete the following information):**
 - OS: macOS Catalina 10.15,.7
 - Branch: master
 - Commit: ce68da57b3878591f77c21bb2acf28e6a58269fa
 - Python version: 3.8.5
 - Database version: 44.17

**Comment by medariox** [comment] 2020-12-05 12:29
Duplicate of https://github.com/pymedusa/Medusa/issues/8786 
We can't fix it until we have access to the provider.

**Closed by medariox** 2020-12-05 12:29 UTC
