### ISSUE TITLE
Season Folders option always set to true (checked) when adding new show

### ISSUE THREAD

**Issue by elrock** [pymedusa/Medusa#4186] opened 2018-05-11 22:18 UTC
Medusa: master branch, latest commit 77b2091
OS/Browser: OS X Chrome

Bug: When a new show is added, the Season Folders option is always set to true (checked) and user input is ignored.

**Comment by sharkykh** [comment] 2018-05-11 23:04
Duplicate of #4170.
#4172 most likely fixed that issue. Please wait for next release.

**Closed** 2018-05-11 23:05 UTC
Labels: Duplicate, Fixed
