### ISSUE TITLE
Backlog Overview Shows Episodes Airing Days in the Future

### ISSUE THREAD

**Issue by gmusgrave** [pymedusa/Medusa#4249] opened 2018-05-25 16:16 UTC
**Branch/Commit:**
Branch: master
Commit: 212cd1c8a350f2d5ca40f172ed5a227d9a5cb80f
Version: 0.2.4

**OS:**
Windows-7-6.1.7601-SP1

**What you did:**
Nothing. Medusa was just operating automatically.

**What happened:**
It is now 11am on Fri May 25

My Backlog Overview shows three shows in the future:
    The Fourth Estate Airdate: Sun, 27-05-2018, 12:00 AM
    Patrick Melrose Airdate: Sat, 26-05-2018, 12:00 AM
    Vida: Sat, 26-05-2018, 12:00 AM

I don't know if this is significant or not, but one thing they all have in common is airing at 12:00 AM. Could this be a bug?

**What you expected:**
That these shows would not appear in the Backlog Overview until after their airdates.

**Logs:**
```
2018-05-25 07:36:46 DEBUG    DAILYSEARCHER :: [212cd1c] Started updating network timezones
2018-05-25 07:36:47 DEBUG    DAILYSEARCHER :: [212cd1c] GET URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt [Status: 200]
2018-05-25 07:36:47 DEBUG    DAILYSEARCHER :: [212cd1c] User-Agent: Medusa/0.2.3 (Windows; 7; de851640-600f-11e8-80eb-4061868c11e8)
2018-05-25 07:36:47 DEBUG    DAILYSEARCHER :: [212cd1c] Finished updating network timezones
2018-05-25 07:36:47 DEBUG    DAILYSEARCHER :: [212cd1c] 347162: Formatting pattern: %SN - S%0SE01 - %EN -> The Fourth Estate - S01E01 - First 100 Days
2018-05-25 07:36:47 INFO     DAILYSEARCHER :: [212cd1c] Setting status (Wanted) for show airing today: The Fourth Estate - S01E01 - First 100 Days 
2018-05-25 07:36:47 DEBUG    DAILYSEARCHER :: [212cd1c] Looking up XEM scene mapping for show ID 338946 on tvdb
2018-05-25 07:36:48 DEBUG    DAILYSEARCHER :: [212cd1c] GET URL: http://thexem.de/map/havemap?origin=tvdb [Status: 200]
2018-05-25 07:36:48 DEBUG    DAILYSEARCHER :: [212cd1c] User-Agent: Medusa/0.2.3 (Windows; 7; de851640-600f-11e8-80eb-4061868c11e8)
2018-05-25 07:36:48 DEBUG    DAILYSEARCHER :: [212cd1c] No XEM data for show ID 338946 on tvdb
2018-05-25 07:36:48 DEBUG    DAILYSEARCHER :: [212cd1c] 338946: Formatting pattern: %SN - S%0SE03 - %EN -> Patrick Melrose - S01E03 - Some Hope
2018-05-25 07:36:48 INFO     DAILYSEARCHER :: [212cd1c] Setting status (Wanted) for show airing today: Patrick Melrose - S01E03 - Some Hope 
2018-05-25 07:36:48 DEBUG    DAILYSEARCHER :: [212cd1c] Looking up XEM scene mapping for show ID 340976 on tvdb
2018-05-25 07:36:48 DEBUG    POSTPROCESSOR :: [212cd1c] Starting new thread: POSTPROCESSOR
2018-05-25 07:36:48 DEBUG    POSTPROCESSOR :: [212cd1c] Processing path: D:\Downloads\SickRage
2018-05-25 07:36:48 DEBUG    POSTPROCESSOR :: [212cd1c] No processable items found in folder: D:\Downloads\SickRage
2018-05-25 07:36:48 INFO     POSTPROCESSOR :: [212cd1c] Successfully processed.
2018-05-25 07:36:48 DEBUG    DAILYSEARCHER :: [212cd1c] GET URL: http://thexem.de/map/havemap?origin=tvdb [Status: 200]
2018-05-25 07:36:48 DEBUG    DAILYSEARCHER :: [212cd1c] User-Agent: Medusa/0.2.3 (Windows; 7; de851640-600f-11e8-80eb-4061868c11e8)
2018-05-25 07:36:48 DEBUG    DAILYSEARCHER :: [212cd1c] No XEM data for show ID 340976 on tvdb
2018-05-25 07:36:49 DEBUG    DAILYSEARCHER :: [212cd1c] 340976: Formatting pattern: %SN - S%0SE04 - %EN -> Vida - S01E04 - Episode 4
2018-05-25 07:36:49 INFO     DAILYSEARCHER :: [212cd1c] Setting status (Wanted) for show airing today: Vida - S01E04 - Episode 4 
2018-05-25 07:36:49 DEBUG    DAILYSEARCHER :: [212cd1c] Transaction with 3 queries executed
2018-05-25 07:36:50 INFO     SEARCHQUEUE-DAILY-SEARCH :: [212cd1c] Beginning daily search for new episodes

```

**Comment by gmusgrave** [comment] 2018-06-01 14:17
This behaviour is definitely triggered by an air time of 12:00am.

Today (Fri Jun 1), two shows were added to my Backlog Overview: 
    Vida S01E05 –  airdate: Sun, 03-06-2018, 12:00 AM

    A Very English Scandal S01E03 –   airdate: Sun, 03-06-2018, 12:00 AM

I had just added this last show this morning.

I suspect it has something to do with the ambiguity surrounding the time of 12:00am. This is a vague time, and there is differing consensus as to whether this means "first thing in the morning," or "last thing at night." In either case, it doesn't explain why it's out by two days or so.

**Comment by gmusgrave** [comment] 2018-06-12 15:00
OK... I think I can safely confirm that this issue only happens when the airtime of a show is 12:00am.

I recently added two new shows, and they both appeared in the Backlog Overview about two days in advance of airing. They both had airtimes of 12:00am.

**Comment by OmgImAlexis** [comment] 2018-06-13 11:30
Just adding about the 24 hour time, there's no such thing as `24:00`. Time goes from `23:59:59` to `00:00:01`.

**Comment by gmusgrave** [comment] 2018-06-13 12:11
Sorry, but I must respectfully disagree. The seconds around midnight tick by as follows: 23:59:59, 24:00:00, 00:00:01. Or, because 24:00:00 can also be written as 00:00:00, 23:59:59, 00:00:00, 00:00:01. 

Refer to this link for a chart: http://militarytimechart.com/

**Comment by OmgImAlexis** [comment] 2018-06-13 14:49
I'm talking about python/js not military time.

**Comment by gmusgrave** [comment] 2018-06-13 15:14
So midnight doesn't exist in Python or JavaScript? That seems like a serious oversight. I would have expected it to be 00:00:00.

If this is true, then this could be the problem. A show with an airtime of midnight would have a non-existent time as far as the scripting language is concerned!

**Comment by labrys** [comment] 2018-06-22 22:39
@gmusgrave In python versions before 3.5, a time of midnight UTC (aka 0:00:00) evaluates to False.  That was intended by design and is documented in the python docs.  They did change their mind and as of python 3.5 it evaluates to True.  See https://bugs.python.org/issue13936

**Comment by labrys** [comment] 2018-06-22 22:45
@OmgImAlexis python still keeps time in 24-hour just like military time.  It uses 00:00:00 to represent Midnight (24:00:00 is not valid in python) but a python time of 00:00:00 if it is not timezone aware or if it is in UTC.  This was intended so that a time of 0 evaluates to False like most python objects generally do.  Time still ticks from 23:59:59 to 00:00:00 though.  Modern versions of python no longer have this issue.

**Comment by gmusgrave** [comment] 2019-01-30 12:51
Has this been fixed? 

It is still an issue that affects many shows. For me, it affects about 4 out of 10 new shows I add – especially those from streaming services such as Amazon, Netflix, or Hulu, where they often have airtimes of midnight.

These shows show up in the backlog overview days before their air date.

Is it not possible to fix?

**Comment by labrys** [comment] 2019-01-31 02:50
@gmusgrave It has not been fixed with Python 2.7.  Medusa has begun Python 3 compatibility.  I am not certain how far they have gotten, but if it is currently usable then you can run Medusa with Python 3.5 or greater and this bug would no longer be an issue.

**Comment by p0psicles** [comment] 2019-01-31 04:06
It is with the develop branch

**Comment by gmusgrave** [comment] 2019-10-11 12:52
@labrys Sorry, but I'm now running Python 3 (3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]), and this is still happening.

A new show I recently added is doing the same thing. **The Birch S01E01** airs on "Fri, 11-10-2019, 12:00 AM," and started appearing in my Backlog Overview list on Tuesday (Oct 8).

**Comment by narimanshariat** [comment] 2022-02-17 16:18
Seems to be an issue still. Doesn't anyone have a workaround for this?

**Comment by p0psicles** [comment] 2022-02-17 17:08
You'd have to provide a lot more details. I'd say open a new issue.

I'm closing this one.

**Closed by p0psicles** 2022-02-17 17:08 UTC
Labels: Bug, Priority: 3. Low

**Comment by gmusgrave** [comment] 2022-02-17 17:32
I'm the OP, and I believe that I provided rather a lot of detail about this issue (please read this thread from the beginning).  If you need more, please elaborate.

It has never been addressed or fixed, and is still an issue. I don't think it should be closed.

Thanks.
