### ISSUE TITLE
Special Characters In Episode Name Break Post Processing

### ISSUE THREAD

**Issue by AshleyAshes** [pymedusa/Medusa#3646] opened 2018-01-22 01:37 UTC
So basically, Medusa is trying to post process an anime episode, encounters a bunch of errors, seemingly deletes the file without moving it or processing it, and then reports mission accomplished:

https://pastebin.com/PK1jTjf1

It seems to THINK it moved it.  IT lists 'Recovery of an MMO Junkie 1x01 ? IRL, ? Online [1080p HDTV][Golumpa].mkv' in Medusa but the folder is actually empty.  If I hit 'Re-Scan Files' it stops thinking it has a file.  It thinks it successfully has it and what image, but no longer knows what the file name is.

My guess would be the episode's name:  ♀ IRL, ♂ Online

My guess is that the sex symbols are breaking it.

https://www.thetvdb.com/?tab=episode&seriesid=332771&seasonid=723305&id=6235587&lid=7

**Comment by AshleyAshes** [comment] 2018-03-27 22:11
This problem persists and remains unaddressed.  All episodes of Magical Girl Ore contain a star character in their names and Medusa fails to process them correctly.

https://pastebin.com/rZcV7fsG

The critical flaw is seen here:
`UnicodeEncodeError: 'charmap' codec can't encode character u'\u2606' in position 38: character maps to <undefined>
2018-03-27 18:06:10 ERROR    Thread-32 :: [7b9111e] BraceMessage string formatting failed. Using representation instead.`

The real problem in the log is where it states "Successfully processed.".  It has not been successfully process, it discarded the file while convincing itself that it successfully processed it.

The problem also occurs with DARLING in the FRANXX episode 8 as the episode's title is 'Boys ✕ Girls'.

**Comment by adamgoldberg** [comment] 2018-07-02 12:21
I think this is a similar problem (below).

The biggest problem is that post-processing fails silently - a file with this issue will never be processed, and if you attempt to manually post-process, you end up with a nearly blank page and hung there.  

It'd be nice if Medusa would do something helpful, either emailing to say there's an issue, or (better) replacing the bad characters with SOMETHING (underscore, hyphen, something) so that it'd process well.

`2018-07-02 08:05:40 ERROR    POSTPROCESSOR :: [c65ca26] Exception generated: 'ascii' codec can't encode character u'\xf1' in position 82: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/share/Medusa/Medusa/medusa/scheduler.py", line 93, in run
    self.action.run(self.force)
  File "/usr/local/share/Medusa/Medusa/medusa/auto_post_processor.py", line 58, in run
    process_tv.ProcessResult(app.TV_DOWNLOAD_DIR, app.PROCESS_METHOD).process(force=force)
  File "/usr/local/share/Medusa/Medusa/medusa/process_tv.py", line 149, in process
    ignore_subs=ignore_subs)
  File "/usr/local/share/Medusa/Medusa/medusa/process_tv.py", line 337, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/usr/local/share/Medusa/Medusa/medusa/process_tv.py", line 538, in process_media
    self.result = processor.process()
  File "/usr/local/share/Medusa/Medusa/medusa/post_processor.py", line 1223, in process
    app.MOVE_ASSOCIATED_FILES, app.USE_SUBTITLES and ep_obj.series.subtitles)
  File "/usr/local/share/Medusa/Medusa/medusa/post_processor.py", line 508, in post_process_action
    action=action, subtitle_action=subtitle_action, subtitles=subtitles)
  File "/usr/local/share/Medusa/Medusa/medusa/post_processor.py", line 451, in _combined_file_operation
    action(cur_associated_file, new_file_path)
  File "/usr/local/share/Medusa/Medusa/medusa/post_processor.py", line 476, in copy
    helpers.copy_file(cur_file_path, new_file_path)
  File "/usr/local/share/Medusa/Medusa/medusa/helpers/__init__.py", line 286, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "/usr/local/share/Medusa/Medusa/lib/shutil_custom/__init__.py", line 42, in copyfile_custom
    fout = os.open(dst, WRITE_FLAGS)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 82: ordinal not in range(128)
`

**Comment by sharkykh** [comment] 2018-07-02 18:09
**I'm unable to reproduce** this issue with the [same episode](https://www.thetvdb.com/series/recovery-of-an-mmo-junkie/episodes/6235587).
Not on current `develop` (e308ef34cf3911a78fef2fc1de3b32a7a100eaa6) or current `master` (c65ca2607fae74405dcceaaf8c02f3d29d0313ea).
I'm on Windows 7 with a `he_IL.cp1255` locale.

**Comment by sharkykh** [comment] 2018-07-02 18:20
@AshleyAshes @adamgoldberg 
Could you please provide your environments' information, visible on the Help & Info page:
```
OS: Windows-7-6.1.7601-SP1
Locale: he_IL.cp1255
```

**Comment by AshleyAshes** [comment] 2018-07-02 19:00
OS:  Windows-10-10.0.17134
Locale:  en_US.cp1252

**Comment by adamgoldberg** [comment] 2018-07-02 21:40
OS: | FreeBSD-10.3-STABLE-amd64-64bit-ELF
Locale: | Unknown.Unknown

**Comment by AshleyAshes** [comment] 2018-07-02 22:32
Actually, I might be out of date.  I've not seen updates in a while and now I see an error for updates 'Error: No branches found.'  So it's not looking at ANY branches for updates... Maybe this was fixed but in the meanwhile my own ability to update broke

**Comment by sharkykh** [comment] 2018-07-02 23:23
@adamgoldberg 
Your system locale isn't set.
Please attempt this fix: [FAQ: I have problems with special characters (é etc.) What can i do?](https://github.com/pymedusa/Medusa/wiki/FAQ's-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

@AshleyAshes 
1. What version or commit hash show up on Help & Info?
2. In order to help you please enable debug logging, click "Check for updates" and then get the debug logs from the View Logs page (select level: DEBUG)

**Comment by AshleyAshes** [comment] 2018-07-02 23:34
0.1.22  I actually found the git config file filled with nothing but null characters, so it hadn't been hitting Github successfully for months I just never noticed.  I'm working on getting up to date, but yeah, it seems that while this was a problem, it's likely been fixed, but I had a secondary problem of my Medusa not updating.

**Comment by sharkykh** [comment] 2018-07-02 23:49
That's usually caused by a system shutdown while git is doing something.
Anyway, usually all you need in `.git/config` is this:
```ini
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
[remote "origin"]
	url = https://github.com/pymedusa/Medusa.git
	pushurl = https://github.com/pymedusa/Medusa.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

**Comment by adamgoldberg** [comment] 2018-07-04 21:33
Ok, I have my locale set properly, and I'll report back if it happens again.

`OS: | FreeBSD-10.3-STABLE-amd64-64bit-ELF
Locale: | en_US.UTF-8
`

**Comment by sharkykh** [comment] 2018-07-07 14:22
I'll close this for now, as I believe the issue is fixed.
If the error comes back, just comment here again.

**Closed by sharkykh** 2018-07-07 14:22 UTC
Labels: Support
