### ISSUE TITLE
[APP SUBMITTED]: OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by klauf** [pymedusa/Medusa#6382] opened 2019-03-19 13:13 UTC
### INFO
**Python Version**: `3.6.4 (default, Jan  5 2018, 02:13:53) [GCC 7.2.0]`
**Operating System**: `Linux-4.14.78-4-osmc-armv7l-with-debian-buster-sid`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@94fae847b6e7e443d74c59cb11bdbd37c464b363
**Link to Log**: https://gist.github.com/0a785760fbfe96bcaaad7332395ea5a4
### ERROR
<pre>
2019-03-18 19:35:11 ERROR    FINDSUBTITLES :: [94fae84] Environment error: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/94fae847b6e7e443d74c59cb11bdbd37c464b363/medusa/scheduler.py#L93">medusa/scheduler.py</a>", line 93, in run
    self.action.run(self.force)
  File "/opt/medusa/<a href="../blob/94fae847b6e7e443d74c59cb11bdbd37c464b363/medusa/subtitles.py#L1062">medusa/subtitles.py</a>", line 1062, in run
    episode_object.download_subtitles()
  File "/opt/medusa/<a href="../blob/94fae847b6e7e443d74c59cb11bdbd37c464b363/medusa/tv/episode.py#L492">medusa/tv/episode.py</a>", line 492, in download_subtitles
    new_subtitles = subtitles.download_subtitles(self, lang=lang)
  File "/opt/medusa/<a href="../blob/94fae847b6e7e443d74c59cb11bdbd37c464b363/medusa/subtitles.py#L420">medusa/subtitles.py</a>", line 420, in download_subtitles
    embedded_subtitles=embedded_subtitles, release_name=release_name)
  File "/opt/medusa/<a href="../blob/94fae847b6e7e443d74c59cb11bdbd37c464b363/medusa/subtitles.py#L723">medusa/subtitles.py</a>", line 723, in get_video
    video = scan_video(video_path)
  File "/opt/medusa/<a href="../blob/94fae847b6e7e443d74c59cb11bdbd37c464b363/ext/subliminal/core.py#L436">ext/subliminal/core.py</a>", line 436, in scan_video
    video.hashes['opensubtitles'] = hash_opensubtitles(path)
  File "/opt/medusa/<a href="../blob/94fae847b6e7e443d74c59cb11bdbd37c464b363/ext/subliminal/utils.py#L24">ext/subliminal/utils.py</a>", line 24, in hash_opensubtitles
    filebuffer = f.read(bytesize)
OSError: [Errno 5] Input/output error
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment] 2019-03-19 18:08
Duplicate of https://github.com/pymedusa/Medusa/issues/6381

**Closed by medariox** 2019-03-19 18:08 UTC
Labels: triage

**Comment by klauf** [comment] 2019-03-19 18:27
Sorry, didn't know medusa posts automatically on Github! Great feature btw. Thanks for the feedback.
