### ISSUE TITLE
2017-06-04 22:46:00 WARNING  Thread-16 :: [2a21fd4] Invalid Github credentials. Please check your Github credentials in Medusa settings.

### ISSUE THREAD

**Issue by ward0** [pymedusa/Medusa#2860] opened 2017-06-04 20:47 UTC
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

 Medusa Info:	Branch: master
Commit: 2a21fd430ad688cd633f8929d2fb90cd78362e9e
Version: v0.1.12
Database: 43.8
 Python Version:	2.7.13 (default, Dec 18 2016, 21:23:50) [GCC 4.6.4]
 SSL Version:	OpenSSL 1.0.2j 26 Sep 2016
 OS:	Linux-3.2.40-armv7l-with-glibc2.4
 Locale:	en_US.UTF-8
**Logs:**
```
2017-06-04 22:46:00 WARNING  Thread-16 :: [2a21fd4] Invalid Github credentials. Please check your Github credentials in Medusa settings.
```

I double checked my github settings..

**Comment by fernandog** [comment] 2017-06-06 15:52
@ward0 which logging method are you using? token or pass?

**Comment by ward0** [comment] 2017-06-07 07:31
@fernandog pass

encryption is default setting, i haven't changed it yet.

**Comment by fernandog** [comment] 2017-06-07 09:07
@ward0 open config file and make sure user/pass is correct there

**Comment by fernandog** [comment] 2017-06-13 17:20
@ward0 all good?

**Comment by ward0** [comment] 2017-06-14 06:58
@fernandog: Ah, sorry i haven't tested yet.. I will let you know tonight.

**Comment by ward0** [comment] 2017-06-14 19:45
@fernandog : i just checked the config.ini .. its correct.

**Comment by fernandog** [comment] 2017-06-14 20:33
@ward0 can you try with token?

**Comment by ward0** [comment] 2017-06-15 06:24
@fernandog i will try with token and let you know.

**Comment by ward0** [comment] 2017-06-15 20:10
seems to work, i didn't get an error and i submitted a error to you guys tonight( you should see it)

**Comment by fernandog** [comment] 2017-06-16 17:47
i can't reproduce this. working here with pass and token. 
Close it for now.

**Closed by fernandog** 2017-06-16 17:47 UTC
