### ISSUE TITLE
[APP SUBMITTED]: HTTPError: 500 Server Error: Internal Server Error for url: https://api.themoviedb.org/3/tv/changes?api_key=**********&start_date=2017-09-05&end_date=2017-09-19&page=6

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#3086] opened 2017-09-10 06:14 UTC
### INFO
**Python Version**: `2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.15063`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@1d0d7ea39cddd8b0a40f0dcec26dfa2eeac724fd
**Link to Log**: https://gist.github.com/deb53a51749635a867a69fca379edfce
### ERROR
<pre>
2017-09-10 03:02:14 ERROR    SHOWUPDATER :: [1d0d7ea] Problem running show_updater, Indexer TMDB seems to be having issues while trying to get updates for show The Corner. Cause: 500 Server Error: Internal Server Error for url: https://api.themoviedb.org/3/tv/changes?api_key=**********&start_date=2017-09-05&end_date=2017-09-19&page=6.
Traceback (most recent call last):
  File "C:\Medusa\medusa\show_updater.py", line 88, in run
    last_update, update_max_weeks
  File "C:\Medusa\medusa\indexers\tmdb\tmdb.py", line 523, in get_last_updated_series
    total_updates += self._get_all_updates(search_from.strftime('%Y-%m-%d'), search_until.strftime('%Y-%m-%d'))
  File "C:\Medusa\medusa\indexers\tmdb\tmdb.py", line 495, in _get_all_updates
    updates = self.tmdb.Changes().tv(start_date=start_date, end_date=end_date, page=page)
  File "C:\Medusa\lib\tmdbsimple\changes.py", line 79, in tv
    response = self._GET(path, kwargs)
  File "C:\Medusa\lib\tmdbsimple\base.py", line 87, in _GET
    return self._request('GET', path, params=params)
  File "C:\Medusa\lib\tmdbsimple\base.py", line 82, in _request
    response.raise_for_status()
  File "C:\Medusa\lib\requests\models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: https://api.themoviedb.org/3/tv/changes?api_key=**********&start_date=2017-09-05&end_date=2017-09-19&page=6
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment] 2017-09-11 13:49
Duplicate of: https://github.com/pymedusa/Medusa/issues/3072

**Closed by medariox** 2017-09-11 13:49 UTC
