### ISSUE TITLE
"Post Process" and "Proper Finder" crash

### ISSUE THREAD

**Issue by annomatik** [pymedusa/Medusa#6644] opened 2019-05-04 15:39 UTC
**Describe the bug**
Hi! After a while, both "Post Process" and "Proper Finder" are shown as "Alive = False" in the Scheduler (Tools --> Server Status), Medusa then (of course) does not take the downloaded files from the download directory and does not put them into their proper tv show folder.

Restarting Medusa helps, but not permanently.

Currently, the "Proper Finder" has "Alive = False", the "Post Process" is still running.

**To Reproduce**
Don't know.

**Expected behavior**
Alive should always be true for Post Process and Proper Finder.

**Medusa (please complete the following information):**
 - OS: Raspbian Stretch
 - Branch: master
 - Commit: f46bfacf8763204fbde4f26a5916095371d494d1 

**Logs:**
this is what I found with a grep, if you need more, please tell.
$ grep ERROR *
application.log:2019-05-04 14:43:25 ERROR    FINDPROPERS :: [Torrenting] :: [f46bfac] Exception generated: local variable 'torrent_rows' referenced before assignment
application.log.2:2019-05-01 12:27:25 ERROR    FINDPROPERS :: [Torrenting] :: [f46bfac] Exception generated: local variable 'torrent_rows' referenced before assignment
application.log.5:2019-04-28 02:03:56 ERROR    SHOWQUEUE-REFRESH :: [f46bfac] 80379: Error while refreshing show The Big Bang Theory. Error: Indexer TMDB is unavailable at this time. Cause: 502 Server Error: Bad Gateway for url: https://api.themoviedb.org/3/configuration?api_key=**********
application.log.5:2019-04-28 02:14:12 ERROR    SHOWQUEUE-REFRESH :: [f46bfac] 324068: Error while refreshing show Mama June: From Not to Hot. Error: Indexer TMDB is unavailable at this time. Cause: 502 Server Error: Bad Gateway for url: https://api.themoviedb.org/3/configuration?api_key=**********

**Comment by medariox** [comment] 2019-05-04 15:47
It's caused by Torrenting provider being offline. Already fixed in develop: https://github.com/pymedusa/Medusa/pull/6430

Disable Torrenting provider until the next release.

**Closed by medariox** 2019-05-04 15:47 UTC
Labels: triage

**Comment by annomatik** [comment] 2019-05-04 16:23
Thanks!
