### ISSUE TITLE
setting eps to downloaded uses wrong quality

### ISSUE THREAD

**Issue by udochrist** [pymedusa/Medusa#4329] opened 2018-06-10 16:33 UTC
```
Medusa Info:
Branch: master
Commit: c65ca2607fae74405dcceaaf8c02f3d29d0313ea
Version: v0.2.5
Database: 44.9
Python Version: 2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]
```

after upgrade to latest version medusa started to re-download a previous d/l'ed shows setting all ep's to snatched. i stopped the d/ls and set the status in medusa back to downloaded.

now all ep's are suddenly marked "sd" from "720-web-dl" before. show was/is set to HD720p.
i cannot set the quality back to 720p on the ep's and medusa is redownload all ep's again and again.
how can i set the quality of files back to their correct value?

**Comment by p0psicles** [comment] 2018-06-10 16:49
Did you try the option rescan files?

**Comment by udochrist** [comment] 2018-06-10 17:20
Yes. Multiple times refresh from disk as well as set to downloaded. 
According to mkvinfo my current files are not hd. I don‘t understand where Medusa gets the information about the quality from.

**Comment by p0psicles** [comment] 2018-06-10 17:32
Do you maybe have debug logging already enabled? Could you else enable, refresh from disk and share logs

**Comment by medariox** [comment] 2018-06-10 17:53
What are your these files named like?

**Comment by udochrist** [comment] 2018-06-10 17:54
this is the refresh log. I've not copied all the logs. they are all the same except the ep names.
Interestingly enough medusa has now already tried to d/l all ep's over and over (with fails) and nothing more to download. now the setting of "Downloaded" status has put them back to 720 web-dl from snatched 720p-web-dl. my file names do not contain the quality currently.

``` 
2018-06-10 18:07:12 DEBUG    Thread_9 :: [c65ca26] 341704: Queueing show refresh for ShowName
2018-06-10 18:07:13 INFO     SHOWQUEUE-REFRESH :: [c65ca26] 341704: Performing refresh on ShowName
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: Loading all episodes from the show directory: /volume1/Media/TV Shows/ShowName
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: Found files: [u'/volume1/Media/TV Shows/ShowName/ShowName - s01e06 - Name.mkv', u'/volume1/Media/TV Shows/ShowName/ShowName - s01e01 - Name.mkv', u'/volume1/Media/TV Shows/ShowName/ShowName - s01e04 - Name.mkv', u'/volume1/Media/TV Shows/ShowName/ShowName - s01e05 - Name.mkv', u'/volume1/Media/TV Shows/ShowName/ShowName - s01e02 - Name.mkv', u"/volume1/Media/TV Shows/ShowName/ShowName - s01e07 - Name.mkv", u'/volume1/Media/TV Shows/ShowName/ShowName - s01e08 - Name’, u'/volume1/Media/TV Shows/ShowName/ShowName - s01e03 - Name.mkv']
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: Creating episode from: /volume1/Media/TV Shows/ShowName/ShowName - s01e06 - Name.mkv
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: Creating episode object from /volume1/Media/TV Shows/ShowName/ShowName - s01e06 - Name.mkv
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Using cached parse result for /volume1/Media/TV Shows/ShowName/ShowName - s01e06 - Name.mkv
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: /volume1/Media/TV Shows/ShowName/ShowName - s01e06 - Name.mkv parsed to ShowName S01E06
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: Setter sets location to /volume1/Media/TV Shows/ShowName/ShowName - s01e06 - Name.mkv
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] ShowName: Not changing current status 'Downloaded' or quality 'SDTV' based on file: /volume1/Media/TV Shows/ShowName/ShowName - s01e06 - Name.mkv
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Transaction with 1 queries executed
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Using cached parse result for ShowName - s01e06 - Name
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: Creating episode from: /volume1/Media/TV Shows/ShowName/ShowName - s01e01 - Name.mkv
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: Creating episode object from /volume1/Media/TV Shows/ShowName/ShowName - s01e01 - Name.mkv
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Using cached parse result for /volume1/Media/TV Shows/ShowName/ShowName - s01e01 - Name.mkv
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: /volume1/Media/TV Shows/ShowName/ShowName - s01e01 - Name.mkv parsed to ShowName S01E01
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: Setter sets location to /volume1/Media/TV Shows/ShowName/ShowName - s01e01 - Name.mkv
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] ShowName: Not changing current status 'Downloaded' or quality '720p WEB-DL' based on file: /volume1/Media/TV Shows/ShowName/ShowName - s01e01 - Name.mkv
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Transaction with 1 queries executed
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Using cached parse result for ShowName - s01e01 - Name
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: Creating episode from: /volume1/Media/TV Shows/ShowName/ShowName - s01e04 - Name.mkv
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: Creating episode object from /volume1/Media/TV Shows/ShowName/ShowName - s01e04 - Name.mkv
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Using cached parse result for /volume1/Media/TV Shows/ShowName/ShowName - s01e04 - Name.mkv
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: /volume1/Media/TV Shows/ShowName/ShowName - s01e04 - Name.mkv parsed to ShowName S01E04
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: Setter sets location to /volume1/Media/TV Shows/ShowName/ShowName - s01e04 - Name.mkv
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] ShowName: Not changing current status 'Downloaded' or quality 'SDTV' based on file: /volume1/Media/TV Shows/ShowName/ShowName - s01e04 - Name.mkv
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Transaction with 1 queries executed
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Using cached parse result for ShowName - s01e04 - Name
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: Creating episode from: /volume1/Media/TV Shows/ShowName/ShowName - s01e05 - Name.mkv
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: Creating episode object from /volume1/Media/TV Shows/ShowName/ShowName - s01e05 - Name.mkv
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Using cached parse result for /volume1/Media/TV Shows/ShowName/ShowName - s01e05 - Name.mkv
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: /volume1/Media/TV Shows/ShowName/ShowName - s01e05 - Name.mkv parsed to ShowName S01E05
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: Setter sets location to /volume1/Media/TV Shows/ShowName/ShowName - s01e05 - Name.mkv
2018-06-10 18:07:13 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] ShowName: Not changing current status 'Downloaded' or quality 'SDTV' based on file: /volume1/Media/TV Shows/ShowName/ShowName - s01e05 - Name.mkv
```

**Comment by udochrist** [comment] 2018-06-10 18:53
Here you are: The ep was 720-web-dl before renaming the ep file. a rescan has set that the quality back to SD-TV.

``` 
2018-06-10 20:47:30 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Parsed ShowName - s01e02 - EPName into title: ShowName, season: 1, episode: [2], episode_title: EPName, type: episode, parsing_time: 0.103418111801, total_time: 0.105278968811, absolute_episode: [], quality: Unknown
2018-06-10 20:47:30 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Matched release ShowName - s01e02 - EPName to a series in your database: ShowName
2018-06-10 20:47:30 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Transaction with 1 queries executed
**2018-06-10 20:47:30 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] ShowName: Setting the status from 'Downloaded' to 'Downloaded' and quality '720p WEB-DL' to 'SDTV' based on file: /volume1/Media/TV Shows/ShowName/Season 01/ShowName - s01e02 - EPName.mkv**
2018-06-10 20:47:30 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Skipping rule language since property is already present
2018-06-10 20:47:30 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Handling subtitle track
2018-06-10 20:47:30 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Skipping rule language since property is already present
2018-06-10 20:47:30 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Handling subtitle track
2018-06-10 20:47:30 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Skipping rule language since property is already present
2018-06-10 20:47:30 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Handling subtitle track
2018-06-10 20:47:30 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Skipping rule language since property is already present
2018-06-10 20:47:30 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Handling subtitle track
2018-06-10 20:47:30 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Skipping rule language since property is already present
2018-06-10 20:47:30 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Handling subtitle track
2018-06-10 20:47:30 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Skipping rule language since property is already present
2018-06-10 20:47:30 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Handling audio track
2018-06-10 20:47:30 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Skipping rule language since property is already present
2018-06-10 20:47:30 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Handling audio track
2018-06-10 20:47:30 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Skipping rule language since property is already present
2018-06-10 20:47:30 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Handling video track
2018-06-10 20:47:30 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Handling general track
2018-06-10 20:47:29 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] ShowName: The old episode had a different file associated with it, re-checking the quality using the new filename /volume1/Media/TV Shows/ShowName/Season 01/ShowName - s01e02 - EPName.mkv
2018-06-10 20:47:29 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: Setter sets location to /volume1/Media/TV Shows/ShowName/Season 01/ShowName - s01e02 - EPName.mkv
2018-06-10 20:47:29 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: /volume1/Media/TV Shows/ShowName/Season 01/ShowName - s01e02 - EPName.mkv parsed to ShowName S01E02
2018-06-10 20:47:29 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Parsed /volume1/Media/TV Shows/ShowName/Season 01/ShowName - s01e02 - EPName.mkv into title: ShowName, season: 1, episode: [2], episode_title: EPName, container: mkv, mimetype: video/x-matroska, type: episode, parsing_time: 0.146595954895, total_time: 0.147378921509, absolute_episode: [], quality: Unknown
2018-06-10 20:47:29 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] Matched release /volume1/Media/TV Shows/ShowName/Season 01/ShowName - s01e02 - EPName.mkv to a series in your database: ShowName
2018-06-10 20:47:29 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: Creating episode object from /volume1/Media/TV Shows/ShowName/Season 01/ShowName - s01e02 - EPName.mkv
2018-06-10 20:47:29 DEBUG    SHOWQUEUE-REFRESH :: [c65ca26] 341704: Creating episode from: /volume1/Media/TV Shows/ShowName/Season 01/ShowName - s01e02 - EPName.mkv
```

**Comment by udochrist** [comment] 2018-06-10 19:00
and the worst about this: i have to snatch an ep with the desired quality so marking the ep as downloaded sets it back to the correct quality.

i think ep quality management still needs some serious love in future versions.

do i btw remember correctly that earlier versions of medusa where capable of setting the quality with marking an ep "downloaded <quality>" or am i dreaming? if so, whats the rationale/idea behind the change if i might ask?

**Comment by medariox** [comment] 2018-06-10 19:08
If you remove the quality from the file name you have to deal with the fact that Medusa will need to scan the file to determine it's quality, because that will be the only way to find out the true quality of the file. Evidently the files you have there are not really 720p, but a lower resolution. If you post the output of mkvinfo we can see if the detected quality is correct or not.

**Comment by udochrist** [comment] 2018-06-10 19:12
i've simply been following the Plex naming scheme.
the file was snatched and d/l'ed as 720p web-dl by medusa earlier.

mkvinfo gives
``` 
|+ Segment tracks
| + A track
|  + Track number: 1 (track ID for mkvmerge & mkvextract: 0)
|  + Track UID: 1
|  + Track type: video
|  + Lacing flag: 0
|  + MinCache: 1
|  + Codec ID: V_MPEG4/ISO/AVC
|  + CodecPrivate, length 43 (h.264 profile: High @L4.1)
|  + Default duration: 40.000ms (25.000 frames/fields per second for a video track)
|  + Language: dan
|  + Video track
|   + Pixel width: 1280
|   + Pixel height: 640
|   + Display width: 1280
|   + Display height: 640
|   + Interlaced: 0
```

**Comment by medariox** [comment] 2018-06-10 19:35
Sadly these files are not 720p as the minimum height would need to be 720. If you really want to keep them as 720p you will have to include the quality in their name. This can be easily achieved by using a custom naming scheme, e.g.: `%Sx%0E - %QN - %EN`.

**Comment by udochrist** [comment] 2018-06-10 19:51
ok. thats a 2:1 aspect ratio not 16:9. 

Looking at a cheat sheet this still would be named 720p. http://blog.chameleondg.com/post/111891072017/resolution-aspect-ratio-cheat-sheet

```
720p
Frame Aspect Ratio  /  Resolution (Square Pixels 1.0)

1.33:1 (4:3)  /  1280x962
1.66:1 (5:3)  /  1280x768
1.77:1 (16:9)  /  1280x720
1.85:1  /  1280x692
2:1  /  1280x640
2.35:1  /  1280x545
2.37:1 (RED Wide)  /  1280x540
2.39:1 (referred to as 2.40)  /  1280x536
2.44  /  1280x525
```

**Comment by medariox** [comment] 2018-06-10 20:36
That sheet is surely helpful. Seems like we currently only support 16:9. Do you have many shows that are 2:1. Eventually, this is the code that would need to be changed: https://github.com/pymedusa/Medusa/blob/master/medusa/common.py#L428-L438

**Comment by udochrist** [comment] 2018-06-10 21:22
i don't actually know. i would have to check quite some files to get a statistic of used formats.
for the standard 1080p and 720p (basically everything except the CINEMA 2k &4k formats) it might just make sense to focus on widths, not heights when looking at pixels. for 720p the width should always be 1280 while the height will be adjusted to 720p depending upon the aspect ratio.

**Comment by udochrist** [comment] 2018-06-11 05:33
As i‘ve feared Medusa has started to re-download over 100 eps from various shows after upgrading to the latest version. I cannot make it stop since Incan no longer set the eps to downloaded from the manage status page. 

This is really annoying. Why can’t Medusa honor that an episode is downloaded with the correct quality and simply keep it as it is? The quality shown on the GUI and stored in the dB are perfectly fine.

I‘m rather sick when software assumes it is smarter than the people using it!

**Comment by medariox** [comment] 2018-06-11 11:28
I strongly believe that something went wrong with your upgrade. Please follow this instructions and see if it helps: https://github.com/pymedusa/Medusa/issues/4335#issuecomment-396208650

**Comment by nucshuco** [comment] 2018-06-11 14:50
I woke up this morning and Medusa was re-downloading over 300 episodes. What a mess.

**Comment by MotleyC** [comment] 2018-06-11 21:41
You are going to need to use SQLLiteDb Browser to manually fix it. I had an episode download that was 1080p and it was set to unknown. I had to force it in to fix it.

**Comment by HPMSGEN8** [comment] 2018-06-15 11:29
Hi All, I have just installed clean version of the latest master and i have the same issue. I added 1 show to test and it showed up as Archived SD when it is a 720p WEB-DL.

**Comment by medariox** [comment] 2018-06-15 11:41
How did you "change it" to HD-720p? Did you rescan the show?

**Comment by HPMSGEN8** [comment] 2018-06-15 12:28
@medariox I manually changed it as it was Unknown, SDTV. But the files still show as SDTV even if i change them to Downloaded.

**Comment by HPMSGEN8** [comment] 2018-06-15 12:37
[https://imgur.com/a/3P1qx2s](url)

**Comment by medariox** [comment] 2018-06-15 13:46
https://github.com/pymedusa/Medusa/issues/4329#issuecomment-396075638

**Comment by HPMSGEN8** [comment] 2018-06-15 14:52
@medariox so this means medusa needs to support more file versions / codex ?

**Comment by udochrist** [comment] 2018-06-15 15:10
I think on postprocessing the quality is determined by the file name snatched whereas upon loading from disk Medusa checks the file contents for width and height unless you have a quality in the file name pattern. The file based check is a tad limited right now if I understand the above linked code correct...

**Comment by udochrist** [comment] 2018-06-15 15:12
Once the ep is snatched the quality is already stored from the file name. Hence the difference when setting to downloaded. (From how my tests show the behavior)

**Comment by medariox** [comment] 2018-06-15 15:49
```
safe.s01e01.720p.webrip.x264-strife.mkv
Width : 1 280 pixels
Height : 534 pixels
```
Same as above.

**Comment by HPMSGEN8** [comment] 2018-06-15 17:06
@udochrist Ok so then i should re-name all my files to %Sx%0E - %QN - %EN ? if i want MedUSA to work correctly from on disk ?

**Comment by udochrist** [comment] 2018-06-15 17:19
I am now using „Season %0S/%SN - s%0Se%0E - %EN [%QN]“ which is working for me.

**Comment by HPMSGEN8** [comment] 2018-06-15 18:48
@udochrist Can you paste an Example of an file name plz 

@medariox is there any way to set this up with SQL so it keeps track of what is what. Then i can migrate from any Fork to medusa or from medusa to any fork ?

**Comment by factorion** [comment] 2018-06-16 16:43
You used to be able to set the type along with choosing downloaded.  I understand wanting to automate this, but also removing the ability to select manually seems to be a bad idea.  You're adding in automation and not giving an option to fix it if it doesn't work correctly.

**Comment by p0psicles** [comment] 2018-06-16 17:43
The combined quality / status values where causing other issues. So thats why we decided to get rid of it.

It would not be allot of work to add a separate 'overwrite administrative quality' feature. But we need to think about if thats a workaround or really adressing the root cause issue here.

**Comment by HPMSGEN8** [comment] 2018-06-16 18:00
So if there is 100 Shows with SDTV, HDTV, 720p and 1080p and u want to move it to MEDUSA you cannot right now due to this issue.

So cannot this be integrated into SQL like MariaDB 5 / 10 ?  That way it will use the Show info in the DB instead of MEDUSA deciding.

When you download a show it will use what you set it to like normal.

The issue is only with shows that exist right now that i see.

**Comment by medariox** [comment] 2018-06-16 18:56
The shows you import are required to have a quality in the name (e.g. 720p) or they need to have the proper resolution (e.g. min. width of 720 - this will improved in the future to allow other aspect ratios besides 16:9) to be detected correctly. Manually selecting an incorrect quality is not allowed anymore I'm afraid.

**Comment by factorion** [comment] 2018-06-16 19:58
This seems to be a decision that doesn't really solve what you're talking about while removing a lot of functionality.

You're saying it's a problem that people give videos an incorrect quality so you detect it.  Except your detection looks in the filename which can easily be changed.  In fact, importing into medusa now seems to REQUIRE putting it in the filename where someone can still easily put an incorrect quality as you say.
Regarding detection, you seem to imply it will look at resolution, but what else?  If it sees it's 720p, does it know if it's from a web-dl or a blu-ray or just HDTV?  Will it offer the ability to upgrade from one 720p option to another if it can't detect the difference anymore?
For all the existing medusa users and their databases, what happens with all the files currently in there that don't have the quality in the filename?  For any show they rescan, will it lose that knowledge and then decide that it needs to redownload the show?

**Comment by medariox** [comment] 2018-06-16 20:06
@factorion 
No, as I wrote, correct qualities will be detected from the file itself and not from the name in case they don't contain quality information. Yes, you can still "fake" the quality by adding the quality information you wish to the file name.

Medusa won't refresh files that are unchanged, so this doesn't have any influence on files that are already present.

**Comment by HPMSGEN8** [comment] 2018-06-17 04:53
@medariox i have tried as per the above but still it add it as unknown sdtv and the episodes show as archived SDTV.

So how else can i get this to work please.

**Comment by factorion** [comment] 2018-06-17 15:56
@p0psicles , can you please put in the feature you were talking about?  Having partly functional automation and the only way to fix it is with filename change doesn't seem like a useful feature.  Right now any new users to Medusa with an existing library need to go through their entire library and add the quality to the filenames.  I've already tested three different qualities and they all came up as unknown.

4:3 480p
4:3 720p
16:9 1080p

I know supposedly only 16:9 detection works, but for me even that failed.

**Comment by medariox** [comment] 2018-06-17 23:17
@HPMSGEN8 
What have you tried exactly? Explain what you did, what happened and what you expected to happen instead.

**Comment by HPMSGEN8** [comment] 2018-06-18 05:30
@medariox 

Right, I installed Medusa on my NAS and set up it like i would do for any fork.

Then i selected - Add Existing Show, Selected the show SAFE and added it. This added the show as UNKOWN SDTV and the episodes where Archived SD.

This was wrong so so i changed the show from UNKOWN SDTV to HD720p and rescan'd. This did not work and i change them to Downloaded but they came back as Downloaded SDTV.

Then i deleted this all and tried again as per what you guys have stated. Rename the episodes to have 720p in it.

This gave me the same results as the the above and as per the post where i posted a screen shot.

Then i tried to search for it again as the show was set to HD720p and this time it was snatched as 720 WEB-DL. So i know that the install was not broken.

If i change the Snatched to Downloaded this keeps the show as Downloaded 720 WEB-DL. This is what i am after to keep the show Quality of what i have.

So in the end only new shows work as i want them to (720p, 1080p etc...) BUT if you have a show already then it defaults to (UNKOWN SDTV and the episodes where Archived SD)

Thanks

**Comment by HPMSGEN8** [comment] 2018-06-19 07:18
Anyone test this ?

**Comment by medariox** [comment] 2018-06-19 15:41
Detection will be improved with: https://github.com/pymedusa/Medusa/pull/4410

**Comment by HPMSGEN8** [comment] 2018-06-19 16:04
Thanks 💯

**Comment by p0psicles** [comment] 2018-06-19 16:40
If you want, yeah please. Always good to have testers

**Comment by HPMSGEN8** [comment] 2018-06-19 19:54
Just tested and it is still the same now, SD & Archived SD. If you want me to do anything else please ask.

**Comment by medariox** [comment] 2018-06-19 20:22
Do you have 720p in the name?

**Comment by HPMSGEN8** [comment] 2018-06-20 06:00
With and without NAME.mkv & NAME 720p HD.mkv

**Comment by medariox** [comment] 2018-06-20 07:27
Are you sure you switched branch correctly? Working fine here with 720p and 720p HD.

**Comment by HPMSGEN8** [comment] 2018-06-20 07:56
Yes i did it has an banner stating i am on DEV. Can you paste and screenshot of what  you getting and the file names. Let me try that as well then.

**Comment by HPMSGEN8** [comment] 2018-06-20 08:16
oops. will get this done now

**Comment by medariox** [comment] 2018-06-21 16:05
@HPMSGEN8 
The show quality settings don't matter in this context. If you name the files as 720p, they will show up as 720p. Files added with `refresh` and not via post-processing are always `archived`, you can hower change that by selecting a different status. The files recognized as 720p will always default to HDTV as there is no way for Medusa to know about the source of the files if you don't include it in the name.

**Comment by HPMSGEN8** [comment] 2018-06-21 17:18
@medariox so in an nutshell if i want to move over say 10 shows i need to Post-Process them again ?

People with massive Library's are going to find this an issue. 

Is there no other way tyo solve this issue as Archived for me is not what i want. Also the Show Type needs to be the same as it was on any other Fork.

Thanks

**Comment by HPMSGEN8** [comment] 2018-06-21 19:53
Also on another note. I want to Thank you and the team that supports MedUSA :)

**Comment by medariox** [comment] 2018-06-21 20:28
@HPMSGEN8 
Like I said, in that case, you will need to change every imported show manually to `Downloaded`. Even with 50 shows, it should be pretty doable since it's just a one-time operation you won't have to repeat ever again. To retain the episode type you need to include the quality in the name e.g. `720p WEB` - there is no other way.

**Comment by HPMSGEN8** [comment] 2018-06-22 05:13
@medariox
Ok thanks i did this now and it worked. Then i went into Re-Name for the Show and Changed the file names to what i set the the settings.

It has remembered the settings even with an Force Update & Re-Scan Files. So this issues is a 1 Time issue on the time of import to the DataBase. 

I think this is resolved now.

Thanks again :)

**Comment by Scythe42** [comment] 2018-06-22 12:52
@p0psicles
A kind of administrative feature would be highly welcome. I can understand you want to automate this, but there are too many cases where this will fail and you are forcing users to include the quality in the filenames, which basically defeats automation if it is not in the filename already. And you will not be able to detect if it's a 720p WEB-DL, 720 HDTV or 720p Bluray from the video stream information itself. So instead of giving users an option to override the quality as it was before, they are now forced to either rename files or edit the SQL, followed be rescanning. Basically more work than before when it fails.

So some kind of admin feature to override the downloaded quality in the web interface would be nice to correct anything that could not be properly detected and where the quality is not in the filename. Renaming, and rescanning takes more work than just fixing the quality as it one was.

**Comment by deusxanime** [comment] 2018-06-22 17:37
I'm migrating over from SickRage (which has worked wonderfully for me the past couple years, but now fails when sending any magent links to my newly upgraded rTorrent 0.9.7 container, so I have no choice really) and this is INFURIATING me. I somewhat used SR to keep track of my qualities and would just rename the file "Show Name - 1x01 - Ep Name.ext" with processing to keep it nice and clean. That has worked fine and great though as SR retained/remembered the qualities for all my stuff for me.

Trying to import 300+ TV shows into Medusa now and it is puking on them of course. NBD if I could at least just go in and manually set the qualities based on what I have in SR right now. But it doesn't allow me to set the quality to HDTV/Web/BluRay only change status to Download/Archived/etc. So I'm basically having to embark on manually renaming 1000s (probably 10s of thousands) of files and adding in 720p.WEB-DL.h264 or 720p.HDTV.h264 or whatever they are to the end of the file name to them so that they can be detected correctly. Should I have done that in the past? Probably, but it shouldn't be necessary. If I manually want to set/override a quality/status it should honor that, like it did in SR. Instead it won't even let me set the quality and/or automatically overrides it on the next scan which just messes it up again.

I agree with earlier comments that the program is trying to be "smarter" than the user but instead it is just making things more convoluted. I'm not sure what was the issue with the old way SR did it, manually letting you set things as needed, but I feel this is a downgrade of features we had previously.

**Comment by HPMSGEN8** [comment] 2018-06-22 18:32
Right now i am doing this method and once the show is on teh correct status i use the re-name options to re-name the files back and then all done and dusterd.

But yes for u with 300+ this is massive issue.

**Comment by OmgImAlexis** [comment] 2018-06-23 00:15
For now let's just add a second dropdown that gives the quality selector back but we're not going to join them so you'll still need to set quality and status separately.

Everyone good with that?

**Comment by MotleyC** [comment] 2018-06-23 00:17
Anything that allows some manual control would be great.

**Comment by deusxanime** [comment] 2018-06-23 03:32
@OmgImAlexis That is actually what I was thinking might help give us some control back, but clean up the list a bit. Having a separate dropdown for quality and status would make them a lot shorter than having the super long list like in SR which combined both. You could even possibly split it one more time  into three and have a dropdown for resolution (SD, 720p, 1080p, 4k), for source (HDTV, Web, BluRay), and for status (Downloaded, Archived, Skipped) all separate, but the trade-off might be overload of too many dropdown boxes then. Whatever works to let us set it manually again though would be great. 

Does that also mean that it won't automatically override it every time it scans the files too? Perhaps if the quality/status is ever set manually then it locks the record, but if not then it is allowed to automatically override it on subsequent scans? Might be too complicated but just thinking of potential things and questions that could arise.

**Comment by OmgImAlexis** [comment] 2018-06-23 09:00
@deusxanime currently the quality still contains the source and resolution so there's no point in adding a third dropdown right now.

> Does that also mean that it won't automatically override it every time it scans the files too?
Once a quality is set it'll stay that way as long as the file isn't moved. It is still recommended to keep the whole quality in your title though.

>Perhaps if the quality/status is ever set manually then it locks the record, but if not then it is allowed to automatically override it on subsequent scans? Might be too complicated but just thinking of potential things and questions that could arise.
No need as the above states, it doesn't get changed if the files don't get moved around.

**Comment by deusxanime** [comment] 2018-06-24 19:31
Sounds good. Thanks for listening to us!

**Comment by medariox** [comment] 2018-06-27 10:48
Closing as there is a feature request now: https://github.com/pymedusa/Medusa/issues/4474

**Closed by medariox** 2018-06-27 10:48 UTC
Labels: Discussion
