### ISSUE TITLE
GUI  glitches (with v0.5.29)

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#10549] opened 2022-05-05 13:27 UTC
After updating to python 3.10.4 (and updating to the latest medusa), I've noticed couple of UI glitches:
1. In the show view page, The  search icon is not dynamic ("rotating") as before, and is not being removed after the search is complete (!)
![image](https://user-images.githubusercontent.com/2458280/166933491-30cd1b40-ffe7-4da8-bb90-db32f9516682.png)

2. In the show list page - the order of the indexers' icons is not being kept/consistent (looks like when the fanart.tv is added)
![image](https://user-images.githubusercontent.com/2458280/166933246-01e674d7-2e63-44f3-87bd-943f6db5a9fe.png)

3. Deleted... [After renaming of the path of medusa, the log file folder on the info page remains the old one path (maybe this is as designed?)   Maybe mention that a restart is needed for path related changes to take effect?]
4. NA
5. One more observation: on the shows list page - since the date now includes the time, at >80% zoom - we get double line/size list. Can the column be made adjustable? BTW, at least on "Previous Ep" column the hour is redundant, since it's always the same...  

![image](https://user-images.githubusercontent.com/2458280/166935019-831530e8-ea62-40b2-b116-160705b2f9b2.png)

6. When doing a force search in a show->episode page, the 2 top-right menus are not operable or very slow to respond during the processing of the search (drop-down lists are not showing or slow to show even when clicked) :( 

![image](https://user-images.githubusercontent.com/2458280/166989298-12a5069b-98ca-4130-859e-e6ac3b2d1017.png)

7. Highlighted ep. line is (for some reason) designed without  separation lines. IMHO they should be left untouched, but as it is - you forgot to remove (or re-add...) couple of lines, for consistency sake... 

![167205559-a4235cd6-cdec-4d28-8334-8bc10e166715](https://user-images.githubusercontent.com/2458280/167244723-62ae8bc1-5f15-4bc9-991b-7c4ce92e668d.png)

8. Switching to a specific show from the show list - displays the wrong (previous?) show title and fanart, sometimes for some time, and sometimes - forever... Should be faster, or at least - blank until correct. Used to be fast and without issues :( 
https://drive.google.com/file/d/1lNiFJJPaYg2hV22Eeo-zUnu6c4NZ0ldD/view?usp=sharing

9. *All* Torznab search provider's fields should be edit-able  (like the API key field), Now they are not :(
![image](https://user-images.githubusercontent.com/2458280/167284086-a5f9a327-4f6f-4419-b47a-a99f1aea463e.png)

10. Show title used to be Blue - to reflect it being also a link to the show main page, now it is white... "typo" ? Better leave it blue as before , to show it is a link... 
![image](https://user-images.githubusercontent.com/2458280/167311071-270b4d2a-a05f-4ab5-96dd-525daede50a8.png)

11. Locally added per-show ignore/pref./etc words - should be set the same as the global ones - as a link too.
 
![image](https://user-images.githubusercontent.com/2458280/168525232-59ab7e0c-99fb-497a-a26f-19fab790d66d.png)

12a. Sometimes, when clicking a show-list show,  the episodes' list is missing. Hard to reproduce, maybe more often when a search is running in the background. Page refresh in FF - brings them back on... 

![image](https://user-images.githubusercontent.com/2458280/169594699-d634f849-99ff-4578-8f47-cfe153caf641.png)

12b. Not sure if "refresh results" in manual search work, there is no indication... 

13. Cannot succeed in  manual subtitle DL ? Something must be wrong... My config (it's set to Heb + En)?
![image](https://user-images.githubusercontent.com/2458280/169598103-9c7ed6cd-9809-4973-886c-13fbcebfe405.png)

<html><body>
<h1 class="header">Medusa Configuration</h1> <div data-v-0e222bd8="" id="config-content">

Medusa Info: | Branch:                 master                  Commit:                 Unknown                  Version:                 0.5.29                  Database:                 44.19
-- | --
Python Version: | 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.1n  15 Mar 2022
OS: | Windows-10-10.0.19042-SP0
Locale: | en_IL.cp1255
Timezone: | Jerusalem Daylight Time
  |  
  |  
User: | RAFI-PC-DELL$
Program Folder: | D:\Program Files\Medusa\Medusa
Config File: | D:\Program Files\Medusa\Data\config.ini
Database File: | D:\Program Files\Medusa\Data\main.db
Cache Folder: | D:\Program Files\Medusa\Data\cache
Log Folder: | D:\Program Files\Medusa\Data-0.5.29\Logs
Arguments: | --nolaunch --datadir=D:\Program Files\Medusa\Data

</div>
</body>
</html>Medusa Configuration
Medusa Info: 	Branch: [master](https://github.com/pymedusa/Medusa/tree/master)
Commit: Unknown
Version: [0.5.29](https://github.com/pymedusa/Medusa/releases/tag/v0.5.29)
Database: 44.19
Python Version:	3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
SSL Version:	OpenSSL 1.1.1n 15 Mar 2022
OS:	Windows-10-10.0.19042-SP0
Locale:	en_IL.cp1255
Timezone:	Jerusalem Daylight Time
 	 
 	 

Thanks
Rafi

**Comment by mmhere** [comment] 2022-05-11 00:21
May I also suggest that the manual search screen (when you click on a specific episode to see what releases are available from which providers) also has unusually wide columns for both Provider and Group in 0.5.29.  I previously used 0.5.20 which had a much better and more economical table layout.

This means things wrap when they needn't (uses lots of extra vertical space) or the display becomes really wide if your browser window isn't currently wide enough and the table is required to extend horizontally so it can all be displayed (then scrolls left to right within the browser window).

In particular, Provider is only ever populated with a tiny icon, so it doesn't need to be like 225 pixels wide.  It's the same width as Group and Release.  In 0.5.20, this column was just wide enough to show the icon as well as the column header.

Similarly, Group is overly wide, as most group names are, what a dozen characters maximum?  This column is also about 225 pixels, same as Release and Group, but needn't be.

Looks like the default minimum widths for all three columns Release, Group, Provider got set to 225 pixels or thereabouts.

As the OP said above, if these widths could be adjustable that'd be cool.  But at a minimum it seems Group and Provider should be reduced in width to save space.  In fact, that extra horiz space could be given back to Release which is usually much much wider.

If I knew how to amend these default GUI settings and test them (I think there's a "compile stage" or something for the VUE stuff?  I can't just change a .py file temporarily and restart?)  I'd make a change submit a pull request.  I don't know how to change GUI stuff like this.

Cheers!

**Comment by rafi-d** [comment] 2022-05-12 14:52
> As the OP said above, if these widths could be adjustable that'd be cool. 

There is no point to try and statically change columns width. Eacj use is using different browser/zoom etc. Adjustable widths all over - would be a sustainable solution. 

> Can we continue to discuss it on discord?

Sure, just let me know when you are done with most of the changes and I'll try it out on that  branch you mentioned in #10566. Not sure it's worth while checking one at a time, best do them all first, so to avoid re-updating it from github again and again.... 

For me it cannot be a daily driver ( due to couple of permanent changes I have which you , guys , refuse to take as a patch... I'll need to side-install it...

**Comment by p0psicles** [comment] 2022-05-12 17:26
> One more observation: on the shows list page - since the date now includes the time, at >80% zoom - we get double line/size list. Can the column be made adjustable? BTW, at least on "Previous Ep" column the hour is redundant, since it's always the same...

No can't make the column width adjustable. I like how it wraps on two lines. I could set a `white-space: nowrap`, but that would take up a lot of width when I don't mind date and time wrapped below each other.

**Comment by p0psicles** [comment] 2022-05-12 17:28
> Highlighted ep. line is (for some reason) designed without separation lines. IMHO they should be left untouched, but as it is - you forgot to remove (or re-add...) couple of lines, for consistency sake...

That's an artifact from the vue-good-table component. Don't know how to fix that. It's unpredictable for which rows it displays like that.

**Comment by p0psicles** [comment] 2022-05-12 17:59
> Show title used to be Blue - to reflect it being also a link to the show main page, now it is white... "typo" ? Better leave it blue as before , to show it is a link.

Don't understand this one. It's not linking anywhere right? Or more like it's linking to itself. That why I didn't see the necessity to show it as a link

**Comment by p0psicles** [comment] 2022-05-12 18:00
I'll try to improve the editting of the provider. But then I think I covered most of it.
I'll also see if I can smallen some of the table fields.

**Comment by mmhere** [comment] 2022-05-12 18:03
> > Show title used to be Blue - to reflect it being also a link to the show main page, now it is white... "typo" ? Better leave it blue as before , to show it is a link.
> 
> Don't understand this one. It's not linking anywhere right? Or more like it's linking to itself. That why I didn't see the necessity to show it as a link

It does link to the show when clicked.  It's just that it used to be blue giving an extra indication that it *is* a link, while now it is white.

For browsers that change the pointer when hovered over a link (before clicking), the pointer does change when you hover over the white title.  Then you click on it and it takes you to the top of the show page.

So it works as before, just that the title is now white not blue.

**Comment by mmhere** [comment] 2022-05-12 18:04
Thanks for looking into conserving column horizontal space.  I know the GUI stuff is very subjective and also very easy to fall afoul of VUE doing various ...whatever... when things are changed.  The attention to space use is much appreciated.

**Comment by p0psicles** [comment] 2022-05-12 18:17
Can you create a screenshot that depicts the misuse of space? As for me it works fine.
![image](https://user-images.githubusercontent.com/1331394/168142045-df49bc41-feaf-43f3-8c95-30bdd7f138d1.png)

**Comment by mmhere** [comment] 2022-05-12 20:12
first image is with a few columns turned off, which exacerbates the issue.  2nd is with all columns and still provider and group are pretty wide.

current config snapshot for reference

![1](https://user-images.githubusercontent.com/16172883/168159909-20cdaf6e-d406-47aa-a8b5-75cb4cd07dd3.png)

![2](https://user-images.githubusercontent.com/16172883/168159959-8092e9bd-a0df-4235-91c6-3c9f3be1f57b.png)

![config](https://user-images.githubusercontent.com/16172883/168160010-553496b6-11e3-43ba-ae5f-dd86bbfb770a.png)

**Comment by mmhere** [comment] 2022-05-12 20:13
When the release name is super wide as with some shows, it seems to grab more of the space but this various.

**Comment by rafi-d** [comment] 2022-05-13 15:05
> No can't make the column width adjustable. I like how it wraps on two lines. I could set a `white-space: nowrap`, but that would take up a lot of width when I don't mind date and time wrapped below each other.

:(  too bad

> 
> Also the previous ep column's hour is not redundant. I have different hours for different shows.

I meant the same  for the same show (a column before)

**Comment by rafi-d** [comment] 2022-05-13 15:09
> 

It IS link to the show's main page ("itself")  and I use it all over the places - mainly from the episode search page, backlog etc. Even from some settings.  Blue even underlined (== link) was the right color...

**Comment by rafi-d** [comment] 2022-05-13 19:37
> 
> The first row has an indexer set to tvmaze. The second row uses tvdb. That's why they're different

The point is for you to try to keep the order of the icons the same as mach as possible, and not shuffle them around randomly... 

![image](https://user-images.githubusercontent.com/2458280/168377920-498bf7de-e2ec-498b-a0cf-40097bec9c04.png)

**Comment by rafi-d** [comment] 2022-05-14 14:29
Not sure if these can help, but I have a couple of references for VUE solutions to resizable columns. Maybe one of they can be of use:
https://github.com/search?q=vue+resizable+columns
https://codepen.io/crwilson311/pen/Bajbdwd
https://www.vuescript.com/resizable-table-columns-in-vue-js/
https://mdbootstrap.com/docs/vue/layout/grid-usage/

**Comment by p0psicles** [comment] 2022-05-14 14:41
That's something that would need to integrate into vue-good-table. But they don't accept feature requests anymore

**Comment by p0psicles** [comment] 2022-05-15 09:44
I've experimented with making the Show title the default link color (blue). But I find it ugly compared to the less in your face white.
I did add an underline on hover. Users will just have to get customed to being that a link.

**Comment by p0psicles** [comment] 2022-05-15 12:16
> 



> The point is for you to try to keep the order of the icons the same as mach as possible, and not shuffle them around randomly..

Your not listening. The first icon shows by which indexer the show was added. Then there is a `-` then you see all the other external IDs it has. If you want to always have them in order. Only use one indexer to add your shows

**Comment by rafi-d** [comment] 2022-05-16 05:10
> > 
> 
> > The point is for you to try to keep the order of the icons the same as mach as possible, and not shuffle them around randomly..
> 
> Your not listening. The first icon shows by which indexer the show was added. Then there is a `-` then you see all the other external IDs it has. If you want to always have them in order. Only use one indexer to add your shows

Ok, I see. maybe just add left justification.

Regarding the show name-link, possibly underline it permanently, to indicate a link?

**Comment by rafi-d** [comment] 2022-05-16 08:20
> That's something that would need to integrate into vue-good-table. But they don't accept feature requests anymore

There are two possible suggestions in that repo that may be relevant:
1.  https://github.com/xaksis/vue-good-table/pull/422 - pull request that was never used
2. https://github.com/xaksis/vue-good-table/issues/226#issuecomment-428846090 - suggestion to use Native JS

**Comment by p0psicles** [comment] 2022-05-16 19:37
Also added the changes to allow for editing url.
Please test.

**Comment by rafi-d** [comment] 2022-05-17 19:18
> Please test.

Done. https://github.com/pymedusa/Medusa/pull/10566#issuecomment-1128530115

**Comment by rafi-d** [comment] 2022-05-20 19:14
#11 &  #12  added

**Comment by rafi-d** [comment] 2022-05-27 10:28
Any progress with completing the fixes? worth testing already?

**Comment by p0psicles** [comment] 2022-05-27 15:06
Haven't done much for it lately. Also don't think I will spend a lot more time on it. Maybe I'll try to improve the switching of shows in the show-selector component.

**Comment by rafi-d** [comment] 2022-05-28 12:48
1, 6, (7), 12, 12 are actually bugs IMHO...

**Comment by p0psicles** [comment] 2022-05-29 13:15
1: fixed
6: tried reproducing that, but wasn't succesfull. But I don't have a lot of providers. I'll try with bigger searches
7: sould be fixed now (latest commit)
12: need more investigating
12: I'll add some indication

**Closed** 2022-06-25 08:35 UTC
