### ISSUE TITLE
Trakt Authorisation not working

### ISSUE THREAD

**Issue by jeffski10** [pymedusa/Medusa#8871] opened 2020-12-13 20:58 UTC
I've an issue with the trakt connection in that I cannot seem to authorise my account to a new instance of medusa. I follow the step to get the PIN to paste in, click authorise and save which all appears to work. Then fire the test which again reports successful.   Shortly after the sync tries to happen and I get an auth error. 

**Medusa (please complete the following information):**

Medusa Info: | Branch: masterCommit: ce68da57b3878591f77c21bb2acf28e6a58269faVersion: UnknownDatabase: 44.17
-- | --
Python Version: | 3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]
SSL Version: | OpenSSL 1.1.1d 10 Sep 2019
OS: | Linux-4.14.24-qnap-x86_64-with
Locale: | en_US.UTF-8

2020-12-13 20:46:13 WARNING	Thread-18 :: [ce68da5] Unable to test TRAKT: TraktException('Unknown Trakt request exception. Error: 400')
2020-12-13 20:46:13 ERROR	Thread-18 :: [ce68da5] Unknown Trakt request exception. Error: 400
Traceback (most recent call last):
  File "/app/medusa/lib/traktor/trakt.py", line 118, in request
    resp.raise_for_status()
  File "/app/medusa/ext/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.trakt.tv/users/settings
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/medusa/lib/traktor/trakt.py", line 118, in request
    resp.raise_for_status()
  File "/app/medusa/ext/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://trakt.tv/oauth/token
2020-12-13 20:43:19 DEBUG	MAIN :: [ce68da5] Finished updating network timezones
2020-12-13 20:43:19 DEBUG	MAIN :: [ce68da5] User-Agent: Medusa/0.5.0 (Linux; 4.14.24-qnap; d0cae5f8-3d83-11eb-9c63-02420a000307)
2020-12-13 20:43:19 DEBUG	MAIN :: [ce68da5] GET URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt [Status: 200]
2020-12-13 20:43:19 DEBUG	MAIN :: [ce68da5] Started updating network timezones
```

**Additional context**
I checked the config.ini and I see there is a refresh token but no access token stored.

My reason for updating was a name change on the trakt account so had to reauthorise and this has then kicked in.

**Comment by medariox** [comment] 2020-12-16 16:06
Duplicate of https://github.com/pymedusa/Medusa/issues/8410

**Closed by medariox** 2020-12-16 16:06 UTC
