### ISSUE TITLE
[APP SUBMITTED]: ConnectionError: HTTPSConnectionPool(host='api.imdbws.com', port=443): Max retries exceeded with url: /title/tt4925366/auxiliary (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000001574E630>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

### ISSUE THREAD

**Issue by Bilbo** [pymedusa/Medusa#5381] opened 2018-10-11 03:38 UTC
### INFO
**Python Version**: `2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/241faa2cf4278fed4f08085ff0168cc5
### ERROR
<pre>
2018-10-10 20:34:01 ERROR    SHOWQUEUE-ADD :: [4614efc] Error loading IMDb info: HTTPSConnectionPool(host='api.imdbws.com', port=443): Max retries exceeded with url: /title/tt4925366/auxiliary (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000001574E630>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
Traceback (most recent call last):
  File "C:\Program Files\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/show_queue.py#L587">medusa\show_queue.py</a>", line 587, in run
    self.show.load_imdb_info()
  File "C:\Program Files\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/tv/series.py#L1553">medusa\tv\series.py</a>", line 1553, in load_imdb_info
    imdb_info = imdb_api.get_title(self.imdb_id)
  File "C:\Program Files\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/imdbpie/imdbpie.py#L80">ext\imdbpie\imdbpie.py</a>", line 80, in get_title
    '/title/{0}/auxiliary'.format(imdb_id)
  File "C:\Program Files\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/imdbpie/imdbpie.py#L296">ext\imdbpie\imdbpie.py</a>", line 296, in _get_resource
    return self._get(url=url)['resource']
  File "C:\Program Files\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/imdbpie/imdbpie.py#L305">ext\imdbpie\imdbpie.py</a>", line 305, in _get
    resp = self.session.get(url, headers=headers, params=params)
  File "C:\Program Files\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/requests/sessions.py#L525">ext\requests\sessions.py</a>", line 525, in get
    return self.request('GET', url, **kwargs)
  File "C:\Program Files\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/requests/sessions.py#L512">ext\requests\sessions.py</a>", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/requests/sessions.py#L622">ext\requests\sessions.py</a>", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/requests/adapters.py#L513">ext\requests\adapters.py</a>", line 513, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='api.imdbws.com', port=443): Max retries exceeded with url: /title/tt4925366/auxiliary (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000001574E630>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment] 2018-10-11 16:06
Fixed with https://github.com/pymedusa/Medusa/pull/5386

**Closed by medariox** 2018-10-11 16:06 UTC
Labels: triage

**Comment by MadMungo** [comment] 2018-10-14 06:14
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: **No Log available**
### ERROR
<pre>
2018-10-14 17:07:52 ERROR    SHOWQUEUE-ADD :: [4614efc] Error loading IMDb info: HTTPSConnectionPool(host='api.imdbws.com', port=443): Max retries exceeded with url: /title/tt3337194/auxiliary (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000020D80AC8>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
Traceback (most recent call last):
  File "G:\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/show_queue.py#L587">medusa\show_queue.py</a>", line 587, in run
    self.show.load_imdb_info()
  File "G:\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/tv/series.py#L1553">medusa\tv\series.py</a>", line 1553, in load_imdb_info
    imdb_info = imdb_api.get_title(self.imdb_id)
  File "G:\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/imdbpie/imdbpie.py#L80">ext\imdbpie\imdbpie.py</a>", line 80, in get_title
    '/title/{0}/auxiliary'.format(imdb_id)
  File "G:\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/imdbpie/imdbpie.py#L296">ext\imdbpie\imdbpie.py</a>", line 296, in _get_resource
    return self._get(url=url)['resource']
  File "G:\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/imdbpie/imdbpie.py#L305">ext\imdbpie\imdbpie.py</a>", line 305, in _get
    resp = self.session.get(url, headers=headers, params=params)
  File "G:\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/requests/sessions.py#L525">ext\requests\sessions.py</a>", line 525, in get
    return self.request('GET', url, **kwargs)
  File "G:\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/requests/sessions.py#L512">ext\requests\sessions.py</a>", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "G:\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/requests/sessions.py#L622">ext\requests\sessions.py</a>", line 622, in send
    r = adapter.send(request, **kwargs)
  File "G:\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/requests/adapters.py#L513">ext\requests\adapters.py</a>", line 513, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='api.imdbws.com', port=443): Max retries exceeded with url: /title/tt3337194/auxiliary (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000020D80AC8>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by MadMungo** [comment] 2018-10-14 08:09
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/677f3392ca95c8a41093ec17a1001d8e
### ERROR
<pre>
2018-10-14 19:07:04 ERROR    SHOWQUEUE-ADD :: [4614efc] Error loading IMDb info: HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /title/tt5515212/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000021039B38>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
Traceback (most recent call last):
  File "G:\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/show_queue.py#L587">medusa\show_queue.py</a>", line 587, in run
    self.show.load_imdb_info()
  File "G:\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/tv/series.py#L1553">medusa\tv\series.py</a>", line 1553, in load_imdb_info
    imdb_info = imdb_api.get_title(self.imdb_id)
  File "G:\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/imdbpie/imdbpie.py#L77">ext\imdbpie\imdbpie.py</a>", line 77, in get_title
    self._redirection_title_check(imdb_id)
  File "G:\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/imdbpie/imdbpie.py#L326">ext\imdbpie\imdbpie.py</a>", line 326, in _redirection_title_check
    if self.is_redirection_title(imdb_id):
  File "G:\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/imdbpie/imdbpie.py#L334">ext\imdbpie\imdbpie.py</a>", line 334, in is_redirection_title
    response = self.session.get(page_url, allow_redirects=False)
  File "G:\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/requests/sessions.py#L525">ext\requests\sessions.py</a>", line 525, in get
    return self.request('GET', url, **kwargs)
  File "G:\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/requests/sessions.py#L512">ext\requests\sessions.py</a>", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "G:\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/requests/sessions.py#L622">ext\requests\sessions.py</a>", line 622, in send
    r = adapter.send(request, **kwargs)
  File "G:\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/requests/adapters.py#L513">ext\requests\adapters.py</a>", line 513, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /title/tt5515212/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000021039B38>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
