### ISSUE TITLE
Errors on poster.jpg

### ISSUE THREAD

**Issue by bobbysteel** [pymedusa/Medusa#3630] opened 2018-01-19 14:34 UTC
I'm getting about 7 of these errors a day. I've tried deleting the poster.jpg files but they seem necessary for Plex.

```
2018-01-19 07:09:05 DEBUG    SHOWQUEUE-REFRESH :: [bd08325] Skipping image. Unable to get metadata from /mnt/Resources/TV/The Good Doctor/poster.jpg
2018-01-19 07:09:05 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /mnt/Resources/TV/The Good Doctor/poster.jpg
2018-01-19 07:09:05 DEBUG    SHOWQUEUE-REFRESH :: [bd08325] Checking <medusa.metadata.media_browser.MediaBrowserMetadata object at 0x7f3742547bd0> metadata for fanart
2018-01-19 07:09:05 DEBUG    SHOWQUEUE-REFRESH :: [bd08325] Checking <medusa.metadata.wdtv.WDTVMetadata object at 0x7f3742547d10> metadata for fanart
2018-01-19 07:09:05 DEBUG    SHOWQUEUE-REFRESH :: [bd08325] Checking <medusa.metadata.kodi.KODIMetadata object at 0x7f3742547d90> metadata for fanart
2018-01-19 07:09:05 DEBUG    SHOWQUEUE-REFRESH :: [bd08325] Checking <medusa.metadata.tivo.TIVOMetadata object at 0x7f3742547d50> metadata for fanart
2018-01-19 07:09:05 DEBUG    SHOWQUEUE-REFRESH :: [bd08325] Skipping image. Unable to get metadata from /mnt/Resources/TV/The Good Doctor/poster.jpg
2018-01-19 07:09:05 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /mnt/Resources/TV/The Good Doctor/poster.jpg
2018-01-19 07:09:05 DEBUG    SHOWQUEUE-REFRESH :: [bd08325] Checking <medusa.metadata.mede8er.Mede8erMetadata object at 0x7f3742547dd0> metadata for fanart
2018-01-19 07:09:05 DEBUG    SHOWQUEUE-REFRESH :: [bd08325] Checking <medusa.metadata.ps3.PS3Metadata object at 0x7f3742547c90> metadata for fanart
```

**Comment by p0psicles** [comment] 2018-01-19 14:59
Where did you get the poster from? From the indexer?

**Comment by bobbysteel** [comment] 2018-01-19 15:07
It's been in my nas forever. I assumed plex or sickbeard downloaded it
previously. Are these not used anymore? I can't find any good advice on
this naming convention anywhere that's up to date. For now I've just did a
'find -delete' on them

**Comment by medariox** [comment] 2018-01-19 18:23
Something fails in: https://github.com/pymedusa/Medusa/blob/ef68ec25f7cb0563e5f687dba61a4c9d8dc84c58/medusa/helpers/__init__.py#L1641-L1667
Probably the image is not a supported image type of imghdr.

**Comment by jtwill** [comment] 2018-01-19 23:28
I got a similar poster.jpg warning yesterday. It was for a different show than bobbysteel's, but otherwise it was the same error. It seemed to me that it may have been a bug introduced in the v0.1.24 update. I'm not sure why it errors on a certain poster.jpg when I have dozens of them on my system. The poster.jpg in question seems to be a valid JPG file.

**Comment by p0psicles** [comment] 2018-01-20 06:39
Can you upload the image?

**Comment by mikeo999** [comment] 2018-01-20 06:58
I also get the error for a few days.
Example of one image: https://ibb.co/kzggJb


`2018-01-19 04:02:22 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/The Gifted/folder.jpg
2018-01-18 11:28:53 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/The Orville/poster.jpg
2018-01-18 11:28:11 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Beyond/folder.jpg
2018-01-18 11:12:28 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Training Day/poster.jpg
2018-01-18 11:12:28 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Training Day/folder.jpg
2018-01-18 10:58:54 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Salvation/folder.jpg
2018-01-18 10:58:54 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Salvation/poster.jpg
2018-01-18 10:55:16 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Ransom/poster.jpg
2018-01-18 10:55:16 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Ransom/folder.jpg
2018-01-18 10:53:11 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Lethal Weapon/folder.jpg
2018-01-18 10:52:46 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Emerald City/folder.jpg
2018-01-18 10:49:24 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Shooter/folder.jpg
2018-01-18 10:48:27 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Midnight, Texas/poster.jpg
2018-01-18 10:48:27 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Midnight, Texas/folder.jpg
2018-01-18 10:47:01 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Incorporated/poster.jpg
2018-01-18 10:47:01 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Incorporated/folder.jpg
2018-01-18 10:39:51 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Outsiders/poster.jpg
2018-01-18 10:38:20 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Greenleaf/poster.jpg
2018-01-18 10:36:13 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/24 Legacy/poster.jpg
2018-01-18 10:36:13 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/24 Legacy/folder.jpg
2018-01-18 10:18:49 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Medici Masters of Florence/folder.jpg
2018-01-18 10:18:49 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Medici Masters of Florence/poster.jpg
2018-01-18 10:11:12 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Kingdom (2014)/poster.jpg
2018-01-18 10:04:24 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/You Are Wanted/folder.jpg
2018-01-18 10:04:24 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/You Are Wanted/poster.jpg
2018-01-18 10:02:03 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Stranger Things/poster.jpg`

**Comment by p0psicles** [comment] 2018-01-20 12:01
Can you give give me some more info. Like where did you get the poster from? Was it added by medusa's metadata provider? Are these all tvdb shows?
Which metadata provider do you use?

**Comment by bobbysteel** [comment] 2018-01-20 12:15
Sounds like we should at least have guidance somewhere how to cleanup from
those going on years of updates from kodi, sickbeard, etc. Seems like one
needs to manually clean folder.jpg poster.jpg and maybe others from legacy
media stores. Perhaps a cleaning routine would be nice to add as a feature
request and in the meantime just change these errors to something that
doesn't trigger a notification?

**Comment by p0psicles** [comment] 2018-01-20 12:17
@mikeo999 I placed you image in the show, but it didn't have any issues reading the resolution from it.
So I can't reproduce it. Maybe I can try to get the image from the original source?

Would you be willing to move to the develop branch? You should know that we made some big changes in it, regarding the multi-indexer functionality. So you need to created a full copy of your data directory, before moving to develop.

**Comment by mikeo999** [comment] 2018-01-20 12:24
I think the poster is coming from Medusa but it could also be from Kodi. For the test I will remove the poster.jpg files and let Medusa scan everything. If it then already goes wrong we maybe have some more info on how to handle with it.

It is no problem to go the the Develop branch. I will test first the poster way and if that not helping i will switch to the develop branch, have to find out how, and let you know how it goes.

**Comment by mikeo999** [comment] 2018-01-20 13:04
I removed all the jpg files from my series folder and let Medusa scan and download the images.

Metadata  = Kodi 12+


Then the first error are there so it look like it goes wrong already with Medusa.

```
018-01-20 13:50:22 INFO     SHOWQUEUE-REFRESH :: [bd08325] Cache check completed
2018-01-20 13:50:22 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Lethal Weapon/poster.jpg
2018-01-20 13:50:22 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Lethal Weapon/poster.jpg
2018-01-20 13:50:22 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Lethal Weapon/poster.jpg
2018-01-20 13:50:22 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Lethal Weapon/poster.jpg
2018-01-20 13:50:20 INFO     SHOWQUEUE-REFRESH :: [bd08325] 311790: Updating NFOs for show with new indexer info
2018-01-20 13:50:20 INFO     SHOWQUEUE-REFRESH :: [bd08325] Trying to clean any empty folder under /volume1/video/series/Lethal Weapon
2018-01-20 13:49:41 INFO     SHOWQUEUE-REFRESH :: [bd08325] 311790: Performing refresh on Lethal Weapon
2018-01-20 13:45:39 INFO     SHOWQUEUE-REFRESH :: [bd08325] Cache check completed
2018-01-20 13:45:39 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Emerald City/poster.jpg
2018-01-20 13:45:38 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Emerald City/poster.jpg
2018-01-20 13:45:38 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Emerald City/poster.jpg
2018-01-20 13:45:38 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Emerald City/poster.jpg
2018-01-20 13:45:34 INFO     SHOWQUEUE-REFRESH :: [bd08325] 295779: Updating NFOs for show with new indexer info

```
I also get the error

`2018-01-20 13:59:09 WARNING  TORNADO :: [bd08325] 400 GET /api/v2/series/311790/asset/fanart?api_key=**********`

I will switch to Develop branch and repeat the steps to see if it solves something.

**Comment by mikeo999** [comment] 2018-01-20 13:08
Try to switch to Devlop and get Failure

`Thread-17 :: [bd08325] git checkout -f develop returned : error: pathspec 'develop' did not match any file(s) known to git.`

**Comment by p0psicles** [comment] 2018-01-20 13:13
Git checkout -t origin/develop

**Comment by mikeo999** [comment] 2018-01-20 13:16
Problem is the it is running on a Synology with Package Center. So no Git option.
I will remove it and install it again and try again.

**Comment by p0psicles** [comment] 2018-01-20 13:27
Yeah you have git. Its located in a few places. Try like a `which git` or `find / -type f -name "git"

**Comment by mikeo999** [comment] 2018-01-20 14:07
Reinstalled and restore backup was easy so did that and will try GIT when i switch back.

Process is running now and takes some time for all series are done i think.
Will let je know how it goes later of tommorw. When all is working fine i will switch back to master and repeat everything. Maybe the new installation solved some stuff then.

Then we know for sure if the problem is still there.

**Comment by mikeo999** [comment] 2018-01-21 12:56
I removed all jpg files in the series folder 
Then run the Mass update scan for the pictures.

Everything running fine with Develop branch.

Only one error in log after 24hours
`Thread-17 :: [c25e86a] Missing time zone for network: Sony Crackle`

Today i will 
1. Remove all jpg files again
2. Switch back to master branch
2. Run Mass Update again

Then we know if it is a local problem of that er goes something wrong with Medusa.

**Comment by mikeo999** [comment] 2018-01-21 14:18
1. Removed Medusa from my NAS.
2. Removed all jpg files again.
3. Reinstalled Medusa again and now choose the master branch.
4. Restored my backup.
5. Run Mass Update again the get jpg files back

Errors back and still busy downloading zo i think there we be more.

So I think we could say problem is in master. In Develop branch it is working fine.
Hope this helps.

```

2018-01-21 15:10:59 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Salvation/poster.jpg
2018-01-21 15:03:35 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Ransom/poster.jpg
2018-01-21 14:59:39 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Lethal Weapon/poster.jpg
2018-01-21 14:54:46 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Emerald City/poster.jpg
```

**Comment by p0psicles** [comment] 2018-01-21 14:27
Tnx for the analysis. Still weird as we didn't change anything in dev that could explain this. But I also ran master with your uploaded poster and I couldn't reproduce it.

**Comment by mikeo999** [comment] 2018-01-21 14:36
And if you remove all your jpg files and let Medusa scan the folder. Medusa download the poster files so if you follow the same way it did maybe that way you can reproduce it.

Indeed strange that it works in Develop version if nothing changed. 
If you need more thing to let me try let me know.

**Comment by labrys** [comment] 2018-01-21 17:01
@p0psicles it's not a change to the code.  The default way we detect image type (as in poster vs fanart etc)  is by resolution.  The simple code we have is a pure-python implementation but does not work with all jpegs.  Using a library like Pillow would properly detect the image resolution for all images (including types other than jpeg) but has a lot of os-native dependencies.  This is the issue i mentioned to you about a week ago in Slack.

**Comment by p0psicles** [comment] 2018-01-21 17:04
Wel I copied the poster that was supposed to cause the issue. But that parsed fine with what we got in my dev env. So it has to be some external factor.

Pillow will never be an option because of its dependencies. At rather make Medusa dependency lighter not heavy.

**Comment by labrys** [comment] 2018-01-21 17:04
@pymedusa/developers my recommendation for fixing this is to optionally use Pillow if available.   If pillow is not available warning that some images may not be properly detected without it and then downgrading the log message to an info statement

**Comment by p0psicles** [comment] 2018-01-21 17:13
Your already thinking in solutions while you don't know what the issue is. First let's try to  get an image that we 100% sure cannot scan. And even then I'm very hesitant to add something like pillow. Even if it's optional.

**Comment by labrys** [comment] 2018-01-22 01:40
I have them in my own library and I have tested it (about 3 weeks ago) with a simple script and pillow and it worked like a charm.

**Comment by labrys** [comment] 2018-01-22 01:42
Also in my opinion it's no different having it as an optional dependency than other libraries like SAB having yenc as optional.  It allows improved performance if its there, but if not then it still does what it can.

**Comment by labrys** [comment] 2018-01-22 03:24
**Simple test script**:

```python
import struct
import imghdr
from PIL import Image

bad_file = r'D:\series\active\Valor\poster.jpg'
good_file = r'D:\series\active\100, The (2014)\poster.jpg'


# http://stackoverflow.com/a/20380514
def get_image_size(image_path):
    """Determine the image type of image_path and return its size.."""
    with open(image_path, 'rb') as f:
        head = f.read(24)
        if len(head) != 24:
            return
        if imghdr.what(image_path) == 'png':
            check = struct.unpack('>i', head[4:8])[0]
            if check != 0x0d0a1a0a:
                return
            return struct.unpack('>ii', head[16:24])
        elif imghdr.what(image_path) == 'gif':
            return struct.unpack('<HH', head[6:10])
        elif imghdr.what(image_path) == 'jpeg':
            f.seek(0)  # Read 0xff next
            size = 2
            ftype = 0
            while not 0xc0 <= ftype <= 0xcf:
                f.seek(size, 1)
                byte = f.read(1)
                while ord(byte) == 0xff:
                    byte = f.read(1)
                ftype = ord(byte)
                size = struct.unpack('>H', f.read(2))[0] - 2
            # We are at a SOFn block
            f.seek(1, 1)  # Skip `precision' byte.
            return struct.unpack('>HH', f.read(4))


def get_pil_image_size(path):
    """Use pil to get the image size"""
    return Image.open(path).size


for filename in bad_file, good_file:
    hdr = get_image_size(filename)
    pil = get_pil_image_size(filename)
    print '{0:>15} - {1:15}'.format(hdr, pil)
```

**Results**:
```
           None - (680, 1000)    
   (1426, 1000) - (1000, 1426)   
```

**Comment by labrys** [comment] 2018-01-22 03:56
@bobbysteel I know that getting persistent warnings is frustrating.  You can be assured that this is not a significant issue, Medusa simply can't confirm from image content what type of image (fanart, etc) the image is.

**Comment by labrys** [comment] 2018-01-22 04:55
First to clarify when I say it's not a significant issue I don't mean the issue should not be addressed but that the issue does not impact the performance of Medusa.

@jtwill Since you obviously have an opinion on this I'd like to know why you would be against PIL/Pillow as an optional dependency.  Pros are faster performance, more supported image types, and would not be required.  Cons are it would have to be installed manually.  Most platforms that's as simple as `pip install pillow`.

**Comment by jtwill** [comment] 2018-01-22 05:50
As p0psicles already wrote, you are trying to solve a problem that is not confirmed yet. In fact, it looks like your "solution" is likely not going to fix this bug, since it is not as simple as some JPGs not being recognized by the current method. 

I think the important facts are:

(1) This appears to be a new problem. I only saw it a few days ago, and I believe the other people reporting it will say the same.

(2) p0psicles downloaded one of the images that did not work for someone else, but it worked fine for p0psicles

This points to the bug being something that will not be solved by using a different library.

**Comment by mikeo999** [comment] 2018-01-22 06:38
The scan is finished and as a result these are the ones with problems for my setup. As i let Medusa download the files it looks to me if you setup Medusa in master branch and and one of the series you should be able to reproduce the problem.  

Mybe that way you can find a good solution for it.

In the log it download this image for one of them
https://www.thetvdb.com/banners/posters/153021-64.jpg

```
2018-01-21 17:45:44 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/The Walking Dead/poster.jpg
2018-01-21 17:43:42 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Midnight, Texas/poster.jpg
2018-01-21 17:42:33 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Incorporated/poster.jpg
2018-01-21 17:37:08 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Game of Thrones/poster.jpg
2018-01-21 17:34:07 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Outsiders/poster.jpg
2018-01-21 17:32:35 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Greenleaf/poster.jpg
2018-01-21 17:29:37 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/24 Legacy/poster.jpg
2018-01-21 17:19:45 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Last Man Standing/poster.jpg
2018-01-21 17:01:47 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Medici Masters of Florence/poster.jpg
2018-01-21 16:52:21 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Kingdom (2014)/poster.jpg
2018-01-21 16:43:29 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/You Are Wanted/poster.jpg
2018-01-21 16:39:44 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Stranger Things/poster.jpg
2018-01-21 16:31:02 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Suits/poster.jpg
2018-01-21 16:25:06 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/The Gifted/poster.jpg
2018-01-21 16:20:08 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/The Orville/poster.jpg
2018-01-21 16:09:23 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Sherlock/poster.jpg
2018-01-21 16:01:08 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Blindspot/poster.jpg
2018-01-21 15:41:26 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Training Day/poster.jpg
2018-01-21 15:29:28 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Salem/poster.jpg
2018-01-21 15:10:59 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Salvation/poster.jpg
2018-01-21 15:03:35 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Ransom/poster.jpg
2018-01-21 14:59:39 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Lethal Weapon/poster.jpg
2018-01-21 14:54:46 WARNING  SHOWQUEUE-REFRESH :: [bd08325] Unable to determine image type for /volume1/video/series/Emerald City/poster.jpg 
```

**Comment by labrys** [comment] 2018-01-22 11:38
@jtwill 
1) The relevant code that checks the image has been unchanged for quite a while.  The method uses the image from your library as a candidate for medusa's cached artwork.  You first saw it a few days ago due to changes in the code to the image cache, not because of changes to the method.  I have had these warnings since well before these changes.

2) The code sample I posted above tests the method outside of medusa showing that its specific to that code.  I posted example pictures for a failure and a success for testing.  Additionally it shows that pill successfully detects the resolution.  As for @p0psicles method of testing the images, he doesnt provide enough information for me to explain why he did not get the error.  My initial assumption is he has an image in his cache so it does not fall back to the series folder to get the artwork.

**Comment by p0psicles** [comment] 2018-01-22 23:12
As @medariox already suggested the issue was in the fact that imghdr cannot determine the image type. A simple solution could be to `assume` the image type is jpg if the extension is jpeg, if no image type is returned by imghdr.

When using the image provided by @labrys, it still parses the resolution fine if we just assume it's jpg.
@medariox what you think?

**Comment by p0psicles** [comment] 2018-01-23 11:20
Should be fixed in develop branch.
Like @labrys already mentioned, the issue was also in develop. But it's not very serious. I'm pretty confident the issue will be resolved for at least images that have been added through one of our indexers.

**Closed by p0psicles** 2018-01-23 11:20 UTC
Labels: Bug, Confirmed
