### ISSUE TITLE
[APP SUBMITTED]: IOError: [Errno 2] No such file or directory: u'/config/cache/mako/layouts/main.mako.py'

### ISSUE THREAD

**Issue by mattail** [pymedusa/Medusa#4033] opened 2018-04-16 15:04 UTC
### INFO
**Python Version**: `2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]`
**Operating System**: `Linux-3.10.102-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**Link to Log**: https://gist.github.com/9050c8a23272d4d53ee74eaee3429489
### ERROR
<pre>
2018-04-16 16:54:54 ERROR    Thread-18 :: [d6eb72d] Environment error: [Errno 2] No such file or directory: u'/config/cache/mako/layouts/main.mako.py'
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 283, in async_call
    result = function(**kwargs)
  File "/app/medusa/medusa/server/web/config/general.py", line 38, in index
    controller='config', action='index')
  File "/app/medusa/medusa/server/web/core/base.py", line 155, in render
    kwargs['backtrace'] = RichTraceback()
  File "/app/medusa/ext/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/app/medusa/ext/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/app/medusa/ext/mako/template.py", line 660, in code
    return util.read_python_file(self.module_filename)
  File "/app/medusa/ext/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/config/cache/mako/layouts/main.mako.py'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Miicker** [comment] 2018-04-21 22:43
### INFO
**Python Version**: `2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]`
**Operating System**: `Linux-3.10.102-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@77b20916ab577b82112ebc624f816054788c63f2
**Link to Log**: https://gist.github.com/5b17d7e205e4ccb58cc34fccf1e4ec8b
### ERROR
<pre>
2018-04-22 00:42:14 ERROR    Thread_0 :: [77b2091] Environment error: [Errno 2] No such file or directory: u'/config/cache/mako/home.mako.py'
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 285, in async_call
    result = function(**kwargs)
  File "/app/medusa/medusa/server/web/home/handler.py", line 172, in index
    max_download_count=stats[1], controller='home', action='index')
  File "/app/medusa/medusa/server/web/core/base.py", line 149, in render
    kwargs['backtrace'] = RichTraceback()
  File "/app/medusa/ext/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/app/medusa/ext/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/app/medusa/ext/mako/template.py", line 660, in code
    return util.read_python_file(self.module_filename)
  File "/app/medusa/ext/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/config/cache/mako/home.mako.py'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sharkykh** [comment] 2018-06-08 07:59
Looks like this happens when two instances of Medusa are being loaded (or rather trying to load) at the same time.
I was able to reproduce it by restarting an instance through the web UI and simultaneously trying to start a new instance.
**I'm not sure but I think** I only get this error when running Medusa as a daemon.

**Comment by jasimancas** [comment] 2018-06-26 17:43
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.16.0-0.bpo.2-amd64-x86_64-with`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@7279ba6490aadc0dd12ae7a1d33803a11072bc32
**Link to Log**: https://gist.github.com/a54b7fbf3c74af39e18e371959fcbc98
### ERROR
<pre>
2018-06-26 19:41:07 ERROR    Thread_0 :: [7279ba6] Environment error: [Errno 2] No such file or directory: u'/config/cache/mako/layouts/main.mako.py'
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/7279ba6490aadc0dd12ae7a1d33803a11072bc32/medusa/server/web/core/base.py#L283">medusa/server/web/core/base.py</a>", line 283, in async_call
    result = function(**kwargs)
  File "/app/medusa/<a href="../blob/7279ba6490aadc0dd12ae7a1d33803a11072bc32/medusa/server/web/home/handler.py#L172">medusa/server/web/home/handler.py</a>", line 172, in index
    max_download_count=stats[1], controller='home', action='index')
  File "/app/medusa/<a href="../blob/7279ba6490aadc0dd12ae7a1d33803a11072bc32/medusa/server/web/core/base.py#L147">medusa/server/web/core/base.py</a>", line 147, in render
    kwargs['backtrace'] = RichTraceback()
  File "/app/medusa/<a href="../blob/7279ba6490aadc0dd12ae7a1d33803a11072bc32/ext/mako/exceptions.py#L93">ext/mako/exceptions.py</a>", line 93, in __init__
    self.records = self._init(traceback)
  File "/app/medusa/<a href="../blob/7279ba6490aadc0dd12ae7a1d33803a11072bc32/ext/mako/exceptions.py#L165">ext/mako/exceptions.py</a>", line 165, in _init
    module_source = info.code
  File "/app/medusa/<a href="../blob/7279ba6490aadc0dd12ae7a1d33803a11072bc32/ext/mako/template.py#L660">ext/mako/template.py</a>", line 660, in code
    return util.read_python_file(self.module_filename)
  File "/app/medusa/<a href="../blob/7279ba6490aadc0dd12ae7a1d33803a11072bc32/ext/mako/util.py#L374">ext/mako/util.py</a>", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/config/cache/mako/layouts/main.mako.py'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by MarioCaires** [comment] 2018-07-04 19:44
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.14.49-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@7cfc79d5280b719c6288090fb805521dfc0402cd
**Link to Log**: https://gist.github.com/d44a32213d549dfb5a97cea14d4a2870
### ERROR
<pre>
2018-07-04 20:33:39 ERROR    Thread_15 :: [7cfc79d] Environment error: [Errno 2] No such file or directory: u'/config/cache/mako/layouts/main.mako.py'
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/medusa/server/web/core/base.py#L283">medusa/server/web/core/base.py</a>", line 283, in async_call
    result = function(**kwargs)
  File "/app/medusa/<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/medusa/server/web/home/handler.py#L1006">medusa/server/web/home/handler.py</a>", line 1006, in displayShow
    title=series_obj.name, controller='home', action='displayShow',
  File "/app/medusa/<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/medusa/server/web/core/base.py#L147">medusa/server/web/core/base.py</a>", line 147, in render
    kwargs['backtrace'] = RichTraceback()
  File "/app/medusa/<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/ext/mako/exceptions.py#L93">ext/mako/exceptions.py</a>", line 93, in __init__
    self.records = self._init(traceback)
  File "/app/medusa/<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/ext/mako/exceptions.py#L165">ext/mako/exceptions.py</a>", line 165, in _init
    module_source = info.code
  File "/app/medusa/<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/ext/mako/template.py#L660">ext/mako/template.py</a>", line 660, in code
    return util.read_python_file(self.module_filename)
  File "/app/medusa/<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/ext/mako/util.py#L374">ext/mako/util.py</a>", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/config/cache/mako/layouts/main.mako.py'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by jasimancas** [comment] 2018-07-06 06:32
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.16.0-0.bpo.2-amd64-x86_64-with`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4773e568b47cc48a08418a05867acee459c5e485
**Link to Log**: https://gist.github.com/132087a19cf6125d2a5db348409d0607
### ERROR
<pre>
2018-07-06 08:29:22 ERROR    Thread_0 :: [4773e56] Environment error: [Errno 2] No such file or directory: u'/config/cache/mako/home.mako.py'
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/4773e568b47cc48a08418a05867acee459c5e485/medusa/server/web/core/base.py#L281">medusa/server/web/core/base.py</a>", line 281, in async_call
    result = function(**kwargs)
  File "/app/medusa/<a href="../blob/4773e568b47cc48a08418a05867acee459c5e485/medusa/server/web/home/handler.py#L172">medusa/server/web/home/handler.py</a>", line 172, in index
    max_download_count=stats[1], controller='home', action='index')
  File "/app/medusa/<a href="../blob/4773e568b47cc48a08418a05867acee459c5e485/medusa/server/web/core/base.py#L145">medusa/server/web/core/base.py</a>", line 145, in render
    kwargs['backtrace'] = RichTraceback()
  File "/app/medusa/<a href="../blob/4773e568b47cc48a08418a05867acee459c5e485/ext/mako/exceptions.py#L93">ext/mako/exceptions.py</a>", line 93, in __init__
    self.records = self._init(traceback)
  File "/app/medusa/<a href="../blob/4773e568b47cc48a08418a05867acee459c5e485/ext/mako/exceptions.py#L165">ext/mako/exceptions.py</a>", line 165, in _init
    module_source = info.code
  File "/app/medusa/<a href="../blob/4773e568b47cc48a08418a05867acee459c5e485/ext/mako/template.py#L660">ext/mako/template.py</a>", line 660, in code
    return util.read_python_file(self.module_filename)
  File "/app/medusa/<a href="../blob/4773e568b47cc48a08418a05867acee459c5e485/ext/mako/util.py#L374">ext/mako/util.py</a>", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/config/cache/mako/home.mako.py'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sharkykh** [comment] 2018-08-10 20:04
@mattail @Miicker @jasimancas @MarioCaires 

Hello all, I'm testing a theory that may fix this issue, as well as some database upgrade issues we had two months ago.
**I'd like if any of you are using the Medusa Docker container?**

If you do, please go into your Medusa general configuration, and under advanced settings enable the `No Restart` option, and save.
It should hopefully fix these issues.
I am looking at ways to fix the Docker issue.

**Comment by sharkykh** [comment] 2018-08-10 20:41
**And if you're not using Dockers, but you are using a restarting service of some kind for Medusa,
you should enable the `No Restart` option too!**

**Comment by mattail** [comment] 2018-08-11 06:37
Hi Sharkykh
I'm using the Medusa Docker on Synology but it looks like the error (at least for me) has disappeared somehow. I have checked the logs back to 5th August and no sign of this particular issue so far.
Maybe it was fixed in an update or maybe the error has not been triggered in that period.
If you know how to reproduce the issue I could try.
And should I still have the "No restart" enabled?

**Comment by sharkykh** [comment] 2018-08-11 12:13
Yes, please enable the `No restart` option. It should prevent worse issues in the future.

**Comment by medariox** [comment] 2019-03-03 19:55
Fixed with the next release as updates will be done only through the docker images.

**Closed by medariox** 2019-03-03 19:55 UTC
Labels: Bug, Confirmed
