### ISSUE TITLE
Search Status Stuck

### ISSUE THREAD

**Issue by elit3ge** [pymedusa/Medusa#7893] opened 2020-03-29 21:52 UTC
**Describe the bug**
After the 0.3.13 update in the log it gets stuck on 

> MAIN :: [fc471d2] Building internal name cache for all shows

No show refresh will happen and no searching for releases happen. Restarted a few times.

**To Reproduce**
Update to 0.3.13

**Expected behavior**
I expect it to continue like normal.
**Screenshots**
![image](https://user-images.githubusercontent.com/1644699/77861840-3719fc00-7263-11ea-9123-6cee20f54bc0.png)

**Medusa (please complete the following information):**
 - OS: Windows 7 x64
 - Branch: Master
 - Commit: fc471d206394047800fe5bd7e897c89ad89a43db
 - Python version: 2.7.13
 - Database version: 44.14

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for deadliest catch set to: deadliest catch
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for on the edge 2018 set to: on the edge 2018
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for the plot against america set to: the plot against america
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for ozzy and jacks world detour set to: ozzy and jacks world detour
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for on my block set to: on my block
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for unwrapped set to: unwrapped
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for belgravia set to: belgravia
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for little fires everywhere set to: little fires everywhere
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for trigonometry set to: trigonometry
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for feel good set to: feel good
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for motherland fort salem set to: motherland fort salem
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for rick steins spain set to: rick steins spain
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for rick steins far eastern odyssey set to: rick steins far eastern odyssey
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for rick steins long weekends set to: rick steins long weekends
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for rick steins seafood odyssey set to: rick steins seafood odyssey
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for rick steins german bite set to: rick steins german bite
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for rick steins food heroes set to: rick steins food heroes
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for hudson and rex set to: hudson and rex
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for trauma 2018 set to: trauma 2018
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for wicked tuna set to: wicked tuna
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for zerozerozero set to: zerozerozero
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for farscape set to: farscape
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for workin moms set to: workin moms
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for the nest set to: the nest
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for deep water 2019 set to: deep water 2019
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for zoeys extraordinary playlist set to: zoeys extraordinary playlist
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for how its made set to: how its made
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for the oland murder set to: the oland murder
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for tribal set to: tribal
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for the midnight gospel set to: the midnight gospel
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for the english game set to: the english game
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for bless this mess set to: bless this mess
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for hitmen set to: hitmen
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Internal name cache for mcdonald and dodds set to: mcdonald and dodds
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Started updating network timezones
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] GET URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt [Status: 200]
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] User-Agent: Medusa/0.3.13 (Windows; 7; 7b173470-7206-11ea-aa22-dc4a3e83b3a7)
2020-03-30 08:44:46 DEBUG    MAIN :: [fc471d2] Finished updating network timezones
2020-03-30 08:44:52 DEBUG    Thread_0 :: [fc471d2] Checking GitHub for latest news.
2020-03-30 08:44:52 DEBUG    Thread_0 :: [fc471d2] GET URL: https://cdn.pymedusa.com/news/news.md [Status: 200]
2020-03-30 08:44:52 DEBUG    Thread_0 :: [fc471d2] User-Agent: Medusa/0.3.13 (Windows; 7; 7b173470-7206-11ea-aa22-dc4a3e83b3a7)
2020-03-30 08:44:52 DEBUG    Thread_0 :: [fc471d2] Broken providers already updated in the last hour
2020-03-30 08:45:23 DEBUG    Thread_0 :: [fc471d2] Checking GitHub for latest news.
2020-03-30 08:45:23 DEBUG    Thread_0 :: [fc471d2] GET URL: https://cdn.pymedusa.com/news/news.md [Status: 200]
2020-03-30 08:45:23 DEBUG    Thread_0 :: [fc471d2] User-Agent: Medusa/0.3.13 (Windows; 7; 7b173470-7206-11ea-aa22-dc4a3e83b3a7)
2020-03-30 08:45:23 DEBUG    Thread_0 :: [fc471d2] Broken providers already updated in the last hour
2020-03-30 08:50:46 DEBUG    Thread_12 :: [fc471d2] Checking GitHub for latest news.
2020-03-30 08:50:46 DEBUG    Thread_12 :: [fc471d2] GET URL: https://cdn.pymedusa.com/news/news.md [Status: 200]
2020-03-30 08:50:46 DEBUG    Thread_12 :: [fc471d2] User-Agent: Medusa/0.3.13 (Windows; 7; 7b173470-7206-11ea-aa22-dc4a3e83b3a7)
2020-03-30 08:50:46 DEBUG    Thread_12 :: [fc471d2] Broken providers already updated in the last hour
```
</details>

**Comment by medariox** [comment] 2020-03-29 21:59
That is a normal log after a restart.

**Comment by elit3ge** [comment] 2020-03-29 22:14
Debug was enabled before restarting. Debug is still ticked.

**Comment by elit3ge** [comment] 2020-03-29 22:22
<details>

```
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 363815: Finding the episode which airs next
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 363815: Found episode S01E09
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 79485: Loading show info from database
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] Building black and white list for How It's Made
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 79485: Finding the episode which airs next
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 79485: No episode found... need to implement a show status
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 378030: Loading show info from database
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] Building black and white list for The Oland Murder
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 378030: Finding the episode which airs next
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 378030: No episode found... need to implement a show status
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 377719: Loading show info from database
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] Building black and white list for Tribal
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 377719: Finding the episode which airs next
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 377719: Found episode S01E07
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 378553: Loading show info from database
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] Building black and white list for The Midnight Gospel
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 378553: Finding the episode which airs next
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 378553: Found episode S01E01
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 378014: Loading show info from database
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] Building black and white list for The English Game
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 378014: Finding the episode which airs next
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 378014: No episode found... need to implement a show status
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 357882: Loading show info from database
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] Building black and white list for Bless This Mess
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 357882: Finding the episode which airs next
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 357882: Found episode S02E17
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 353283: Loading show info from database
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] Building black and white list for Hitmen
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 353283: Finding the episode which airs next
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 353283: Found episode S01E03
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 377023: Loading show info from database
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] Building black and white list for McDonald & Dodds
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 377023: Finding the episode which airs next
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] 377023: No episode found... need to implement a show status
2020-03-30 09:17:56 INFO     MAIN :: [fc471d2] Starting Medusa [master] using u'C:\\Apps\\medusa\\config.ini'
2020-03-30 09:17:56 INFO     TORNADO :: [fc471d2] Starting Medusa on http://0.0.0.0:8081/
2020-03-30 09:17:56 INFO     MAIN :: [fc471d2] Updating exception_cache and exception_season_cache
2020-03-30 09:17:56 INFO     MAIN :: [fc471d2] Finished processing 3327 scene exceptions.
2020-03-30 09:17:56 INFO     MAIN :: [fc471d2] Building internal name cache for all shows
2020-03-30 09:17:56 DEBUG    MAIN :: [fc471d2] Internal name cache for outlander set to: outlander
2020-03-30 09:17:57 DEBUG    MAIN :: [fc471d2] Started updating network timezones
2020-03-30 09:17:57 DEBUG    MAIN :: [fc471d2] GET URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt [Status: 200]
2020-03-30 09:17:57 DEBUG    MAIN :: [fc471d2] User-Agent: Medusa/0.3.13 (Windows; 7; 1dfeb55e-720b-11ea-a58e-dc4a3e83b3a7)
2020-03-30 09:17:57 DEBUG    MAIN :: [fc471d2] Finished updating network timezones
2020-03-30 09:18:23 ERROR    Thread_1 :: [fc471d2] Missing time zone for network: Rai Gulp
2020-03-30 09:18:28 DEBUG    Thread_1 :: [fc471d2] Checking GitHub for latest news.
2020-03-30 09:18:28 DEBUG    Thread_1 :: [fc471d2] GET URL: https://cdn.pymedusa.com/news/news.md [Status: 200]
2020-03-30 09:18:28 DEBUG    Thread_1 :: [fc471d2] User-Agent: Medusa/0.3.13 (Windows; 7; 1dfeb55e-720b-11ea-a58e-dc4a3e83b3a7)
2020-03-30 09:18:28 DEBUG    Thread_1 :: [fc471d2] Broken providers already updated in the last hour
```
</details>

It wanted to be shut down and started again.

**Comment by medariox** [comment] 2020-03-29 22:52
Okay. The debug log doesn't show anything wrong. If you go to the status page you can see when the next daily search will take place.

**Comment by elit3ge** [comment] 2020-03-29 23:49
The next one is in 17hrs, it's set at 4am. It didn't run this morning. All the entries just sat there like it was stuck so I restarted.

**Comment by elit3ge** [comment] 2020-03-30 00:45
Forced an update on a Show.
It's just stuck on the update.
![image](https://user-images.githubusercontent.com/1644699/77865460-2fb21d00-727a-11ea-99eb-ad7aa5008b73.png)
![image](https://user-images.githubusercontent.com/1644699/77865478-422c5680-727a-11ea-821a-616de632f5a7.png)

**Comment by mastafrooper** [comment] 2020-03-30 09:43
Getting the same issue after the last update. Grabbed some stuff that was queued today manually and the post-processor still found and sorted the files.

If you try and search for an episode manually it just sits at "The episode has been queued, because another search is taking place. please wait.." forever.

Logs all look pretty fine.

Attached a Debug log if that helps at all.

[application.zip](https://github.com/pymedusa/Medusa/files/4401931/application.zip)

**Comment by medariox** [comment] 2020-03-30 10:12
Please try this brach: https://github.com/pymedusa/Medusa/pull/7898
Does it fix the issue?

**Comment by xmenxmen** [comment] 2020-03-30 11:12
Synology DSM 6
Branch: master
Commit: fc471d206394047800fe5bd7e897c89ad89a43db
Version: 0.3.13
Database: 44.14
 

Same problem.The episode has been queued, because another search is taking place. please wait.." forever.

**Comment by xmenxmen** [comment] 2020-03-30 11:14
Please try this brach: #7898

How do I try this on a Synology Dsm 6

**Comment by enrique131** [comment] 2020-03-30 11:15
I have the same issue as of today. Restarted a few times.
Saw this on "manageSearches"
Search Queue:
Backlog: 0 pending items
Daily: 4 pending items
Forced: 1 pending items
Manual: 0 pending items
Failed: 0 pending items

When looking for an individual episode:
The episode has been queued, because another search is taking place. please wait.." forever.

it was working as of last saturday.

**Comment by elit3ge** [comment] 2020-03-30 11:37
> Please try this brach: #7898
> Does it fix the issue?

Tried a manual full refresh, still hangs. Will see if it complete a full show refresh at 4am.

**Comment by p0psicles** [comment] 2020-03-30 12:32
I'm currently running the branch. I'll monitor if that improves for me.

**Comment by dabonetn** [comment] 2020-03-30 13:01
Same issue here,  Windows install.

**Comment by Undeadllama** [comment] 2020-03-30 13:12
Believe I'm observing very similar symptoms also, even with the updated scheduler.py in place.

OS: Windows Server 2012 R2
Branch: Master
Python version: 2.7.13
Database version: 44.14

Interestingly sometimes after restarting Medusa it can get all the way through a daily search as far as attempting to send an nzb to the download manager but then it seems to hang;

`2020-03-30 12:32:51 INFO     SEARCHQUEUE-DAILY-SEARCH :: [fc471d2] Downloading xxxxx.S08E08.1080P.WEB.X264-POKE with size: 2.90 GB from Omgwtfnzbs
`
`2020-03-30 12:32:53 INFO     SEARCHQUEUE-DAILY-SEARCH :: [fc471d2] Downloading xxxxx.S03E03.1080p.AMZN.WEB-DL.x265.10bit.DDP5.1-Kronos with size: 1.94 GB from Omgwtfnzbs
`
`2020-03-30 12:32:55 INFO     SEARCHQUEUE-DAILY-SEARCH :: [fc471d2] Downloading xxxxx.S10E14.1080p.WEB.H264-XLF with size: 1.93 GB from Omgwtfnzbs
`

And no downloads appear in nzbget.

Attempts to download the same nzb again manually result in:

`2020-03-30 12:36:49 DEBUG    Thread_2 :: [fc471d2] Not adding item, it's already in the queue`

During other Medusa restart attempts anything search related will grind to a sudden halt much earlier with no obvious error messages.

**Comment by p0psicles** [comment] 2020-03-30 13:44
First I would recommend you to upgrade to python 3.7. second, you sure you properly restarted after overwriting the file?

It's actually running fine here for over an hour. Multiple daily searches. And one forced backlog search. Also it snatched some eps

**Comment by PlaceboPRS** [comment] 2020-03-30 14:30
Having the same issue and also when adding a new show it does nothing:

![image](https://user-images.githubusercontent.com/23120453/77924234-b7f8e800-72a3-11ea-937f-ea9f79da34c6.png)

Added those three shows as new and it stays like that a day later since I upgraded.

**Comment by p0psicles** [comment] 2020-03-30 14:44
Did you try out this branch? #7898
What are your specs? The more info the better

**Comment by PlaceboPRS** [comment] 2020-03-30 14:46
> 
> 
> Did you try out this branch? #7898
> What are your specs? The more info the better

I have no idea how to "try out a branch", everyone keeps saying that assuming we all know how to do it ;) Am currently trying to switch to Develop mode but if that branch works please, please, please explain to a dummy how one "tries out a branch"? :)

**Comment by p0psicles** [comment] 2020-03-30 15:07
Was more interested in Python version

**Comment by PlaceboPRS** [comment] 2020-03-30 15:08
> 
> 
> Was more interested in Python version

Oh sorry, I was on 2.7 but after the advice in here I updated to 3.7

**Comment by p0psicles** [comment] 2020-03-30 15:18
While running the branch. It got stuck for me. 6 daily searches queued up.

**Comment by xmenxmen** [comment] 2020-03-30 15:33
Synology DSM6
Branch: develop
Commit: 170937491681b28afbb53d9c939d7d64c21882eb
Version: 0.3.13 
Database: 44.14
Python Version: | 2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)

Hi.
Just try this, still not working, same problem.

**Comment by PlaceboPRS** [comment] 2020-03-30 16:03
I uninstalled completely in Add/Remove programs (choosing "no" to keep data of course), then reinstalled via the installer and it seems to all be working again, this is the version info I'm now on:

![image](https://user-images.githubusercontent.com/23120453/77934610-99e5b480-72b0-11ea-9f34-6c6feb333db8.png)


It's finding episodes, it's letting me add new shows and then find episodes for them etc. etc.

**Comment by p0psicles** [comment] 2020-03-30 16:04
currently running this commit: https://github.com/pymedusa/Medusa/pull/7898/commits/93f7c5cf45440824d9f0a172fcd7b0e31bdbe07d

**Comment by Undeadllama** [comment] 2020-03-30 19:05
So the last commit that popsicles mentioned appears to have resolved the issue to the point where searches are no longer completely hanging.

However testing all this made me notice that generally page loads are very slow, even when just browsing to pages such as Schedule, History, Manage Searches.
Often I received browser messages saying the connection to Medusa has been lost when attempting to load pages.
This continued even after fully restarting Medusa and then waiting till it was completely idle.
To begin with I figured this was just my db starting to get a bit big and sluggish.

However to be sure I switched back to v0.3.12, **making no other changes.**
Doing so confirmed there is indeed an extremely severe difference in page load times and general responsiveness of Medusa.

I'm not sure which change in v0.3.13 causes this or whether others are seeing the same behaviour, but at least for now the new version appears to be a misfire for my particular environment and config.

Has there been any changes in requirements with the new release, such as minimum Python version?

Either way I'll be staying on v0.3.12 until another a new version rolls out and will be sure to test it more thoroughly when it does.

**Comment by elit3ge** [comment] 2020-03-30 20:35
Just changed to Develop branch after you pushed the PR. It works now.

**Comment by medariox** [comment] 2020-03-30 20:52
The bug is fixed in the new release. Please update https://github.com/pymedusa/Medusa/releases

**Closed** 2020-03-30 20:54 UTC
Labels: Support

**Comment by enrique131** [comment] 2020-03-31 08:20
> First I would recommend you to upgrade to python 3.7. second, you sure you properly restarted after overwriting the file?

Not sure if you can help with this... i just realize even though i have python 3 installed is still using 2.7. But i have no idea how to tell it to use python 3 without uninstalling medusa (synology NAS)
 Any guidance?

**Comment by p0psicles** [comment] 2020-03-31 08:48
Isn't there a Python 3 package for Synology. Like the custom sickbeard installer, but python 3? I think you have to reinstall anyway. But move over your data folder/config files.

**Comment by enrique131** [comment] 2020-03-31 10:34
> Just checked, there isn't one yet. There is a medusa specific package, but you need to manually install the PKG. [SynoCommunity/spksrc#3710 (comment)](https://github.com/SynoCommunity/spksrc/issues/3710#issuecomment-524808904)
I installed the specific package and it is using python 3 now... Now i have to configure everything again... which is a good thing. thanks
