### ISSUE TITLE
Prioritize on title, rather than alias

### ISSUE THREAD

**Issue by elpedriyo** [pymedusa/Medusa#9941] opened 2021-10-14 00:18 UTC
Hello,

I have an example where I am being impacted because Alias is being taking first, than the title itself, provided by guessit:

`2021-10-12 19:30:12 INFO	FORCEDSEARCHQUEUE-MANUAL-383275 :: [21e350c] Unable to find manual season pack results for: El juego del calamar - S01E01 - Luz roja, luz verde
2021-10-12 19:30:12 DEBUG	FORCEDSEARCHQUEUE-MANUAL-383275 :: [21e350c] 383275: Formatting pattern: %SN - S%0SE01 - %EN -> El juego del calamar - S01E01 - Luz roja, luz verde
2021-10-12 19:30:12 DEBUG	FORCEDSEARCHQUEUE-MANUAL-383275 :: HDO :: [21e350c] We aren't interested in this result: El.juego.del.Calamar.(2021).S01.PACK.NF.WEB-DL.1080p.AVC.ES-EN.DD+.Subs..SPANISH with url: http://192.168.1.204:9117/dl/hdolimpo2/?jackett_apikey=**********&path=Q2ZESjhQY1NtNXJ4djN4Q3ROYml1eHlUTmlUSDNRVFgzRGtKQjhqeGRDZC0zSE9jRkJNQ3BQbXB1cUFXSGVIYlVnOE0yaHhNb0JMQ2FrN2tvcjM0dGFXWk81cTlubmZMQjJfSnRDdUViN0VIMGczVFpCTU5XdGpQMDR3LWxDaXRFZDdYT1dRejR2VGc5TS10UHh3ekdtWE9FUGxuN2llU0xVUGxRRXFoRFB4QXVYaFk&file=El+juego+del+Calamar+(2021)+S01+PACK+NF+WEB-DL+1080p+AVC+ES-EN+DD%2B+Subs++SPANISH
2021-10-12 19:30:12 DEBUG	FORCEDSEARCHQUEUE-MANUAL-383275 :: HDO :: [21e350c] Error during parsing of release name: El.juego.del.Calamar.(2021).S01.PACK.NF.WEB-DL.1080p.AVC.ES-EN.DD+.Subs..SPANISH, with error: Unable to match El.juego.del.Calamar.(2021).S01.PACK.NF.WEB-DL.1080p.AVC.ES-EN.DD+.Subs..SPANISH to a series in your database. Parser result: title: El juego del Calamar, alias: El juego del Calamar 2021, year: 2021, season: 1, episode_title: PACK, streaming_service: Netflix, source: Web, screen_size: 1080p, video_codec: H.264, video_profile: Advanced Video Codec High Definition, language: [<Language [es]>, <Language [en]>], audio_codec: Dolby Digital Plus, subtitle_language: ['und', <Language [es]>], type: episode, parsing_time: 0.03382110595703125, episode: [], absolute_episode: [], quality: 1080p WEB-DL, total_time: 0.0544583797454834
2021-10-12 19:30:12 DEBUG	FORCEDSEARCHQUEUE-MANUAL-383275 :: HDO :: [21e350c] GuessIt cache was cleared due to invalidation object change: previous={'show_type': 'anime', 'type': 'episode', 'implicit': True, 'episode_prefer_number': True, 'expected_title': [], 'expected_group': ['TV2LAX9', 'DHD', '20-40', 'E7'], 'allowed_languages': ['de', 'en', 'es', 'ca', 'fr', 'he', 'hu', 'it', 'jp', 'nl', 'pl', 'pt', 'ro', 'ru', 'sv', 'uk', 'mul', 'und'], 'allowed_countries': ['us', 'gb']} new={'show_type': 'normal', 'type': 'episode', 'implicit': True, 'episode_prefer_number': False, 'expected_title': ['Shingeki no Kyojin S3', 'Shingeki no Kyojin Season 3', 'Attack on Titan S3', 'Shingeki no Kyojin S4', 'Attack on Titan - S4', 'Shingeki no Kyojin S2', 'Shingeki no Kyojin Season 2', 'Attack on Titan S2', 'Fairy Tail S3', 'Fairy Tail (2014)', 'Fairy Tail S2', 'Fairy Tail (2018)', 'Fairy Tail 2', 'Psycho-Pass 3', 'Psycho-Pass', 'PSYCHO-PASS Extended Edition', 'Psycho-Pass 2', 'Sword Art Online - Alicization', 'SAO3 WoU', 'Sword Art Online - Alicization - War of Underworld', 'Sword Art Onlineː Alicization - War of Underworld', 'Ansatsu Kyoushitsu S2', 'Assassination Classroom S2', 'Ansatsu Kyoushitsu 2', 'One Punch Man S2', 'One Punch Man (2019)'], 'expected_group': ['TV2LAX9', 'DHD', '20-40', 'E7'], 'allowed_languages': ['de', 'en', 'es', 'ca', 'fr', 'he', 'hu', 'it', 'jp', 'nl', 'pl', 'pt', 'ro', 'ru', 'sv', 'uk', 'mul', 'und'], 'allowed_countries': ['us', 'gb']}
2021-10-12 19:30:12 DEBUG	FORCEDSEARCHQUEUE-MANUAL-383275 :: HDO :: [21e350c] Found 1 unique search results`

It was discussed on discord, this is done because of reboots only having the year in the name of the TV show. However, not all trackers are following this case, and it would be nice, to make some sort of prioritization level of mapping, where medusa, will first check the title, and if it has conflict with any other TV show, then it will take the Alias.

Kind regards

**Comment by medariox** [comment] 2021-10-21 16:13
Duplicate of https://github.com/pymedusa/Medusa/issues/9952

**Closed by medariox** 2021-10-21 16:13 UTC
