### ISSUE TITLE
Medusa can't start anymore in Synology

### ISSUE THREAD

**Issue by mikeo999** [pymedusa/Medusa#3618] opened 2018-01-17 10:33 UTC
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
**OS:** Synology DSM 6.1.4.15217 Update 5
**What you did: Update where available for DSM also on for Pyhton to 2.7.14-17 version.
**What happened: The next day a saw that Medusa was stopped. Trying to start it failed with an error **failed to run the package service**
Medusa was running fine before this.

Then i try to start it manually with Putty
`/var/packages/sickbeard-custom/scripts/start-stop-status start`

And get this error.

**Logs:**
```

```
Traceback (most recent call last):
  File "/usr/local/sickbeard-custom/var/SickBeard/SickBeard.py", line 4, in <module>
    from medusa.__main__ import main
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/medusa/__main__.py", line 67, in <module>
    from . import (
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/medusa/providers/__init__.py", line 10, in <module>
    from medusa.providers.nzb import (
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/medusa/providers/nzb/anizb.py", line 14, in <module>
    from medusa.providers.nzb.nzb_provider import NZBProvider
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/medusa/providers/nzb/nzb_provider.py", line 8, in <module>
    from medusa.providers.generic_provider import GenericProvider
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/medusa/providers/generic_provider.py", line 18, in <module>
    from medusa import (
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/medusa/config.py", line 30, in <module>
    from medusa.version_checker import CheckVersion
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/medusa/version_checker.py", line 31, in <module>
    from medusa.github_client import get_github_repo
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/medusa/github_client.py", line 6, in <module>
    import github
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/ext/github/__init__.py", line 37, in <module>
    from MainClass import Github, GithubIntegration
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/ext/github/MainClass.py", line 34, in <module>
    import jwt
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/ext/jwt/__init__.py", line 19, in <module>
    from .api_jwt import (
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/ext/jwt/api_jwt.py", line 8, in <module>
    from .api_jws import PyJWS
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/ext/jwt/api_jws.py", line 7, in <module>
    from .algorithms import (
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/ext/jwt/algorithms.py", line 8, in <module>
    from .utils import (
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/ext/jwt/utils.py", line 8, in <module>
    from cryptography.hazmat.primitives.asymmetric.utils import (
  File "/usr/local/python/lib/python2.7/site-packages/cryptography/hazmat/primitives/asymmetric/utils.py", line 9, in <module>
    from asn1crypto.algos import DSASignature
  File "/usr/local/python/lib/python2.7/site-packages/asn1crypto/algos.py", line 24, in <module>
    from ._int import fill_width
  File "/usr/local/python/lib/python2.7/site-packages/asn1crypto/_int.py", line 56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "/usr/local/python/lib/python2.7/site-packages/asn1crypto/_perf/_big_num_ctypes.py", line 35, in <module>
    libcrypto_path = find_library(b'crypto' if sys.version_info < (3,) else 'crypto')
  File "/usr/local/python/lib/python2.7/ctypes/util.py", line 274, in find_library
    return _findSoname_ldconfig(name) or _get_soname(_findLib_gcc(name))
  File "/usr/local/python/lib/python2.7/ctypes/util.py", line 107, in _findLib_gcc
    temp.close()
  File "/usr/local/python/lib/python2.7/tempfile.py", line 431, in close
    self.unlink(self.name)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/medusa/init/filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
TypeError: remove() takes exactly 1 argument (2 given)
```

```

**Comment by jbaun** [comment] 2018-01-17 11:46
i have the same problem. i think its after Phyton was updated. reinstallation of Medusa did not help.

**Comment by stefaang** [comment] 2018-01-17 12:01
Duplicate of https://github.com/pymedusa/Medusa/issues/3613
Please try this simple fix: https://github.com/pymedusa/Medusa/pull/3619/commits/34dae1c4cfcbdfe65ce42030dab83e52fd79eb4a

**Comment by p0psicles** [comment] 2018-01-17 12:47
@stefaang if this fixes it could you also create a PR against master? then we'll hotfix it with version 0.1.24.

**Comment by mikeo999** [comment] 2018-01-17 14:26
That fixes indeed the problem. Thanks for the quick response and fix

**Comment by p0psicles** [comment] 2018-01-17 14:39
Fixed with a hotfix in master (v0.1.24)

**Closed by p0psicles** 2018-01-17 14:39 UTC
