### ISSUE TITLE
[APP SUBMITTED]: IOError: [Errno 36] File name too long: '/media/bigdisk/Anime/The Disastrous Life of Saiki K/Season 01/The Disastrous Life of Saiki K - S01E01E02 - The Disastrous Life of a Psychic + The Worst of the Worst! Riki Nendou + Shun Kaidou, AKA The Jet-Black Wings + Intelligent and Beautiful! Kokomi Teruhashi & Hot-Blooded! Dodgeball! + Reach Him! Sign of Love + Saiki Family Home Renovation! Drastic Makeover!! + Deceive! Mind Control.nfo'

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#3698] opened 2018-02-03 10:35 UTC
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-4-amd64-x86_64-with-debian-9.2`
**Locale**: `UTF-8`
**Branch**: [feature/add-theming](../tree/feature/add-theming)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@4e0d16b55903c9dc2bb98d593b530c203be803ff
**Link to Log**: https://gist.github.com/f79de4711191ef7da34ab73afc5055be
### ERROR
<pre>
2018-02-03 10:00:29 ERROR    POSTPROCESSOR :: [4e0d16b] Unable to write file to /media/bigdisk/Anime/The Disastrous Life of Saiki K/Season 01/The Disastrous Life of Saiki K - S01E01E02 - The Disastrous Life of a Psychic + The Worst of the Worst! Riki Nendou + Shun Kaidou, AKA The Jet-Black Wings + Intelligent and Beautiful! Kokomi Teruhashi & Hot-Blooded! Dodgeball! + Reach Him! Sign of Love + Saiki Family Home Renovation! Drastic Makeover!! + Deceive! Mind Control.nfo: Environment error: [Errno 36] File name too long: '/media/bigdisk/Anime/The Disastrous Life of Saiki K/Season 01/The Disastrous Life of Saiki K - S01E01E02 - The Disastrous Life of a Psychic + The Worst of the Worst! Riki Nendou + Shun Kaidou, AKA The Jet-Black Wings + Intelligent and Beautiful! Kokomi Teruhashi & Hot-Blooded! Dodgeball! + Reach Him! Sign of Love + Saiki Family Home Renovation! Drastic Makeover!! + Deceive! Mind Control.nfo'
Traceback (most recent call last):
  File "/opt/medusa/medusa/metadata/generic.py", line 470, in write_ep_file
    nfo_file = io.open(nfo_file_path, u'wb')
  File "/opt/medusa/medusa/init/filesystem.py", line 111, in patched_output
    return handle_output(f(*args, **kwargs))
IOError: [Errno 36] File name too long: '/media/bigdisk/Anime/The Disastrous Life of Saiki K/Season 01/The Disastrous Life of Saiki K - S01E01E02 - The Disastrous Life of a Psychic + The Worst of the Worst! Riki Nendou + Shun Kaidou, AKA The Jet-Black Wings + Intelligent and Beautiful! Kokomi Teruhashi & Hot-Blooded! Dodgeball! + Reach Him! Sign of Love + Saiki Family Home Renovation! Drastic Makeover!! + Deceive! Mind Control.nfo'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment] 2018-02-03 12:55
Duplicate of https://github.com/pymedusa/Medusa/issues/3699

**Closed by medariox** 2018-02-03 12:55 UTC
Labels: Duplicate
