### ISSUE TITLE
[APP SUBMITTED]: IOError: [Errno 2] No such file or directory: '/mnt/Space/Needtomove/[HorribleSubs] Arifureta Shokugyou de Sekai Saikyou - S1E01 [1080p].mkv'

### ISSUE THREAD

**Issue by Ryanssingh** [pymedusa/Medusa#6947] opened 2019-07-16 00:06 UTC
### INFO
**Python Version**: `2.7.16 (default, Apr  9 2019, 04:50:39) [GCC 8.3.0]`
**Operating System**: `Linux-4.18.0-25-generic-x86_64-with-Ubuntu-18.10-cosmic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@74c3f124fb599ad923e23f46fc320778b8b4217c
**Link to Log**: https://gist.github.com/20db13ae6a2e5cb861f581781f4cb8e1
### ERROR
<pre>
2019-07-15 13:42:12 ERROR    Thread_16 :: [74c3f12] Unable to link file /mnt/Space/Needtomove/[HorribleSubs] Arifureta Shokugyou de Sekai Saikyou - S1E01 [1080p].mkv to /mnt/Space/anime/Arifureta - From Commonplace to World's Strongest/Season 01/Arifureta - From Commonplace to World's Strongest - S01E01 - The Monster of the Abyss.mkv: IOError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/74c3f124fb599ad923e23f46fc320778b8b4217c/medusa/post_processor.py#L503">medusa/post_processor.py</a>", line 503, in symlink
    helpers.move_and_symlink_file(cur_file_path, new_file_path)
  File "/opt/medusa/<a href="../blob/74c3f124fb599ad923e23f46fc320778b8b4217c/medusa/helpers/__init__.py#L430">medusa/helpers/__init__.py</a>", line 430, in move_and_symlink_file
    copy_file(src_file, dest_file)
  File "/opt/medusa/<a href="../blob/74c3f124fb599ad923e23f46fc320778b8b4217c/medusa/helpers/__init__.py#L295">medusa/helpers/__init__.py</a>", line 295, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "/opt/medusa/<a href="../blob/74c3f124fb599ad923e23f46fc320778b8b4217c/lib/shutil_custom/__init__.py#L32">lib/shutil_custom/__init__.py</a>", line 32, in copyfile_custom
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
  File "/opt/medusa/<a href="../blob/74c3f124fb599ad923e23f46fc320778b8b4217c/medusa/init/filesystem.py#L112">medusa/init/filesystem.py</a>", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
IOError: [Errno 2] No such file or directory: '/mnt/Space/Needtomove/[HorribleSubs] Arifureta Shokugyou de Sekai Saikyou - S1E01 [1080p].mkv'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment] 2019-07-16 08:48
Duplicate of https://github.com/pymedusa/Medusa/issues/6799

**Closed by medariox** 2019-07-16 08:48 UTC
Labels: triage
