### ISSUE TITLE
Renaming TV Series does not rename the image thumbnails

### ISSUE THREAD

**Issue by Sinsid24** [pymedusa/Medusa#8807] opened 2020-11-30 22:32 UTC
Goto a Show
Click on Preview Rename
Select all the episodes or some of the episodes.
Click Rename.

Expected:
All files are renamed to match the new video file names. (nfo, jpg).

Actual:
jpg files are not renamed.

**Comment by medariox** [comment] 2020-12-16 16:05
Duplicate of https://github.com/pymedusa/Medusa/issues/8378

**Closed by medariox** 2020-12-16 16:05 UTC
