### ISSUE TITLE
Jackett saves .torrent files as .nzb

### ISSUE THREAD

**Issue by adaur** [pymedusa/Medusa#3349] opened 2017-11-30 05:26 UTC
Some Jackett users have reported this to me (https://mondedie.fr/d/9915-medusa-jackett-rutorrent-petit-soucis-de-renommage-de-fichier) The issue was raised 4 days ago so I assume that is was on the latest version.

It's been explained by Jackett's dev here; https://github.com/SickRage/SickRage/issues/4132#issuecomment-344009629 

`On jackett we recently (starting with version v0.8.396) changed the usage of the file argument, it now only contains the basename (no extension).`

**Comment by medariox** [comment] 2017-11-30 13:16
Fixed with: https://github.com/pymedusa/Medusa/pull/3352

**Comment by saitoh183** [comment] 2017-12-01 13:51
Does this mean we can use the latest version of jackett again? i had to revert back to a old version to have something working.

https://github.com/Jackett/Jackett/issues/2182

**Comment by medariox** [comment] 2017-12-01 14:01
@saitoh183 
Yes, it's the whole point of that PR.

**Comment by saitoh183** [comment] 2017-12-01 16:17
@medariox 
How do i apply this fix? im on Dev branch but it says there is no updates.

**Comment by medariox** [comment] 2017-12-01 16:18
As you can see the PR hasn't been merged yet. Have patience.

**Comment by saitoh183** [comment] 2017-12-01 16:19
@medariox 

yeah i just noticed...sorry :)

**Comment by saitoh183** [comment] 2017-12-01 16:43
@medariox 

I replaced the files in my medusa so i could test your fix and it works. But its important to note that the field for Black hole folder location must be black or else it will create a nzb file. I had it setup so that i could rename the files to .torrent while i had the problem because the files were falling into config directory because Black hole folder location was blank at the time.

**Comment by medariox** [comment] 2017-12-01 16:48
The black hole folder must be black? What do you mean?

**Comment by saitoh183** [comment] 2017-12-01 16:50
@medariox 

sorry typo... Blank

**Comment by medariox** [comment] 2017-12-01 17:50
Nzb or torrent black hole?

**Comment by adaur** [comment] 2017-12-01 18:15
From what I've understood, the blackhole folder filled must be left blank.

**Comment by medariox** [comment] 2017-12-01 18:24
Yes, but there is one for nzb and one for torrents. Which one is it? So I can try to reproduce it.

**Comment by saitoh183** [comment] 2017-12-01 19:28
@medariox 

the one for nzb. If it is filled, then the search will produce a dot nzb file

**Comment by MajorSlaye** [comment] 2017-12-03 01:54
Well for my part its still get .NBZ extension even after i manualy update all files. I still got Torrent save as .NBZ

**Comment by saitoh183** [comment] 2017-12-03 02:54
@MajorSlaye 

Do you have a path set in Black hole folder location under NZB search..if you do, remove it

**Comment by MajorSlaye** [comment] 2017-12-03 10:47
@saitoh183 
Thanks you for answer, it's empty, I try put a path then i clean it with select nothing and i retry with erase it manually. But nothing its still save .NZB file instead of torrent

https://goo.gl/m3Xp7n
https://goo.gl/UZj89A

**Comment by medariox** [comment] 2017-12-03 11:50
You just need to be on latest develop without changing stuff around.

I've tried all possible settings combination once again and all work as expected. If you still have issues it means that you are trying to download links that were generated before the fix. What you need to do in that case: 1) Force a manual search and download the **new** results and/or optionally 2) Delete your cache.db (usually located in `medusa/cache.db`).

**Closed by medariox** 2017-12-03 11:50 UTC
Labels: Bug, Fixed

**Comment by MajorSlaye** [comment] 2017-12-03 14:12
@medariox 
Thanks you,
I make the search and I delete cache.DB i still find new .Nzb file in my folder Opt/Medusa. I did a git reinitialise, i switched from master to dev branch again then i retry delete cache. Its still unable to send torrent to transmission https://goo.gl/XJida9. But now i dont find any file in Opt/Medusa or into my torrent  folder. So i dont know if its resolve the extension or if its with transmission i got a trouble now

**Comment by medariox** [comment] 2017-12-03 14:31
@MajorSlaye 
You need to post a full debug log if you wish to get any help, half of a screenshot is sadly not enough.

**Comment by MajorSlaye** [comment] 2017-12-03 14:32
Actually, i got the provider on medusa who get update and now finaly work. I dont need use Jackett.

**Comment by cpainchaud** [comment] 2017-12-04 09:34
Here is the full debug after deleting Medusa and doing manual search, running on today dev branch:

`2017-12-04 10:33:03 INFO     SEARCHQUEUE-FORCED-328711 :: [b96b3ee] Saved Star.Trek.Discovery.S01E09.FRENCH.720p.NF.WEB-DL.DD5.1.x264-ARK01 to Star.Trek.Discovery.S01E09.FRENCH.720p.NF.WEB-DL.DD5.1.x264-ARK01.nzb
2017-12-04 10:33:03 INFO     SEARCHQUEUE-FORCED-328711 :: [b96b3ee] Downloading Star.Trek.Discovery.S01E09.FRENCH.720p.NF.WEB-DL.DD5.1.x264-ARK01 from jackett_YGG at http://192.168.0.12:9117/dl/yggtorrent/?jackett_apikey=**********&path=bHUvZG85a2ViSSt3QmVtYy8rS0dRbXNoOTJFRVZWN0dodktEMDlFa2RSeGZZem82TG1NUlBzTXBlNDRxYm1hL2trRW41N2VRcUd4WFpmalRPc0RkT21yZVNuOStRYTA3eTZzV2ZiN1VTMTFwSVpoUCtocVZLUFpCNWJ0QzRtYUk4Vys0N09HNDVmNmRZWVFlM3UzR3AyOVlYa3Y1QkgvNm9nemFEWDhrQWlMdXFibi9ERjNHKzB6SFlEZ0hpRHFkTFNLODM2TytxRG4vZjZyY2NPVnVlN3dGblREUlJybVFPQ2tGR0gvb0tkb0xHZnlYSnA4T1FhZWVCcXRYRWtFUm94ZE51aFNGamxmR0Zic2tBblJMMmpVMGM3ZUlOaVlMNHAvTXlYODFaaWVwcFhFYkNIazZZR2dHVEY1RVZZWW5kRW5kM09USHA2L2l2YkRFKzMxR2UrNkVBR0xZcFFEaTFESlJXd1JoSWNnPQ2&file=Star.Trek.Discovery.S01E09.FRENCH.720p.NF.WEB-DL.DD5.1.x264-ARK01
2017-12-04 10:33:03 INFO     SEARCHQUEUE-FORCED-328711 :: [b96b3ee] Downloading Star.Trek.Discovery.S01E09.FRENCH.720p.NF.WEB-DL.DD5.1.x264-ARK01 with 191 seeders and 1 leechers and size 846.05 MB from jackett_YGG
2017-12-04 10:33:03 INFO     SEARCHQUEUE-FORCED-328711 :: [jackett_YGG] :: [b96b3ee] Quality of Star.Trek.Discovery.S01E09.VOSTFR.WEBRip.x264-OvD is SDTV
2017-12-04 10:33:03 INFO     SEARCHQUEUE-FORCED-328711 :: [jackett_YGG] :: [b96b3ee] Quality of Star.Trek.Discovery.S01E09.Into.the.Forest.I.Go.1080p.TrueFrench.SubForced.MULTI.WEBRip.aac.x264.PLF is 1080p WEB-DL
2017-12-04 10:33:03 INFO     SEARCHQUEUE-FORCED-328711 :: [jackett_YGG] :: [b96b3ee] Quality of Star.Trek.Discovery.S01E09.VOSTFR.WEB-DL.x264-ARK01 is SDTV
2017-12-04 10:33:03 INFO     SEARCHQUEUE-FORCED-328711 :: [jackett_YGG] :: [b96b3ee] Quality of star.trek.discovery.s01e09.french.720p.webrip.x264-brink is 720p WEB-DL
2017-12-04 10:33:03 INFO     SEARCHQUEUE-FORCED-328711 :: [jackett_YGG] :: [b96b3ee] Quality of Star.Trek.Discovery.S01E09.MULTi.1080p.WEBRip.x264-BRiNK is 1080p WEB-DL
2017-12-04 10:33:03 INFO     SEARCHQUEUE-FORCED-328711 :: [jackett_YGG] :: [b96b3ee] Quality of Star.Trek.Discovery.S01E09.VOSTFR.1080p.WEB-DL.x264-FDS is 1080p WEB-DL
2017-12-04 10:33:03 INFO     SEARCHQUEUE-FORCED-328711 :: [jackett_YGG] :: [b96b3ee] Quality of Star.Trek.Discovery.S01E09.MULTi.1080p.NF.WEB-DL.DD5.1.x264-ARK01 is 1080p WEB-DL
2017-12-04 10:33:03 INFO     SEARCHQUEUE-FORCED-328711 :: [jackett_YGG] :: [b96b3ee] Quality of Star.Trek.Discovery.S01E09.FRENCH.720p.NF.WEB-DL.DD5.1.x264-ARK01 is 720p WEB-DL
2017-12-04 10:32:55 INFO     SEARCHQUEUE-FORCED-328711 :: [jackett_YGG] :: [b96b3ee] Performing episode search for Star Trek: Discovery
2017-12-04 10:32:53 INFO     SEARCHQUEUE-FORCED-328711 :: [Torrent9] :: [b96b3ee] Performing episode search for Star Trek: Discovery
2017-12-04 10:32:53 INFO     SEARCHQUEUE-FORCED-328711 :: [b96b3ee] Using backlog search providers
2017-12-04 10:32:53 INFO     SEARCHQUEUE-FORCED-328711 :: [b96b3ee] Building internal name cache for Star Trek: Discovery
2017-12-04 10:32:53 INFO     SEARCHQUEUE-FORCED-328711 :: [b96b3ee] Finished processing 2564 scene exceptions.
2017-12-04 10:32:53 INFO     SEARCHQUEUE-FORCED-328711 :: [b96b3ee] Updating exception_cache and exception_season_cache
2017-12-04 10:32:53 INFO     SEARCHQUEUE-FORCED-328711 :: [b96b3ee] Beginning forced search for: Star Trek Discovery - S01E09 - Into the Forest I Go
`

**Comment by medariox** [comment] 2017-12-04 10:11
@cpainchaud
You are on master.

**Comment by cpainchaud** [comment] 2017-12-04 10:15
@medariox  I have a sticker on each GUI page that says 
"You're using the develop branch. Please use 'master' unless specifically asked"

**Comment by medariox** [comment] 2017-12-04 10:51
Don't know what to tell you, the logs you posted are from master.

**Comment by cpainchaud** [comment] 2017-12-04 11:07
What can I do to show/prove it's master or develop branch for you ?

**Comment by medariox** [comment] 2017-12-04 11:12
Post logs from develop.

**Comment by p0psicles** [comment] 2017-12-04 11:27
Do you have access to a console? Can you run some git commands? Then run this in your medusa application directory:
```
git branch
```

**Comment by cpainchaud** [comment] 2017-12-04 11:38
admin@Alexandrie:/volume1/@appstore/sickbeard-custom/var/SickBeard$ git branch
* develop
  master

admin@Alexandrie:/volume1/@appstore/sickbeard-custom/var/SickBeard$ cat .git/config
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://github.com/pymedusa/Medusa
        fetch = +refs/heads/master:refs/remotes/origin/master
        pushurl = https://github.com//Medusa
[branch "master"]
        remote = origin
        merge = refs/heads/master

**Comment by p0psicles** [comment] 2017-12-04 11:56
Can you run this: `git rev-parse HEAD` ?

**Comment by cpainchaud** [comment] 2017-12-04 12:04
sh-4.3$ git rev-parse HEAD
b96b3ee10760ffa03a15a207841a1a2bc65798dd

it does not seem to be the last commit from develop .... weird

**Comment by p0psicles** [comment] 2017-12-04 12:08
Not even that, that commit isn't in develop. It was a merged hotfix.
What you can do to fix it is this:
* Make sure you are logged in as the same user as which you use to start medusa.
```
git fetch origin
git reset --hard origin/develop
```

It should give you the output:
`HEAD is now at 014c3bf16 Fix notifiers timeout by socket (#3399)`

**Comment by cpainchaud** [comment] 2017-12-04 12:10
> sh-4.3$ git fetch origin
>sh-4.3$ git reset --hard origin/develop
>fatal: ambiguous argument 'origin/develop': unknown revision or path not in the working tree.
>Use '--' to separate paths from revisions, like this:
>'git <command> [<revision>...] -- [<file>...]'

**Comment by p0psicles** [comment] 2017-12-04 12:19
aah I see. Can you make the following change in your .git/config? Don't know the git commands for it. But you can just change it.
change this:
```
[remote "origin"]
url = https://github.com/pymedusa/Medusa
fetch = +refs/heads/master:refs/remotes/origin/master
```
into:
```
[remote "origin"]
url = https://github.com/pymedusa/Medusa.git
fetch = +refs/heads/*:refs/remotes/origin/*
```

**Comment by cpainchaud** [comment] 2017-12-04 12:25
I should have seen it!
Let me do a new row of tests .... brb

**Comment by cpainchaud** [comment] 2017-12-04 12:33
I confirm it works perfectly now!
