### ISSUE TITLE
Naked News make browser unresponsive

### ISSUE THREAD

**Issue by jxer** [pymedusa/Medusa#6267] opened 2019-03-03 17:40 UTC
Branch: master
Commit: 918cfe7ce01808499585ffe6c1356fd5ed369f76
Version: v0.2.14

simply adding naked news into show list. once added. just browsing to the show to see the episode list causes multiple browsers to go unresponsive. have to delete it from mass update, as i am never able to get into the show itself.

i assume it has something to do with the number of episodes (2k+)

**Comment by p0psicles** [comment] 2019-03-03 17:46
Known issue. Is being worked on

**Comment by jxer** [comment] 2019-03-03 17:47
any idea whats causing it?

**Comment by p0psicles** [comment] 2019-03-03 17:48
Yeah the amount of episodes

**Comment by p0psicles** [comment] 2019-03-03 18:25
I'm working on it in a branch https://github.com/pymedusa/Medusa/tree/feature/vueify-display-show
Just tested the show. And it works fine.

**Comment by medariox** [comment] 2019-03-03 20:07
Duplicate of https://github.com/pymedusa/Medusa/issues/5856

**Closed by medariox** 2019-03-03 20:07 UTC
Labels: triage

**Comment by jxer** [comment] 2019-03-03 20:47
appreciate the work on this, when do you plan to merge it into master?

**Comment by p0psicles** [comment] 2019-03-03 20:48
Master? Probably in two / three months

**Comment by jxer** [comment] 2019-03-03 20:50
thanks for the quick response, thanks for everything you do.
