### ISSUE TITLE
[APP SUBMITTED]: HTTPError: 503 Server Error: Service Unavailable for url: https://api.themoviedb.org/3/tv/changes?api_key=**********&start_date=2017-08-27&end_date=2017-09-10&page=1

### ISSUE THREAD

**Issue by DazzFX** [pymedusa/Medusa#3092] opened 2017-09-11 10:52 UTC
### INFO
**Python Version**: `2.7.13 (default, Dec 18 2016, 22:44:40) [GCC 4.9.3 20150311 (prerelease)]`
**Operating System**: `Linux-3.10.102-armv7l-with-glibc2.4`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@3f23fd272652b10cf781e3058fee50daf79f11b6
**Link to Log**: https://gist.github.com/49cbeb4b136eb05309d12c6eef5af578
### ERROR
<pre>
2017-09-11 03:03:03 ERROR    SHOWUPDATER :: [3f23fd2] Problem running show_updater, Indexer TMDB seems to be having issues while trying to get updates for show WWE Raw. Cause: 503 Server Error: Service Unavailable for url: https://api.themoviedb.org/3/tv/changes?api_key=**********&start_date=2017-08-27&end_date=2017-09-10&page=1.
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/3f23fd272652b10cf781e3058fee50daf79f11b6/SickBeard/medusa/show_updater.py#L88">SickBeard/medusa/show_updater.py</a>", line 88, in run
    last_update, update_max_weeks
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/3f23fd272652b10cf781e3058fee50daf79f11b6/SickBeard/medusa/indexers/tmdb/tmdb.py#L523">SickBeard/medusa/indexers/tmdb/tmdb.py</a>", line 523, in get_last_updated_series
    total_updates += self._get_all_updates(search_from.strftime('%Y-%m-%d'), search_until.strftime('%Y-%m-%d'))
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/3f23fd272652b10cf781e3058fee50daf79f11b6/SickBeard/medusa/indexers/tmdb/tmdb.py#L495">SickBeard/medusa/indexers/tmdb/tmdb.py</a>", line 495, in _get_all_updates
    updates = self.tmdb.Changes().tv(start_date=start_date, end_date=end_date, page=page)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/3f23fd272652b10cf781e3058fee50daf79f11b6/SickBeard/lib/tmdbsimple/changes.py#L79">SickBeard/lib/tmdbsimple/changes.py</a>", line 79, in tv
    response = self._GET(path, kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/3f23fd272652b10cf781e3058fee50daf79f11b6/SickBeard/lib/tmdbsimple/base.py#L87">SickBeard/lib/tmdbsimple/base.py</a>", line 87, in _GET
    return self._request('GET', path, params=params)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/3f23fd272652b10cf781e3058fee50daf79f11b6/SickBeard/lib/tmdbsimple/base.py#L82">SickBeard/lib/tmdbsimple/base.py</a>", line 82, in _request
    response.raise_for_status()
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/3f23fd272652b10cf781e3058fee50daf79f11b6/SickBeard/lib/requests/models.py#L844">SickBeard/lib/requests/models.py</a>", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 503 Server Error: Service Unavailable for url: https://api.themoviedb.org/3/tv/changes?api_key=**********&start_date=2017-08-27&end_date=2017-09-10&page=1
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by DazzFX** [comment] 2017-09-11 10:57
There may not be anything that can be done here, but figured I'd raise a ticket for awareness anyway.  Thanks.  Have gotten this for the past couple of days.

**Comment by medariox** [comment] 2017-09-11 13:48
Yes, there is not much we can do about it. TMDB is having some server issues. If you wish, you can use the other indexers in the meanwhile. Duplicate of: https://github.com/pymedusa/Medusa/issues/3072

**Closed by medariox** 2017-09-11 13:48 UTC
