### ISSUE TITLE
[ FEATURE ] Allow selection of series art to display on Medusa

### ISSUE THREAD

**Issue by StuffonGithub** [pymedusa/Medusa#8109] opened 2020-05-20 01:37 UTC
### **Is your feature request related to a problem? Please describe.**
A small issue when adding a new series and the banner/poster won't show up. Issue can be sort of fixed by removing it from Medusa and adding it with a different indexer.
![image](https://user-images.githubusercontent.com/65162653/82394119-b618fd00-9a7a-11ea-90a6-6b6b2d25edc2.png)

Another issue where a series poster updates and picks one from another language since it gained more likes on the series art database that is being used _(or at least that's how I understood why that happens)_.
![image](https://user-images.githubusercontent.com/65162653/82394195-f6787b00-9a7a-11ea-84e3-395f77b5cff2.png)

But over-all, would be better if users just get the option to pick what banner/poster/background to show on Medusa.

### **Describe the solution you'd like**
Just an option to individually change which poster, banner, background to appear on Medusa without removing the initial auto fetch function.

The easiest explanation would be to link to a feature of another manager, Emby.
![image](https://user-images.githubusercontent.com/65162653/82394385-756db380-9a7b-11ea-9050-37a32af4a317.png)
Clicking the magnifier basically shows you a list of available art (depending on category) from the available series art databases like fanart.tv, tvdb.com, etc. where you can select which one you'd like to display on your library.

### **Describe alternatives you've considered**
Nothing as I am not aware of any possible alternatives to modify this since I think users are quite limited with options in this regard.

### **Additional context**
Not really an important feature considering other requests but just a nice QoL thing I guess. So no rush or anything about this one. You're all doing an awesome work with Medusa and thanks!

**Comment by p0psicles** [comment] 2020-05-20 03:38
I think that's a good feature and pretty much ready to be added with all the UI changes we've been making lately.

**Comment by medariox** [comment] 2020-12-16 14:54
Duplicate of https://github.com/pymedusa/Medusa/discussions/7551

**Closed by medariox** 2020-12-16 14:54 UTC
Labels: Feature request
