### ISSUE TITLE
Mako Error After Adding New Show

### ISSUE THREAD

**Issue by gmusgrave** [pymedusa/Medusa#6415] opened 2019-03-24 13:55 UTC
**Describe the bug**
I just added a new show - Jeopardy!

It appears in my show list, and shows the previous and next episodes.

However, if I click on the show to see the show info, it opens the show info page with "500" in the title, and this error:

> Mako Error
> 
> A mako error has occured.
> If this happened during an update a simple page refresh may be the solution.
> Mako errors that happen during updates may be a one time error if there were significant ui changes.
> 
> File C:\Medusa\Medusa\medusa\sbdatetime.py:247, in sbfdatetime:
> strd = dt.strftime(app.DATE_PRESET)
> ValueError: year=1089 is before 1900; the datetime strftime() methods require year >= 1900

I have refreshed the page, with no change. I have stopped and restarted Medusa (it's running as a Windows Service), with no change.

**Medusa (please complete the following information):**
 - OS: Windows-7-6.1.7601-SP1
 - Branch: master
 - Commit: b34f1df336e52cf0a690acbc393440ac9f8b3581

**Logs:**
<details>

```
2019-03-24 07:19:07 DEBUG    Thread_20 :: [b34f1df] File C:\Medusa\Medusa\ext\mako\template.py, line 471, in render_unicode
2019-03-24 07:19:07 DEBUG    Thread_20 :: [b34f1df] File C:\Medusa\Medusa\ext\mako\runtime.py, line 838, in _render
2019-03-24 07:19:07 DEBUG    Thread_20 :: [b34f1df] File C:\Medusa\Medusa\ext\mako\runtime.py, line 873, in _render_context
2019-03-24 07:19:07 DEBUG    Thread_20 :: [b34f1df] File C:\Medusa\Medusa\ext\mako\runtime.py, line 899, in _exec_template
2019-03-24 07:19:07 DEBUG    Thread_20 :: [b34f1df] File C:/Medusa/Medusa/themes/dark/templates/layouts/main.mako, line 121, in render_body
2019-03-24 07:19:07 DEBUG    Thread_20 :: [b34f1df] File C:/Medusa/Medusa/themes/dark/templates/displayShow.mako, line 232, in render_scripts
2019-03-24 07:19:07 DEBUG    Thread_20 :: [b34f1df] File C:\Medusa\Medusa\medusa\sbdatetime.py, line 247, in sbfdatetime
2019-03-24 07:19:07 INFO     Thread_20 :: [b34f1df] ValueError: year=1089 is before 1900; the datetime strftime() methods require year >= 1900
2019-03-24 07:19:28 DEBUG    Thread_10 :: [b34f1df] File C:\Medusa\Medusa\medusa\server\web\core\base.py, line 120, in render
2019-03-24 07:19:28 DEBUG    Thread_10 :: [b34f1df] File C:\Medusa\Medusa\ext\mako\template.py, line 471, in render_unicode
2019-03-24 07:19:28 DEBUG    Thread_10 :: [b34f1df] File C:\Medusa\Medusa\ext\mako\runtime.py, line 838, in _render
2019-03-24 07:19:28 DEBUG    Thread_10 :: [b34f1df] File C:\Medusa\Medusa\ext\mako\runtime.py, line 873, in _render_context
2019-03-24 07:19:28 DEBUG    Thread_10 :: [b34f1df] File C:\Medusa\Medusa\ext\mako\runtime.py, line 899, in _exec_template
2019-03-24 07:19:28 DEBUG    Thread_10 :: [b34f1df] File C:/Medusa/Medusa/themes/dark/templates/layouts/main.mako, line 121, in render_body
2019-03-24 07:19:28 DEBUG    Thread_10 :: [b34f1df] File C:/Medusa/Medusa/themes/dark/templates/displayShow.mako, line 232, in render_scripts
2019-03-24 07:19:28 DEBUG    Thread_10 :: [b34f1df] File C:\Medusa\Medusa\medusa\sbdatetime.py, line 247, in sbfdatetime
2019-03-24 07:19:28 INFO     Thread_10 :: [b34f1df] ValueError: year=1089 is before 1900; the datetime strftime() methods require year >= 1900
```
</details>

**Additional context**
The unusual thing about this show (compared to most of the shows I add) is its longevity (started in 1984) and the number of episodes (over 200 per season/year).

**Comment by medariox** [comment] 2019-03-24 14:02
Someone mistakenly set the date to 1089 instead of 1989. You need to have it fixed by the indexer. Then just remove the show and add it again.

**Comment by medariox** [comment] 2019-03-24 14:16
I've also set this as bug, as Medusa shouldn't error out like that.

**Comment by gmusgrave** [comment] 2019-03-24 15:16
Thanks! 

You are correct, one episode in the 1989 season on TVMaze has a typo. 

I've submitted a request for them to fix it.

**Comment by p0psicles** [comment] 2019-03-25 12:16
Shouldn't we just import the dates with a minimum of 1970?

**Comment by medariox** [comment] 2019-03-30 14:30
Why? I'm sure some shows aired before 1970.

**Comment by p0psicles** [comment] 2019-03-30 17:22
What is the minimum ordinal date then?

**Comment by gmusgrave** [comment] 2019-03-30 17:34
The big three networks (ABC, CBS, & NBC) started broadcasting between 1946 and 1956. So if you used 1940, you should be safe.

**Comment by medariox** [comment] 2020-01-13 14:07
Duplicate of https://github.com/pymedusa/Medusa/issues/5944

**Closed by medariox** 2020-01-13 14:07 UTC
Labels: Bug
