### ISSUE TITLE
Medusa downloads highest resolution allowed even if preferred resolution is available

### ISSUE THREAD

**Issue by Frono** [pymedusa/Medusa#3590] opened 2018-01-09 16:12 UTC
Medusa downloads highest resolution allowed even if preferred resolution is available. When adding older shows this wastes considerable bandwidth.

Branch/Commit: Master
OS:Linux-4.4.0-104-generic-x86_64-with-Ubuntu-16.04-xenial
What you did:Add new show with custom resolution. Set quality to "allow" all 1080 and 720 resolutions and "preferred" to only 720 resolutions
What happened:Medusa downloads 1080 resolution versions, then downloads 720 versions to replace the 1080 versions
What you expected: If the preferred version was available I would expect medusa to select it for download first, then fall back to allowed resolutions if no preferred resolutions are available.

I believe this is default behavior, if I need to submit logs to show this happening I can.

**Comment by Trotter73** [comment] 2018-01-16 10:50
It maybe related, I have had episodes downloaded multiple times, my criteria was met with the first download but for some reason Medusa had tried to download the same release again, post processing fails and the episodes are marked a snatched. I'll turn on debugging and see if I can get a log.

Branch/Commit: Master
OS:Windows-10-10.0.16299

Allowed - Unknown
Preferred words - HEVC,720p

**Comment by labrys** [comment] 2018-01-16 22:21
Duplicate of #3080

**Closed by labrys** 2018-01-16 22:21 UTC
