### ISSUE TITLE
[APP SUBMITTED]: KeyError: 'Host'

### ISSUE THREAD

**Issue by ChangChiChun** [pymedusa/Medusa#8229] opened 2020-07-09 02:10 UTC
### INFO
**Python Version**: `3.5.6 (default, Nov 25 2018, 14:24:15) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.105-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: https://gist.github.com/ac28a1386536c271287dbf45c9d4831c
### ERROR
<pre>
2020-07-08 23:09:27 ERROR    TORNADO :: [d9c31da] 500 GET /login/?next=%2F (83.97.xx.xx) 268.43ms
Traceback (most recent call last):
  File "/volume2/@appstore/medusa/var/Medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/ext/tornado/web.py#L1590">ext/tornado/web.py</a>", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/volume2/@appstore/medusa/var/Medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/server/web/core/authentication.py#L66">medusa/server/web/core/authentication.py</a>", line 66, in get
    t = PageTemplate(rh=self, filename='index.mako')
  File "/volume2/@appstore/medusa/var/Medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/server/web/core/base.py#L98">medusa/server/web/core/base.py</a>", line 98, in __init__
    if rh.request.headers['Host'][0] == '[':
  File "/volume2/@appstore/medusa/var/Medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/ext/tornado/httputil.py#L229">ext/tornado/httputil.py</a>", line 229, in __getitem__
    return self._dict[_normalized_headers[name]]
KeyError: 'Host'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment] 2020-07-21 13:02
Duplicate of https://github.com/pymedusa/Medusa/issues/8230

**Closed by medariox** 2020-07-21 13:02 UTC
Labels: triage

**Comment by kiwicacid** [comment] 2020-10-06 19:49
### INFO
**Python Version**: `3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]`
**Operating System**: `Linux-4.19.0-10-amd64-x86_64-with-debian-10.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-10-06 15:07:54 ERROR    Thread_12 :: [b352bb6] Exception generated: 'Host'
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/server/web/core/base.py#L251">medusa/server/web/core/base.py</a>", line 251, in async_call
    result = function(**kwargs)
  File "/opt/medusa/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/server/web/home/handler.py#L119">medusa/server/web/home/handler.py</a>", line 119, in index
    t = PageTemplate(rh=self, filename='index.mako')
  File "/opt/medusa/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/server/web/core/base.py#L98">medusa/server/web/core/base.py</a>", line 98, in __init__
    if rh.request.headers['Host'][0] == '[':
  File "/opt/medusa/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/ext/tornado/httputil.py#L229">ext/tornado/httputil.py</a>", line 229, in __getitem__
    return self._dict[_normalized_headers[name]]
KeyError: 'Host'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by kiwicacid** [comment] 2020-10-09 20:35
### INFO
**Python Version**: `3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]`
**Operating System**: `Linux-4.19.0-10-amd64-x86_64-with-debian-10.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-10-09 03:30:54 ERROR    Thread_16 :: [b352bb6] Exception generated: 'Host'
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/server/web/core/base.py#L251">medusa/server/web/core/base.py</a>", line 251, in async_call
    result = function(**kwargs)
  File "/opt/medusa/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/server/web/home/handler.py#L119">medusa/server/web/home/handler.py</a>", line 119, in index
    t = PageTemplate(rh=self, filename='index.mako')
  File "/opt/medusa/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/server/web/core/base.py#L98">medusa/server/web/core/base.py</a>", line 98, in __init__
    if rh.request.headers['Host'][0] == '[':
  File "/opt/medusa/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/ext/tornado/httputil.py#L229">ext/tornado/httputil.py</a>", line 229, in __getitem__
    return self._dict[_normalized_headers[name]]
KeyError: 'Host'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by kiwicacid** [comment] 2020-10-12 15:49
### INFO
**Python Version**: `3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]`
**Operating System**: `Linux-4.19.0-10-amd64-x86_64-with-debian-10.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-10-11 15:17:43 ERROR    Thread_16 :: [b352bb6] Exception generated: 'Host'
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/server/web/core/base.py#L251">medusa/server/web/core/base.py</a>", line 251, in async_call
    result = function(**kwargs)
  File "/opt/medusa/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/server/web/home/handler.py#L119">medusa/server/web/home/handler.py</a>", line 119, in index
    t = PageTemplate(rh=self, filename='index.mako')
  File "/opt/medusa/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/server/web/core/base.py#L98">medusa/server/web/core/base.py</a>", line 98, in __init__
    if rh.request.headers['Host'][0] == '[':
  File "/opt/medusa/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/ext/tornado/httputil.py#L229">ext/tornado/httputil.py</a>", line 229, in __getitem__
    return self._dict[_normalized_headers[name]]
KeyError: 'Host'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by kiwicacid** [comment] 2020-10-23 02:47
### INFO
**Python Version**: `3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]`
**Operating System**: `Linux-4.19.0-10-amd64-x86_64-with-debian-10.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-10-22 19:33:39 ERROR    Thread_7 :: [b352bb6] Exception generated: 'Host'
Traceback (most recent call last):
KeyError: 'Host'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
