### ISSUE TITLE
Error "resource_check_for_existing_folder" during adding of existing series

### ISSUE THREAD

**Issue by cheese1** [pymedusa/Medusa#8781] opened 2020-11-29 14:38 UTC
**Describe the bug**
while trying to add an existing series:
2020-11-29 15:28:27 ERROR    APIv2-Thread_7 :: [f39927e] Unable to get function "resource_check_for_existing_folder" for resource "checkForExistingFolder"

**Medusa (please complete the following information):**
 - OS: fedora 31 x86_64
 - Medusa 0.4.6 
 - Python version: 3.7.9
 - Database version: 44.17

**Comment by p0psicles** [comment] 2020-11-29 14:46
Can you be more specific in the steps to reproduce the issue?

**Comment by cheese1** [comment] 2020-11-29 14:56
* click onto "Add Shows" under "Shows"
* "Add existing Shows"
* on the next screen:
i have only one directory under 
"Manage Directories" : "/home/sickbeard/Downloads/Serien.staging" which is my default.
"Prompt me to set settings for each show" is OFF
"Use the customized options for each show" is OFF
"Displaying folders within these directories which aren't already added to Medusa:" is set ON with:
    /home/sickbeard/Downloads/Serien.staging
All but one directories are unset. i have only a tick at
/home/sickbeard/Downloads/Serien.staging/Rush
and click onto "Add". All indexers is set.
a new part of the page opens and i see
"Error while checking for existing folder" in orange
the above error is in the error-log.

**Comment by p0psicles** [comment] 2020-11-29 15:05
Can you, create a screenahot of the page just before you click add?

**Comment by cheese1** [comment] 2020-11-29 15:09
![Screenshot from 2020-11-29 16-08-50](https://user-images.githubusercontent.com/6437726/100545684-4f607180-325d-11eb-8401-1b567d41c13a.png)
![Screenshot from 2020-11-29 16-08-04](https://user-images.githubusercontent.com/6437726/100545685-50919e80-325d-11eb-9286-d5eac659ec14.png)

**Comment by p0psicles** [comment] 2020-11-29 15:27
And it's not giving the error when your adding a new show?

**Comment by cheese1** [comment] 2020-11-29 15:31
if i try to add a new series, eg "Spy City", everything works as expected.
![Screenshot from 2020-11-29 16-29-30](https://user-images.githubusercontent.com/6437726/100546202-458c3d80-3260-11eb-8fd9-97380847f139.png)
after clicking Add i get transfered to the main screen and the show is added.

**Comment by p0psicles** [comment] 2020-11-29 15:35
What, happens when you add a new show, but for a show that you already have?

**Comment by p0psicles** [comment] 2020-11-29 16:20
found the issue.
tnx for reporting, i'll push a fix to develop

**Comment by p0psicles** [comment] 2020-11-29 16:38
Can you verify it's fixed in develop?

**Comment by cheese1** [comment] 2020-11-29 18:11
sorry. i'm currently not at home, will test tomorrow. thanks for the fix in advance :)

**Comment by papampi** [comment] 2020-11-30 09:16
I'm getting the same yellow error of "Error while checking for existing folder"
Also cant add new shows, after click add it goes to shows list page but the show is not added and folder not created too

![Screenshot from 2020-11-30 12-34-09](https://user-images.githubusercontent.com/1108483/100590022-167dd680-3309-11eb-8bc9-e9fea63eed55.png)

Debug log:
```
2020-11-30 12:40:34 DEBUG	SHOWQUEUE-ADD :: [e6025de] 387115: Loading show info from IMDb with ID: tt10048342
2020-11-30 12:40:34 DEBUG	SHOWQUEUE-ADD :: [e6025de] Transaction with 2 queries executed
2020-11-30 12:40:33 WARNING	SHOWQUEUE-ADD :: [e6025de] Could not get tvmaze externals. Cause: ConnectionError(MaxRetryError("HTTPConnectionPool(host='api.tvmaze.com', port=80): Max retries exceeded with url: /lookup/shows?imdb=tt10048342 (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))"))
2020-11-30 12:40:27 WARNING	SHOWQUEUE-ADD :: [e6025de] Could not get tvmaze externals. Cause: ConnectionError(MaxRetryError("HTTPConnectionPool(host='api.tvmaze.com', port=80): Max retries exceeded with url: /lookup/shows?thetvdb=387115 (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))"))
2020-11-30 12:40:22 DEBUG	SHOWQUEUE-ADD :: [e6025de] Trying other indexer: TVmaze get_id_by_external
2020-11-30 12:40:22 DEBUG	SHOWQUEUE-ADD :: [e6025de] 387115: Loading show info from TVDBv2
2020-11-30 12:40:22 DEBUG	SHOWQUEUE-ADD :: [e6025de] User-Agent: Medusa/0.4.6 (Linux; 4.14.24-qnap; 4f50c1a2-32eb-11eb-b69a-00089bef61c6)
2020-11-30 12:40:22 DEBUG	SHOWQUEUE-ADD :: [e6025de] GET URL: https://api.thetvdb.com/series/387115/episodes/query?page=1 [Status: 200]
2020-11-30 12:40:21 DEBUG	SHOWQUEUE-ADD :: [e6025de] Getting all episodes of 387115
2020-11-30 12:40:21 DEBUG	SHOWQUEUE-ADD :: [e6025de] User-Agent: Medusa/0.4.6 (Linux; 4.14.24-qnap; 4f50c1a2-32eb-11eb-b69a-00089bef61c6)
2020-11-30 12:40:21 DEBUG	SHOWQUEUE-ADD :: [e6025de] GET URL: https://api.thetvdb.com/series/387115 [Status: 200]
2020-11-30 12:40:21 DEBUG	SHOWQUEUE-ADD :: [e6025de] Getting all show data for 387115
2020-11-30 12:40:21 DEBUG	SHOWQUEUE-ADD :: [e6025de] Getting all series data for 387115
2020-11-30 12:40:21 DEBUG	SHOWQUEUE-ADD :: [e6025de] Configured language en override show language of en
2020-11-30 12:40:21 DEBUG	SHOWQUEUE-ADD :: [e6025de] TVDBv2: {'language': 'en', 'use_zip': True, 'session': <medusa.session.core.MedusaSession object at 0x43c4060>, 'cache': '/share/CACHEDEV1_DATA/.qpkg/OMedusa/config/cache/indexers/TVDBv2'}
2020-11-30 12:40:21 INFO	SHOWQUEUE-ADD :: [e6025de] 387115: Unable to find the show in the database
2020-11-30 12:40:21 DEBUG	SHOWQUEUE-ADD :: [e6025de] 387115: Loading show info from database
2020-11-30 12:40:21 INFO	SHOWQUEUE-ADD :: [e6025de] Starting to add show by show_dir: /share/CACHEDEV8_DATA/TV_Series/The Queen's Gambit
2020-11-30 12:40:16 DEBUG	APIv2-Thread :: [e6025de] Using custom UI: <class 'medusa.classes.AllShowsListUI'>
2020-11-30 12:40:16 DEBUG	APIv2-Thread :: [e6025de] User-Agent: Medusa/0.4.6 (Linux; 4.14.24-qnap; 4f50c1a2-32eb-11eb-b69a-00089bef61c6)
2020-11-30 12:40:16 DEBUG	APIv2-Thread :: [e6025de] GET URL: https://api.thetvdb.com/search/series?name=queen%27s+gambit [Status: 200]
2020-11-30 12:40:16 DEBUG	APIv2-Thread :: [e6025de] Searching for show: queen's gambit
2020-11-30 12:40:16 DEBUG	APIv2-Thread :: [e6025de] Using custom UI: <class 'medusa.classes.AllShowsListUI'>
2020-11-30 12:40:16 DEBUG	APIv2-Thread :: [e6025de] User-Agent: Medusa/0.4.6 (Linux; 4.14.24-qnap; 4f50c1a2-32eb-11eb-b69a-00089bef61c6)
2020-11-30 12:40:16 DEBUG	APIv2-Thread :: [e6025de] GET URL: https://api.thetvdb.com/search/series?name=the+queen%27s+gambit [Status: 200]
2020-11-30 12:40:13 DEBUG	APIv2-Thread :: [e6025de] Searching for show: the queen's gambit
2020-11-30 12:40:13 DEBUG	APIv2-Thread :: [e6025de] Searching for show with search term(s): ["The Queen's Gambit", "Queen's Gambit"] on indexer: tvdb

```

**Comment by papampi** [comment] 2020-11-30 09:35
Wanted to switch to develope branch but its grayed out and wont let me select branch either. just gives "Please select a branch"

Medusa Info: | Branch: master Commit: e6025de42a034b5887e5806fda210e30f5a1e150 Version: .0.4.6 Database: 44.17
-- | --
Python Version: | 3.8.5 (default, Sep 10 2020, 19:39:36) [GCC 8.4.0]
SSL Version: | OpenSSL 1.1.1g 21 Apr 2020
OS: | Linux-4.14.24-qnap-x86_64-with-glibc2.2.5
Locale: | en_US.UTF-8
  |  

![Screenshot from 2020-11-30 12-53-00](https://user-images.githubusercontent.com/1108483/100591751-6f4e6e80-330b-11eb-9fb3-d06e0050a96d.png)

**Comment by medariox** [comment] 2020-11-30 09:37
Just refresh the page.

**Comment by papampi** [comment] 2020-11-30 09:59
Wont switch to develop
What I do is click develop branch then checkout branch, it keeps circling with "Checking out branch develop"
Save, restart ... it still shows master in the info page.

  
log:

```
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] "/opt/bin/git" clean -d -f -x lib lib2 lib3 ext ext2 ext3 medusa static sickbeard sickrage gui : returned successful
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] Executing "/opt/bin/git" clean -d -f -x lib lib2 lib3 ext ext2 ext3 medusa static sickbeard sickrage gui with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:22:32 WARNING	APIv2-Thread-1 :: [e6025de] "/opt/bin/git" checkout -f develop returned : error: pathspec 'develop' did not match any file(s) known to git
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] Executing "/opt/bin/git" checkout -f develop with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] "/opt/bin/git" symbolic-ref -q HEAD : returned successful
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] Executing "/opt/bin/git" symbolic-ref -q HEAD with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] "/opt/bin/git" clean -d -f -x lib lib2 lib3 ext ext2 ext3 medusa static sickbeard sickrage gui : returned successful
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] Executing "/opt/bin/git" clean -d -f -x lib lib2 lib3 ext ext2 ext3 medusa static sickbeard sickrage gui with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] "/opt/bin/git" reset --hard origin/master : returned successful
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] Executing "/opt/bin/git" reset --hard origin/master with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] "/opt/bin/git" config remote.origin.pushurl https://github.com/pymedusa/Medusa.git : returned successful
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] Executing "/opt/bin/git" config remote.origin.pushurl https://github.com/pymedusa/Medusa.git with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] "/opt/bin/git" config remote.origin.url https://github.com/pymedusa/Medusa.git : returned successful
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] Executing "/opt/bin/git" config remote.origin.url https://github.com/pymedusa/Medusa.git with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] Branch checkout: master->develop
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] "/opt/bin/git" symbolic-ref -q HEAD : returned successful
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] Executing "/opt/bin/git" symbolic-ref -q HEAD with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] "/opt/bin/git" symbolic-ref -q HEAD : returned successful
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] Executing "/opt/bin/git" symbolic-ref -q HEAD with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] "/opt/bin/git" symbolic-ref -q HEAD : returned successful
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] Executing "/opt/bin/git" symbolic-ref -q HEAD with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] Using: "/opt/bin/git"
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] "/opt/bin/git" version : returned successful
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] Executing "/opt/bin/git" version with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] Checking if we can use git commands: "/opt/bin/git" version
2020-11-30 13:22:32 INFO	APIv2-Thread-1 :: [e6025de] Config backup successful
2020-11-30 13:21:44 INFO	APIv2-Thread-1 :: [e6025de] Config backup in progress...
2020-11-30 13:21:44 DEBUG	APIv2-Thread-1 :: [e6025de] "/opt/bin/git" symbolic-ref -q HEAD : returned successful
2020-11-30 13:21:44 DEBUG	APIv2-Thread-1 :: [e6025de] Executing "/opt/bin/git" symbolic-ref -q HEAD with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:21:44 DEBUG	APIv2-Thread-1 :: [e6025de] Using: "/opt/bin/git"
2020-11-30 13:21:44 DEBUG	APIv2-Thread-1 :: [e6025de] "/opt/bin/git" version : returned successful
2020-11-30 13:21:44 DEBUG	APIv2-Thread-1 :: [e6025de] Executing "/opt/bin/git" version with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:21:44 DEBUG	APIv2-Thread-1 :: [e6025de] Checking if we can use git commands: "/opt/bin/git" version
2020-11-30 13:21:44 DEBUG	Thread :: [e6025de] Checkout branch has the same DB version - Equal
2020-11-30 13:21:44 DEBUG	Thread :: [e6025de] User-Agent: Medusa/0.4.6 (Linux; 4.14.24-qnap; 2e6bbacc-32f1-11eb-a9da-00089bef61c6)
2020-11-30 13:21:44 DEBUG	Thread :: [e6025de] GET URL: http://rawcdn.githack.com/pymedusa/Medusa/e6025de42a034b5887e5806fda210e30f5a1e150/medusa/databases/main_db.py [Status: 200]
2020-11-30 13:21:43 DEBUG	Thread :: [e6025de] cur_commit = e6025de42a034b5887e5806fda210e30f5a1e150, newest_commit = e6025de42a034b5887e5806fda210e30f5a1e150, num_commits_behind = 0, num_commits_ahead = 0
2020-11-30 13:21:43 DEBUG	Thread :: [e6025de] "/opt/bin/git" rev-list --left-right "@{upstream}"...HEAD : returned successful
2020-11-30 13:21:43 DEBUG	Thread :: [e6025de] Executing "/opt/bin/git" rev-list --left-right "@{upstream}"...HEAD with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:21:43 DEBUG	Thread :: [e6025de] "/opt/bin/git" rev-parse --verify --quiet "@{upstream}" : returned successful
2020-11-30 13:21:43 DEBUG	Thread :: [e6025de] Executing "/opt/bin/git" rev-parse --verify --quiet "@{upstream}" with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:21:43 DEBUG	Thread :: [e6025de] "/opt/bin/git" fetch --prune origin : returned successful
2020-11-30 13:21:41 DEBUG	Thread :: [e6025de] Executing "/opt/bin/git" fetch --prune origin with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:21:41 DEBUG	Thread :: [e6025de] "/opt/bin/git" branch master --set-upstream-to origin/master : returned successful
2020-11-30 13:21:41 DEBUG	Thread :: [e6025de] Executing "/opt/bin/git" branch master --set-upstream-to origin/master with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:21:41 DEBUG	Thread :: [e6025de] "/opt/bin/git" config remote.origin.pushurl https://github.com/pymedusa/Medusa.git : returned successful
2020-11-30 13:21:41 DEBUG	Thread :: [e6025de] Executing "/opt/bin/git" config remote.origin.pushurl https://github.com/pymedusa/Medusa.git with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:21:41 DEBUG	Thread :: [e6025de] "/opt/bin/git" config remote.origin.url https://github.com/pymedusa/Medusa.git : returned successful
2020-11-30 13:21:41 DEBUG	Thread :: [e6025de] Executing "/opt/bin/git" config remote.origin.url https://github.com/pymedusa/Medusa.git with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:21:41 DEBUG	Thread :: [e6025de] "/opt/bin/git" rev-parse HEAD : returned successful
2020-11-30 13:21:41 DEBUG	Thread :: [e6025de] Executing "/opt/bin/git" rev-parse HEAD with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:21:41 DEBUG	Thread :: [e6025de] "/opt/bin/git" symbolic-ref -q HEAD : returned successful
2020-11-30 13:21:41 DEBUG	Thread :: [e6025de] Executing "/opt/bin/git" symbolic-ref -q HEAD with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:21:41 DEBUG	Thread :: [e6025de] "/opt/bin/git" symbolic-ref -q HEAD : returned successful
2020-11-30 13:21:41 DEBUG	Thread :: [e6025de] Executing "/opt/bin/git" symbolic-ref -q HEAD with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:21:41 DEBUG	Thread :: [e6025de] Using: "/opt/bin/git"
2020-11-30 13:21:41 DEBUG	Thread :: [e6025de] "/opt/bin/git" version : returned successful
2020-11-30 13:21:41 DEBUG	Thread :: [e6025de] Executing "/opt/bin/git" version with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
2020-11-30 13:21:41 DEBUG	Thread :: [e6025de] Checking if we can use git commands: "/opt/bin/git" version
```

**Comment by papampi** [comment] 2020-11-30 10:06
Updated the show in kodi and exported metadata to the folder not getting the orange error anymore but Medusa still wont add it:
It only shows running in the action and stays there



![Screenshot from 2020-11-30 13-32-38](https://user-images.githubusercontent.com/1108483/100595832-b25f1080-3310-11eb-83bf-708474280772.png)

```
2020-11-30 13:30:12 DEBUG	SHOWQUEUE-ADD :: [e6025de] 387115: Loading show info from IMDb with ID: tt10048342
2020-11-30 13:30:12 DEBUG	SHOWQUEUE-ADD :: [e6025de] Transaction with 2 queries executed
2020-11-30 13:30:11 WARNING	SHOWQUEUE-ADD :: [e6025de] Could not get tvmaze externals. Cause: ConnectionError(MaxRetryError("HTTPConnectionPool(host='api.tvmaze.com', port=80): Max retries exceeded with url: /lookup/shows?imdb=tt10048342 (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))"))
2020-11-30 13:30:05 WARNING	SHOWQUEUE-ADD :: [e6025de] Could not get tvmaze externals. Cause: ConnectionError(MaxRetryError("HTTPConnectionPool(host='api.tvmaze.com', port=80): Max retries exceeded with url: /lookup/shows?thetvdb=387115 (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))"))
2020-11-30 13:30:00 DEBUG	SHOWQUEUE-ADD :: [e6025de] Trying other indexer: TVmaze get_id_by_external
2020-11-30 13:30:00 DEBUG	SHOWQUEUE-ADD :: [e6025de] 387115: Loading show info from TVDBv2
2020-11-30 13:30:00 DEBUG	SHOWQUEUE-ADD :: [e6025de] User-Agent: Medusa/0.4.6 (Linux; 4.14.24-qnap; 2e6bbacc-32f1-11eb-a9da-00089bef61c6)
2020-11-30 13:30:00 DEBUG	SHOWQUEUE-ADD :: [e6025de] GET URL: https://api.thetvdb.com/series/387115/episodes/query?page=1 [Status: 200]
2020-11-30 13:30:00 DEBUG	SHOWQUEUE-ADD :: [e6025de] Getting all episodes of 387115
2020-11-30 13:30:00 DEBUG	SHOWQUEUE-ADD :: [e6025de] User-Agent: Medusa/0.4.6 (Linux; 4.14.24-qnap; 2e6bbacc-32f1-11eb-a9da-00089bef61c6)
2020-11-30 13:30:00 DEBUG	SHOWQUEUE-ADD :: [e6025de] GET URL: https://api.thetvdb.com/series/387115 [Status: 200]
2020-11-30 13:30:00 DEBUG	SHOWQUEUE-ADD :: [e6025de] Getting all show data for 387115
2020-11-30 13:30:00 DEBUG	SHOWQUEUE-ADD :: [e6025de] Getting all series data for 387115
2020-11-30 13:30:00 DEBUG	SHOWQUEUE-ADD :: [e6025de] Configured language en override show language of en
2020-11-30 13:30:00 DEBUG	SHOWQUEUE-ADD :: [e6025de] TVDBv2: {'language': 'en', 'use_zip': True, 'session': <medusa.session.core.MedusaSession object at 0x4e91ea0>, 'cache': '/share/CACHEDEV1_DATA/.qpkg/OMedusa/config/cache/indexers/TVDBv2'}
2020-11-30 13:30:00 INFO	SHOWQUEUE-ADD :: [e6025de] 387115: Unable to find the show in the database
2020-11-30 13:30:00 DEBUG	SHOWQUEUE-ADD :: [e6025de] 387115: Loading show info from database
2020-11-30 13:30:00 INFO	SHOWQUEUE-ADD :: [e6025de] Starting to add show by show_dir: /share/CACHEDEV8_DATA/TV_Series/The Queen's Gambit
2020-11-30 13:29:29 DEBUG	APIv2-Thread-1 :: [e6025de] Loading show info from KODI metadata file in /share/CACHEDEV8_DATA/TV_Series/The Queen's Gambit

**Comment by p0psicles** [comment] 2020-11-30 11:12
Make sure you on latest develop commit. Or else wait until we release. I think it's fixed in develop. Will release later today

**Comment by papampi** [comment] 2020-11-30 11:22
> Make sure you on latest develop commit. Or else wait until we release. I think it's fixed in develop. Will release later today

Switching to develop gives this error:
```
2020-11-30 13:22:32 WARNING	APIv2-Thread-1 :: [e6025de] "/opt/bin/git" checkout -f develop returned : error: pathspec 'develop' did not match any file(s) known to git
2020-11-30 13:22:32 DEBUG	APIv2-Thread-1 :: [e6025de] Executing "/opt/bin/git" checkout -f develop with your shell in /share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa
```

**Comment by cheese1** [comment] 2020-11-30 20:04
works for me
![Screenshot from 2020-11-30 20-58-57](https://user-images.githubusercontent.com/6437726/100658588-99298480-334f-11eb-9566-0b92481817f4.png)

**Comment by papampi** [comment] 2020-11-30 20:31
Still won't add neither existing nor new shows for me

**Comment by medariox** [comment] 2020-11-30 21:04
Yours is a connectivity issue. Probably IP blocked by TheTVDB or some kind of misconfiguration.

**Comment by p0psicles** [comment] 2020-11-30 21:07
Should be in Master now

**Closed by p0psicles** 2020-11-30 21:07 UTC

**Comment by papampi** [comment] 2020-11-30 22:15
TVDB responds ok but TVmaze always blocks expressvpn 
It was working fine before last commit
here is my log:

```

2020-12-01 01:41:36 DEBUG	SHOWQUEUE-ADD :: [ce68da5] Error requesting url http://api.tvmaze.com/lookup/shows?thetvdb=265913 Error: HTTPConnectionPool(host='api.tvmaze.com', port=80): Max retries exceeded with url: /lookup/shows?thetvdb=265913 (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))
2020-12-01 01:41:28 DEBUG	SHOWQUEUE-ADD :: [ce68da5] Trying other indexer: TVmaze get_id_by_external
2020-12-01 01:41:28 DEBUG	SHOWQUEUE-ADD :: [ce68da5] 265913: Loading show info from TVDBv2
2020-12-01 01:41:28 DEBUG	SHOWQUEUE-ADD :: [ce68da5] User-Agent: Medusa/0.5.0 (Linux; 4.14.24-qnap; db7c3f50-3348-11eb-9098-00089bef61c6)
2020-12-01 01:41:28 DEBUG	SHOWQUEUE-ADD :: [ce68da5] GET URL: https://api.thetvdb.com/series/265913/episodes/query?page=1 [Status: 200]
2020-12-01 01:41:28 DEBUG	SHOWQUEUE-ADD :: [ce68da5] Getting all episodes of 265913
2020-12-01 01:41:28 DEBUG	SHOWQUEUE-ADD :: [ce68da5] User-Agent: Medusa/0.5.0 (Linux; 4.14.24-qnap; db7c3f50-3348-11eb-9098-00089bef61c6)
2020-12-01 01:41:28 DEBUG	SHOWQUEUE-ADD :: [ce68da5] GET URL: https://api.thetvdb.com/series/265913 [Status: 200]
2020-12-01 01:41:26 DEBUG	SHOWQUEUE-ADD :: [ce68da5] Getting all show data for 265913
2020-12-01 01:41:26 DEBUG	SHOWQUEUE-ADD :: [ce68da5] Getting all series data for 265913
2020-12-01 01:41:26 DEBUG	SHOWQUEUE-ADD :: [ce68da5] Configured language en override show language of en
2020-12-01 01:41:26 DEBUG	SHOWQUEUE-ADD :: [ce68da5] TVDBv2: {'language': 'en', 'use_zip': True, 'session': <medusa.session.core.IndexerSession object at 0x41e02f0>, 'cache': '/share/CACHEDEV1_DATA/.qpkg/OMedusa/config/cache/indexers/TVDBv2'}
2020-12-01 01:41:26 INFO	SHOWQUEUE-ADD :: [ce68da5] 265913: Unable to find the show in the database
2020-12-01 01:41:25 DEBUG	SHOWQUEUE-ADD :: [ce68da5] 265913: Loading show info from database
2020-12-01 01:41:25 INFO	SHOWQUEUE-ADD :: [ce68da5] Starting to add show by show_dir: /share/CACHEDEV8_DATA/TV_Series/The Queen's Gambit
2020-12-01 01:41:23 DEBUG	APIv2-Thread-4 :: [ce68da5] Using custom UI: <class 'medusa.classes.AllShowsListUI'>
2020-12-01 01:41:23 DEBUG	APIv2-Thread-4 :: [ce68da5] User-Agent: Medusa/0.5.0 (Linux; 4.14.24-qnap; db7c3f50-3348-11eb-9098-00089bef61c6)
2020-12-01 01:41:23 DEBUG	APIv2-Thread-4 :: [ce68da5] GET URL: https://api.thetvdb.com/search/series?name=queen%27s+gambit [Status: 200]
2020-12-01 01:41:23 DEBUG	APIv2-Thread-4 :: [ce68da5] Searching for show: queen's gambit
2020-12-01 01:41:23 DEBUG	APIv2-Thread-4 :: [ce68da5] Using custom UI: <class 'medusa.classes.AllShowsListUI'>
2020-12-01 01:41:23 DEBUG	APIv2-Thread-4 :: [ce68da5] User-Agent: Medusa/0.5.0 (Linux; 4.14.24-qnap; db7c3f50-3348-11eb-9098-00089bef61c6)
2020-12-01 01:41:23 DEBUG	APIv2-Thread-4 :: [ce68da5] GET URL: https://api.thetvdb.com/search/series?name=the+queen%27s+gambit [Status: 200]
2020-12-01 01:41:23 DEBUG	APIv2-Thread-4 :: [ce68da5] Searching for show: the queen's gambit
2020-12-01 01:41:23 DEBUG	APIv2-Thread-4 :: [ce68da5] Searching for show with search term(s): ["The Queen's Gambit", "Queen's Gambit"] on indexer: tvdb
2020-12-01 01:41:15 DEBUG	APIv2-Thread-2 :: [ce68da5] Cannot load the KODI 12+ metadata file from /share/CACHEDEV8_DATA/TV_Series/The Queen's Gambit/tvshow.nfo, it does not exist
2020-12-01 01:41:15 DEBUG	APIv2-Thread-2 :: [ce68da5] Cannot load the KODI metadata file from /share/CACHEDEV8_DATA/TV_Series/The Queen's Gambit/tvshow.nfo, it does not exist
```
