### ISSUE TITLE
Preferred quality episodes displayed as Allowed quality

### ISSUE THREAD

**Issue by sebeksd** [pymedusa/Medusa#7398] opened 2019-11-22 18:38 UTC
**Describe the bug**
After updating Medusa from 0.3.5 to 0.3.6 (same on 0.3.7) already correctly downloaded episodes start to show in yellow as allowed when quality clearly is Preferred.  Same behaviour for all shows

**To Reproduce**
All TV series with "HD1080p" and any 1080p quality episodes are shown as allowed. It's true for both already downloaded and newly downloaded files.

**Expected behavior**
If files are within selected quality then they should show as preferred (in green).

**Screenshots**
![image](https://user-images.githubusercontent.com/18705953/69450596-d2531000-0d5d-11ea-9321-4f493fa67bf2.png)
![image](https://user-images.githubusercontent.com/18705953/69451055-c74caf80-0d5e-11ea-8888-e04c9a74f60a.png)

**Medusa (please complete the following information):**
Official docker image
Branch: master
Commit: 6bfdb2236003331e639a1845f765ee0462ae8a5d
Version: 0.3.7
Database: 44.14
Python Version: | 3.7.5 (default, Oct 17 2019, 12:25:15) [GCC 8.3.0]
SSL Version: | OpenSSL 1.1.1d 10 Sep 2019
OS: | Linux-4.14.24-qnap-x86_64-with
Locale: | en_US.UTF-8

**Comment by p0psicles** [comment] 2019-11-22 18:43
duplicate of #7341

**Closed** 2019-11-22 18:43 UTC
Labels: Duplicate
