### ISSUE TITLE
PP picks sample files in sample folders and won't overwite it with main file

### ISSUE THREAD

**Issue by nicktdot** [pymedusa/Medusa#7538] opened 2019-12-29 22:09 UTC
As described, the archive contains a sample folder with a smaller sample file ( .s. in the filename).

Post-Processing picks the sample file and then won't overwrite when it finds the main file.

2019-12-29 16:23:38 INFO	POSTPROCESSOR :: Post-processing completed.
2019-12-29 16:13:52 WARNING	POSTPROCESSOR :: /data/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED[rartv]/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED[rartv]/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED.mkv: Processing failed: File exists. Marking it unsafe to replace. Reason: New quality is equal than current Preferred. Ignoring quality
2019-12-29 16:13:52 WARNING	POSTPROCESSOR :: Problem(s) during processing, failed for the following files/folders: 
2019-12-29 16:13:52 INFO	POSTPROCESSOR :: Not deleting folder /data/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED[rartv]/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED[rartv] found the following files: ['RARBG.txt', 'The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED.mkv', 'the.mandalorian.s01e08.hdr.2160p.webrip.x265-petrified.nfo']
2019-12-29 16:13:52 WARNING	POSTPROCESSOR :: Processing failed for /data/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED[rartv]/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED[rartv]/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED.mkv: File exists. Marking it unsafe to replace. Reason: New quality is equal than current Preferred. Ignoring quality
2019-12-29 16:13:52 INFO	POSTPROCESSOR :: Checking if new quality 4K UHD WEB-DL should replace current quality: 4K UHD WEB-DL
2019-12-29 16:13:52 INFO	POSTPROCESSOR :: New file is 3.75 GB larger
2019-12-29 16:13:52 INFO	POSTPROCESSOR :: New size: 3.85 GB
2019-12-29 16:13:52 INFO	POSTPROCESSOR :: Old size: 101.49 MB
2019-12-29 16:13:52 INFO	POSTPROCESSOR :: New file: /data/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED[rartv]/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED[rartv]/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED.mkv
2019-12-29 16:13:52 INFO	POSTPROCESSOR :: Old file: /media/The Mandalorian/Season 01/the.mandalorian.s01e08.hdr.2160p.webrip.x265-petrified.s.mkv
2019-12-29 16:13:52 INFO	POSTPROCESSOR :: Processing /data/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED[rartv]/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED[rartv]/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED.mkv
2019-12-29 16:13:52 INFO	POSTPROCESSOR :: Deleting folder (if it's empty): /data/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED[rartv]/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED[rartv]/Sample
2019-12-29 16:13:52 INFO	POSTPROCESSOR :: Processing succeeded for /data/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED[rartv]/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED[rartv]/Sample/the.mandalorian.s01e08.hdr.2160p.webrip.x265-petrified.s.mkv
2019-12-29 16:13:47 INFO	POSTPROCESSOR :: Trying to clean any empty folder under /media/The Mandalorian/Season 01
2019-12-29 16:13:37 INFO	POSTPROCESSOR :: This download is marked a priority download so I'm going to replace an existing file if I find one
2019-12-29 16:13:37 INFO	POSTPROCESSOR :: New file is 2.58 GB smaller
2019-12-29 16:13:37 INFO	POSTPROCESSOR :: New size: 101.49 MB
2019-12-29 16:13:37 INFO	POSTPROCESSOR :: Old size: 2.68 GB
2019-12-29 16:13:37 INFO	POSTPROCESSOR :: New file: /data/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED[rartv]/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED[rartv]/Sample/the.mandalorian.s01e08.hdr.2160p.webrip.x265-petrified.s.mkv
2019-12-29 16:13:37 INFO	POSTPROCESSOR :: Old file: /media/The Mandalorian/Season 01/The.Mandalorian.S01E08.1080p.WEBRiP.x264-PETRiFiED.mkv
2019-12-29 16:13:37 INFO	POSTPROCESSOR :: Processing /data/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED[rartv]/The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED[rartv]/Sample/the.mandalorian.s01e08.hdr.2160p.webrip.x265-petrified.s.mkv
2019-12-29 16:05:20 INFO	SNATCHQUEUE-SNATCH-361753 :: Downloading The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED[rartv] with 1783 seeders and 1063 leechers and size 3.95 GB from LimeTorrents, through a SearchType.BACKLOG_SEARCH search
2019-12-29 16:05:20 INFO	SNATCHQUEUE-SNATCH-361753 :: Beginning to snatch release: The.Mandalorian.S01E08.HDR.2160p.WEBRiP.x265-PETRiFiED[rartv]

**Comment by medariox** [comment] 2019-12-29 22:49
Duplicate of https://github.com/pymedusa/Medusa/issues/7535

**Closed by medariox** 2019-12-29 22:49 UTC
Labels: triage
