### ISSUE TITLE
Unicode characters aren't handled right when replacing a previous download

### ISSUE THREAD

**Issue by Paycho** [pymedusa/Medusa#2839] opened 2017-05-29 19:00 UTC
I'm really sorry for the low-quality bug report. I managed to work around this issue before thinking of filing this, and I can't figure out precisely what the state of things needs to be to repro it (I think because I don't understand the circumstances in which a lot of this code actually gets fired), so I don't have debug logs for you :(. Feel free to close this if it's not useful, but I figured if it were me I'd rather have a low-quality bug report than none.

I screwed around with adding .decode or .encode calls around the 'xfile' argument that it *appears* to be hating in the stack trace, but never was able to get it working (and I can call file.open with that episode's filename just fine), so it's possible that this stack trace is a red herring, and perhaps someone who knows the code better than I do can better-diagnose this - but it does appear that this is happening when trying to replace an old file with a unicode character (in this case, **ö**) in the name - let me know if I can get you my system encoding or anything if that'd be useful.

**Branch**: master
**Commit**: 9c19b10731765197136e042f30ebca793414cac1
**OS**: Linux-4.4.0-72-generic-x86_64-with-Ubuntu-16.04-xenial

**What you did**: 
- Noticed a bunch of shows weren't getting postprocessed (& had .ignore files next to them)
- Removed .ignore files, manually postprocessed

**What happened:**
- taken to blank page, went back to Medusa main page
- "view errors" has the below error, I *believe* due to the episode I found in the 'view log' area

**What you expected:**
- Episodes were successfully postprocessed

**Logs:**

2017-05-29 12:46:38 ERROR    Thread-17 :: [9c19b10] Exception generated: 'ascii' codec can't encode character u'\xf6' in position 78: ordinal not in range(128)
Traceback (most recent call last):
  File "/opt/medusa/medusa/server/web/core/base.py", line 259, in async_call
    result = function(**kwargs)
  File "/opt/medusa/medusa/server/web/home/post_process.py", line 50, in processEpisode
    ignore_subs=argToBool(ignore_subs)
  File "/opt/medusa/medusa/process_tv.py", line 162, in process
    ignore_subs=ignore_subs)
  File "/opt/medusa/medusa/process_tv.py", line 336, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/opt/medusa/medusa/process_tv.py", line 577, in process_media
    self.result = processor.process()
  File "/opt/medusa/medusa/post_processor.py", line 1100, in process
    self._delete(cur_ep.location, associated_files=True)
  File "/opt/medusa/medusa/post_processor.py", line 323, in _delete
    file_list += self.list_associated_files(file_path.decode('utf-8'), base_name_only=True, subfolders=True)
  File "/opt/medusa/medusa/post_processor.py", line 184, in list_associated_files
    processed_names += filter(None, (self._rar_basename(filepath, files),))
  File "/opt/medusa/medusa/post_processor.py", line 293, in _rar_basename
    for rar in rars:
  File "/opt/medusa/medusa/post_processor.py", line 291, in <genexpr>
    rars = (x for x in files if os.path.isfile(x) and rarfile.is_rarfile(x))
  File "/opt/medusa/lib/rarfile.py", line 404, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/opt/medusa/lib/rarfile.py", line 389, in _get_rar_version
    with XFile(xfile) as fd:
  File "/opt/medusa/lib/rarfile.py", line 2401, in __init__
    self._fd = open(xfile, 'rb', bufsize)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 78: ordinal not in range(128)
2017-05-29 12:46:38 INFO     Thread-17 :: [9c19b10] This download is marked a priority download so I'm going to replace an existing file if I find one
2017-05-29 12:46:38 INFO     Thread-17 :: [9c19b10] New file is 107.20 MB larger
2017-05-29 12:46:38 INFO     Thread-17 :: [9c19b10] New size: 623.81 MB
2017-05-29 12:46:38 INFO     Thread-17 :: [9c19b10] Old size: 516.61 MB
2017-05-29 12:46:38 INFO     Thread-17 :: [9c19b10] New file: /var/Media/complete/Archer.S08E08.720p.WEB-DL.DD5.1.H264-RARBG.mkv
2017-05-29 12:46:38 INFO     Thread-17 :: [9c19b10] Old file: /mnt/shares/TV/Archer/Season 08/Archer (2009) - S08E08 - Archer Dreamland Auflösung.mkv
2017-05-29 12:46:38 INFO     Thread-17 :: [9c19b10] Processing /var/Media/complete/Archer.S08E08.720p.WEB-DL.DD5.1.H264-RARBG.mkv

**Comment by medariox** [comment] 2017-05-30 16:03
We can't debug with code that was manually changed.

Please go back to unchanged master, enable debug logs, reproduce and post the logs. We won't be able to help otherwise.

**Comment by Paycho** [comment] 2017-05-30 17:14
To be clear, I have not manually changed the code at all.

**Comment by medariox** [comment] 2017-05-30 17:40
This code is definitely not master:
```
File "/opt/medusa/medusa/post_processor.py", line 323, in _delete
file_list += self.list_associated_files(file_path.decode('utf-8'), base_name_only=True, subfolders=True)
```

You added the .decode('utf-8'), right?

> Please go back to unchanged master, enable debug logs, reproduce and post the logs. We won't be able to help otherwise.

**Comment by Paycho** [comment] 2017-05-30 17:51
Oh, apologies for copy-pasting from a stack with that in it. That line should read

            file_list += self.list_associated_files(file_path, base_name_only=True, subfolders=True)

(and did when this happened originally), I just happened to copy from a spot in the log after I'd started fiddling with things. My mistake. If you need to close this that's cool, I realize I'm not giving you all the info you want - but hoped my description of the problem would be enough for you to reproduce with whatever tests you've got. As I mentioned, I think the best I could do is cross my fingers and hope it happens again, as I'm not sure when all this gets triggered.

Actually, if you've got an idea of when this code path typically gets invoked (clearly it has something to do with replacing an old episode), I can totally try to set things up again such that it would and grab a debug log for you.

**Comment by medariox** [comment] 2017-05-30 20:38
No worries! I would much rather fix the issue than just close it. The problem is that 1) that part of the code has changed quite a bit recently 2) I'm not sure how to reproduce it, as the log seems a bit off.

That last code part is always triggered when you post-process a file... maybe it happened because you tried to process a file with non-ascii chars (e.g. ö)? Sadly it's not that obvious. I can suggest to keep debug logging enabled for now, so you can add a full debug log to the issue if it happens again.

**Comment by Paycho** [comment] 2017-05-30 21:05
I appreciate the understanding :). I'll leave debug logging on and see if I can either get this to repro or just hope I hit it again, and will update again if I have more info.

**Comment by medariox** [comment] 2018-01-23 21:09
Feel free to reopen if it happens again.

**Closed by medariox** 2018-01-23 21:09 UTC
Labels: Need more info

**Comment by Paycho** [comment] 2018-02-07 03:40
Woo! Weird timing - I'd forgotten about this completely until 2 weeks ago, and now it actually reproed!

Branch: master
Commit: bd0832551d836713481dd0a93f4118372bb5d963
Version: v0.1.24

Exactly the same overall symptoms/expectations/etc., here's relevant parts of the log:

2018-02-06 20:33:23 ERROR    Thread-17 :: [bd08325] Exception generated: 'ascii' codec can't encode character u'\xe8' in position 59: ordinal not in range(128)
Traceback (most recent call last):
  File "/opt/medusa/medusa/server/web/core/base.py", line 280, in async_call
    result = function(**kwargs)
  File "/opt/medusa/medusa/server/web/home/post_process.py", line 49, in processEpisode
    ignore_subs=argToBool(ignore_subs)
  File "/opt/medusa/medusa/process_tv.py", line 146, in process
    ignore_subs=ignore_subs)
  File "/opt/medusa/medusa/process_tv.py", line 329, in process_files
    self.process_media(path, video_files, force, is_priority, ignore_subs)
  File "/opt/medusa/medusa/process_tv.py", line 536, in process_media
    self.result = processor.process()
  File "/opt/medusa/medusa/post_processor.py", line 1105, in process
    self._delete(cur_ep.location, associated_files=True)
  File "/opt/medusa/medusa/post_processor.py", line 338, in _delete
    files += self.list_associated_files(files[0], subfolders=True)
  File "/opt/medusa/medusa/post_processor.py", line 204, in list_associated_files
    processed_names += filter(None, (self._rar_basename(file_path, files),))
  File "/opt/medusa/medusa/post_processor.py", line 314, in _rar_basename
    for rar in rars:
  File "/opt/medusa/medusa/post_processor.py", line 312, in <genexpr>
    rars = (x for x in files if rarfile.is_rarfile(x))
  File "/opt/medusa/ext/rarfile.py", line 404, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/opt/medusa/ext/rarfile.py", line 389, in _get_rar_version
    with XFile(xfile) as fd:
  File "/opt/medusa/ext/rarfile.py", line 2401, in __init__
    self._fd = open(xfile, 'rb', bufsize)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 59: ordinal not in range(128)
2018-02-06 20:33:23 INFO     Thread-17 :: [bd08325] This download is marked a priority download so I'm going to replace an existing file if I find one
2018-02-06 20:33:23 INFO     Thread-17 :: [bd08325] New file is 319.65 MB smaller
2018-02-06 20:33:23 INFO     Thread-17 :: [bd08325] New size: 175.26 MB
2018-02-06 20:33:23 INFO     Thread-17 :: [bd08325] Old size: 494.91 MB
2018-02-06 20:33:23 INFO     Thread-17 :: [bd08325] New file: /var/Media/complete/South.Park.S14E14.Creme.Fraiche.HDTV.XviD-FQM/south.park.s14e14.hdtv.xvid-fqm.avi
2018-02-06 20:33:23 INFO     Thread-17 :: [bd08325] Old file: /var/Media/TV/South Park/Season 14/South Park - S14E14 - Crème Fraiche.mkv
2018-02-06 20:33:23 INFO     Thread-17 :: [bd08325] Processing /var/Media/complete/South.Park.S14E14.Creme.Fraiche.HDTV.XviD-FQM/south.park.s14e14.hdtv.xvid-fqm.avi

**Comment by Paycho** [comment] 2018-02-07 03:41
(I don't think I can actually re-open since I'm not a collaborator, but hopefully the new comment notification reaches you :) )
