### ISSUE TITLE
shows with more than 15 seasons don't load any more

### ISSUE THREAD

**Issue by fire222** [pymedusa/Medusa#5417] opened 2018-10-14 21:17 UTC
am I the only one with this problem?
anything with a lot of seasons no longer opens properly 
I get the background wallpaper for the show but the seasons are not there.
I looked around here but don't see anyone else reporting this 
is there a quick fix?

**Comment by nickveldrin** [comment] 2018-10-15 15:48
The Daily Show will cause this to happen, which i found with my library.

**Comment by fire222** [comment] 2018-10-15 16:07
The Rachel Maddow Show
Law & Order: Special Victims Unit
Family Guy
the Simpsons
so far these I have found don't open properly...I thought it was because of lots of seasons but it looks like anything with lots of episodes..I just tried the tv show  "location location location" and it works (lots of seasons but not many episodes in each season)

**Comment by p0psicles** [comment] 2018-10-15 16:12
I think the api call is timing out on your setup. Im running atom and south park loaded fine.

Any errors in browser console?

**Comment by fire222** [comment] 2018-10-15 16:19
sorry have no idea what atom is I'm running medusa on windows 10 with sabnzbd setup 
no errors in setup or log files it just says loading in the top left corner and stops when the fan art appears on the screen... how do I fix the api call? 
Sorry I'm not good with computers

**Comment by p0psicles** [comment] 2018-10-15 16:28
@sharkykh did we already merge the threaded api changes to master? Sorry im a bit out of it.

**Comment by p0psicles** [comment] 2018-10-15 16:33
Can you try the develop branch?

**Comment by fire222** [comment] 2018-10-15 16:42
how do I do that?

**Comment by p0psicles** [comment] 2018-10-15 16:50
You can swich branch version by going to general settings - advanced settings.
Restart medusa after

**Comment by fire222** [comment] 2018-10-15 17:07
ok thanks for the help by the way!!
I switched to develop 
when I reboot it says "error connecting to web socket"
and now it's stuck on waiting for medusa to start again ( or does it just take a long time to switch)

**Comment by fire222** [comment] 2018-10-15 18:02
ok I got it switched over everything is working except "The Rachel Maddow Show" still doesn't open but I can live with that..should I just leave it on develop?

**Comment by p0psicles** [comment] 2018-10-15 22:17
Right now you can safely move back to master. But thats not always the case, when we do database or config migration.

**Comment by p0psicles** [comment] 2018-10-15 22:18
Ill check rachel maddow show

**Comment by p0psicles** [comment] 2018-10-15 22:27
Currently develop is also pretty stable. You can stay on it. Youll just have the warning modal in top of screen

**Comment by GovPerm** [comment] 2018-12-07 21:16
I'm having this issue with The Ellen Degeneres Show (Daily Episodes). When I add the show, it won't load the seasons and episodes, and I can't delete the show since it never loads. I'm on the latest master. 

Using Medusa with Deluge on a Seedbox (Medusa is connected to PlexRequests as well, but I didn't enter the Ellen show via PlexRequests interface. I added directly via Medusa). 

The place where it says 
"Loading…
If this is taking too long,
click here to show the page."
When I "click here" nothing happens either. 

Any help is appreciated. Thanks.

**Comment by p0psicles** [comment] 2019-01-12 17:49
This is a known issue. Should be fixed when we've fixed the displayshow page. It's a high prio issue, and where on it

**Comment by medariox** [comment] 2019-03-03 20:20
Duplicate of https://github.com/pymedusa/Medusa/issues/5856

**Closed by medariox** 2019-03-03 20:20 UTC
Labels: triage
